/* ============ pattern catalogue ============ */
const CAT={normal:'Normal',variant:'Benign variant',artifact:'Artifact',abnormal:'Abnormal'};
const P=[
{id:'awake',cat:'normal',name:'Normal awake, eyes closed',
 feats:['Posterior dominant rhythm about 10 Hz over O1/O2 and P3/P4, waxing and waning','Symmetric between the two sides (within about 50% in amplitude, 1 Hz in frequency)','Faster, lower-amplitude beta anteriorly: amplitude and frequency change front to back','Frontopolar blink artifact is expected whenever the eyes open'],
 sig:'The reference tracing. Every other pattern is judged against this one.',hints:['Check the occipital channels first.','Compare front with back, then left with right.'],sim:['reactivity','alphacoma','mu'],
 vs:{alphacoma:'Alpha coma is diffuse and frontally predominant, monotonous, and does not wax and wane or react. Normal alpha is posterior, symmetric and reactive.'}},
{id:'reactivity',cat:'normal',name:'Alpha attenuation with eye opening',
 feats:['Alpha is present with the eyes closed and disappears when they open','Replaced by low-voltage fast activity while the eyes are open','Alpha returns on eye closure, symmetrically','Blinks and an eye-opening artifact mark the transition'],
 sig:'This is normal reactivity. An unreactive background in a comatose patient is a poor sign.',hints:['The rhythm changes partway through the page.','What happens to the posterior channels at the transition?'],sim:['awake','drowsy','alphacoma'],
 vs:{drowsy:'In drowsiness alpha fades and is replaced by slower theta, with slow eye movements. With eye opening alpha is replaced by low-voltage fast activity and blinks.'}},
{id:'drowsy',cat:'normal',name:'Drowsiness',
 feats:['Alpha slows, fragments and drops out','Diffuse theta replaces it and the front-to-back gradient flattens','Slow rolling eye movements at F7/F8, out of phase with each other','The change is state-related and the patient is arousable'],
 sig:'A normal state transition. It can be mistaken for mild generalized slowing if the state is not noted.',hints:['Look at F7 and F8: they move in opposite directions.','Did the alpha disappear, or was it replaced by faster activity?'],sim:['gen_slow','reactivity','n3'],
 vs:{gen_slow:'Drowsiness fluctuates, comes with slow rolling eye movements, and the alpha returns on arousal. Encephalopathic slowing persists while the patient is awake and stimulated.'}},
{id:'n2',cat:'normal',name:'Stage N2 sleep: spindles and K-complex',
 feats:['Spindles: 12–14 Hz bursts that wax and wane over 0.5–1.5 s, central and frontal','K-complex: a sharp negative wave followed by a slower positive wave, maximal at the vertex','Theta background, no alpha','Often a spindle follows the K-complex'],
 sig:'Normal sleep. Persistent asymmetry of spindles can point to a structural lesion on the side with fewer spindles.',hints:['Look at the central and vertex channels.','Spindle-shaped bursts around 13 Hz.'],sim:['n3','wicket','posts'],
 vs:{n3:'N3 is continuous high-amplitude delta. N2 is theta background with discrete spindles and K-complexes.'}},
{id:'n3',cat:'normal',name:'Slow-wave sleep (N3)',
 feats:['Continuous high-amplitude delta (0.5–2 Hz, over about 75 µV)','Frontally predominant and symmetric','Occasional spindles ride on the slow waves','No alpha and no eye movements'],
 sig:'Normal deep sleep. Frontal sleep delta must not be mistaken for pathologic slowing: check the patient state.',hints:['Slow, large and continuous.','Which region has the largest waves?'],sim:['gen_slow','focal_slow','drowsy'],
 vs:{gen_slow:'Both are slow, but N3 is symmetric, frontal and state-appropriate, with sleep features such as spindles. Encephalopathy occurs in a patient who should be awake.',focal_slow:'N3 delta is bilateral, symmetric and frontal. Focal slowing stays in one region with preserved activity elsewhere.'}},
{id:'mu',cat:'normal',name:'Mu rhythm',
 feats:['8–10 Hz arch-shaped (comb) rhythm over C3 and C4','Central distribution, often asymmetric in amplitude','Blocked by contralateral movement or the thought of it, not by eye opening','Seen in the awake, relaxed patient'],
 sig:'A normal rhythm that is easily mistaken for abnormal sharp or rhythmic activity.',hints:['Which channels carry the rhythm?','Do the peaks look sharp and the troughs rounded?'],sim:['awake','wicket','seizure'],
 vs:{seizure:'A seizure evolves in frequency, amplitude and field. Mu is stable, central, and attenuates with movement.'}},
{id:'wicket',cat:'variant',name:'Wicket spikes',
 feats:['Arch-shaped trains at 6–11 Hz over mid or anterior temporal regions','Drowsiness and light sleep in adults','No after-going slow wave and no disruption of the background','Often unilateral or independently bilateral'],
 sig:'A benign variant. Reading it as temporal epileptiform activity is a classic overcall.',hints:['Notice the rhythmic, arch-shaped morphology.','Is there a slow wave after each sharp peak?'],sim:['temporal_spikes','seizure','mu'],
 vs:{temporal_spikes:'Wicket spikes come in arch-shaped rhythmic trains with no after-going slow wave and no background disruption. Temporal spikes are isolated with a slow wave after each.',seizure:'Wicket trains are brief, stable and do not evolve.'}},
{id:'posts',cat:'variant',name:'Positive occipital sharp transients of sleep (POSTS)',
 feats:['Surface-positive (downward) triangular waves over O1 and O2','Repeat at 4–5 Hz in light sleep and are symmetric','No after-going slow wave','Seen in N1–N2 sleep only'],
 sig:'A benign variant that looks like occipital spikes but is positive in polarity and appears in sleep.',hints:['Which direction do the sharp waves point?','Which channels have them?'],sim:['temporal_spikes','n2','bets'],
 vs:{temporal_spikes:'POSTS are surface-positive, symmetric and occipital in sleep. Epileptiform spikes are negative with an after-going slow wave and a more limited field.'}},
{id:'bets',cat:'variant',name:'Benign epileptiform transients of sleep (BETS)',
 feats:['Small sharp spikes under 50 µV and under 50 ms','Temporal, often bilateral and independent with a wide field','Drowsiness and light sleep','No after-going slow wave and no disruption of the background'],
 sig:'A benign variant. The spikes are small, isolated and occur only in drowsiness or light sleep.',hints:['Are the transients large or small?','Is there a slow wave after each?'],sim:['temporal_spikes','pop','wicket'],
 vs:{temporal_spikes:'BETS are small (under 50 µV), brief, with no after-going slow wave and appear only in drowsiness. Pathologic temporal spikes are larger with a slow wave and appear in wakefulness as well.'}},
{id:'blink',cat:'artifact',name:'Eye blinks',
 feats:['Symmetric frontopolar deflections at Fp1 and Fp2','Fall off posteriorly; positive potential at Fp, downward in Fp1-F7 and Fp2-F8','Present only with the eyes open','Time-locked to eyelid closure and repeat at irregular intervals'],
 sig:'The most common artifact, and a reliable guide that the eyes are open.',hints:['Where are the largest deflections?','Do both sides move together?'],sim:['pop','focal_slow','firda'],
 vs:{firda:'Blink deflections are single, brief, frontopolar and stop with the eyes closed. FIRDA is a run of rhythmic sinusoidal delta over the frontal regions.'}},
{id:'muscle',cat:'artifact',name:'Muscle artifact',
 feats:['High-frequency spiky activity over 30 Hz','Temporal and frontal regions (temporalis, frontalis)','Bursts with chewing or tension and stops on relaxation','Reduced by a 15–35 Hz high-frequency filter'],
 sig:'Obscures the underlying EEG. Reassess after the patient relaxes or after a high-frequency filter.',hints:['Try lowering the high-frequency filter.','Where is it located?'],sim:['line','seizure','awake'],
 vs:{line:'Muscle artifact is irregular and bursting, and depends on movement. 60 Hz noise is perfectly regular and constant.',seizure:'Muscle artifact is high-frequency and unstructured, with no evolving rhythmic pattern and no after-going slowing.'}},
{id:'ecgart',cat:'artifact',name:'ECG artifact',
 feats:['Sharp deflections time-locked to the QRS in the ECG row','Regular rate (60–100 per minute)','Maximal over the left temporal region and ear electrodes','More visible in channels with a large inter-electrode distance'],
 sig:'Harmless, but can resemble periodic sharp waves. Always compare with the ECG channel.',hints:['Compare the timing with the red trace.','Is the rate regular?'],sim:['temporal_spikes','lpd','pop'],
 vs:{lpd:'ECG artifact is locked to the QRS at a regular cardiac rate and stays in the same electrodes. LPDs vary slightly in timing and sit with a background change over the hemisphere.',temporal_spikes:'Artifact repeats with the heartbeat and has no after-going slow wave.'}},
{id:'pop',cat:'artifact',name:'Electrode pop',
 feats:['Abrupt steep rise followed by exponential decay','Confined to a single electrode, so it appears in both channels containing it with opposite polarity','No physiologic field: neighbouring electrodes do not share it','A false phase reversal'],
 sig:'A technical problem. Reapplication or impedance check of the electrode solves it.',hints:['Which electrode is shared by the affected channels?','Is the onset steeper than any brain wave?'],sim:['temporal_spikes','bets','ecgart'],
 vs:{temporal_spikes:'A pop is abrupt with a steep rise and slow exponential decay at one electrode and no field in neighbours. A spike has a physiologic field, an after-going slow wave and a normal-looking rise.'}},
{id:'line',cat:'artifact',name:'60 Hz line noise',
 feats:['Uniform fine 60 Hz fuzz on the affected channels','Often one or two channels with poor electrode contact','Removed by the 60 Hz notch filter','Constant amplitude with no relation to brain state'],
 sig:'Technical. Check impedances and cable placement; the notch filter treats the symptom.',hints:['Try the 60 Hz notch.','Is it confined to a few channels?'],sim:['muscle','awake','ecgart'],
 vs:{muscle:'Line noise is perfectly regular and constant, and vanishes with the notch filter. Muscle artifact is irregular and bursts.'}},
{id:'focal_slow',cat:'abnormal',name:'Focal polymorphic delta',
 feats:['Irregular arrhythmic delta (1–3 Hz) confined to one region','Continuous and unreactive','Normal posterior alpha preserved elsewhere','Polymorphic rather than rhythmic, suggesting a structural lesion'],
 sig:'Suggests focal cortical or subcortical dysfunction such as stroke, tumor, abscess or post-ictal state. Needs correlation and imaging.',hints:['Compare the two hemispheres.','Is the slowing regular or irregular?'],sim:['n3','lpd','gen_slow'],askLoc:true,
 vs:{lpd:'Focal slowing is continuous without a regular periodic discharge. LPDs repeat at a stable interval with sharp contours.',gen_slow:'Focal slowing involves one region with preserved activity elsewhere. Generalized slowing is bilateral and diffuse.'}},
{id:'firda',cat:'abnormal',name:'Frontal intermittent rhythmic delta (FIRDA)',
 feats:['Runs of rhythmic 2–3 Hz delta, frontal predominant, on both sides','Regular and sinusoidal, sometimes notched','Intermittent, lasting seconds','Nonspecific, not epileptiform'],
 sig:'A nonspecific marker of encephalopathy: metabolic, toxic, structural or deep midline.',hints:['Frontal channels, regular rhythm.','Is there a spike component?'],sim:['sw3','blink','seizure'],askLoc:true,
 vs:{sw3:'FIRDA is sinusoidal delta with gradual onset and no spikes. 3 Hz spike-and-wave has sharp spikes and begins and ends abruptly.',seizure:'FIRDA does not evolve in frequency, amplitude or field.'}},
{id:'temporal_spikes',cat:'abnormal',name:'Anterior temporal spikes (interictal)',
 feats:['Focal sharp transients with an after-going slow wave','Phase reversal at F7 or F8 in the double-banana montage','A physiologic field that disrupts the background','Background otherwise normal and the discharges are sporadic'],
 sig:'Interictal epileptiform discharges are strongly associated with focal epilepsy, here temporal lobe.',hints:['Look for a phase reversal.','Is there a slow wave after the sharp peak?'],sim:['wicket','bets','pop'],askLoc:true,
 vs:{wicket:'Temporal spikes are isolated with an after-going slow wave and disrupt the background. Wicket spikes are rhythmic arch trains with no slow wave.',bets:'BETS are small (under 50 µV) and appear only in drowsiness. These discharges are large and have a slow wave.',pop:'A pop has no field in neighbours and decays exponentially. These spikes involve neighbouring electrodes and have an after-going slow wave.',lpd:'Spikes occur sporadically with normal background in between. LPDs repeat at a stable interval.'}},
{id:'sw3',cat:'abnormal',name:'Generalized 3 Hz spike-and-wave (absence)',
 feats:['Abrupt onset and offset of regular spike-wave at about 3 Hz','Generalized, bilaterally synchronous with a frontocentral maximum','Rate slows slightly toward the end of the burst','Normal background between bursts, often provoked by hyperventilation'],
 sig:'Classic for childhood absence epilepsy and genetic generalized epilepsy. Clinically the patient stares and is unresponsive.',hints:['Count the complexes per second.','How abruptly does it start and stop?'],sim:['firda','gpd','seizure'],askLoc:true,
 vs:{gpd:'3 Hz spike-and-wave starts and stops abruptly with a normal background around it. GPD is persistent and periodic with a long interval between discharges.',firda:'FIRDA is smooth sinusoidal delta without spikes, with gradual onset.'}},
{id:'hyps',cat:'abnormal',name:'Hypsarrhythmia',
 feats:['Very high-amplitude chaotic slow waves','Multifocal independent spikes and sharp waves','No organized background','Infants, typically 4–12 months, with epileptic spasms'],
 sig:'Classic for infantile epileptic spasms (West syndrome). An urgent neurological problem that needs prompt treatment.',hints:['Is there any organization at all?','Are the two hemispheres in step?'],sim:['gen_slow','temporal_spikes','bs'],
 vs:{gen_slow:'Hypsarrhythmia is chaotic, high-voltage and multifocal with spikes. Generalized slowing is organized and low to moderate in voltage.',bs:'Burst-suppression has flat periods between synchronous bursts. Hypsarrhythmia is continuous and asynchronous.'}},
{id:'lpd',cat:'abnormal',name:'Lateralized periodic discharges (PLEDs)',
 feats:['Periodic sharp or sharp-slow complexes at about 0.5–2 Hz over one hemisphere','Highly stereotyped with a regular interval','Slow or attenuated background on the same side','The opposite hemisphere is relatively preserved'],
 sig:'Associated with acute structural lesions (stroke, HSV encephalitis, tumor) and with seizures. Falls on the ictal-interictal continuum.',hints:['Which side carries the repeating complexes?','Is the interval regular?'],sim:['gpd','temporal_spikes','focal_slow'],askLoc:true,
 vs:{gpd:'LPDs stay in one hemisphere and the other side has a different background. GPD is bilateral and synchronous.',temporal_spikes:'LPDs repeat at a fixed interval and persist. Interictal spikes are sporadic with a normal background around them.'}},
{id:'gpd',cat:'abnormal',name:'Generalized periodic discharges (GPD)',
 feats:['Bilateral synchronous periodic discharges at about 0.5–2.5 Hz','Stereotyped sharp or triphasic complexes at a regular interval','Often little or no background between discharges, as in post-anoxic injury','Persistent and unreactive in severe encephalopathy; sustained rates above 2.5 Hz approach seizure criteria'],
 sig:'On the ictal-interictal continuum. After cardiac arrest, persistent GPD on a suppressed background is a malignant EEG pattern. Also seen in non-convulsive status and metabolic states.',hints:['Is the pattern symmetric?','What fills the space between the discharges?'],sim:['triphasic','cjd','lpd'],askLoc:true,
 vs:{triphasic:'Triphasic waves have an anterior-to-posterior lag, a dominant positive middle phase and a slow background, and are usually reactive. GPD are sharper and more stereotyped without a lag.',cjd:'CJD complexes are slower (about 1 Hz) and very regular, with progressive slowing and myoclonus. GPD rates vary with the cause.',lpd:'GPD involves both hemispheres synchronously. LPDs remain in one hemisphere.'}},
{id:'triphasic',cat:'abnormal',name:'Triphasic waves',
 feats:['Three phases: small negative, large positive, small negative','Frontal predominant with an anterior-to-posterior lag of 10–140 ms','Regular at about 1–2 Hz on a slow background','Usually reactive and may attenuate with stimulation or benzodiazepines'],
 sig:'Typical of metabolic encephalopathy (hepatic, uremic). Not pathognomonic, and can mimic GPD.',hints:['Look at the delay between frontal and posterior channels.','What is the background like?'],sim:['gpd','cjd','gen_slow'],askLoc:true,
 vs:{gpd:'GPD discharges are sharper and synchronous with no lag, often on a suppressed background. Triphasic waves lead frontally and sit on a slow background.',cjd:'CJD complexes are very regular at about 1 Hz and not frontally led.'}},
{id:'bs',cat:'abnormal',name:'Burst-suppression',
 feats:['High-amplitude mixed bursts alternating with flat suppression (under 10 µV)','Bursts are generalized and synchronous','Suppression lasts several seconds','Seen with deep anesthesia, hypothermia or severe encephalopathy'],
 sig:'Reflects severe cortical dysfunction or deliberate suppression. After cardiac arrest, identical bursts and persistent suppression indicate a poor prognosis.',hints:['What is between the bursts?','Are the bursts the same on every channel?'],sim:['gpd','eci','hyps'],askLoc:true,
 vs:{gpd:'GPD are single repeating complexes. Burst-suppression has multi-second bursts of mixed activity.',eci:'Electrocerebral inactivity has no bursts at all.'}},
{id:'cjd',cat:'abnormal',name:'Periodic sharp wave complexes (CJD)',
 feats:['Generalized, very regular periodic sharp waves at about 1 Hz','Biphasic or triphasic sharp complexes','Slow low-voltage deteriorating background','Associated with myoclonus and rapidly progressive dementia'],
 sig:'Highly characteristic of sporadic Creutzfeldt-Jakob disease in the later stage, though sensitivity is moderate.',hints:['How regular is the interval?','What is the clinical context?'],sim:['gpd','triphasic','lpd'],askLoc:true,
 vs:{gpd:'CJD complexes have an extremely regular interval near 1 Hz with progressive background slowing. GPD rate varies with the cause.',triphasic:'CJD complexes are sharp and not frontally led.'}},
{id:'alphacoma',cat:'abnormal',name:'Alpha coma',
 feats:['Diffuse alpha-frequency activity, frontally predominant','Monotonous, with no posterior gradient','Unreactive to stimuli','The patient is unresponsive'],
 sig:'Indicates severe diffuse or brainstem injury (anoxic or pontine). Prognosis is generally poor.',hints:['Is the posterior gradient present?','Is the rhythm reactive?'],sim:['awake','reactivity','mu'],
 vs:{awake:'Normal alpha is posterior, waxes and wanes and reacts to eye opening. Alpha coma is diffuse, monotonous and unreactive in an unresponsive patient.'}},
{id:'eci',cat:'abnormal',name:'Electrocerebral inactivity',
 feats:['No cerebral activity above 2 µV at high sensitivity','Remaining signal is ECG, pulse or instrument artifact','Recorded at 2 µV/mm with widely spaced electrodes under technical standards','Requires exclusion of sedatives, hypothermia and metabolic causes'],
 sig:'Supports the determination of brain death together with the clinical exam. Strict technical standards apply.',hints:['What is the sensitivity setting?','What signals remain?'],sim:['bs','line','ecgart'],
 vs:{bs:'Burst-suppression has bursts of cerebral activity. Electrocerebral inactivity has none.'}},
{id:'seizure',cat:'abnormal',name:'Focal seizure (ictal pattern)',
 feats:['Evolving rhythmic activity: frequency, amplitude and field change','Focal onset, here temporal, then spread','Lasts 10 seconds or more and may end with post-ictal slowing','Correlates with clinical signs'],
 sig:'An electrographic seizure. Evolution is the key feature separating it from periodic or rhythmic interictal patterns.',hints:['Does the pattern change over time?','Where does it begin?'],sim:['mu','wicket','firda'],askLoc:true,
 vs:{mu:'Mu is stable and symmetric and attenuates with movement. A seizure evolves and spreads.',wicket:'Wicket trains are brief and stable and do not evolve.',firda:'FIRDA is bilateral and does not evolve.'}},
{id:'gen_slow',cat:'abnormal',name:'Generalized slowing (encephalopathy)',
 feats:['Diffuse theta and delta with loss of posterior alpha','Bilateral, symmetric and nonspecific','Posterior rhythm slows below 8 Hz','Severity ranges from mild theta to severe delta'],
 sig:'Nonspecific diffuse cerebral dysfunction: metabolic, toxic, infectious or post-anoxic.',hints:['What happened to the posterior rhythm?','Is the patient awake?'],sim:['drowsy','n3','focal_slow'],
 vs:{drowsy:'Encephalopathic slowing persists with eye opening and stimulation. Drowsiness fluctuates with slow eye movements and alpha returns on arousal.',n3:'N3 is symmetric frontal sleep delta with spindles in a sleeping patient.'}}
];
const PM={};P.forEach(p=>PM[p.id]=p);

