/* ============ atlas: rhythms, leads, signal ============ */
const AX={built:{},draws:{rhy:[],lead:[],sig:[]},cur:'pat'};
const cssv=()=>{const s=getComputedStyle(document.documentElement),v=n=>s.getPropertyValue(n).trim();return{ink:v('--ink'),muted:v('--muted'),line:v('--line'),grid:v('--grid'),major:v('--grid-major'),trace:v('--trace'),accent:v('--accent'),mark:v('--mark'),panel:v('--panel'),good:v('--good'),bad:v('--bad'),warn:v('--warn'),soft:v('--soft')}};
function cvSetup(c){const r=c.getBoundingClientRect();if(r.width<2)return null;const d=window.devicePixelRatio||1,w=Math.round(r.width),h=Math.round(r.height);if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}const g=c.getContext('2d');g.setTransform(d,0,0,d,0,0);g.clearRect(0,0,w,h);return{g,w,h,C:cssv()}}
function mkCanvas(host,h){const c=el('canvas');c.style.cssText='display:block;width:100%;height:'+h+'px';host.appendChild(c);return c}
function slider(host,label,o,on){const L=!!o.log,toV=x=>L?o.min*Math.pow(o.max/o.min,x/1000):x,toX=v=>L?1000*Math.log(v/o.min)/Math.log(o.max/o.min):v;
  const w=el('label','sl');w.innerHTML=`<span class="sn">${label}</span><input type="range" min="${L?0:o.min}" max="${L?1000:o.max}" step="${L?1:o.step}" value="${toX(o.val)}"><output></output>`;
  const i=$('input',w),out=$('output',w);const upd=()=>{out.textContent=o.fmt?o.fmt(toV(+i.value)):toV(+i.value)};
  i.addEventListener('input',()=>{upd();on(toV(+i.value))});upd();host.appendChild(w);return{get:()=>toV(+i.value),set:v=>{i.value=toX(v);upd()},input:i}}
function segment(host,opts,cur,on){const s=el('div','seg');s.setAttribute('role','group');opts.forEach(([v,t])=>{const b=el('button',null,t);b.type='button';b.dataset.v=v;b.setAttribute('aria-pressed',String(v===cur));b.addEventListener('click',()=>{$$('button',s).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));on(v)});s.appendChild(b)});host.appendChild(s);return s}
function fmtSI(v,u){const a=Math.abs(v),p=[[1e9,'G'],[1e6,'M'],[1e3,'k'],[1,''],[1e-3,'m'],[1e-6,'µ'],[1e-9,'n'],[1e-12,'p']];for(const[s,x]of p)if(a>=s*.9995)return(+(v/s).toPrecision(3))+' '+x+u;return(+v.toPrecision(3))+' '+u}
const NICE=[1,2,5,10,20,50,100,200,500,1000,2000];
/* generic multi-row tracing painter (negativity up: positive values are drawn downward) */
function drawRows(cv,rows,o){const S=cvSetup(cv);if(!S)return;const{g,w,C}=S,narrow=w<560,L=o.labelW?(narrow?Math.min(o.labelW,80):o.labelW):0,bw=o.bars===false?6:50,rh=o.rowH,top=4,pw=w-L-bw,t0=o.t0,dur=o.dur,X=t=>L+(t-t0)/dur*pw;
  cv._geo={L,pw,t0,dur};const nr=rows.length,gb=top+nr*rh;
  const kmax=Math.round(dur*10);for(let k=0;k<=kmax;k++){const major=k%10===0;if(!major&&pw/dur/10<5)continue;const x=Math.round(X(t0+k/10))+.5;g.strokeStyle=major?C.major:C.grid;g.lineWidth=1;g.beginPath();g.moveTo(x,top);g.lineTo(x,gb);g.stroke();
    if(major){g.fillStyle=C.muted;g.font='11px '+getComputedStyle(document.body).getPropertyValue('--font-mono');g.textAlign=k===0?'left':k===kmax?'right':'center';g.fillText(k/10+' s',x+(k===0?-2:k===kmax?2:0),gb+15)}}
  rows.forEach((r,k)=>{const y0=top+k*rh,cy=y0+rh/2;g.strokeStyle=C.line;g.lineWidth=1;g.beginPath();g.moveTo(L,y0+rh+.5);g.lineTo(L+pw,y0+rh+.5);g.stroke();
    const i0=Math.max(0,Math.floor(t0*FS)),i1=Math.min(r.data.length-1,Math.ceil((t0+dur)*FS));let m=0,pk=1e-9;for(let i=i0;i<=i1;i++)m+=r.data[i];m/=(i1-i0+1);for(let i=i0;i<=i1;i++)pk=Math.max(pk,Math.abs(r.data[i]-m));
    const sc=r.px!=null?r.px:o.norm?(rh*.42)/pk:o.pxUv;
    g.save();g.beginPath();g.rect(L,y0+1,pw,rh-1);g.clip();g.strokeStyle=C.trace;g.lineWidth=o.lw||1.25;g.lineJoin='round';g.beginPath();
    for(let i=i0;i<=i1;i++){const x=X(i/FS),y=cy+(r.data[i]-m)*sc;i===i0?g.moveTo(x,y):g.lineTo(x,y)}g.stroke();g.restore();
    if(L){g.fillStyle=r.color||C.ink;g.fillRect(0,y0+6,3,rh-12);g.textAlign='left';g.font='600 12.5px '+getComputedStyle(document.body).fontFamily;g.fillText(r.label,9,cy-(r.sub?2:-4));if(r.sub){g.fillStyle=C.muted;g.font='11px '+getComputedStyle(document.body).fontFamily;g.fillText(r.sub,9,cy+12)}}
    if(o.bars!==false){let ub=NICE[0];for(const n of NICE)if(n*sc<=rh*.8)ub=n;const len=ub*sc,bx=L+pw+10;g.strokeStyle=C.muted;g.lineWidth=1.5;g.beginPath();g.moveTo(bx,cy-len/2);g.lineTo(bx,cy+len/2);g.stroke();g.fillStyle=C.muted;g.font='10.5px '+getComputedStyle(document.body).getPropertyValue('--font-mono');g.textAlign='left';g.fillText(ub+' µV',bx+5,cy+4)}});
  return gb+22}
function attachMeasure(cv,out){let a=null,b=null;const T=e=>{const r=cv.getBoundingClientRect(),G=cv._geo;return clamp(G.t0+((e.clientX-r.left)-G.L)/G.pw*G.dur,G.t0,G.t0+G.dur)};
  const paint=()=>{if(cv._redraw)cv._redraw();if(a==null||b==null||a===b)return;const g=cv.getContext('2d'),G=cv._geo,C=cssv(),x=t=>G.L+(t-G.t0)/G.dur*G.pw,h=cv.getBoundingClientRect().height;g.save();g.globalAlpha=.14;g.fillStyle=C.mark;g.fillRect(x(Math.min(a,b)),0,Math.abs(x(b)-x(a)),h-20);g.globalAlpha=1;g.strokeStyle=C.mark;g.lineWidth=1.5;[a,b].forEach(t=>{g.beginPath();g.moveTo(x(t),0);g.lineTo(x(t),h-20);g.stroke()});g.restore();const dt=Math.abs(b-a);out.textContent=`Δt ${(dt*1000).toFixed(0)} ms · if it spans one cycle: ${(1/dt).toFixed(1)} Hz · if it spans n cycles: n ÷ Δt`};
  cv.addEventListener('pointerdown',e=>{a=T(e);b=a;cv.setPointerCapture(e.pointerId);paint()});cv.addEventListener('pointermove',e=>{if(a!=null&&e.buttons){b=T(e);paint()}});cv.addEventListener('dblclick',()=>{a=b=null;out.textContent='';paint()});cv.style.cursor='crosshair';cv.style.touchAction='pan-y'}

/* ---- synthetic band signals (10 s at 200 Hz) ---- */
function bn(r,f1,f2,rms,len){let x=new Float64Array(len+400);for(let i=0;i<x.length;i++)x[i]=r.n();if(f1>0)x=Float64Array.from(ff(x,bq('hp',f1,.707)));if(f2<95)x=Float64Array.from(ff(x,bq('lp',f2,.707)));const o=new Float32Array(len);let s=0;for(let i=0;i<len;i++){o[i]=x[i+200];s+=o[i]*o[i]}const k=rms/Math.sqrt(s/len+1e-12);for(let i=0;i<len;i++)o[i]*=k;return o}
function phs(r,f,fm,len){const m=bn(r,.15,1.2,1,len),o=new Float32Array(len);let p=r.r(0,6.283);for(let i=0;i<len;i++){p+=6.2832*f*(1+fm*m[i])/FS;o[i]=p}return o}
function envl(r,d,len){const e=bn(r,.15,.9,1,len),o=new Float32Array(len);for(let i=0;i<len;i++)o[i]=Math.max(0,.8+d*e[i]);return o}
const SPC=[2.2,6,9];
function makeBands(seed){const r=mkRand(seed),o={},z=()=>new Float32Array(N);let p,e,n,x;
  p=phs(r,.25,.3,N);n=bn(r,.05,.8,1,N);x=z();for(let i=0;i<N;i++)x[i]=Math.sin(p[i])*90+n[i]*30;o.slow=x;
  p=phs(r,1.7,.22,N);e=envl(r,.5,N);n=bn(r,.5,3.5,1,N);x=z();for(let i=0;i<N;i++)x[i]=Math.sin(p[i])*e[i]*50+n[i]*14;o.delta=x;
  p=phs(r,6,.1,N);e=envl(r,.5,N);n=bn(r,4,8,1,N);x=z();for(let i=0;i<N;i++)x[i]=Math.sin(p[i])*e[i]*28+n[i]*6;o.theta=x;
  p=phs(r,10,.035,N);e=envl(r,.9,N);n=bn(r,8,13,1,N);x=z();for(let i=0;i<N;i++)x[i]=Math.sin(p[i])*e[i]*32+n[i]*3;o.alpha=x;
  p=phs(r,9.5,.03,N);e=envl(r,.9,N);n=bn(r,8,13,1,N);x=z();for(let i=0;i<N;i++)x[i]=(Math.sin(p[i])+.5*Math.sin(2*p[i]-1))*e[i]*26+n[i]*3;o.mu=x;
  p=phs(r,13,.02,N);n=bn(r,2,7,1,N);const n2=bn(r,.5,3,1,N);x=z();for(let i=0;i<N;i++){let en=0,t=i/FS;SPC.forEach(c=>{const u=(t-c+.6)/1.2;if(u>0&&u<1)en=Math.max(en,Math.pow(Math.sin(Math.PI*u),2))});x[i]=Math.sin(p[i])*en*38+n[i]*9+n2[i]*8}o.sigma=x;
  p=phs(r,20,.12,N);e=envl(r,.6,N);n=bn(r,14,30,1,N);x=z();for(let i=0;i<N;i++)x[i]=Math.sin(p[i])*e[i]*9+n[i]*4;o.beta=x;
  p=phs(r,40,.1,N);e=envl(r,.6,N);n=bn(r,30,70,1,N);x=z();for(let i=0;i<N;i++)x[i]=Math.sin(p[i])*e[i]*1.6+n[i]*2.4;o.gamma=x;
  return o}
const BD=[
{id:'slow',name:'Infraslow',rng:'< 0.5 Hz',color:'#8a8f98',hz:'About 1 wave every 4 s',amp:'Can exceed 100 µV',where:'Anywhere; follows the electrode, not the cortex',state:'Sweat, respiration, movement, poor electrode contact',clin:'Almost always artifact on a routine EEG. The 0.3–1 Hz low-frequency filter exists to remove it. True infraslow activity needs a DC-coupled amplifier and is mainly a research and ICU topic.',look:'A slow wandering baseline with no regular wave you can count. Suspect sweat or a loose electrode when it sways on every channel that shares one electrode.'},
{id:'delta',name:'Delta',rng:'0.5 to under 4 Hz',color:'#7e57c2',hz:'1 to 3 waves per second',amp:'Largest of the bands, 50 to 150 µV or more',where:'Normal: frontal in deep sleep; posterior slow waves of youth in children. Abnormal if awake adult and continuous',state:'Stage N3 sleep, infancy, encephalopathy, structural lesion',clin:'Diffuse delta in an awake adult means encephalopathy. Focal, irregular (polymorphic) delta points to a structural lesion of that region. Rhythmic delta (FIRDA, OIRDA, TIRDA) has its own meanings.',look:'Slow, tall, broad waves. You can count them on your fingers in one second. Superimposed faster activity rides on top.'},
{id:'theta',name:'Theta',rng:'4 to under 8 Hz',color:'#2c9bb5',hz:'4 to 7 waves per second',amp:'20 to 50 µV',where:'Frontocentral and temporal; widespread in children and in drowsiness',state:'Drowsiness (stage N1), young children, mild encephalopathy, medication',clin:'Scattered theta is normal in drowsy adults. Continuous diffuse theta while awake is a nonspecific mild slowing. Focal theta suggests a focal lesion or irritated cortex.',look:'Rounder and slower than alpha, but faster than the slow rolling of delta. Often irregular and mixed with other frequencies.'},
{id:'alpha',name:'Alpha',rng:'8 to 13 Hz',color:'#2e9e5b',hz:'8 to 13 waves per second',amp:'20 to 60 µV, waxing and waning',where:'Posterior: occipital and parietal (the posterior dominant rhythm)',state:'Relaxed wakefulness with eyes closed. Blocks (attenuates) when the eyes open or with mental effort',clin:'Absent, persistently asymmetric (over 50% amplitude difference) or unreactive alpha matters. Diffuse unreactive alpha after anoxic injury ("alpha coma") carries a poor prognosis.',look:'Regular, smooth, sinusoidal waves in spindle-shaped bursts. The most recognizable rhythm.'},
{id:'mu',name:'Mu',rng:'8 to 13 Hz, arch shaped',color:'#c28a1a',hz:'About 9 to 10 per second',amp:'20 to 50 µV',where:'Central (C3, C4), often one side more than the other',state:'Awake and at rest. Blocks with movement or thinking about movement of the opposite hand, not with eye opening',clin:'Normal. Mistaken for epileptiform activity or for alpha. It is arched, comb or "m" shaped, central rather than posterior, and does not react to eye opening.',look:'Alpha-range but with a sharper, comb-like or arch contour and central location. Compare it directly with alpha in the stacked view.'},
{id:'sigma',name:'Sleep spindle (sigma)',rng:'12 to 15 Hz bursts',color:'#d9663a',hz:'About 13 per second for 0.5 to 2 s',amp:'20 to 50 µV, spindle-shaped envelope',where:'Central and frontocentral, near the vertex',state:'Stage N2 sleep (thalamocortical spindle generator)',clin:'Absent or asymmetric spindles can suggest a focal or thalamic problem. In coma, a "spindle coma" pattern is a recognized finding. Normal spindles are symmetric and synchronous.',look:'A short burst that swells and fades, like a spindle of thread, on a slower sleeping background.'},
{id:'beta',name:'Beta',rng:'Above 13 Hz (13 to 30)',color:'#cc3d5f',hz:'More than 13 per second',amp:'Usually under 20 µV, often 5 to 15',where:'Frontal and central, anterior dominant',state:'Alert, concentrating or anxious; increased by benzodiazepines and barbiturates',clin:'Excess diffuse beta is typically medication. Focal increased beta (a breach rhythm) overlies a skull defect. Focal loss of beta can mark an underlying lesion or collection.',look:'Fast, low amplitude "fuzz" you can barely count. At true scale it is nearly flat next to the slower bands.'},
{id:'gamma',name:'Gamma',rng:'Above 30 Hz (30 to 80)',color:'#b04aa3',hz:'More than 30 per second',amp:'Usually under 5 µV',where:'Barely visible on the scalp; best seen with intracranial electrodes',state:'Sensory processing and attention in research settings',clin:'On a scalp tracing, fast activity in this range is most often muscle artifact (EMG). Seeing true gamma needs a high-frequency filter of 70 Hz or more, and caution.',look:'Very fast, tiny, fuzzy. Hard to tell from muscle without the context of the face and jaw channels.'}];

/* ---- Rhythms panel ---- */
function buildRhy(){const H=$('#aRhy');H.innerHTML='';
  const st={mode:'fit',smode:'true',gain:1,sel:new Set(['delta','theta','alpha','beta'])};let B=makeBands(Math.floor(Math.random()*1e9));
  const intro=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Rhythms, one at a time</h2><div class="row" id="rCtl"></div></div>
   <p style="max-width:80ch">Every scalp EEG is a blend of rhythms. Four things separate them: <b>how many waves fit in a second</b>, <b>how tall they are</b>, <b>where on the head</b> they live, and <b>what state</b> the brain is in. Each trace below is a 2-second window; the heavy lines mark 1 second, the faint lines 0.1 s. Count the humps between heavy lines to get the frequency in Hz.</p><div class="bgrid" id="rGrid"></div>`);
  H.appendChild(intro);
  segment($('#rCtl',intro),[['fit','Fit each trace'],['true','True amplitude']],'fit',v=>{st.mode=v;drawAll()});
  const nb=el('button','btn small','New examples');nb.type='button';nb.addEventListener('click',()=>{B=makeBands(Math.floor(Math.random()*1e9));drawAll();quizNext()});$('#rCtl',intro).appendChild(nb);
  const cvs={};BD.forEach(b=>{const c=el('div','bcard',`<div class="row" style="justify-content:space-between;gap:8px"><b style="color:${b.color}">${b.name}</b><span class="pill" style="border-color:${b.color};color:var(--ink)">${b.rng}</span></div><div class="cvh"></div>
    <dl><dt>Count</dt><dd>${b.hz}</dd><dt>Height</dt><dd>${b.amp}</dd><dt>Where</dt><dd>${b.where}</dd><dt>State</dt><dd>${b.state}</dd><dt>Eye tip</dt><dd>${b.look}</dd><dt>Meaning</dt><dd>${b.clin}</dd></dl>`);$('#rGrid',intro).appendChild(c);cvs[b.id]=mkCanvas($('.cvh',c),142)});
  const more=el('p',null,'<span class="lbl">Not shown here</span> Lambda waves, vertex waves, K-complexes, POSTS, wickets, sawtooth waves and other transients are in the <b>Patterns</b> section, because they are shapes rather than rhythms.');intro.appendChild(more);

  // stacked comparison
  const stk=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Side by side, one time base</h2><div class="row" id="sCtl"></div></div>
   <p style="max-width:80ch">The same 3 seconds, same horizontal scale, one row per band. In <b>true amplitude</b> every row uses the same µV-per-pixel, so you see how tall delta really is and how small beta is. <b>Normalized</b> stretches each row to fill its lane so you can compare shape and speed. The top row is the sum of the bands whose chips are pressed: that is what the amplifier actually records.</p><div class="row" id="sChips"></div><div class="vwrap"><div id="sCv"></div><div class="vfoot"><span>Drag across the tracing to time a wave. Double-click to clear.</span><span class="read" id="sRead"></span></div></div>`);H.appendChild(stk);
  segment($('#sCtl',stk),[['true','True amplitude'],['norm','Normalized']],'true',v=>{st.smode=v;drawAll()});
  const gl=el('label','row lbl','Gain');gl.style.cssText='gap:6px;text-transform:none;letter-spacing:0';const gs=el('select');[[1,'×1 (about 7 µV/mm)'],[2,'×2'],[4,'×4']].forEach(([v,t])=>gs.appendChild(new Option(t,v)));gs.addEventListener('change',()=>{st.gain=+gs.value;drawAll()});gl.appendChild(gs);$('#sCtl',stk).appendChild(gl);
  BD.forEach(b=>{const c=el('button','chip',b.name);c.type='button';c.style.borderLeft='4px solid '+b.color;c.setAttribute('aria-pressed',String(st.sel.has(b.id)));c.addEventListener('click',()=>{st.sel.has(b.id)?st.sel.delete(b.id):st.sel.add(b.id);c.setAttribute('aria-pressed',String(st.sel.has(b.id)));drawAll()});$('#sChips',stk).appendChild(c)});
  const scv=mkCanvas($('#sCv',stk),100);attachMeasure(scv,$('#sRead',stk));scv._redraw=()=>drawStack();

  // quiz
  const qz=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Name that rhythm</h2><span class="lbl" id="qzScore">0 of 0</span></div><p style="max-width:80ch">A 4-second sample, stretched to fill the lane. Count the waves in a second, judge the smoothness, then choose. Mu and alpha are told apart mostly by shape and location, so a hint is given where the trace is central.</p><div id="qzCv"></div><div class="row" id="qzOpts"></div><div id="qzFb" class="note" hidden></div>`);H.appendChild(qz);
  const qcv=mkCanvas($('#qzCv',qz),132);const qs={band:null,t0:1,done:false,n:0,ok:0};const QB=BD.filter(b=>b.id!=='slow');
  QB.forEach(b=>{const x=el('button','chip',b.name);x.type='button';x.dataset.id=b.id;x.addEventListener('click',()=>{if(qs.done)return;qs.done=true;qs.n++;const right=b.id===qs.band;if(right)qs.ok++;const a=BD.find(q=>q.id===qs.band);$$('#qzOpts .chip',qz).forEach(c=>{c.disabled=true;if(c.dataset.id===qs.band)c.style.outline='2px solid var(--good)'});if(!right)x.style.outline='2px solid var(--bad)';
      const fb=$('#qzFb',qz);fb.hidden=false;fb.innerHTML=`<b>${right?'Correct.':'It was '+a.name+'.'}</b> ${a.rng}. ${a.look}`;$('#qzScore',qz).textContent=`${qs.ok} of ${qs.n}`;nxt.hidden=false;drawQuiz()});$('#qzOpts',qz).appendChild(x)});
  const nxt=el('button','btn small','Next sample');nxt.type='button';nxt.hidden=true;nxt.addEventListener('click',()=>quizNext());$('#qzOpts',qz).appendChild(nxt);
  function quizNext(){const b=QB[Math.floor(Math.random()*QB.length)];qs.band=b.id;qs.done=false;qs.t0=b.id==='sigma'?SPC[Math.floor(Math.random()*2)]-1.5:1+Math.random()*4.5;$$('#qzOpts .chip',qz).forEach(c=>{c.disabled=false;c.style.outline=''});$('#qzFb',qz).hidden=true;nxt.hidden=true;drawQuiz()}
  function drawQuiz(){const b=BD.find(q=>q.id===qs.band);if(!b)return;qcv.style.height='132px';drawRows(qcv,[{data:B[b.id],label:'',color:b.color}],{rowH:104,t0:qs.t0,dur:4,norm:true,bars:false,lw:1.35})}

  // dial
  const dl=el('div','card stack',`<h2>Dial a frequency</h2><p style="max-width:80ch">Drag the slider and count the crests in the first second. The band names and boundaries are conventions, not cliffs: 7.9 Hz is theta and 8.0 Hz is alpha only by agreement.</p><div id="dSl" class="stack" style="gap:8px"></div><div id="dCv"></div><p id="dTx"></p>`);H.appendChild(dl);
  const dcv=mkCanvas($('#dCv',dl),120);const ds=slider($('#dSl',dl),'Frequency',{min:.5,max:45,step:.5,val:10,fmt:v=>v.toFixed(1)+' Hz'},()=>drawDial());
  function bandOf(f){return f<.5?'Infraslow':f<4?'Delta':f<8?'Theta':f<13?'Alpha / mu range':f<=30?'Beta':'Gamma'}
  function drawDial(){const f=ds.get(),d=new Float32Array(N);for(let i=0;i<N;i++)d[i]=Math.sin(6.2832*f*i/FS)*40;drawRows(dcv,[{data:d,label:''}],{rowH:92,t0:0,dur:2,norm:false,pxUv:1,bars:false,lw:1.4});
    const S=dcv.getContext('2d'),G=dcv._geo,C=cssv();const n=Math.floor(f+.5/FS);S.fillStyle=C.mark;S.font='600 11px '+getComputedStyle(document.body).fontFamily;S.textAlign='center';if(f<=14)for(let k=0;k<Math.floor(f);k++){const t=(k+.25)/f;S.fillText(String(k+1),G.L+t/G.dur*G.pw,12)}
    $('#dTx',dl).innerHTML=`<b>${f.toFixed(1)} Hz</b>: ${f<=14?'about '+Math.floor(f)+' crests in the first second. ':'too many crests to count by eye. '}Band: <b>${bandOf(f)}</b>. One cycle lasts ${(1000/f).toFixed(0)} ms, which is ${(30/f).toFixed(1)} mm of paper at 30 mm/s.`}

  function drawAll(){BD.forEach(b=>{const c=cvs[b.id];c.style.height='142px';drawRows(c,[{data:B[b.id],label:'',color:b.color}],{rowH:116,t0:1.5,dur:2,norm:st.mode==='fit',pxUv:.55,bars:true})});drawStack();drawQuiz();drawDial()}
  function drawStack(){const comp=new Float32Array(N);BD.forEach(b=>{if(st.sel.has(b.id))for(let i=0;i<N;i++)comp[i]+=B[b.id][i]});
    const rows=[{data:comp,label:'Mixed (Σ)',sub:st.sel.size?'chips pressed':'none selected',color:cssv().ink},...BD.map(b=>({data:B[b.id],label:b.id==='sigma'?'Spindle':b.name,sub:b.rng.replace(' to under ','–').replace('Above ','> ').replace(', arch shaped','').replace(' bursts','').replace(' Hz',''),color:b.color}))];
    scv.style.height=(4+rows.length*60+22)+'px';drawRows(scv,rows,{rowH:60,t0:1,dur:3,norm:st.smode==='norm',pxUv:.5*st.gain,labelW:112,lw:1.2})}
  AX.draws.rhy=[drawAll];quizNext();
}

/* ---- Leads & montages panel ---- */
const ELI={
Fp1:['L frontopolar','F','Left frontal pole: frontopolar and orbitofrontal cortex under the forehead (Brodmann 10/11). It sits over the frontal sinus and just above the eye, so it "sees" the eyes about as well as the brain.','Low-voltage fast activity; frontal delta in drowsiness or sleep','Blinks and vertical eye movements (large, same direction at Fp1 and Fp2), frontalis muscle'],
Fp2:['R frontopolar','F','Right frontal pole: frontopolar and orbitofrontal cortex (Brodmann 10/11), over the frontal sinus and just above the eye.','Low-voltage fast activity; frontal delta in drowsiness or sleep','Blinks and vertical eye movements, frontalis muscle'],
F3:['L dorsolateral frontal','F','Left dorsolateral prefrontal cortex: middle frontal gyrus and the front edge of premotor cortex (Brodmann 8/9/46).','Beta; frontal theta; frontal intermittent rhythmic delta in encephalopathy; frontal spikes','Frontalis muscle, spill-over of eye movements'],
F4:['R dorsolateral frontal','F','Right dorsolateral prefrontal cortex: middle frontal gyrus and the front edge of premotor cortex (Brodmann 8/9/46).','Beta; frontal theta; frontal intermittent rhythmic delta in encephalopathy; frontal spikes','Frontalis muscle, spill-over of eye movements'],
F7:['L inferior frontal / anterior temporal','F','Left inferior frontal gyrus (Broca area, Brodmann 44/45). Because it is low on the head, it also picks up the anterior temporal pole. Also written F7 in both the 10-20 and 10-10 systems.','Anterior temporal spikes and slowing often peak here; beta','Sideways eye movements (opposite polarity at F7 and F8), temporalis muscle'],
F8:['R inferior frontal / anterior temporal','F','Right inferior frontal gyrus. Because it is low on the head, it also picks up the anterior temporal pole.','Anterior temporal spikes and slowing often peak here; beta','Sideways eye movements (opposite polarity at F7 and F8), temporalis muscle'],
Fz:['Midline frontal','F','Superior frontal gyrus and medial frontal cortex, including the front part of the supplementary motor area (Brodmann 6/8).','Frontal midline theta; vertex waves spread forward; maximum of many frontal discharges and triphasic waves','Frontalis muscle'],
C3:['L central','C','Left primary sensorimotor cortex: precentral and postcentral gyri (Brodmann 1 to 4), including the hand area. It governs the right hand. The letter C marks the central (Rolandic) region, not a lobe.','Mu rhythm, beta, sleep spindles, central (Rolandic) sharp waves','Rarely muscle; pulses from a scalp artery can show here'],
C4:['R central','C','Right primary sensorimotor cortex: precentral and postcentral gyri (Brodmann 1 to 4), including the hand area. It governs the left hand.','Mu rhythm, beta, sleep spindles, central (Rolandic) sharp waves','Rarely muscle; pulses from a scalp artery can show here'],
Cz:['Vertex','C','Paracentral lobules and the medial surface of both hemispheres at the top of the head: leg area of motor and sensory cortex, plus supplementary motor area. Samples both hemispheres, which is why it is a popular reference.','Vertex waves, K-complexes, sleep spindles','Head movement on the pillow, cardiac pulse spread'],
Pz:['Midline parietal','P','Precuneus and the medial superior parietal lobule (Brodmann 5/7), the posterior midline of the parietal lobes.','Posterior alpha; spindles; the P300 evoked response peaks here','Rarely: electrode pop from the pillow'],
P3:['L parietal','P','Left inferior parietal lobule: supramarginal and angular gyri (Brodmann 39/40), plus part of the superior parietal lobule.','Alpha; posterior spread of temporal and occipital discharges','Electrode pop, pillow movement'],
P4:['R parietal','P','Right inferior parietal lobule: supramarginal and angular gyri (Brodmann 39/40), plus part of the superior parietal lobule.','Alpha; posterior spread of temporal and occipital discharges','Electrode pop, pillow movement'],
O1:['L occipital','O','Left occipital pole: primary and association visual cortex (Brodmann 17/18/19, around the calcarine fissure).','Posterior dominant (alpha) rhythm, lambda waves, POSTS, photic driving','Electrode pop, neck muscle at low occipital positions'],
O2:['R occipital','O','Right occipital pole: primary and association visual cortex (Brodmann 17/18/19, around the calcarine fissure).','Posterior dominant (alpha) rhythm, lambda waves, POSTS, photic driving','Electrode pop, neck muscle at low occipital positions'],
T3:['L mid-temporal','T','Left middle temporal gyrus on the side of the brain, sitting just above the superior temporal gyrus (auditory cortex; Brodmann 21/22). Also called T7 in the 10-10 system.','Wickets, temporal alpha-range ("third rhythm"), temporal spikes and TIRDA','Jaw clenching (temporalis muscle); pulse from the temporal artery'],
T4:['R mid-temporal','T','Right middle temporal gyrus on the side of the brain, sitting just above auditory cortex (Brodmann 21/22). Also called T8 in the 10-10 system.','Wickets, temporal alpha-range ("third rhythm"), temporal spikes and TIRDA','Jaw clenching (temporalis muscle); pulse from the temporal artery'],
T5:['L posterior temporal','T','Left posterior temporal cortex where the temporal, parietal and occipital lobes meet (Brodmann 37/39). Also called P7 in the 10-10 system.','Posterior temporal spikes, POSTS, alpha that spreads laterally','Neck muscle, electrode pop'],
T6:['R posterior temporal','T','Right posterior temporal cortex where the temporal, parietal and occipital lobes meet (Brodmann 37/39). Also called P8 in the 10-10 system.','Posterior temporal spikes, POSTS, alpha that spreads laterally','Neck muscle, electrode pop'],
A1:['L ear (reference)','R','Left earlobe or mastoid. It is not over cortex, so it is used as a reference. It is not silent: it picks up inferior and anterior temporal activity and the heart.','Reference only. A temporal spike at T3 leaks into A1','ECG, temporalis muscle'],
A2:['R ear (reference)','R','Right earlobe or mastoid. It is not over cortex, so it is used as a reference. It is not silent: it picks up inferior and anterior temporal activity and the heart.','Reference only. A temporal spike at T4 leaks into A2','ECG, temporalis muscle'],
Fpz:['Midline frontopolar','F','Midline frontal pole. Often used as the ground electrode, which does not carry signal but anchors the patient to the amplifier common.','Ground in many systems','n/a'],
Oz:['Midline occipital','O','Medial occipital cortex at the back of the head. Not part of the basic 19-electrode set.','Posterior dominant rhythm','Electrode pop']};
const LOBE={F:['Frontal','#3b82c4'],C:['Central','#2e9e5b'],P:['Parietal','#8e63d6'],T:['Temporal','#d98b2b'],O:['Occipital','#cc3d5f'],R:['Reference','#7a8794']};
const XY={};EL.forEach(e=>XY[e[0]]=[e[1],-e[2]]);XY.Fpz=[0,-1];XY.Oz=[0,1];XY.A1=[-1.33,.06];XY.A2=[1.33,.06];XY.Nasion=[0,-1.14];XY.Inion=[0,1.14];XY.LPA=[-1.13,0];XY.RPA=[1.13,0];
const BUILD=[
{t:'1. Find the landmarks',add:['Nasion','Inion','LPA','RPA'],txt:'Four bony landmarks anchor everything. The <b>nasion</b> is the dip at the top of the nose between the eyes. The <b>inion</b> is the bump you can feel at the base of the back of the skull. The <b>left and right preauricular points</b> are the small depressions just in front of each ear.'},
{t:'2. Measure nasion to inion',add:['Fpz','Fz','Cz','Pz','Oz'],line:[['Nasion','Inion']],txt:'Measure the arc from nasion over the top of the head to inion. Mark points at <b>10%</b>, then every <b>20%</b>: <b>Fpz</b> (10%), <b>Fz</b> (30%), <b>Cz</b> (50%, the vertex), <b>Pz</b> (70%), <b>Oz</b> (90%). The "10 and 20" in the name comes from these steps.'},
{t:'3. Measure ear to ear',add:['T3','C3','C4','T4'],line:[['LPA','RPA']],txt:'Measure the arc from one preauricular point to the other across the vertex. It must cross Cz. Mark at 10%, 30%, 50%, 70% and 90%: <b>T3</b>, <b>C3</b>, <b>Cz</b>, <b>C4</b>, <b>T4</b>.'},
{t:'4. Measure the circumference',add:['Fp1','Fp2','F7','F8','T5','T6','O1','O2'],arc:true,txt:'Measure around the head through Fpz, T3, Oz and T4. Along each side, from Fpz to Oz, mark 10%, 30%, 50%, 70% and 90% of that arc: <b>Fp1, F7, T3, T5, O1</b> on the left and <b>Fp2, F8, T4, T6, O2</b> on the right. T3 and T4 fall exactly where the ear-to-ear arc crosses.'},
{t:'5. Fill in the gaps',add:['F3','F4','P3','P4'],line:[['Fp1','O1'],['Fp2','O2']],txt:'<b>F3, C3, P3</b> and the matching right-sided <b>F4, C4, P4</b> sit on the arcs from Fp1 to O1 and from Fp2 to O2. The five points on each arc are evenly spaced: Fp1, F3, C3, P3, O1. F3 lies roughly halfway between Fz and F7, and P3 roughly halfway between Pz and T5.'},
{t:'6. Reference and ground',add:['A1','A2'],txt:'The 19 scalp electrodes are done. <b>A1</b> and <b>A2</b> are the ear (or mastoid) electrodes used as reference. A <b>ground</b> electrode (often near Fpz) is also attached. It carries no signal but lets the amplifier cancel noise common to every electrode. In total, 19 recording electrodes + 2 reference + 1 ground.'}];
const MONT={tcp:{name:'Longitudinal bipolar (double banana)',pairs:TCP.map(p=>[p[0],p[1]])},trans:{name:'Transverse bipolar',pairs:TRANS.map(p=>[p[0],p[1]])},
 ear:{name:'Referential, ear reference',pairs:AVGL.map(n=>[n,n.endsWith('z')?'A1+A2':(+n.slice(-1))%2?'A1':'A2'])},cz:{name:'Referential, Cz reference',pairs:AVGL.filter(n=>n!=='Cz').map(n=>[n,'Cz'])},avg:{name:'Average reference',pairs:AVGL.map(n=>[n,'Avg'])}};
function buildLead(){const H=$('#aLead');H.innerHTML='';const st={mode:'explore',sel:'C3',step:0,m:'tcp',ch:0};
  const top=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Where each lead sits and what it looks at</h2><div class="row" id="lCtl"></div></div>
  <div class="lead2"><div><div id="lMap"></div><div class="row" id="lLeg" style="gap:6px 14px;margin-top:6px"></div></div><div id="lSide" class="stack" style="gap:10px;min-width:0"></div></div>`);H.appendChild(top);
  segment($('#lCtl',top),[['explore','Explore the leads'],['build','Build the 10–20 system'],['chan','Channels: Input 1 / Input 2']],'explore',v=>{st.mode=v;render()});
  Object.entries(LOBE).forEach(([k,[n,c]])=>$('#lLeg',top).appendChild(el('span','lbl',`<i class="dot" style="background:${c}"></i>${n}`)));
  function vis(){if(st.mode==='explore')return EL.map(e=>e[0]).concat(['A1','A2']);if(st.mode==='chan')return EL.map(e=>e[0]).concat(['A1','A2']);const o=[];for(let i=0;i<=st.step;i++)o.push(...BUILD[i].add);return o}
  function render(){const V=vis(),cur=st.mode==='build'?BUILD[st.step].add:[],R=.1;let s='';
    s+=`<svg viewBox="-1.62 -1.45 3.24 2.92" role="img" aria-label="Top view of the head, nose at top, with the electrode positions" style="width:100%;max-width:560px;display:block;margin:auto"><defs><radialGradient id="vg"><stop offset="0" stop-color="var(--accent)" stop-opacity=".38"/><stop offset="1" stop-color="var(--accent)" stop-opacity="0"/></radialGradient><clipPath id="hc"><circle r="1.14"/></clipPath><marker id="ar" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6z" fill="var(--mark)"/></marker></defs>`;
    s+=`<g clip-path="url(#hc)" opacity="${st.mode==='build'?.0:.13}"><rect x="-1.2" y="-1.2" width="2.4" height="0.85" fill="${LOBE.F[1]}"/><rect x="-1.2" y="-.35" width="2.4" height=".7" fill="${LOBE.C[1]}"/><rect x="-1.2" y=".35" width="2.4" height=".35" fill="${LOBE.P[1]}"/><rect x="-1.2" y=".7" width="2.4" height=".6" fill="${LOBE.O[1]}"/><rect x="-1.2" y="-.45" width=".5" height="1.05" fill="${LOBE.T[1]}"/><rect x=".7" y="-.45" width=".5" height="1.05" fill="${LOBE.T[1]}"/></g>`;
    s+=`<path d="M-.14 -1.13 L0 -1.3 L.14 -1.13" fill="none" stroke="var(--muted)" stroke-width=".02"/><path d="M-1.14 -.14 C-1.3 -.14 -1.34 .22 -1.14 .26 M1.14 -.14 C1.3 -.14 1.34 .22 1.14 .26" fill="none" stroke="var(--muted)" stroke-width=".02"/><circle r="1.14" fill="none" stroke="var(--muted)" stroke-width=".022"/>`;
    s+=`<path d="M0 -1.14V1.14M-1.14 0H1.14" stroke="var(--grid-major)" stroke-width=".008" stroke-dasharray=".03 .03"/>`;
    if(st.mode==='build'){const b=BUILD[st.step];s+=`<g stroke="var(--accent)" stroke-width=".014" fill="none" stroke-dasharray=".05 .03">`;(b.line||[]).forEach(([a,c])=>{s+=`<path d="M${XY[a][0]} ${XY[a][1]}L${XY[c][0]} ${XY[c][1]}"/>`});if(b.arc)s+=`<circle r="1" />`;s+=`</g>`}
    if(st.mode==='build'){V.forEach(n=>{if(['Nasion','Inion','LPA','RPA'].includes(n)){const[x,y]=XY[n];s+=`<g><path d="M${x} ${y-.07}L${x+.07} ${y}L${x} ${y+.07}L${x-.07} ${y}Z" fill="${cur.includes(n)?'var(--accent)':'var(--muted)'}"/><text x="${x+(x===0?.12:0)}" y="${x===0?y+.03:y-.12}" font-size=".075" text-anchor="${x===0?'start':'middle'}" fill="var(--ink)" font-family="var(--font-mono)">${n==='LPA'?'L preauricular':n==='RPA'?'R preauricular':n}</text></g>`}})}
    if(st.mode==='explore'){const[x,y]=XY[st.sel];s+=`<circle cx="${x}" cy="${y}" r=".42" fill="url(#vg)"/>`}
    if(st.mode==='chan'){const p=MONT[st.m].pairs[st.ch];if(p){const a=XY[p[0]];let tg=XY[p[1]];if(p[1]==='A1+A2')s+=`<path d="M${a[0]} ${a[1]}L${XY.A1[0]} ${XY.A1[1]}M${a[0]} ${a[1]}L${XY.A2[0]} ${XY.A2[1]}" stroke="var(--mark)" stroke-width=".022" stroke-dasharray=".04 .03"/>`;else if(tg)s+=`<path d="M${a[0]} ${a[1]}L${tg[0]} ${tg[1]}" stroke="var(--mark)" stroke-width=".026" marker-end="url(#ar)"/>`;else s+=`<text x="0" y="-.23" font-size=".085" text-anchor="middle" fill="var(--mark)" font-family="var(--font-mono)">Input 2 = mean of all electrodes</text>`}}
    V.forEach(n=>{if(['Nasion','Inion','LPA','RPA'].includes(n))return;const[x,y]=XY[n],lobe=(ELI[n]||[,'F'])[1],col=LOBE[lobe][1],isSel=st.mode==='explore'&&n===st.sel,nw=cur.includes(n),p=st.mode==='chan'?MONT[st.m].pairs[st.ch]:null,g1=p&&p[0]===n,g2=p&&p[1]===n;
      s+=`<g class="el" tabindex="${st.mode==='build'?-1:0}" role="button" data-n="${n}" aria-label="${n}, ${(ELI[n]||[''])[0]}"><circle cx="${x}" cy="${y}" r="${R}" fill="${g2?'var(--panel)':col}" stroke="${isSel||nw||g1||g2?'var(--ink)':'var(--panel)'}" stroke-width="${isSel||nw||g1||g2?.032:.014}"/>${g2?`<circle cx="${x}" cy="${y}" r="${R-.02}" fill="none" stroke="${col}" stroke-width=".03"/>`:''}<text x="${x}" y="${y+.027}" font-size=".078" text-anchor="middle" fill="${g2?'var(--ink)':'#fff'}" font-weight="600" font-family="var(--font-mono)" pointer-events="none">${n}</text>${g1?`<text x="${x+.12}" y="${y-.1}" font-size=".09" fill="var(--mark)" font-weight="700" font-family="var(--font-mono)">1</text>`:''}${g2?`<text x="${x+.12}" y="${y-.1}" font-size=".09" fill="var(--mark)" font-weight="700" font-family="var(--font-mono)">2</text>`:''}</g>`});
    s+=`<text x="0" y="-1.37" font-size=".07" text-anchor="middle" fill="var(--muted)" font-family="var(--font-mono)">FRONT (nose)</text><text x="0" y="1.43" font-size=".07" text-anchor="middle" fill="var(--muted)" font-family="var(--font-mono)">BACK</text><text x="-1.58" y="-.02" font-size=".065" fill="var(--muted)" font-family="var(--font-mono)">LEFT</text><text x="1.58" y="-.02" font-size=".065" text-anchor="end" fill="var(--muted)" font-family="var(--font-mono)">RIGHT</text></svg>`;
    $('#lMap',top).innerHTML=s;$$('#lMap .el',top).forEach(g=>{const n=g.dataset.n,act=()=>{if(st.mode==='explore'){st.sel=n;render()}else if(st.mode==='chan'){const i=MONT[st.m].pairs.findIndex(p=>p[0]===n);if(i>=0){st.ch=i;render()}}};g.addEventListener('click',act);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();act()}})});
    side()}
  function side(){const S=$('#lSide',top);
    if(st.mode==='explore'){const n=st.sel,d=ELI[n],lb=LOBE[d[1]];S.innerHTML=`<div class="row" style="gap:10px"><h2 style="font-size:22px">${n}</h2><span class="pill" style="border-color:${lb[1]};color:var(--ink)">${lb[0]}</span><span class="lbl">${d[0]}</span></div><dl class="facts"><dt>Looks at</dt><dd>${d[2]}</dd><dt>Typical activity</dt><dd>${d[3]}</dd><dt>Artifact to expect</dt><dd>${d[4]}</dd></dl><div class="note"><b>What "looking at" means.</b> An electrode is not a camera. It reports the electrical field summed over several square centimetres of cortex, blurred by cerebrospinal fluid, skull and scalp. It is most sensitive to cortex directly beneath it and to cortex whose neurons point straight outward (the crowns of gyri). Activity buried in sulci or deep in the middle of the brain is weak or reaches neighbouring electrodes instead. The shaded disc is the rough area it samples.</div><p class="lbl">Click any electrode or press Tab then Enter</p>`}
    else if(st.mode==='build'){const b=BUILD[st.step];S.innerHTML=`<h2>${b.t}</h2><p>${b.txt}</p><div class="row"><button class="btn small" id="bPrev" type="button" ${st.step?'':'disabled'}>Back</button><button class="btn small primary" id="bNext" type="button" ${st.step<BUILD.length-1?'':'disabled'}>Next step</button><span class="lbl">Step ${st.step+1} of ${BUILD.length}</span></div><div class="note"><b>Naming rule.</b> Letter = region (Fp frontal pole, F frontal, C central, P parietal, T temporal, O occipital, A ear). Number = side and distance: <b>odd = left, even = right, z = midline</b> ("zero"). Within a side, a bigger number is farther from the midline, so F3 is nearer the midline than F7. Standard spacing is the same fraction of every head, so a child and an adult are measured the same way.</div>`;
      $('#bPrev',S).onclick=()=>{st.step--;render()};$('#bNext',S).onclick=()=>{st.step++;render()}}
    else{const M=MONT[st.m];S.innerHTML=`<div class="row"><label class="row lbl" style="gap:6px;text-transform:none;letter-spacing:0">Montage <select id="mSel"></select></label></div><div class="tw" style="max-height:290px;overflow:auto"><table><thead><tr><th>#</th><th>Input 1 (G1)</th><th>Input 2 (G2)</th><th>Samples</th></tr></thead><tbody id="mTb"></tbody></table></div><div id="mTx" class="note"></div>`;
      const sel=$('#mSel',S);Object.entries(MONT).forEach(([k,m])=>sel.appendChild(new Option(m.name,k)));sel.value=st.m;sel.onchange=()=>{st.m=sel.value;st.ch=0;render()};
      $('#mTb',S).innerHTML=M.pairs.map((p,i)=>{const a=ELI[p[0]][0],b=ELI[p[1]]?ELI[p[1]][0]:null;return`<tr data-i="${i}" ${i===st.ch?'aria-current="true"':''} style="cursor:pointer"><td>${i+1}</td><td><b>${p[0]}</b></td><td>${p[1]}</td><td>${st.m==='tcp'||st.m==='trans'?a+' ↔ '+b:a}</td></tr>`}).join('');
      $$('#mTb tr',S).forEach(r=>r.addEventListener('click',()=>{st.ch=+r.dataset.i;render()}));const p=M.pairs[st.ch],bip=st.m==='tcp'||st.m==='trans';
      $('#mTx',S).innerHTML=`<b>${p[0]} − ${p[1]==='Avg'?'average of all electrodes':p[1]}.</b> The amplifier plots Input 1 minus Input 2. When Input 1 is <b>more negative</b> than Input 2 the trace deflects <b>up</b>; when it is more positive the trace goes <b>down</b>. ${bip?'Because both inputs are on the scalp, activity common to both cancels and only the <i>difference</i> between the two sites is drawn. That is why bipolar channels localize well (phase reversals) and why very widespread slow activity can look smaller.':'Input 2 is meant to be quiet, so each trace approximates the absolute potential under Input 1. Any activity at the reference leaks into every channel with the opposite sign.'}`;
      const cr=$('#mTb tr[aria-current]',S);if(cr)cr.scrollIntoView({block:'nearest'})}}
  render();

  // rules card
  H.appendChild(el('div','card two',`<div><h3>Which lead is positive and which is negative?</h3><ul class="f"><li>An EEG channel is always a <b>difference</b> of two inputs, Input 1 (G1) and Input 2 (G2). Neither wire is inherently positive or negative.</li><li>By convention, if <b>Input 1 is more negative than Input 2, the pen deflects up</b>. More positive deflects down. So <b>negativity is plotted up</b>.</li><li>The channel is a statement about <b>Input 1 relative to Input 2</b>. Swap them and the trace flips.</li><li>A <b>ground</b> is also attached to the patient. It is not a recording input; it lets the amplifier reject mains hum common to everything.</li></ul></div><div><h3>Reading polarity to find a focus</h3><ul class="f"><li>In a bipolar chain, the electrode shared by two adjacent channels is the one that matters. If those two channels deflect in <b>opposite</b> directions, it is a <b>phase reversal</b>, and the source is under the shared electrode.</li><li>For a surface-<b>negative</b> source, the pair of tips <b>point toward each other</b> (upper channel down, lower channel up). For a surface-positive source they point away.</li><li>In a referential montage, find the electrode with the biggest deflection. The reference must be quiet or its activity appears in every channel.</li><li>Try it in the polarity lab below.</li></ul></div>`));
  polLab(H);
  AX.draws.lead=[()=>AX.polDraw&&AX.polDraw()];
}
function polLab(H){const CH=['Fp1','F3','C3','P3','O1'],st={s:2,pol:-1,sg:.75};
  const card=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Polarity lab: moving a source under a chain of leads</h2><div class="row" id="pCtl"></div></div><p style="max-width:84ch">A small patch of cortex, a <i>source</i>, makes a field that falls off with distance. Slide it along the left parasagittal chain (Fp1, F3, C3, P3, O1). The top row is the field on the scalp. The middle row is what a bipolar chain draws, each channel Input 1 minus Input 2. The bottom row is what each electrode draws against a quiet reference.</p><div id="pSl" class="stack" style="gap:8px"></div><canvas style="display:block;width:100%;height:450px"></canvas><div id="pTx" class="note"></div>`);H.appendChild(card);
  const cv=$('canvas',card),sl=slider($('#pSl',card),'Source position',{min:-.5,max:4.5,step:.05,val:2,fmt:v=>`${v<-.2||v>4.2?'beyond the chain, near ':'near '}${CH[clamp(Math.round(v),0,4)]}`},v=>{st.s=v;draw()});
  segment($('#pCtl',card),[['-1','Surface-negative source'],['1','Surface-positive source']],'-1',v=>{st.pol=+v;draw()});segment($('#pCtl',card),[['.75','Superficial'],['1.5','Deeper, broader']],'.75',v=>{st.sg=+v;draw()});
  function draw(){const S=cvSetup(cv);if(!S)return;const{g,w,C}=S,ml=14,mr=14,X=i=>ml+(i+.7)/5.4*(w-ml-mr),V=i=>st.pol*Math.exp(-Math.pow(i-st.s,2)/(2*st.sg*st.sg)),fm=getComputedStyle(document.body).getPropertyValue('--font-mono'),ff_=getComputedStyle(document.body).fontFamily;
    const yA=78,kA=52,yB=212,kB=95,yC=386,kC=52;
    const lab=(t,y)=>{g.fillStyle=C.muted;g.font='10.5px '+fm;g.textAlign='left';g.fillText(t,ml,y)};
    const arrow=(x,y0,dy,col)=>{g.strokeStyle=col;g.fillStyle=col;g.lineWidth=3;if(Math.abs(dy)<2.5){g.beginPath();g.arc(x,y0,2.6,0,6.3);g.fill();return}g.beginPath();g.moveTo(x,y0);g.lineTo(x,y0+dy-Math.sign(dy)*7);g.stroke();g.beginPath();g.moveTo(x,y0+dy);g.lineTo(x-6,y0+dy-Math.sign(dy)*10);g.lineTo(x+6,y0+dy-Math.sign(dy)*10);g.closePath();g.fill()};
    [yA,yB,yC].forEach(y=>{g.strokeStyle=C.major;g.lineWidth=1;g.beginPath();g.moveTo(ml,y+.5);g.lineTo(w-mr,y+.5);g.stroke()});
    lab('SCALP POTENTIAL  (negativity plotted up)',14);lab('BIPOLAR CHAIN  (Input 1 − Input 2)',140);lab('REFERENTIAL  (each electrode − quiet reference)',318);
    g.strokeStyle=C.ink;g.lineWidth=1.6;g.beginPath();for(let px=0;px<=w-ml-mr;px+=2){const i=(px/(w-ml-mr)*5.4)-.7;const x=ml+px,y=yA+V(i)*kA;px?g.lineTo(x,y):g.moveTo(x,y)}g.stroke();
    const ds=[];for(let j=0;j<4;j++)ds.push(V(j)-V(j+1));
    CH.forEach((n,i)=>{g.fillStyle=C.ink;g.beginPath();g.arc(X(i),yA+V(i)*kA,4,0,6.3);g.fill();g.fillStyle=C.muted;g.font='11px '+fm;g.textAlign='center';g.fillText(n,X(i),st.pol<0?yA+17:yA-10)});
    const col=d=>d>0?C.mark:C.accent;
    ds.forEach((d,j)=>{const x=(X(j)+X(j+1))/2;arrow(x,yB,d*kB,col(d));g.fillStyle=C.muted;g.font='11px '+fm;g.textAlign='center';g.fillText(CH[j]+'–'+CH[j+1],x,yB+72)});
    CH.forEach((n,i)=>{const v=V(i);arrow(X(i),yC,v*kC,col(v));g.fillStyle=C.muted;g.font='11px '+fm;g.textAlign='center';g.fillText(n,X(i),yC+52)});
    g.font='11px '+ff_;g.textAlign='right';g.fillStyle=C.accent;g.fillText('▲ up = Input 1 more negative',w-mr,14);g.fillStyle=C.mark;g.fillText('▼ down = Input 1 more positive',w-mr,28);
    // reversal
    const sig=[];ds.forEach((d,j)=>{if(Math.abs(d)>.05)sig.push(j)});let rev=null;for(let k=0;k<sig.length-1;k++){const a=sig[k],b=sig[k+1];if(ds[a]*ds[b]<0){rev={a,b};break}}
    const dir=d=>d>0?'down':'up';let tx;
    if(rev){const{a,b}=rev;const neg=ds[a]>0,at=b===a+1?CH[b]:null,x0=at?X(b):(X(a+1)+X(b))/2;g.strokeStyle=C.good;g.lineWidth=1.5;g.setLineDash([5,4]);g.beginPath();g.moveTo(x0,30);g.lineTo(x0,yC+36);g.stroke();g.setLineDash([]);g.fillStyle=C.good;g.font='600 11px '+fm;g.textAlign='center';g.fillText('phase reversal',x0,122);
      tx=at?`<b>Phase reversal at ${at}.</b> ${CH[a]}–${CH[a+1]} deflects <b>${dir(ds[a])}</b> and ${CH[b]}–${CH[b+1]} deflects <b>${dir(ds[b])}</b>. The tips point <b>${neg?'toward':'away from'}</b> each other, so the focus is <b>${neg?'surface-negative':'surface-positive'}</b> and lies under <b>${at}</b>.`:`<b>Reversal across a flat channel.</b> The source sits between ${CH[a+1]} and ${CH[b]}, which read nearly the same (equipotential), so their channel is flat and the reversal straddles it. The focus is ${neg?'surface-negative':'surface-positive'}.`}
    else tx=`<b>No phase reversal.</b> The source is beyond the end of this chain, so every channel deflects the same way and the amplitude is biggest at the end nearest the source. A chain that shows no reversal does not contain the focus. You need a neighbouring chain.`;
    tx+=` In the bottom row, the electrode with the tallest arrow is the one closest to the source.`;$('#pTx',card).innerHTML=tx}
  AX.polDraw=draw}

/* ---- Signal & filters panel ---- */
const stageFc=(k,f,n)=>{const q=Math.sqrt(Math.pow(2,1/n)-1);return k==='hp'?f*q:f/q};
function rc1(x,fc,type){const K=Math.tan(Math.PI*fc/FS),y=new Float32Array(x.length);let px=x[0],py=type==='lp'?x[0]:0;if(type==='lp'){const a=K/(1+K),b=(1-K)/(1+K);for(let i=0;i<x.length;i++){py=a*(x[i]+px)+b*py;px=x[i];y[i]=py}}else{const c=1/(1+K),b=(1-K)/(1+K);for(let i=0;i<x.length;i++){py=c*(x[i]-px)+b*py;px=x[i];y[i]=py}}return y}
function magK(k,f){const w=2*Math.PI*f/FS,c1=Math.cos(w),s1=Math.sin(w),c2=Math.cos(2*w),s2=Math.sin(2*w);return Math.hypot(k[0]+k[1]*c1+k[2]*c2,k[1]*s1+k[2]*s2)/Math.hypot(1+k[3]*c1+k[4]*c2,k[3]*s1+k[4]*s2)}
function gainRC(kind,f,fc,n){const x=Math.tan(Math.PI*f/FS)/Math.tan(Math.PI*fc/FS);return kind==='lp'?Math.pow(1/Math.sqrt(1+x*x),n):Math.pow(x/Math.sqrt(1+x*x),n)}
const NOTCH=bq('notch',60,25);
const card=(h,body)=>el('div','card stack',`<h2>${h}</h2>${body}`);

function buildSig(){const H=$('#aSig');H.innerHTML='';
  // 1. pipeline
  H.appendChild(el('div','card stack',`<h2>From brain to screen: how a scalp signal is measured</h2><p style="max-width:84ch">A scalp EEG is a few tens of microvolts, about a thousand times smaller than the ECG on the same patient. Everything that makes a tracing clear is about protecting that tiny difference from much larger interference. Follow the chain left to right.</p>
  <div class="pipe"><div class="stage"><b>1 Electrode and skin</b><span>Silver/silver chloride or gold cup with conductive gel on abraded skin. Aim for impedance under 5 kΩ and similar at every site.</span></div><div class="stage"><b>2 Differential amplifier</b><span>Subtracts Input 2 from Input 1 and multiplies the difference about 1000 times. Noise common to both inputs cancels. A ground electrode anchors the patient. Good amplifiers reject common signals by more than 100 dB.</span></div><div class="stage"><b>3 Anti-alias filter</b><span>A hardware low-pass keeps frequencies above half the sampling rate out, so they cannot fold back as false slow waves.</span></div><div class="stage"><b>4 Digitizer</b><span>Samples 256 to 512 times a second or more, with enough resolution to see a fraction of a microvolt.</span></div><div class="stage"><b>5 Display filters</b><span>Low-frequency filter (high-pass), high-frequency filter (low-pass) and a 60 Hz notch are chosen for each view and normally leave the stored data untouched.</span></div><div class="stage"><b>6 Display</b><span>Sensitivity in µV per mm (7 is typical) and a 30 mm per second time base.</span></div></div>
  <ul class="f" style="columns:2;column-gap:28px"><li>Brain: 10 to 100 µV, 0.5 to 40 Hz mostly</li><li>ECG: about 1 mV on the chest, much less on the scalp</li><li>Muscle: hundreds of µV, 20 to 300 Hz</li><li>Mains pickup: can be thousands of µV at the input, at exactly 60 Hz (50 Hz in many countries)</li><li>Sweat and electrode drift: hundreds of µV, below 0.5 Hz</li><li>Eye movement: hundreds of µV, below about 5 Hz</li></ul>`));

  // 2. reading amplitude and time
  const rd=el('div','card stack',`<h2>Measuring a wave on the page</h2><p style="max-width:84ch">The standard display is <b>30 mm per second</b>, so 1 mm is about 33 ms and 30 mm is exactly 1 s. Height is set by the <b>sensitivity</b>: at 7 µV/mm, a wave 5 mm tall (peak to peak) is 35 µV. Count waves, measure the paper, and the arithmetic follows.</p><div class="calc"><label>Waves counted<input type="number" id="cN" value="10" min="1" step="1"></label><label>over (mm of paper)<input type="number" id="cD" value="30" min="1" step="1"></label><label>Paper speed<select id="cS"><option>15</option><option selected>30</option><option>60</option></select></label><label>Wave height (mm, peak to peak)<input type="number" id="cH" value="5" min="0" step=".5"></label><label>Sensitivity (µV/mm)<select id="cV"><option>3</option><option>5</option><option selected>7</option><option>10</option><option>15</option><option>20</option></select></label></div><p id="cOut" class="note"></p>`);H.appendChild(rd);
  const calc=()=>{const n=+$('#cN',rd).value,d=+$('#cD',rd).value,sp=+$('#cS',rd).value,h=+$('#cH',rd).value,sv=+$('#cV',rd).value;const f=d>0?n/(d/sp):0;const b=f<.5?'infraslow':f<4?'delta':f<8?'theta':f<13?'alpha range':f<=30?'beta':'gamma';$('#cOut',rd).innerHTML=`<b>${f.toFixed(1)} Hz</b> (${b}). ${n} waves in ${(d/sp).toFixed(2)} s. Amplitude <b>${(h*sv).toFixed(0)} µV</b> peak to peak. One cycle is ${(1000/Math.max(f,.01)).toFixed(0)} ms.`};$$('input,select',rd).forEach(i=>i.addEventListener('input',calc));calc();

  diffLab(H);filtLab(H);rcLab(H);aliasLab(H);

  // checklist
  H.appendChild(el('div','card two',`<div><h3>Settings in routine use</h3><div class="tw"><table><thead><tr><th>Filter</th><th>Corner</th><th>Time constant</th></tr></thead><tbody>${[['Low-frequency (high-pass)',.1],['',.3],['',.5],['',1],['',5],['High-frequency (low-pass)',15],['',35],['',70]].map(([n,f],i)=>`<tr><td>${n||''}</td><td>${f} Hz</td><td>${(1/(2*Math.PI*f)).toFixed(f<2?2:3)} s</td></tr>`).join('')}</tbody></table></div><p class="lbl" style="margin-top:8px">Time constant TC = 1 ÷ (2π × corner frequency)</p></div>
  <div><h3>Pitfalls</h3><ul class="f"><li><b>Low-frequency filter too high</b> (above about 1 Hz) removes true delta, shrinks slow waves and bends the baseline after every big deflection.</li><li><b>High-frequency filter too low</b> rounds off spikes so they look like slow waves and hides fast activity. It also removes muscle, which can make a tracing look cleaner than the recording was.</li><li><b>The 60 Hz notch</b> hides, rather than cures, a poor electrode connection. Fix the contact first, and use the notch last.</li><li><b>Filters ring.</b> A sharp event passed through a filter can leave an echo that looks like a second wave, and a filtered tracing is not a faithful copy of what the brain did.</li><li><b>Compare before you conclude.</b> If a pattern changes drastically when a filter is changed, it was filter-sensitive. Review it with wide settings.</li></ul></div>`));
  H.appendChild(el('div','card stack',`<h2>Checklist for a clean tracing</h2><ul class="f" style="columns:2;column-gap:28px"><li><b>Skin and electrodes.</b> Abrade, gel, check impedance under 5 kΩ and balanced between sites.</li><li><b>Matched impedance.</b> Common-mode rejection is only as good as the match between the two inputs.</li><li><b>Ground and shielding.</b> Short twisted leads, keep cables away from mains cords and monitors, one ground.</li><li><b>Right montage.</b> Bipolar to localize, referential for field and amplitude, average reference only with wide coverage.</li><li><b>Filters in their place.</b> Wide while reading, narrow only to confirm, notch last.</li><li><b>Sampling high enough.</b> At least 3 times the highest frequency of interest, with the anti-alias filter on.</li><li><b>Document artifacts.</b> Tag blinks, chewing, movement and electrode pops so they are not read as brain.</li><li><b>Averaging.</b> For evoked responses, noise falls with the square root of the number of trials averaged, so 100 trials gain 10 times in signal-to-noise.</li></ul>`));
  AX.draws.sig=[()=>AX.sigDraw.forEach(f=>f())]}
AX.sigDraw=[];

/* ---- differential amplifier lab ---- */
function diffLab(H){const LEN=400,r=mkRand(41),t=i=>i/FS,st={mains:300,m:.25};
  const p=phs(r,10,.03,LEN),e=envl(r,.6,LEN),n1=bn(r,3,8,1,LEN),n2=bn(r,3,8,1,LEN),a=new Float32Array(LEN),b=new Float32Array(LEN),mains=new Float32Array(LEN);
  for(let i=0;i<LEN;i++){a[i]=Math.sin(p[i])*e[i]*26+n1[i]*6;mains[i]=Math.sin(6.2832*60*t(i))}for(let i=0;i<LEN;i++)b[i]=.6*(a[Math.max(0,i-8)])+n2[i]*7;
  const c=el('div','card stack',`<h2>Why two inputs? The differential amplifier</h2><p style="max-width:84ch">Both electrodes pick up the same 60 Hz hum from the room, hundreds of times bigger than the brain signal. Because the hum is <i>common</i> to both inputs, subtracting one from the other removes it, while the brain signal, which differs between sites, survives. The cancellation is only as good as the <b>balance</b> between the two skin contacts. Unequal impedance turns some of the common hum into a difference.</p><div id="dfS" class="stack" style="gap:8px"></div><div class="vwrap"><div id="dfC"></div></div><p id="dfT" class="note"></p>`);H.appendChild(c);
  const cv=mkCanvas($('#dfC',c),400),sm=slider($('#dfS',c),'Mains pickup',{min:0,max:600,step:10,val:300,fmt:v=>v+' µV'},v=>{st.mains=v;draw()}),si=slider($('#dfS',c),'Impedance mismatch',{min:0,max:100,step:1,val:25,fmt:v=>v+' %'},v=>{st.m=v/100;draw()});
  const bt=el('button','btn small','Prepare the skin (match the contacts)');bt.type='button';bt.addEventListener('click',()=>{si.set(3);st.m=.03;draw()});$('#dfS',c).appendChild(bt);
  function draw(){const e1=new Float32Array(LEN),e2=new Float32Array(LEN),out=new Float32Array(LEN),idl=new Float32Array(LEN);for(let i=0;i<LEN;i++){e1[i]=a[i]+st.mains*mains[i];e2[i]=b[i]+(1-st.m)*st.mains*mains[i];out[i]=e1[i]-e2[i];idl[i]=a[i]-b[i]}
    const rows=[{data:e1,label:'Electrode 1',sub:'EEG + hum',px:.1},{data:e2,label:'Electrode 2',sub:'EEG + hum (unequal)',px:.1},{data:out,label:'Output',sub:'Input 1 − Input 2',px:.8,color:cssv().accent},{data:idl,label:'Ideal',sub:'no hum at all',px:.8}];
    cv.style.height=(4+rows.length*88+22)+'px';drawRows(cv,rows,{rowH:88,t0:0,dur:2,labelW:132,lw:1.2});
    const res=st.m*st.mains,rej=st.m>0?20*Math.log10(1/st.m):Infinity;$('#dfT',c).innerHTML=`Hum left in the output: <b>${res.toFixed(0)} µV</b> (hum in each electrode ${st.mains} µV; ideal EEG difference about 25 µV). Rejection achieved: <b>${isFinite(rej)?rej.toFixed(0)+' dB':'complete'}</b>. ${st.m>.1?'The brain signal is buried: this is why high or unequal electrode impedance makes a 60 Hz tracing.':st.m>.03?'Better. The hum is smaller than the EEG but still visible.':'The hum cancels almost completely.'}`}
  AX.sigDraw.push(draw)}

/* ---- filter lab ---- */
function filtLab(H){const L=6000,r=mkRand(23),st={lff:.5,hff:70,notch:false,ord:1,on:new Set(['spk','drift','emg','mains'])},T0=20,DU=5;
  const x={eeg:new Float32Array(L),spk:new Float32Array(L),drift:bn(r,.05,.4,150,L),emg:bn(r,25,85,12,L),mains:new Float32Array(L),ecg:new Float32Array(L)};
  {const p=phs(r,10,.04,L),e=envl(r,.9,L),th=bn(r,4,7.5,7,L),de=bn(r,.5,3.5,14,L);for(let i=0;i<L;i++){x.eeg[i]=Math.sin(p[i])*e[i]*22+th[i]+de[i];x.mains[i]=30*Math.sin(6.2832*60*i/FS)}
   [21.6,23.9].forEach(c=>{for(let i=Math.floor((c-.1)*FS);i<(c+.7)*FS;i++){const q=i/FS-c;x.spk[i]+=-95*Math.exp(-Math.pow(q/.012,2))-45*Math.exp(-Math.pow((q-.15)/.09,2))}});
   for(let b=0;b*.8<L/FS;b++){const c=b*.8+.3;for(let i=Math.max(0,Math.floor((c-.2)*FS));i<Math.min(L,(c+.5)*FS);i++){const q=i/FS-c;x.ecg[i]+=60*Math.exp(-Math.pow(q/.011,2))+10*Math.exp(-Math.pow((q-.25)/.05,2))}}}
  const c=el('div','card stack',`<h2>Filters: what each one removes, and what it costs</h2><p style="max-width:84ch">Start with a recording contaminated by drift, muscle and mains hum, and watch the filters clean it. The bottom trace is the result; the top trace is the brain activity we hoped to recover. The response curve shows how each frequency is treated, with the EEG bands shaded. Push the low-frequency filter up and the delta band and the slow wave of the spike disappear. Pull the high-frequency filter down and the spike is rounded off.</p><div class="row" id="fChips"></div><div id="fS" class="stack" style="gap:8px"></div><div class="row" id="fCtl"></div><div class="vwrap"><div id="fC"></div></div><div class="vwrap"><div id="fR"></div></div><p id="fT" class="note"></p>`);H.appendChild(c);
  const chips=[['spk','Spike and slow wave'],['drift','Sweat / drift'],['emg','Muscle (EMG)'],['mains','60 Hz hum'],['ecg','ECG']];chips.forEach(([k,t])=>{const b=el('button','chip',t);b.type='button';b.setAttribute('aria-pressed',String(st.on.has(k)));b.addEventListener('click',()=>{st.on.has(k)?st.on.delete(k):st.on.add(k);b.setAttribute('aria-pressed',String(st.on.has(k)));draw()});$('#fChips',c).appendChild(b)});
  slider($('#fS',c),'Low-frequency filter',{min:.05,max:10,log:1,val:.5,fmt:v=>v.toFixed(v<1?2:1)+' Hz'},v=>{st.lff=v;draw()});slider($('#fS',c),'High-frequency filter',{min:10,max:90,log:1,val:70,fmt:v=>v.toFixed(0)+' Hz'},v=>{st.hff=v;draw()});
  const nl=el('label','row lbl','60 Hz notch');nl.style.cssText='gap:6px;text-transform:none;letter-spacing:0';const nc=el('input');nc.type='checkbox';nc.addEventListener('change',()=>{st.notch=nc.checked;draw()});nl.prepend(nc);$('#fCtl',c).appendChild(nl);
  const ol=el('span','lbl','Steepness');$('#fCtl',c).appendChild(ol);segment($('#fCtl',c),[['1','Gentle (1 stage)'],['2','Steeper (2)'],['4','Steep (4)']],'1',v=>{st.ord=+v;draw()});
  const cv=mkCanvas($('#fC',c),300),rcv=mkCanvas($('#fR',c),230);
  const gainAt=f=>{let g=1;for(let k=0;k<st.ord;k++)g*=gainRC('hp',f,stageFc('hp',st.lff,st.ord),1)*gainRC('lp',f,stageFc('lp',st.hff,st.ord),1);if(st.notch)g*=magK(NOTCH,f);return g};
  function draw(){const clean=new Float32Array(L),raw=new Float32Array(L);for(let i=0;i<L;i++){clean[i]=x.eeg[i]+(st.on.has('spk')?x.spk[i]:0);let v=clean[i];['drift','emg','mains','ecg'].forEach(k=>{if(st.on.has(k))v+=x[k][i]});raw[i]=v}
    let y=raw;for(let k=0;k<st.ord;k++)y=rc1(y,stageFc('hp',st.lff,st.ord),'hp');for(let k=0;k<st.ord;k++)y=rc1(y,stageFc('lp',st.hff,st.ord),'lp');if(st.notch)y=runbq(y,NOTCH);
    const rows=[{data:clean,label:'Brain signal',sub:'what we want',color:cssv().good},{data:raw,label:'Recorded',sub:'signal + noise'},{data:y,label:'After filters',sub:'what you see',color:cssv().accent}];
    cv.style.height=(4+rows.length*96+22)+'px';drawRows(cv,rows,{rowH:96,t0:T0,dur:DU,norm:true,labelW:112,lw:1.2});
    // response
    const S=cvSetup(rcv);if(S){const{g,w,h,C}=S,fm=getComputedStyle(document.body).getPropertyValue('--font-mono'),ml=44,mr=12,mt=22,mb=28,pw=w-ml-mr,ph=h-mt-mb,fx=f=>ml+Math.log10(f/.1)/3*pw,dy=d=>mt+(-d/60)*ph;
      BD.filter(b=>b.id!=='slow'&&b.id!=='mu'&&b.id!=='sigma').forEach(b=>{const r_={delta:[.5,4],theta:[4,8],alpha:[8,13],beta:[13,30],gamma:[30,80]}[b.id];g.globalAlpha=.16;g.fillStyle=b.color;g.fillRect(fx(r_[0]),mt,fx(r_[1])-fx(r_[0]),ph);g.globalAlpha=1;g.fillStyle=b.color;g.font='600 10.5px '+fm;g.textAlign='center';g.fillText(b.name.toLowerCase(),(fx(r_[0])+fx(r_[1]))/2,mt-7)});
      g.strokeStyle=C.grid;g.lineWidth=1;g.fillStyle=C.muted;g.font='10.5px '+fm;for(let d=0;d>=-60;d-=20){g.beginPath();g.moveTo(ml,dy(d)+.5);g.lineTo(w-mr,dy(d)+.5);g.stroke();g.textAlign='right';g.fillText(d+' dB',ml-5,dy(d)+4)}
      [.1,1,10,100].forEach(f=>{g.strokeStyle=C.major;g.beginPath();g.moveTo(fx(f)+.5,mt);g.lineTo(fx(f)+.5,mt+ph);g.stroke();g.textAlign='center';g.fillText(f+' Hz',fx(f),h-9)});
      g.strokeStyle=C.bad;g.setLineDash([4,4]);g.beginPath();g.moveTo(fx(60),mt);g.lineTo(fx(60),mt+ph);g.stroke();g.setLineDash([]);g.fillStyle=C.bad;g.textAlign='right';g.fillText('mains',fx(60)-4,mt+ph-6);g.fillText('muscle →',fx(25)-2,mt+ph-6);g.textAlign='left';g.fillText('drift',fx(.1)+4,mt+ph-6);
      g.strokeStyle=C.accent;g.lineWidth=2.6;g.beginPath();for(let k=0;k<=360;k++){const f=.1*Math.pow(1000,k/360),gv=Math.max(gainAt(f),1e-3),d=clamp(20*Math.log10(gv),-60,0);k?g.lineTo(fx(f),dy(d)):g.moveTo(fx(f),dy(d))}g.stroke();
      [[st.lff],[st.hff]].forEach(([f])=>{g.fillStyle=C.accent;g.beginPath();g.arc(fx(f),dy(-3),4,0,6.3);g.fill()})}
    const gp=f=>(gainAt(f)*100).toFixed(f>=60?1:0)+'%',tc=1/(2*Math.PI*st.lff);
    $('#fT',c).innerHTML=`<b>−3 dB corners ${st.lff.toFixed(st.lff<1?2:1)} Hz and ${st.hff.toFixed(0)} Hz</b> (low-frequency filter time constant ${tc.toFixed(2)} s). Passes at 1 Hz (delta): <b>${gp(1)}</b> · 5 Hz (theta): <b>${gp(5)}</b> · 10 Hz (alpha): <b>${gp(10)}</b> · 20 Hz (beta): <b>${gp(20)}</b> · 60 Hz: <b>${gp(60)}</b>. ${st.lff>=2?'The low-frequency filter is now eating real delta.':st.hff<=25?'The high-frequency filter is now rounding spikes and removing fast activity.':'This is close to a routine setting.'}`}
  AX.sigDraw.push(draw)}

/* ---- RC lab ---- */
function schem(t){const zig='M0 0h10l5-9 10 18 10-18 10 18 10-18 5 9h10',gnd='<path d="M138 100h24M142 106h16M146 112h8"/>',vz=`<g transform="translate(150 30) rotate(90)"><path d="${zig}"/></g>`;
  return`<svg viewBox="0 0 250 128" width="100%" style="max-width:340px" role="img" aria-label="${t==='lp'?'Low-pass':'High-pass'} RC circuit" fill="none" stroke="var(--ink)" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"><circle cx="12" cy="30" r="3.5" fill="var(--panel)"/>`+(t==='lp'?`<path d="M16 30H40"/><g transform="translate(40 30)"><path d="${zig}"/></g><path d="M110 30H235M150 30V62M138 62h24M138 70h24M150 70V100"/>${gnd}<text x="62" y="12" fill="var(--ink)" stroke="none" font-size="13" font-family="var(--font-mono)">R</text><text x="166" y="72" fill="var(--ink)" stroke="none" font-size="13" font-family="var(--font-mono)">C</text>`:`<path d="M16 30H70M70 14v32M78 14v32M78 30H235M150 30"/>${vz}<path d="M150 100"/>${gnd}<text x="68" y="10" fill="var(--ink)" stroke="none" font-size="13" font-family="var(--font-mono)">C</text><text x="166" y="68" fill="var(--ink)" stroke="none" font-size="13" font-family="var(--font-mono)">R</text>`)+`<circle cx="150" cy="30" r="3" fill="var(--ink)"/><circle cx="235" cy="30" r="3.5" fill="var(--panel)"/><text x="2" y="50" fill="var(--muted)" stroke="none" font-size="12" font-family="var(--font-mono)">Vin</text><text x="205" y="50" fill="var(--accent)" stroke="none" font-size="12" font-family="var(--font-mono)">Vout</text></svg>`}
function rcLab(H){const st={type:'lp',inp:'step',R:15915,C:1e-6,ratio:5};
  const c=el('div','card stack',`<h2>Resistor and capacitor: the filter you can build with two parts</h2><p style="max-width:84ch">A resistor and a capacitor together make a first-order filter, the building block behind EEG filtering. The capacitor charges through the resistor on a time scale of <b>τ = R × C</b>. The corner frequency is <b>fc = 1 ÷ (2π R C)</b>. Which part is in series decides what passes.</p>
   <ul class="f"><li><b>Low-pass</b> (resistor in series, output across the capacitor): slow changes get through, fast ones are smoothed away. Well above fc it <b>integrates</b>: the output is the running total of the input, so a square wave becomes a triangle.</li><li><b>High-pass</b> (capacitor in series, output across the resistor): only <i>changes</i> get through and a steady level drains away with time constant τ. Well below fc it <b>differentiates</b>: a square wave becomes spikes at the edges.</li><li>Put the two in series and you have a <b>band-pass</b>, exactly what an EEG amplifier does between its low-frequency and high-frequency filter settings.</li></ul>
   <div class="rcg"><div id="rcS" class="stack" style="gap:8px"><div class="row" id="rcCtl"></div><div id="rcSv"></div><div id="rcSl" class="stack" style="gap:8px"></div></div><div style="min-width:0"><div class="vwrap"><div id="rcT"></div></div><div class="vwrap" style="margin-top:10px"><div id="rcB"></div></div></div></div><p id="rcTx" class="note"></p>`);H.appendChild(c);
  segment($('#rcCtl',c),[['lp','Low-pass'],['hp','High-pass']],'lp',v=>{st.type=v;if(st.inp!=='step'){st.ratio=v==='lp'?5:.2;rs.set(st.ratio)}draw()});segment($('#rcCtl',c),[['step','Step'],['sq','Square wave'],['sin','Sine']],'step',v=>{st.inp=v;draw()});
  slider($('#rcSl',c),'Resistance R',{min:100,max:1e7,log:1,val:st.R,fmt:v=>fmtSI(v,'Ω')},v=>{st.R=v;draw()});slider($('#rcSl',c),'Capacitance C',{min:1e-9,max:1e-3,log:1,val:st.C,fmt:v=>fmtSI(v,'F')},v=>{st.C=v;draw()});
  const rs=slider($('#rcSl',c),'Input freq ÷ fc',{min:.05,max:20,log:1,val:5,fmt:v=>'× '+(+v.toPrecision(2))},v=>{st.ratio=v;draw()});
  const tcv=mkCanvas($('#rcT',c),240),bcv=mkCanvas($('#rcB',c),170);
  function draw(){$('#rcSv',c).innerHTML=schem(st.type);const tau=st.R*st.C,fc=1/(2*Math.PI*tau),per=st.inp!=='step';rs.input.disabled=!per;rs.input.parentElement.style.opacity=per?1:.45;
    let T,pre=0,inp;if(!per){T=7*tau;inp=t=>t>=tau?1:0}else{const f=st.ratio*fc,P=1/f;T=4*P;pre=6*P;inp=st.inp==='sq'?(t=>(t%P)<P/2?1:-1):(t=>Math.sin(2*Math.PI*f*t))}
    const n=1600,dt=(T+pre)/n,al=Math.exp(-dt/tau);let y=0;const xi=[],yo=[];for(let i=0;i<n;i++){const t=i*dt,x=inp(t);y=al*y+(1-al)*x;if(t>=pre){xi.push(x);yo.push(st.type==='lp'?y:x-y)}}
    let S=cvSetup(tcv);if(S){const{g,w,h,C}=S,fm=getComputedStyle(document.body).getPropertyValue('--font-mono'),ml=12,mr=12,mt=16,mb=26,pw=w-ml-mr,ph=h-mt-mb,lo=per?-1.25:-.1,hi=per?1.25:1.15,Y=v=>mt+(hi-v)/(hi-lo)*ph,Xn=i=>ml+i/(xi.length-1)*pw;
      g.strokeStyle=C.grid;g.lineWidth=1;g.beginPath();g.moveTo(ml,Y(0)+.5);g.lineTo(w-mr,Y(0)+.5);g.stroke();
      if(!per){
        for(let k=1;k<=5;k++){const x=ml+((tau+k*tau)/T)*pw;g.strokeStyle=C.major;g.beginPath();g.moveTo(x+.5,mt);g.lineTo(x+.5,mt+ph);g.stroke();g.fillStyle=C.muted;g.font='10.5px '+fm;g.textAlign='center';g.fillText(k+'τ',x,h-9)}
        const lv=st.type==='lp'?.632:.368;g.setLineDash([4,4]);g.strokeStyle=C.mark;g.beginPath();g.moveTo(ml,Y(lv));g.lineTo(w-mr,Y(lv));g.stroke();g.setLineDash([]);g.fillStyle=C.mark;g.textAlign='right';g.fillText(st.type==='lp'?'63% after 1τ':'37% left after 1τ',w-mr-2,Y(lv)-4)}
      else{g.fillStyle=C.muted;g.font='10.5px '+fm;g.textAlign='left';g.fillText('4 cycles = '+fmtSI(T,'s'),ml,h-9)}
      g.lineJoin='round';g.strokeStyle=C.muted;g.lineWidth=1.6;g.beginPath();xi.forEach((v,i)=>i?g.lineTo(Xn(i),Y(v)):g.moveTo(Xn(i),Y(v)));g.stroke();g.strokeStyle=C.accent;g.lineWidth=2.6;g.beginPath();yo.forEach((v,i)=>i?g.lineTo(Xn(i),Y(v)):g.moveTo(Xn(i),Y(v)));g.stroke();
      g.font='600 11px '+fm;g.textAlign='left';g.fillStyle=C.muted;g.fillText('input',ml+2,mt+6);g.fillStyle=C.accent;g.fillText('output',ml+46,mt+6)}
    S=cvSetup(bcv);if(S){const{g,w,h,C}=S,fm=getComputedStyle(document.body).getPropertyValue('--font-mono'),ml=44,mr=12,mt=12,mb=26,pw=w-ml-mr,ph=h-mt-mb,fx=r=>ml+(Math.log10(r)+2)/4*pw,dy=d=>mt+(-d/40)*ph;
      g.strokeStyle=C.grid;g.fillStyle=C.muted;g.font='10.5px '+fm;g.lineWidth=1;for(let d=0;d>=-40;d-=10){g.beginPath();g.moveTo(ml,dy(d)+.5);g.lineTo(w-mr,dy(d)+.5);g.stroke();g.textAlign='right';g.fillText(d+' dB',ml-5,dy(d)+4)}
      [.01,.1,1,10,100].forEach(r=>{g.strokeStyle=C.major;g.beginPath();g.moveTo(fx(r)+.5,mt);g.lineTo(fx(r)+.5,mt+ph);g.stroke();g.textAlign='center';g.fillText(r===1?'fc':'×'+r,fx(r),h-9)});
      g.strokeStyle=C.accent;g.lineWidth=2.6;g.beginPath();for(let k=0;k<=300;k++){const r=Math.pow(10,-2+4*k/300),m=st.type==='lp'?1/Math.sqrt(1+r*r):r/Math.sqrt(1+r*r),d=Math.max(-40,20*Math.log10(m));k?g.lineTo(fx(r),dy(d)):g.moveTo(fx(r),dy(d))}g.stroke();
      g.fillStyle=C.accent;g.beginPath();g.arc(fx(1),dy(-3.01),4,0,6.3);g.fill();if(per){g.strokeStyle=C.mark;g.setLineDash([4,4]);g.beginPath();g.moveTo(fx(st.ratio),mt);g.lineTo(fx(st.ratio),mt+ph);g.stroke();g.setLineDash([]);g.fillStyle=C.mark;g.textAlign='center';g.fillText('input',fx(st.ratio),mt+10)}
      g.fillStyle=C.muted;g.textAlign='left';g.fillText('−6 dB per octave beyond fc',ml+6,st.type==='lp'?dy(-30):dy(-6)-14)}
    const reg=!per?(st.type==='lp'?'After a step the output climbs toward the input and reaches 63% at 1τ, 95% at 3τ and 99% at 5τ.':'After a step the output jumps and then drains away: 37% remains at 1τ, 5% at 3τ. This is why a high low-frequency-filter setting makes slow waves and baseline shifts sag.'):(st.type==='lp'?(st.ratio>=3?'Input frequency is well above fc: the capacitor never gets time to charge, so the circuit <b>integrates</b>. A square wave becomes a triangle and the amplitude shrinks as frequency rises.':st.ratio<=.33?'Input frequency is well below fc: the output follows the input and passes unchanged.':'Near fc the output is attenuated to about 70% and delayed.'):(st.ratio<=.33?'Input frequency is well below fc: the circuit <b>differentiates</b>. A square wave becomes spikes at each edge; only changes get through.':st.ratio>=3?'Input frequency is well above fc: the signal passes unchanged.':'Near fc the output is attenuated to about 70% and shifted forward in time.'));
    $('#rcTx',c).innerHTML=`<b>τ = R × C = ${fmtSI(tau,'s')}</b> · <b>fc = 1 ÷ (2π R C) = ${fmtSI(fc,'Hz')}</b> · 10–90% rise time ≈ 2.2 τ = ${fmtSI(2.2*tau,'s')}. ${reg}`}
  AX.sigDraw.push(draw)}

/* ---- sampling and aliasing ---- */
function aliasLab(H){const st={f:70,fs:128};
  const c=el('div','card stack',`<h2>Sampling: why the digitizer rate and the low-pass filter go together</h2><p style="max-width:84ch">A digital recorder takes snapshots. To capture a wave it needs more than two snapshots per cycle (the <b>Nyquist rule</b>: sampling rate at least twice the highest frequency). A faster wave is not lost: it <b>folds back</b> and shows up as a slower, false wave. That is <b>aliasing</b>, and it is why the amplifier has a low-pass filter before the digitizer.</p><div id="aS" class="stack" style="gap:8px"></div><div class="vwrap"><div id="aC"></div></div><p id="aT" class="note"></p>`);H.appendChild(c);
  slider($('#aS',c),'Signal frequency',{min:1,max:240,step:1,val:70,fmt:v=>v+' Hz'},v=>{st.f=v;draw()});slider($('#aS',c),'Sampling rate',{min:32,max:512,log:1,val:128,fmt:v=>Math.round(v)+' Hz'},v=>{st.fs=Math.round(v);draw()});
  const cv=mkCanvas($('#aC',c),200);
  function draw(){const S=cvSetup(cv);if(!S)return;const{g,w,h,C}=S,fm=getComputedStyle(document.body).getPropertyValue('--font-mono'),ml=12,mr=12,mt=14,mb=22,pw=w-ml-mr,ph=h-mt-mb,W=.125,X=t=>ml+t/W*pw,Y=v=>mt+ph/2-v*ph*.42;
    g.strokeStyle=C.grid;g.lineWidth=1;g.beginPath();g.moveTo(ml,Y(0)+.5);g.lineTo(w-mr,Y(0)+.5);g.stroke();g.fillStyle=C.muted;g.font='10.5px '+fm;g.textAlign='left';g.fillText('0',ml,h-8);g.textAlign='right';g.fillText('125 ms',w-mr,h-8);
    g.strokeStyle=C.major;g.lineWidth=1.4;g.beginPath();for(let k=0;k<=pw;k++){const t=k/pw*W,v=Math.sin(2*Math.PI*st.f*t);k?g.lineTo(ml+k,Y(v)):g.moveTo(ml,Y(v))}g.stroke();
    const n=Math.floor(W*st.fs),pts=[];for(let i=0;i<=n;i++){const t=i/st.fs;pts.push([X(t),Y(Math.sin(2*Math.PI*st.f*t))])}g.strokeStyle=C.accent;g.lineWidth=2.4;g.lineJoin='round';g.beginPath();pts.forEach((p,i)=>i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1]));g.stroke();g.fillStyle=C.accent;pts.forEach(p=>{g.beginPath();g.arc(p[0],p[1],3.2,0,6.3);g.fill()});
    g.font='600 11px '+fm;g.textAlign='left';g.fillStyle=C.muted;g.fillText('true wave',ml+2,mt+4);g.fillStyle=C.accent;g.fillText('what the recorder keeps',ml+74,mt+4);
    const nyq=st.fs/2,al=Math.abs(st.f-st.fs*Math.round(st.f/st.fs));$('#aT',c).innerHTML=st.f<nyq?`<b>${st.f} Hz is below the Nyquist limit of ${nyq} Hz</b> (${(st.fs/st.f).toFixed(1)} samples per cycle). The recorder keeps the wave faithfully, though with few samples per cycle the straight-line joins look angular.`:st.f===nyq?`<b>Exactly at the Nyquist limit.</b> Two samples per cycle is the bare minimum, and amplitude depends on where the samples happen to land.`:`<b>${st.f} Hz is above the Nyquist limit of ${nyq} Hz.</b> It is recorded as a false <b>${al.toFixed(0)} Hz</b> wave. A 60 Hz hum sampled at 100 Hz would appear as a 40 Hz wave, and fast muscle activity can masquerade as brain rhythm. The anti-alias filter must remove it <i>before</i> sampling, since afterwards it cannot be told apart from the real thing.`}
  AX.sigDraw.push(draw)}

/* ---- atlas sub-navigation ---- */
