/* ============ trends & evolution: page, compact panels and trajectory questions ============ */
const CMAP=[[13,8,48],[45,35,120],[30,95,160],[30,150,150],[95,190,100],[220,215,60],[250,245,170]];
function cmap(u){u=clamp(u,0,1)*(CMAP.length-1);const i=Math.min(CMAP.length-2,Math.floor(u)),f=u-i,a=CMAP[i],b=CMAP[i+1];return`rgb(${a.map((v,k)=>Math.round(v+(b[k]-v)*f)).join(',')})`}
const PCH=['Fp1-F7','F7-T3','T3-T5','C3-P3','Fp2-F8','F8-T4','T4-T6','C4-P4'];
function drawPage(cv,rec,o={}){const S_=cvSetup(cv);if(!S_)return;const{g:x,w,h,C}=S_,rows=buildRows(rec,{mont:'tcp',lff:1,hff:35,notch:false}).filter(r=>PCH.includes(r.label)),L=w<420?44:54,rh=(h-14)/rows.length,sens=o.sens||rec.sens||7,ppu=3.2/sens*(rh/26);
  x.fillStyle=C.panel;x.fillRect(0,0,w,h);for(let s=0;s<=DUR;s++){const X=L+s/DUR*(w-L-4);x.strokeStyle=s%5?C.grid:C.major;x.beginPath();x.moveTo(X,0);x.lineTo(X,h-12);x.stroke()}
  x.font='10px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.textBaseline='middle';
  rows.forEach((r,i)=>{const cy=rh*i+rh/2+(i>=4?2:0);x.fillStyle=C.muted;x.textAlign='right';x.fillText(r.label,L-5,cy);x.save();x.beginPath();x.rect(L,cy-rh/2-1,w-L,rh+2);x.clip();x.strokeStyle=C.trace;x.lineWidth=1*(typeof LRN!=='undefined'?LRN.tw():1);x.beginPath();
    for(let n=0;n<N;n+=2){const X=L+n/(N-1)*(w-L-4),Y=cy-r.data[n]*ppu;n?x.lineTo(X,Y):x.moveTo(X,Y)}x.stroke();x.restore()});
  x.fillStyle=C.muted;x.textAlign='right';x.fillText(`${sens} µV/mm · 10 s`,w-4,h-5)}
/* ---- trend painter ---- */
function drawTrend(cv,sc,o={}){const S_=cvSetup(cv);if(!S_)return null;const{g:x,w,h,C}=S_,tr=trendOf(sc),n=tr.length,L=w<520?58:86,R_=8,pw=w-L-R_,X=i=>L+i/n*pw,mono=getComputedStyle(document.body).getPropertyValue('--font-mono');
  const lanes=[['csaL','CSA left',58],['csaR','CSA right',58],['aeeg','aEEG',46],['rhy','Rhythmicity',18],['adr','Alpha/delta',34],['ai','Asymmetry',28],['bsr','BSR %',26]].filter(l=>!o.only||o.only.includes(l[0]));
  const tot=lanes.reduce((a,l)=>a+l[2]+6,0)+22,sc2=(h-22)/tot;let y=4;const geo={L,pw,dur:sc.dur,lanes:{}};x.fillStyle=C.panel;x.fillRect(0,0,w,h);x.font='10.5px '+mono;x.textBaseline='middle';
  const dbs=[];tr.forEach(p=>{p.L.forEach(v=>dbs.push(10*Math.log10(v+1e-9)));});dbs.sort((a,b)=>a-b);const lo=dbs[Math.floor(dbs.length*.05)],hi=dbs[Math.floor(dbs.length*.995)];
  for(const[k,lab,hh0]of lanes){const hh=hh0*sc2+6*sc2-6;geo.lanes[k]=[y,hh];x.fillStyle=C.muted;x.textAlign='right';x.fillText(lab,L-5,y+hh/2);
    if(k==='csaL'||k==='csaR'){const key=k==='csaL'?'L':'R',cw=pw/n+.6,chh=hh/FQ.length;tr.forEach((p,i)=>p[key].forEach((v,j)=>{x.fillStyle=cmap((10*Math.log10(v+1e-9)-lo)/(hi-lo));x.fillRect(X(i),y+hh-(j+1)*chh,cw,chh+.6)}));
      x.fillStyle=C.muted;x.textAlign='left';x.font='9px '+mono;x.fillText('20 Hz',L+2,y+6);x.font='10.5px '+mono}
    else{x.strokeStyle=C.line;x.strokeRect(L+.5,y+.5,pw-1,hh-1)}
    if(k==='aeeg'){const sy=v=>{const u=v<=10?v/10*.5:.5+.5*Math.log10(v/10);return y+hh-clamp(u,0,1)*hh};x.fillStyle=C.accent;x.globalAlpha=.55;x.beginPath();tr.forEach((p,i)=>x.lineTo(X(i),sy(p.up)));for(let i=n-1;i>=0;i--)x.lineTo(X(i),sy(tr[i].lo));x.closePath();x.fill();x.globalAlpha=1;
      [[10,'10'],[50,'50 µV']].forEach(([v,t])=>{x.strokeStyle=C.grid;x.beginPath();x.moveTo(L,sy(v));x.lineTo(L+pw,sy(v));x.stroke();x.fillStyle=C.muted;x.textAlign='left';x.font='9px '+mono;x.fillText(t,L+2,sy(v)-5);x.font='10.5px '+mono})}
    if(k==='rhy'){tr.forEach((p,i)=>{if(p.rhy>.05){x.fillStyle=C.bad;x.globalAlpha=Math.min(1,.2+p.rhy);x.fillRect(X(i),y+hh*(1-p.rhy),pw/n+.6,hh*p.rhy)}});x.globalAlpha=1}
    if(k==='adr'){const av=tr.map(p=>Math.max(p.adrL,p.adrR)).sort((a,b)=>a-b),mx=Math.max(.05,av[Math.floor(av.length*.9)]*1.25),sy=v=>y+hh-Math.min(1,v/mx)*hh*.92;[['adrL',C.accent],['adrR',C.mark]].forEach(([q,c])=>{x.strokeStyle=c;x.lineWidth=1.4;x.beginPath();tr.forEach((p,i)=>x.lineTo(X(i)+pw/n/2,sy(p[q])));x.stroke()});x.lineWidth=1;
      x.font='9px '+mono;x.textAlign='left';x.fillStyle=C.accent;x.fillText('left',L+pw-50,y+7);x.fillStyle=C.mark;x.fillText('right',L+pw-26,y+7);x.font='10.5px '+mono}
    if(k==='ai'){const sy=v=>y+hh/2-v*hh/2*.95;x.strokeStyle=C.grid;x.beginPath();x.moveTo(L,y+hh/2);x.lineTo(L+pw,y+hh/2);x.stroke();x.strokeStyle=C.ink;x.lineWidth=1.3;x.beginPath();tr.forEach((p,i)=>x.lineTo(X(i)+pw/n/2,sy(p.ai)));x.stroke();x.lineWidth=1;x.font='9px '+mono;x.textAlign='left';x.fillStyle=C.muted;x.fillText('L>R',L+2,y+6);x.fillText('R>L',L+2,y+hh-5);x.font='10.5px '+mono}
    if(k==='bsr'){x.fillStyle=C.muted;tr.forEach((p,i)=>{if(p.bsr>0){x.globalAlpha=.75;x.fillRect(X(i),y+hh*(1-p.bsr/100),pw/n+.6,hh*p.bsr/100)}});x.globalAlpha=1}
    y+=hh+6}
  const T0=y;x.strokeStyle=C.major;x.fillStyle=C.muted;x.textAlign='center';const step=sc.dur<=180?15:sc.dur<=720?60:sc.dur<=1440?120:720;for(let m=0;m<=sc.dur;m+=step){const X_=L+m/sc.dur*pw;x.beginPath();x.moveTo(X_,T0-4);x.lineTo(X_,T0);x.stroke();x.fillText(sc.dur<=180?m+' min':(m/60)+' h',Math.min(w-14,Math.max(L+10,X_)),T0+9)}
  (sc.events||[]).forEach(([m,t],i)=>{const X_=L+m/sc.dur*pw;x.strokeStyle=C.ink;x.globalAlpha=.55;x.setLineDash([3,3]);x.beginPath();x.moveTo(X_,2);x.lineTo(X_,T0-2);x.stroke();x.setLineDash([]);x.globalAlpha=1;x.fillStyle=C.ink;x.beginPath();x.arc(X_,8,7,0,6.29);x.fill();x.fillStyle=C.panel;x.font='600 9.5px '+mono;x.fillText(String(i+1),X_,8.5);x.font='10.5px '+mono});
  if(o.cur!=null){const X_=L+o.cur/sc.dur*pw;x.strokeStyle=C.accent;x.lineWidth=2.5;x.beginPath();x.moveTo(X_,2);x.lineTo(X_,T0-2);x.stroke();x.lineWidth=1}
  if(o.mark!=null){const X_=L+o.mark/sc.dur*pw;x.fillStyle=C.mark;x.beginPath();x.moveTo(X_-7,T0-1);x.lineTo(X_+7,T0-1);x.lineTo(X_,T0-12);x.fill();x.strokeStyle=C.mark;x.lineWidth=2;x.setLineDash([5,3]);x.beginPath();x.moveTo(X_,2);x.lineTo(X_,T0-12);x.stroke();x.setLineDash([]);x.lineWidth=1}
  cv._tgeo=geo;return geo}
function trendTime(cv,e){const g_=cv._tgeo;if(!g_)return null;const b=cv.getBoundingClientRect(),xx=e.clientX-b.left;return clamp((xx-g_.L)/g_.pw,0,1)*g_.dur}
function stSummary(R){const M=R.meta,st=R.st,b=[];b.push(M.cont==='supp'?'suppressed':M.cont==='bs'?'burst-suppression':M.cont==='discont'?'discontinuous':'continuous');b.push(M.volt==='normal'?'normal voltage':M.volt==='low'?'low voltage':'very low voltage');if(M.pdr)b.push(`posterior rhythm ${M.pdr.toFixed(1)} Hz`);if(st.spind)b.push('spindles');
  if(st.pd)b.push(`${st.pd.m1==='L'?'LPDs':'GPDs'} ${st.pd.f.toFixed(1)} Hz${st.pd.tri?' (triphasic morphology)':''}`);if(st.rda)b.push(`${st.rda.m1}RDA ${st.rda.f} Hz`);if(st.fd>8)b.push(`${st.fside<0?'left':'right'} focal slowing`);if(st.asym>.2)b.push(`${st.aside<0?'left':'right'} attenuation`);if(R.sz)b.push('seizure');return b.join(' · ')}
/* ---- Trends & evolution atlas page ---- */
const EV={id:'statusEp',t:30,step:0,viewer:null};
function buildEvo(host){host=host||$('#aEvo');host.innerHTML='';
  const top=el('div','card stack',`<div class="row" style="justify-content:space-between;align-items:flex-start"><div class="stack" style="gap:6px;max-width:80ch"><h2>Trends and evolution</h2><p style="margin:0">Continuous EEG is read twice: as <b>trends</b> that compress hours into one screen, and as the <b>raw pages</b> behind them. Every trend here is computed from the same brain state that draws the raw EEG, so you can click any moment and see exactly what produced it. The numbered markers are clinical events; the steps walk through the turning points and the mechanism behind each.</p></div></div>
    <div class="row"><label class="lbl" style="text-transform:none;letter-spacing:0;display:flex;gap:8px;align-items:center">Scenario <select id="evSel" style="max-width:min(420px,70vw)">${SCNL.map(k=>`<option value="${k}">${SCN[k].name}</option>`).join('')}</select></label><button class="btn small" id="evPlay" type="button">Step through</button></div>
    <p id="evSum" style="margin:0;color:var(--muted)"></p>
    <div><canvas id="evCv" style="display:block;width:100%;height:330px;cursor:crosshair;touch-action:pan-y" aria-label="Quantitative EEG trend; click to open the raw EEG at that time"></canvas></div>
    <div class="row" id="evEvents" style="gap:6px"></div>
    <details><summary>How to read these trends</summary><ul class="f"><li><b>CSA</b> (compressed spectral array): time left to right, frequency bottom (0.5 Hz) to top (20 Hz), brightness = power. Seizures are bright vertical “flames”; sleep spindles a 12–14 Hz band; suppression dark columns.</li><li><b>aEEG</b>: the envelope of amplitude on a semi-log scale. A low lower margin means discontinuity or suppression.</li><li><b>Rhythmicity</b>: how much of each epoch is rhythmic or periodic (seizures, PDs, RDA).</li><li><b>Alpha/delta ratio</b>: falls when fast activity fades and delta grows, the earliest sign of falling flow (delayed cerebral ischemia).</li><li><b>Asymmetry</b>: relative power left versus right.</li><li><b>BSR</b>: burst-suppression ratio, the percentage of time suppressed.</li></ul></details>`);host.appendChild(top);
  const steps=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2 id="evT"></h2><div class="row" id="evSteps" style="gap:6px"></div></div><p id="evState" class="lbl" style="text-transform:none;letter-spacing:0;margin:0"></p><div id="evViewer"></div><div class="two"><div class="stack" style="gap:6px"><h3>What changed</h3><div id="evDiff"></div></div><div class="stack" style="gap:6px"><h3>Why</h3><div id="evWhy"></div></div></div>`);host.appendChild(steps);
  EV.viewer=Viewer($('#evViewer',steps));const cv=$('#evCv',top);
  const paint=()=>drawTrend(cv,SCN[EV.id],{cur:EV.t});
  const show=()=>{const sc=SCN[EV.id],si0=sc.steps.findIndex(s=>Math.abs(s.t-EV.t)<1e-6),R=scnPage(EV.id,si0>=0?stepT(sc,si0):EV.t);EV.viewer.setRec(R);EV.viewer.setAnn(true);$('#evT',steps).textContent=`${fmtT(sc,R.tm)} · ${sc.name}`;$('#evState',steps).textContent='This page: '+stSummary(R);
    const si=sc.steps.findIndex(s=>Math.abs(s.t-EV.t)<1e-6);$$('#evSteps button',steps).forEach((b,i)=>b.setAttribute('aria-pressed',String(i===si)));
    const prev=si>0?sc.steps[si-1]:null,cur=si>=0?sc.steps[si]:null;
    if(cur){const A=stateAt(sc,prev?prev.t:0),B=stateAt(sc,cur.t),d=prev?diffState(A,B,szAt(sc,prev.t),szAt(sc,cur.t)):[];$('#evDiff',steps).innerHTML=prev?(d.length?`<ul class="f">${d.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p>No major change.</p>')+`<p class="lbl" style="text-transform:none;letter-spacing:0">Compared with step ${si}: ${prev.ev}.</p>`:'<p>Starting point.</p>';
      $('#evWhy',steps).innerHTML=`<p style="margin:0"><b>${cur.ev}.</b> ${cur.why}</p>${cur.dir!=='base'?`<p style="margin:6px 0 0"><span class="pill ${cur.dir==='better'?'normal':cur.dir==='worse'?'isch':''}">${cur.dir==='better'?'Improving':cur.dir==='worse'?'Worsening':'Unchanged'}</span></p>`:''}`}
    else{$('#evDiff',steps).innerHTML='<p class="lbl" style="text-transform:none;letter-spacing:0">Free selection: choose a step to compare turning points.</p>';const near=sc.steps.reduce((a,s)=>Math.abs(s.t-EV.t)<Math.abs(a.t-EV.t)?s:a,sc.steps[0]);$('#evWhy',steps).innerHTML=`<p style="margin:0" class="lbl">Nearest step: ${near.ev} (${fmtT(sc,near.t)}).</p>`}paint()};
  const load=id=>{EV.id=id;const sc=SCN[id];$('#evSel',top).value=id;$('#evSum',top).textContent=sc.sum;EV.t=sc.steps[0].t;$('#evEvents',top).innerHTML=(sc.events||[]).map(([m,t],i)=>`<span class="chip" style="cursor:default"><b>${i+1}</b> ${fmtT(sc,m)}: ${t}</span>`).join('');
    $('#evSteps',steps).innerHTML=sc.steps.map((s,i)=>`<button class="chip" type="button" data-st="${i}" title="${s.ev}">${i+1}. ${fmtT(sc,s.t)}</button>`).join('');$$('#evSteps [data-st]',steps).forEach(b=>b.addEventListener('click',()=>{EV.t=sc.steps[+b.dataset.st].t;show()}));show()};
  $('#evSel',top).addEventListener('change',e=>load(e.target.value));
  cv.addEventListener('click',e=>{const t=trendTime(cv,e);if(t==null)return;EV.t=Math.round(t*10)/10;show();steps.scrollIntoView({behavior:document.documentElement.classList.contains('rmo')?'auto':'smooth',block:'start'})});
  $('#evPlay',top).addEventListener('click',()=>{const sc=SCN[EV.id],i=sc.steps.findIndex(s=>s.t>EV.t+1e-6);EV.t=(i<0?sc.steps[0]:sc.steps[i]).t;show()});
  AX.draws.evo=[paint,()=>EV.viewer.draw()];EV.load=load;EV.show=show;load(EV.id)}
function openEvo(id,i){setTab('atlas');setSub('evo');if(EV.load){EV.load(id);if(i!=null&&SCN[id].steps[i]){EV.t=SCN[id].steps[i].t;EV.show()}}window.scrollTo({top:0})}
/* ---- trajectory questions ---- */
const TT={seq:'Order the pages',next:'What comes next',diff:'What changed',dir:'Better or worse',trend:'Read the trend'};
function trendTruth(sc,tm){const st=stateAt(sc,tm);if(szAt(sc,tm))return'sz';if(st.supp>=.5)return'bs';if(st.fd>12&&st.asym>.2)return'focal';if(st.pd)return'pd';if(st.spind&&st.delta<20)return'spind';if(st.delta>=25&&st.state==='sleep')return'n3';return null}
const TLAB={sz:'An electrographic seizure',bs:'Burst-suppression (long flat periods)',focal:'Loss of fast activity with slowing on one side',pd:'Periodic discharges',spind:'Sleep spindles (N2 sleep)',n3:'Slow-wave sleep (N3)'};
function newTrajQ(seed,type,scnId){const r=mkRand(seed>>>0),ids=scnId&&SCN[scnId]?[scnId]:SCNL;let id=ids[Math.floor(r.u()*ids.length)];const types=type?[type]:['seq','next','diff','dir','trend'];let tt=types[Math.floor(r.u()*types.length)];let sc=SCN[id];
  if(tt==='trend'){const cands=[];for(let k=0;k<60;k++){const tm=r.r(.02,.98)*sc.dur,t=trendTruth(sc,tm);if(t)cands.push([tm,t])}if(!cands.length)tt='dir';else{const[tm,t]=cands[Math.floor(r.u()*cands.length)],keys=Object.keys(TLAB).filter(k=>k!==t),opts=shuffle([t,...shuffle(keys,r).slice(0,3)],r);
    return{kind:'trend',tt,scn:id,seed,tm,truth:t,opts,a:opts.indexOf(t),chosen:null}}}
  if(tt==='seq'){const n=Math.min(4,sc.steps.length),pick=shuffle(sc.steps.map((s,i)=>i),r).slice(0,n).sort((a,b)=>a-b),ord=shuffle(pick,r);return{kind:'traj',tt,scn:id,seed,idx:ord,truth:pick,recs:ord.map(i=>scnPage(id,stepT(sc,i),seed+i)),chosen:null,sel:[]}}
  const pairs=[];sc.steps.forEach((s,i)=>{if(i>0)pairs.push(i)});const i=pairs[Math.floor(r.u()*pairs.length)]||1,A=sc.steps[i-1],B=sc.steps[i],rA=scnPage(id,stepT(sc,i-1),seed),rB=scnPage(id,stepT(sc,i),seed+1);
  if(tt==='next'){const others=[];SCNL.forEach(k=>SCN[k].steps.forEach((s,j)=>{if(!(k===id&&j===i))others.push([k,j])}));const d=shuffle(others,r).filter(([k,j])=>k!==id||Math.abs(j-i)>0).slice(0,2),opts=shuffle([[id,i],...d],r);
    return{kind:'traj',tt,scn:id,seed,i,ctx:rA,recs:opts.map(([k,j],q)=>scnPage(k,stepT(SCN[k],j),seed+10+q)),opts,a:opts.findIndex(([k,j])=>k===id&&j===i),chosen:null}}
  if(tt==='diff'){const truth=diffState(stateAt(sc,A.t),stateAt(sc,B.t),szAt(sc,A.t),szAt(sc,B.t));if(truth.length){const pool=['Seizure activity has appeared','The seizure has stopped','The background is now suppressed','Continuity has returned (less flat time)','A posterior rhythm has returned','The posterior rhythm is gone','Lateralized periodic discharges have appeared','Generalized periodic discharges have appeared','The periodic discharges have resolved','Rhythmic delta has appeared','Focal slowing and attenuation on one side have increased','Sleep spindles have appeared','Voltage is lower','Voltage is higher','The bursts are now identical'].filter(x=>!truth.includes(x)),opts=shuffle([truth[0],...shuffle(pool,r).slice(0,3)],r);
    return{kind:'traj',tt,scn:id,seed,i,recs:[rA,rB],opts,a:opts.indexOf(truth[0]),all:truth,chosen:null}}tt='dir'}
  const dirs=['better','worse','same'],opts=['Improving','Worsening','Essentially unchanged'];return{kind:'traj',tt:'dir',scn:id,seed,i,recs:[rA,rB],opts,a:dirs.indexOf(B.dir==='base'?'same':B.dir),chosen:null}}
function trajOk(q){if(q.tt==='seq')return Array.isArray(q.chosen)&&q.chosen.length===q.truth.length&&q.chosen.every((x,k)=>x===q.truth[k]);return q.chosen===q.a}
function panelHtml(i,lab,sub,cls){return`<div class="tpanel ${cls||''}" data-tp="${i}" tabindex="0" role="button"><div class="tphead"><span class="tpl">${lab}</span><span class="lbl" style="text-transform:none;letter-spacing:0">${sub||''}</span></div><canvas style="display:block;width:100%;height:190px"></canvas></div>`}
function renderTraj(q,card,answered){const sc=SCN[q.scn];let h=`<div class="row" style="justify-content:space-between"><h2 style="max-width:72ch">${q.tt==='seq'?'Put these pages in time order':q.tt==='next'?'Which page comes next?':q.tt==='diff'?'What changed between these pages?':q.tt==='dir'?'Is the patient’s brain better or worse?':'What is happening at the marked time?'}</h2><span class="pill">${TT[q.tt]}</span></div><p style="margin:0"><b>${sc.name}.</b> ${sc.sum}</p>`;const L='ABCD';
  if(answered){const ok=trajOk(q);h=`<div class="verdict ${ok?'ok':'no'}">${ok?'Correct':'Not quite'}<span style="color:var(--ink);font-weight:500"> · ${TT[q.tt]}</span></div>`+h}
  if(q.kind==='trend'){h+=`<canvas class="tcv" style="display:block;width:100%;height:300px"></canvas><div class="qgrid long">${q.opts.map((o,i)=>answered?`<div class="opt ${i===q.a?'ok':i===q.chosen?'no':''}"><span>${TLAB[o]}</span></div>`:`<button class="opt" data-mi="${i}"><kbd>${i+1}</kbd><span>${TLAB[o]}</span></button>`).join('')}</div>`;
    if(answered){const R=scnPage(q.scn,q.tm,q.seed);h+=`<p>At ${fmtT(sc,q.tm)}: <b>${TLAB[q.truth]}</b>. ${q.truth==='sz'?'A bright flame in the CSA with a spike in rhythmicity.':q.truth==='bs'?'Dark CSA columns, a low aEEG lower margin and a high BSR.':q.truth==='focal'?'One CSA darkens in the fast range, the alpha/delta ratio falls on that side and the asymmetry index swings.':q.truth==='pd'?'Harmonic stripes in the CSA at the discharge rate, with rhythmicity but no evolving flame.':q.truth==='spind'?'A band at 12–14 Hz in both CSAs.':'Bright low-frequency power in both CSAs.'} The raw page behind it:</p><div class="tpanel ctx"><canvas class="rcv" style="display:block;width:100%;height:190px"></canvas></div><p class="lbl" style="text-transform:none;letter-spacing:0">${stSummary(R)}</p>`;q._R=R}}
  else if(q.tt==='seq'){h+=`<p class="lbl" style="text-transform:none;letter-spacing:0">${answered?'':'Tap the pages from earliest to latest. Think about what each mechanism does over time.'} ${!answered&&q.sel.length?`Order so far: ${q.sel.map(i=>L[q.idx.indexOf(i)]).join(' → ')}`:''}</p><div class="tpgrid">${q.idx.map((si,k)=>panelHtml(k,L[k],answered?fmtT(sc,sc.steps[si].t)+' · '+sc.steps[si].ev:q.sel.includes(si)?'#'+(q.sel.indexOf(si)+1):'',q.sel.includes(si)?'sel':'')).join('')}</div>`;
    if(!answered)h+=`<div class="row"><button class="btn small" id="tqUndo" ${q.sel.length?'':'disabled'}>Undo</button></div>`;
    else h+=`<p>Correct order: <b>${q.truth.map(i=>L[q.idx.indexOf(i)]).join(' → ')}</b>${Array.isArray(q.chosen)&&q.chosen.length?` · yours: ${q.chosen.map(i=>L[q.idx.indexOf(i)]).join(' → ')}`:''}.</p><ol class="f">${q.truth.map(i=>`<li><b>${fmtT(sc,sc.steps[i].t)}: ${sc.steps[i].ev}.</b> ${sc.steps[i].why}</li>`).join('')}</ol>`}
  else if(q.tt==='next'){const A=sc.steps[q.i-1];h+=`<p class="lbl" style="text-transform:none;letter-spacing:0">Now (${fmtT(sc,A.t)}): ${A.ev}. ${(sc.events||[]).filter(([m])=>m>A.t&&m<=sc.steps[q.i].t).map(([m,t])=>`Then: ${t}.`).join(' ')}</p><div class="tpanel ctx"><div class="tphead"><span class="tpl">·</span><span class="lbl" style="text-transform:none;letter-spacing:0">Current page</span></div><canvas class="ccv" style="display:block;width:100%;height:190px"></canvas></div><h3>Choose the next page</h3>
    <div class="tpgrid">${q.recs.map((R,k)=>panelHtml(k,L[k],answered?(k===q.a?'✓ the next page':SCN[q.opts[k][0]].name):'',answered?(k===q.a?'sel':''):'')).join('')}</div>`;if(answered){const B=sc.steps[q.i];h+=`<div class="note"><b>${fmtT(sc,B.t)}: ${B.ev}.</b> ${B.why}</div>`}}
  else{const A=sc.steps[q.i-1],B=sc.steps[q.i];h+=`<p class="lbl" style="text-transform:none;letter-spacing:0">${(sc.events||[]).filter(([m])=>m>A.t&&m<=B.t).map(([m,t])=>`Between the pages: ${t}.`).join(' ')||`${fmtT(sc,B.t-A.t)} apart.`}</p><div class="tpgrid">${panelHtml(0,'1',`Before · ${fmtT(sc,A.t)}`,'ctx')}${panelHtml(1,'2',`After · ${fmtT(sc,B.t)}`,'ctx')}</div>
    <div class="qgrid long">${q.opts.map((o,i)=>answered?`<div class="opt ${i===q.a?'ok':i===q.chosen?'no':''}"><span>${o}</span></div>`:`<button class="opt" data-mi="${i}"><kbd>${i+1}</kbd><span>${o}</span></button>`).join('')}</div>`;
    if(answered)h+=`<div class="note"><b>${B.ev}.</b> ${B.why}${q.all&&q.all.length>1?` Also: ${q.all.slice(1).map(lc).join('; ')}.`:''}</div>`}
  if(answered)h+=`<div class="row"><button class="btn primary" id="qNext">Next (N)</button><button class="btn" id="tqOpen">Open this scenario</button></div>`;
  card.innerHTML=h;
  if(q.kind==='trend'){const c=$('.tcv',card);requestAnimationFrame(()=>{drawTrend(c,sc,{mark:q.tm});if(answered)drawPage($('.rcv',card),q._R)})}
  else{const cvs=$$('.tpanel canvas',card);const recs=q.tt==='next'?[q.ctx,...q.recs]:q.recs;requestAnimationFrame(()=>cvs.forEach((c,k)=>drawPage(c,recs[k])))}
  $$('.opt[data-mi]',card).forEach(b=>b.addEventListener('click',()=>choose(+b.dataset.mi)));
  if(!answered&&(q.tt==='seq'||q.tt==='next'))$$('.tpanel[data-tp]:not(.ctx)',card).forEach(p=>{const f=()=>{const k=+p.dataset.tp;if(q.tt==='next'){choose(k);return}const si=q.idx[k];if(q.sel.includes(si))return;q.sel.push(si);if(q.sel.length===q.idx.length)choose(q.sel.slice());else renderCard()};p.addEventListener('click',f);p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();f()}})});
  const u=$('#tqUndo',card);if(u)u.addEventListener('click',()=>{q.sel.pop();renderCard()});const nb=$('#qNext',card);if(nb)nb.addEventListener('click',next);const ob=$('#tqOpen',card);if(ob)ob.addEventListener('click',()=>openEvo(q.scn,q.i));
  q._redraw=()=>{if(q.kind==='trend')drawTrend($('.tcv',card),sc,{mark:q.tm})}}
