/* ============ mechanism labs: fields, thalamus, synapses, blood flow, regions ============ */
const LABS=(()=>{
const LAB=[['field','Dipoles & fields'],['thal','Thalamus & rhythms'],['syn','Synapses, E/I & drugs'],['cbf','Blood flow & energy'],['map','Regions & semiology']];
const patBtns=ids=>`<div class="row" style="gap:6px">${ids.filter(i=>PM[i]).map(i=>`<button class="chip" type="button" data-pat="${i}">${PM[i].name}</button>`).join('')}</div>`;
const rgb=c=>{const d=document.createElement('canvas').getContext('2d');d.fillStyle=c;const h=d.fillStyle;if(h[0]==='#'){const n=parseInt(h.slice(1),16);return[n>>16&255,n>>8&255,n&255]}const m=h.match(/\d+/g);return m?m.slice(0,3).map(Number):[128,128,128]};
/* ---- scalp map ---- */
function drawTopo(cv,vals,o={}){const S_=cvSetup(cv);if(!S_)return;const{g:x,w,h,C}=S_,R=Math.min(w,h-28)/2-14,cx=w/2,cy=R+16,pos=EL.map(([n,ex,ey])=>[cx+ex*R*.86,cy-ey*R*.86]);
  let v=vals.slice();if(o.avg!==false){const m=v.reduce((a,b)=>a+b,0)/v.length;v=v.map(a=>a-m)}const mx=o.range||Math.max(1e-6,...v.map(Math.abs)),neg=rgb(C.mark),pos_=rgb(C.accent),bg=rgb(C.panel),st=3,img=x.createImageData(Math.ceil(2*R/st)+1,Math.ceil(2*R/st)+1);
  const mix=(c,u)=>c.map((k,i)=>Math.round(bg[i]+(k-bg[i])*u));const iw=img.width;
  for(let j=0;j<img.height;j++)for(let i=0;i<iw;i++){const px=cx-R+i*st,py=cy-R+j*st,dx=(px-cx)/R,dy=(py-cy)/R;if(dx*dx+dy*dy>1)continue;let sw=0,sv=0;for(let k=0;k<NE;k++){const d2=(px-pos[k][0])**2+(py-pos[k][1])**2+1;const ww=1/(d2*d2);sw+=ww;sv+=ww*v[k]}const u=clamp(sv/sw/mx,-1,1),c=mix(u<0?neg:pos_,Math.abs(u)**.8*.9),q=(j*iw+i)*4;img.data[q]=c[0];img.data[q+1]=c[1];img.data[q+2]=c[2];img.data[q+3]=255}
  const tmp=document.createElement('canvas');tmp.width=iw;tmp.height=img.height;tmp.getContext('2d').putImageData(img,0,0);x.save();x.beginPath();x.arc(cx,cy,R,0,6.29);x.clip();x.imageSmoothingEnabled=true;x.drawImage(tmp,cx-R,cy-R,iw*st,img.height*st);x.restore();
  x.strokeStyle=C.ink;x.lineWidth=1.4;x.beginPath();x.arc(cx,cy,R,0,6.29);x.stroke();x.beginPath();x.moveTo(cx-9,cy-R+1);x.lineTo(cx,cy-R-10);x.lineTo(cx+9,cy-R+1);x.stroke();
  [[-1],[1]].forEach(([s])=>{x.beginPath();x.ellipse(cx+s*(R+4),cy,5,13,0,0,6.29);x.stroke()});
  x.font='10px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.textAlign='center';x.textBaseline='middle';
  pos.forEach(([px,py],k)=>{const n=EL[k][0],mk=(o.marks||[]).includes(n);x.fillStyle=C.panel;x.globalAlpha=.85;x.beginPath();x.arc(px,py,mk?10:8.5,0,6.29);x.fill();x.globalAlpha=1;x.strokeStyle=mk?C.ink:C.muted;x.lineWidth=mk?2:1;x.stroke();x.fillStyle=C.ink;x.fillText(n,px,py+.5)});
  const by=cy+R+12;x.textAlign='left';x.fillStyle=C.mark;x.fillRect(cx-R,by-4,12,8);x.fillStyle=C.muted;x.fillText('negative',cx-R+16,by);x.fillStyle=C.accent;x.fillRect(cx+R-70,by-4,12,8);x.fillStyle=C.muted;x.fillText('positive',cx+R-54,by);if(o.title){x.textAlign='center';x.fillStyle=C.ink;x.fillText(o.title,cx,8)}}
/* ---- 1. dipoles and fields ---- */
const CHAINS=[['Left temporal',['Fp1','F7','T3','T5','O1']],['Left parasagittal',['Fp1','F3','C3','P3','O1']],['Right parasagittal',['Fp2','F4','C4','P4','O2']],['Right temporal',['Fp2','F8','T4','T6','O2']]];
const SRC={lat:[-.85,.45,'Left anterior temporal (F7/T3)'],ct:[-.66,.3,'Left centrotemporal (C3/T3)'],vx:[0,.05,'Vertex (Cz)'],fp:[-.32,.9,'Left frontopolar (Fp1)'],occ:[.31,-.92,'Right occipital (O2)'],rp:[.5,-.5,'Right parietal (P4)']};
function fieldLab(host){const st={src:'lat',sx:-.85,sy:.45,ori:0,dir:0,depth:.25,area:10,skull:.35,pol:-1,breach:0};
  host.innerHTML=`<div class="card stack"><h2>Dipoles and fields</h2><p style="margin:0;max-width:86ch">A patch of cortex in which pyramidal cells are depolarized together behaves like a current dipole: current enters the apical dendrites near the surface (a sink, surface-negative) and leaves deeper down (a source). What the scalp sees depends on how much cortex is synchronous, how deep it is, which way it points, and how much the skull smears it. Click the map to move the generator.</p>
   <div class="labg"><div class="stack" style="gap:8px"><canvas class="fcv" style="display:block;width:100%;height:340px;cursor:crosshair" aria-label="Scalp potential map; click to move the source"></canvas><div class="row" style="gap:6px" id="fSrc"></div></div>
   <div class="stack" style="gap:8px" id="fCtl"></div></div><p id="fRead" class="note" style="margin:0"></p></div>
   <div class="card stack"><h2>What the montage shows</h2><p style="margin:0;max-width:86ch">Each double-banana channel is front electrode minus back electrode, drawn negative-up. Where the field peaks, the channel before the peak points one way and the channel after it points the other: a <b>phase reversal</b> at the shared electrode. If the peak sits at the end of a chain (Fp or O), there is no electrode beyond it, so no reversal: check a referential montage.</p><canvas class="ccv" style="display:block;width:100%;height:300px"></canvas></div>
   <div class="card stack"><h3>At the bedside</h3><p style="margin:0">Phase reversals localize spikes; tangential dipoles explain the frontal positivity of centrotemporal spikes; skull defects raise amplitude (breach); fluid or a subdural lowers it. Most cortex is invisible to scalp EEG until roughly 6–20 cm² (estimates vary) fires together.</p>${patBtns(['temporal_spikes','cts','breach','asym','pop','blink'])}</div>`;
  const ctl=$('#fCtl',host),cv=$('.fcv',host),ccv=$('.ccv',host);
  const sl=[slider(ctl,'Orientation',{min:0,max:90,step:1,val:st.ori,fmt:v=>v<15?'radial (crown)':v>75?'tangential (sulcus)':Math.round(v)+'° tilt'},v=>{st.ori=v;draw()}),slider(ctl,'Negative end leans',{min:0,max:359,step:1,val:st.dir,fmt:v=>['backward','toward midline','forward','outward'][Math.round(v/90)%4]},v=>{st.dir=v;draw()}),
   slider(ctl,'Depth',{min:.08,max:.6,step:.01,val:st.depth,fmt:v=>v<.15?'crown':v<.35?'sulcal wall':'deep'},v=>{st.depth=v;draw()}),slider(ctl,'Synchronous area',{min:2,max:40,step:1,val:st.area,fmt:v=>v+' cm²'},v=>{st.area=v;draw()}),
   slider(ctl,'Skull smearing',{min:.15,max:.6,step:.01,val:st.skull,fmt:v=>v<.25?'low':v<.45?'typical':'high'},v=>{st.skull=v;draw()})];
  const tg=el('div','row');tg.innerHTML=`<label class="row lbl" style="gap:6px;text-transform:none;letter-spacing:0"><input type="checkbox" id="fPol"> Surface-positive generator</label><label class="row lbl" style="gap:6px;text-transform:none;letter-spacing:0"><input type="checkbox" id="fBr"> Skull defect over the source</label>`;ctl.appendChild(tg);
  $('#fPol',host).addEventListener('change',e=>{st.pol=e.target.checked?1:-1;draw()});$('#fBr',host).addEventListener('change',e=>{st.breach=e.target.checked?1:0;draw()});
  $('#fSrc',host).innerHTML=Object.entries(SRC).map(([k,s])=>`<button class="chip" type="button" data-fs="${k}" aria-pressed="${k===st.src}">${s[2]}</button>`).join('');
  $$('[data-fs]',host).forEach(b=>b.addEventListener('click',()=>{const s=SRC[b.dataset.fs];st.src=b.dataset.fs;st.sx=s[0];st.sy=s[1];if(st.src==='ct'){st.ori=80;st.dir=0;sl[0].set(80);sl[1].set(0)}else{st.ori=0;sl[0].set(0)}$$('[data-fs]',host).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw()}));
  cv.addEventListener('click',e=>{const b=cv.getBoundingClientRect(),w=b.width,h=b.height,R=Math.min(w,h-28)/2-14,x=(e.clientX-b.left-w/2)/(R*.86),y=-(e.clientY-b.top-(R+16))/(R*.86);if(x*x+y*y>1.25)return;st.sx=x;st.sy=y;st.src=null;$$('[data-fs]',host).forEach(q=>q.setAttribute('aria-pressed','false'));draw()});
  const sph=(x,y)=>{const r=Math.min(1.15,Math.hypot(x,y)),th=r*Math.PI/2,ph=Math.atan2(y,x);return[Math.sin(th)*Math.cos(ph),Math.sin(th)*Math.sin(ph),Math.cos(th)]};
  function field(){const s=sph(st.sx,st.sy),rs=s.map(c=>c*(1-st.depth)),up=s,proj=v=>{const d=v[0]*up[0]+v[1]*up[1]+v[2]*up[2];return v.map((c,i)=>c-d*up[i])},e1=norm3(proj([0,-1,0])),m0=proj([0,0,1]),mm=Math.hypot(...m0)>.05?m0:proj([-Math.sign(up[0]||1),0,0]),md=mm[0]*e1[0]+mm[1]*e1[1]+mm[2]*e1[2],e2=norm3(mm.map((c,i)=>c-md*e1[i])),a=st.dir*Math.PI/180,tan=e1.map((c,i)=>c*Math.cos(a)+e2[i]*Math.sin(a)),o=st.ori*Math.PI/180,p=up.map((c,i)=>c*Math.cos(o)+tan[i]*Math.sin(o));
    const raw=EL.map(([n,x,y])=>{const re=sph(x,y),d=re.map((c,i)=>c-rs[i]),r3=Math.hypot(...d)**3;return(p[0]*d[0]+p[1]*d[1]+p[2]*d[2])/r3});
    const sm=EL.map(([,x,y],i)=>{let sw=0,sv=0;const sig=st.breach&&Math.hypot(x-st.sx,y-st.sy)<.45?st.skull*.45:st.skull;EL.forEach(([,x2,y2],k)=>{const ww=Math.exp(-((x-x2)**2+(y-y2)**2)/(2*sig*sig));sw+=ww;sv+=ww*raw[k]});let v=sv/sw;if(st.breach&&Math.hypot(x-st.sx,y-st.sy)<.45)v*=1.8;return v});
    const k=st.pol*st.area*1.15/(1+3*st.skull);return sm.map(v=>v*k)}
  function draw(){const V=field(),m=V.reduce((a,b)=>a+b,0)/NE,Va=V.map(v=>v-m),mxi=Va.reduce((bi,v,i)=>Math.abs(v)>Math.abs(Va[bi])?i:bi,0),peak=Va[mxi];
    drawTopo(cv,V,{marks:[EL[mxi][0]],range:Math.max(15,Math.max(...Va.map(Math.abs)))});
    const S_=cvSetup(ccv);if(S_){const{g:x,w,h,C}=S_,rowH=(h-10)/4,mono=getComputedStyle(document.body).getPropertyValue('--font-mono');x.font='10.5px '+mono;x.textBaseline='middle';
      CHAINS.forEach(([nm,ch],ri)=>{const y0=6+ri*rowH;x.fillStyle=C.muted;x.textAlign='left';x.fillText(nm,4,y0+9);const n=ch.length-1,cw=(w-8)/n;let vmax=1;CHAINS.forEach(([,c2])=>{for(let i=0;i<c2.length-1;i++)vmax=Math.max(vmax,Math.abs(V[IX[c2[i]]]-V[IX[c2[i+1]]]))});
        for(let i=0;i<n;i++){const a=ch[i],b=ch[i+1],dv=V[IX[a]]-V[IX[b]],x0=4+i*cw,cy=y0+rowH*.58,amp=-dv/vmax*rowH*.36;x.strokeStyle=C.grid;x.beginPath();x.moveTo(x0+4,cy);x.lineTo(x0+cw-4,cy);x.stroke();
          x.strokeStyle=C.trace;x.lineWidth=1.6;x.beginPath();for(let k=0;k<=60;k++){const t=k/60,yy=cy-(-amp)*(Math.exp(-((t-.45)**2)/.004)-.35*Math.exp(-((t-.62)**2)/.01));k?x.lineTo(x0+6+t*(cw-12),yy):x.moveTo(x0+6,yy)}x.stroke();x.lineWidth=1;x.fillStyle=C.ink;x.textAlign='center';x.fillText(`${a}–${b}`,x0+cw/2,y0+rowH-6)}
        for(let i=0;i<n-1;i++){const d1=V[IX[ch[i]]]-V[IX[ch[i+1]]],d2=V[IX[ch[i+1]]]-V[IX[ch[i+2]]];if(d1*d2<0&&Math.min(Math.abs(d1),Math.abs(d2))>.08*vmax){const xx=4+(i+1)*cw;x.strokeStyle=C.mark;x.lineWidth=2;x.setLineDash([4,3]);x.beginPath();x.moveTo(xx,y0+14);x.lineTo(xx,y0+rowH-14);x.stroke();x.setLineDash([]);x.lineWidth=1;x.fillStyle=C.mark;x.fillText('reversal at '+ch[i+1],xx,y0+12)}}})}
    const tang=st.ori>60;$('#fRead',host).innerHTML=`Largest ${peak<0?'negativity':'positivity'} at <b>${EL[mxi][0]}</b> (about ${Math.abs(peak).toFixed(0)} µV against the average). ${tang?'A tangential generator makes two poles of opposite sign with little directly above it, as with centrotemporal spikes.':'A radial generator puts one maximum over the source.'} ${st.area<6?'With so little synchronous cortex the scalp signal would be lost in the background.':''} ${['Fp1','Fp2','O1','O2'].includes(EL[mxi][0])?'The maximum is at the end of a chain: no phase reversal in the double banana.':''}`}
  return{draw}}
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm3=a=>{const m=Math.hypot(...a)||1;return a.map(v=>v/m)};
/* ---- 2. thalamus and rhythms ---- */
function thalLab(host){const st={vm:-55,eyes:'closed',drug:null,absence:false};
  host.innerHTML=`<div class="card stack"><h2>Thalamus and rhythms</h2><p style="margin:0;max-width:86ch">Thalamic relay neurons decide what the cortex does. Arousal transmitters (acetylcholine from the brainstem and basal forebrain, noradrenaline from the locus coeruleus, serotonin, histamine, orexin) hold them depolarized, in <b>tonic mode</b>: they relay input faithfully and the cortex desynchronizes. As arousal input falls they hyperpolarize; T-type Ca²⁺ channels recover, and the neurons fire in <b>bursts</b> paced by the GABAergic thalamic reticular nucleus (TRN): spindles, then delta. Move the membrane potential and watch the cortex follow.</p>
   <div class="labg"><div class="stack" style="gap:10px"><div id="tSvg"></div><div id="tCtl" class="stack" style="gap:8px"></div><div class="row" style="gap:6px" id="tDrug"></div></div>
   <div class="stack" style="gap:8px"><span class="lbl">Relay neuron membrane potential (3 s)</span><canvas class="vcv" style="display:block;width:100%;height:150px"></canvas><span class="lbl">Scalp EEG (referential, 10 s)</span><canvas class="ecv" style="display:block;width:100%;height:230px"></canvas></div></div>
   <div class="note" id="tRead"></div></div>
   <div class="card stack"><h3>At the bedside</h3><p style="margin:0">Alpha that blocks with eye opening, spindles in N2, delta in N3, 3 Hz spike-and-wave in absence epilepsy, sleep-like spindles under dexmedetomidine and frontal alpha under propofol all come from this one circuit in different states.</p>${patBtns(['awake','reactivity','drowsy','n2','n3','sw3','dexmed','propofol','benzo'])}</div>`;
  const ctl=$('#tCtl',host);const vs=slider(ctl,'Relay membrane potential',{min:-80,max:-50,step:1,val:st.vm,fmt:v=>Math.round(v)+' mV'},v=>{st.vm=v;run()});
  const sg=el('div','row');ctl.appendChild(sg);segment(sg,[['closed','Eyes closed'],['open','Eyes open']],'closed',v=>{st.eyes=v;run()});const ab=el('label','row lbl','<input type="checkbox"> Absence-prone network (strong GABA-B, hyperexcitable cortex)');ab.style.cssText='gap:6px;text-transform:none;letter-spacing:0';sg.appendChild(ab);$('input',ab).addEventListener('change',e=>{st.absence=e.target.checked;run()});
  const DR={none:['No drug',0],dexmed:['Dexmedetomidine (α2: less noradrenaline)',-9],benzo:['Benzodiazepine (GABA-A)',-3],propofol:['Propofol (strong GABA-A)',-12],etho:['Ethosuximide (T-type block)',0],arouse:['Loud voice (arousal burst)',+10]};
  $('#tDrug',host).innerHTML=Object.entries(DR).map(([k,[t]])=>`<button class="chip" type="button" data-dr="${k}" aria-pressed="${k==='none'}">${t}</button>`).join('');$$('[data-dr]',host).forEach(b=>b.addEventListener('click',()=>{st.drug=b.dataset.dr==='none'?null:b.dataset.dr;$$('[data-dr]',host).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));run()}));
  let seed=1,rec=null,mode='';
  function modeOf(){let v=st.vm+(st.drug?DR[st.drug][1]:0);const tBlock=st.drug==='etho';if(st.drug==='propofol')return['propofol',v];if(v>-60)return[st.eyes==='open'?'tonic-open':'tonic-alpha',v];if(st.absence&&v<=-60&&v>-72&&!tBlock)return['sw',v];if(v>-68)return[tBlock?'quiet':'spindle',v];return[tBlock?'quiet':'delta',v]}
  function run(){const[m,v]=modeOf();mode=m;seed++;const r=mkRand(seed),R=newRec();
    if(m==='tonic-alpha'){awakeBg(R,r,{A:34})}else if(m==='tonic-open'){addBg(R,r,{rms:3,lo:1,hi:30});addBand(R,r,W.all,14,28,5);addBand(R,r,W.post,8,12,3)}
    else if(m==='spindle'){addBg(R,r,{rms:2,lo:1,hi:20});addBand(R,r,W.all,4,7,5);ev(R,r,[r.r(1,2),r.r(4.5,5.5),r.r(7.5,8.8)],T.spind,one(['Cz',1],['C3',.8],['C4',.8],['Fz',.7],['F3',.5],['F4',.5],['Pz',.4]),45,{span:.8})}
    else if(m==='delta'){addBg(R,r,{rms:2.5,lo:1,hi:20});addBand(R,r,W.fc.map(x=>.35+.65*x),.6,2.5,40,waxwane(r,.25,[2,4]))}
    else if(m==='sw'){addBg(R,r,{rms:2,lo:1,hi:20});addBand(R,r,W.all,4,7,4);const ts=[];let t=1.2;while(t<8.6){ts.push(t);t+=1/3.1}ev(R,r,ts,T.sw,blob(0,.35,.8).map(x=>.3+.7*x),150,{span:.5})}
    else if(m==='quiet'){addBg(R,r,{rms:2.2,lo:1,hi:20});addBand(R,r,W.all,3,7,4)}
    else{addBg(R,r,{rms:2,lo:1,hi:25});const P=phaseOf(r,r.r(9.5,11),.04);addOsc(R,W.ant.map((x,i)=>.15+.85*Math.max(x,W.fc[i])),P,waxwane(r,.3),30,0);addBand(R,r,W.fc,.5,1.5,24)}
    if(st.drug==='benzo'&&m!=='propofol')addBand(R,r,W.fc,16,24,6);rec=R;draw()}
  function vmTrace(m,v,n){const r=mkRand(seed+9),o=new Float32Array(n),fs=n/3;let t=0;const base=m==='propofol'?-70:clamp(v,-82,-48);for(let i=0;i<n;i++)o[i]=base+.6*r.n();
    const spike=(i0,amp=95)=>{for(let k=0;k<4&&i0+k<n;k++)o[i0+k]=base+amp*(k<2?1:-.15)};
    if(m.startsWith('tonic')){let tt=0;while(tt<3){tt+=-Math.log(r.u()+1e-9)/(m==='tonic-open'?18:9);const i=Math.floor(tt*fs);if(i<n)spike(i)}}
    else{const per=m==='delta'?1/2:m==='sw'?1/3.1:1/9,cyc=m==='spindle'?[[.3,1],[1.6,1.1]]:[[0,3]];cyc.forEach(([a,len])=>{for(let tt=a;tt<a+len;tt+=per){const i0=Math.floor(tt*fs);for(let k=0;k<Math.floor(.06*fs)&&i0+k<n;k++)o[i0+k]+=(m==='quiet'?3:22)*Math.sin(Math.PI*k/(.06*fs));if(m!=='quiet')for(let q=0;q<(m==='delta'?4:3);q++)spike(i0+Math.floor((.012+q*.008)*fs),75);
      if(m==='spindle'){const j0=Math.floor((tt+per*.55)*fs);for(let k=0;k<Math.floor(.05*fs)&&j0+k<n;k++)o[j0+k]-=6*Math.sin(Math.PI*k/(.05*fs))}}})}return o}
  function draw(){const[m,v]=modeOf(),vcv=$('.vcv',host),S_=cvSetup(vcv);if(S_){const{g:x,w,h,C}=S_,n=600,d=vmTrace(m,v,n),Y=mv=>h-10-(mv+90)/(60)*(h-20);x.strokeStyle=C.grid;[-80,-60,-40,0].forEach(mv=>{x.beginPath();x.moveTo(36,Y(mv));x.lineTo(w,Y(mv));x.stroke();x.fillStyle=C.muted;x.font='10px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.fillText(mv+'',2,Y(mv)+3)});
      x.strokeStyle=C.trace;x.lineWidth=1.2;x.beginPath();for(let i=0;i<n;i++){const X=36+i/(n-1)*(w-40),yy=Y(clamp(d[i],-90,10));i?x.lineTo(X,yy):x.moveTo(X,yy)}x.stroke()}
    const ecv=$('.ecv',host),pick=['Fz','Cz','C3','O1','O2'],rows=pick.map(k=>({data:(()=>{const a=rec.V[IX[k]],m_=new Float32Array(N);let mm=0;for(let e=0;e<NE;e++)for(let i=0;i<N;i+=10)mm+=rec.V[e][i];for(let i=0;i<N;i++)m_[i]=a[i];return runbq(m_,bq('hp',1,.707))})(),label:k}));drawRows(ecv,rows,{rowH:42,t0:0,dur:10,norm:false,pxUv:.35,labelW:44,lw:1.1});
    const TX={'tonic-alpha':'<b>Tonic mode, eyes closed.</b> Relay neurons fire single spikes; the visual thalamocortical loop idles at about 10 Hz, so alpha appears posteriorly.','tonic-open':'<b>Tonic mode, eyes open.</b> Visual input drives the relay neurons asynchronously: alpha blocks and low-voltage fast activity remains.',spindle:'<b>Burst mode: spindles (N2).</b> TRN neurons inhibit relay cells rhythmically; each rebound low-threshold Ca²⁺ burst drives the cortex: 12–14 Hz waxing-waning spindles.',delta:'<b>Deep burst mode: delta (N3).</b> At about −70 mV and below, T-type and H-currents make relay neurons oscillate on their own at 1–4 Hz; the cortex follows with high-amplitude delta.',sw:'<b>Absence mode: 3 Hz spike-and-wave.</b> A hyperexcitable cortex recruits the TRN; GABA-B inhibition and T-type rebound bursts lock thalamus and cortex into a 3 Hz cycle. Try ethosuximide.',quiet:'<b>T-type channels blocked.</b> Hyperpolarized relay neurons can no longer produce low-threshold bursts, so spindles, delta and spike-and-wave all fade. This is how ethosuximide stops absence seizures.',propofol:'<b>Propofol.</b> Strong GABA-A potentiation hyperpolarizes thalamus and cortex; thalamocortical loops settle into a frontal alpha rhythm on top of slow waves (anteriorization).'};
    $('#tRead',host).innerHTML=`${TX[m]} <span class="lbl" style="text-transform:none;letter-spacing:0">Effective membrane potential ${Math.round(v)} mV.</span>`;
    $('#tSvg',host).innerHTML=circuitSvg(m)}
  function circuitSvg(m){const on=c=>`var(--${c})`,ar=m.startsWith('tonic'),burst=['spindle','delta','sw'].includes(m);return`<svg viewBox="0 0 320 170" style="width:100%;max-width:420px;display:block" role="img" aria-label="Thalamocortical circuit"><defs><marker id="ah" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="var(--muted)"/></marker></defs>
    <rect x="70" y="8" width="180" height="34" rx="8" fill="${burst||m==='sw'?'color-mix(in srgb,var(--mark) 25%,var(--panel))':ar?'color-mix(in srgb,var(--accent) 18%,var(--panel))':'var(--soft)'}" stroke="var(--line)"/><text x="160" y="29" text-anchor="middle" font-size="12" fill="var(--ink)">Cortex (pyramidal cells)</text>
    <rect x="40" y="82" width="110" height="34" rx="8" fill="${m==='spindle'||m==='sw'?'color-mix(in srgb,var(--mark) 30%,var(--panel))':'var(--soft)'}" stroke="var(--line)"/><text x="95" y="103" text-anchor="middle" font-size="11.5" fill="var(--ink)">Reticular nucleus</text>
    <rect x="170" y="82" width="110" height="34" rx="8" fill="${burst?'color-mix(in srgb,var(--mark) 25%,var(--panel))':ar?'color-mix(in srgb,var(--accent) 18%,var(--panel))':'var(--soft)'}" stroke="var(--line)"/><text x="225" y="103" text-anchor="middle" font-size="11.5" fill="var(--ink)">Relay nucleus</text>
    <rect x="110" y="134" width="180" height="30" rx="8" fill="${ar?'color-mix(in srgb,var(--good) 22%,var(--panel))':'var(--soft)'}" stroke="var(--line)"/><text x="200" y="153" text-anchor="middle" font-size="11" fill="var(--ink)">Arousal: ACh, NE, 5-HT, orexin</text>
    <path d="M225 82 L225 44" stroke="var(--muted)" stroke-width="1.6" marker-end="url(#ah)"/><path d="M200 44 L200 80" stroke="var(--muted)" stroke-width="1.6" marker-end="url(#ah)"/><path d="M150 99 L168 99" stroke="var(--bad)" stroke-width="2" marker-end="url(#ah)"/><path d="M120 44 L110 80" stroke="var(--muted)" stroke-width="1.6" marker-end="url(#ah)"/>
    <path d="M240 134 L240 118" stroke="var(--good)" stroke-width="${ar?3:1.2}" marker-end="url(#ah)"/><path d="M280 134 C300 100 290 60 252 44" fill="none" stroke="var(--good)" stroke-width="${ar?3:1.2}" marker-end="url(#ah)"/><text x="159" y="78" font-size="9.5" fill="var(--bad)">GABA</text></svg>`}
  run();return{draw}}
/* ---- 3. synapses, excitation-inhibition and drugs: Jansen–Rit neural mass ---- */
function jansenRit(o,seed){const A=o.A,B=o.B,a=100,b=o.b,C=135,C1=C,C2=.8*C,C3=.25*C,C4=.25*C,e0=o.e0,v0=6,r=.56,pm=o.p,ps=30,S=v=>2*e0/(1+Math.exp(r*(v0-v))),rr=mkRand(seed);let y=[0,0,0,0,0,0],p=pm;const dt=.0005,out=new Float32Array(N);let k=0;
  for(let i=0;i<24000;i++){if(i%2===0)p=pm+ps*rr.n();const[y0,y1,y2,y3,y4,y5]=y,d=[y3,y4,y5,A*a*S(y1-y2)-2*a*y3-a*a*y0,A*a*(p+C2*S(C1*y0))-2*a*y4-a*a*y1,B*b*C4*S(C3*y0)-2*b*y5-b*b*y2];for(let q=0;q<6;q++)y[q]+=dt*d[q];if(i>=4000&&i%10===0&&k<N)out[k++]=y1-y2}return out}
function jrStats(x){const n=x.length;let m=0;for(const v of x)m+=v;m/=n;let sd=0;for(const v of x)sd+=(v-m)**2;sd=Math.sqrt(sd/n);let pk=0,last=-99;for(let i=1;i<n-1;i++)if(x[i]>m+Math.max(2.5*sd,3)&&x[i]>=x[i-1]&&x[i]>x[i+1]&&i-last>20){pk++;last=i}
  let best=0,bf=0;for(let f=.5;f<=20;f+=.25){let re=0,im=0;for(let i=0;i<n;i+=2){re+=(x[i]-m)*Math.cos(2*Math.PI*f*i/FS);im+=(x[i]-m)*Math.sin(2*Math.PI*f*i/FS)}const p=re*re+im*im;if(p>best){best=p;bf=f}}
  const lab=sd<.6?['Quiet, low-amplitude background','The population barely oscillates: little drive and balanced inhibition.']:pk>=13&&bf<5.5?[`Rhythmic spike discharges (~${bf} Hz): seizure-like`,'Excitation repeatedly escapes inhibition in synchrony; each spike is followed by a wave of inhibition, then the next spike.']:pk>=1?['Sporadic spikes on a quiet background: interictal-like','Occasionally the excitatory loop runs away into a synchronized discharge, then inhibition restores the background.']:bf>=8&&bf<=13?['Alpha-like background','Excitatory and inhibitory loops resonate near 10 Hz, as in the resting, idling cortex.']:sd>3.5&&bf<8?['High-amplitude rhythmic theta: hypersynchronous','Strong excitation with weak control drives the whole population into a slow, large rhythm.']:['Slower irregular background','The loop resonates below alpha.'];
  return{sd,pk,bf,lab}}
function synLab(host){const P0={A:3.25,B:22,b:50,p:220,e0:2.5},st=Object.assign({},P0);
  host.innerHTML=`<div class="card stack"><h2>Synapses, excitation–inhibition and drugs</h2><p style="margin:0;max-width:86ch">A neural-mass model (Jansen and Rit, 1995) treats a cortical column as three populations: pyramidal cells, excitatory interneurons and inhibitory interneurons, linked by synapses with realistic gains and time constants. Its output (pyramidal membrane potential, the generator of the EEG) changes regime as you shift the balance between glutamatergic excitation and GABAergic inhibition, as Wendling and colleagues showed for epileptic activity. The model is a teaching sketch, not a brain.</p>
   <div class="labg"><div id="sCtl" class="stack" style="gap:8px"></div><div class="stack" style="gap:8px"><div class="row" style="gap:6px" id="sPre"></div><div class="row" style="gap:6px" id="sDrug"></div></div></div>
   <canvas class="scv" style="display:block;width:100%;height:150px"></canvas><div class="note" id="sRead"></div></div>
   <div class="card stack"><h2>One spike, two views</h2><p style="margin:0;max-width:86ch">Inside each neuron of a spiking patch, the <b>paroxysmal depolarization shift</b> (PDS) is a giant depolarization driven by AMPA and NMDA glutamate receptors and voltage-gated Ca²⁺ channels, crowned by a burst of action potentials. It ends in a deep after-hyperpolarization (GABA-B receptors and Ca²⁺-activated K⁺ channels). At the scalp, the synchronized PDS is the surface-negative <b>spike</b>; the synchronized hyperpolarization is the <b>after-going slow wave</b>. That pairing is why the slow wave is one of the best signs that a sharp transient is epileptiform.</p><canvas class="pcv" style="display:block;width:100%;height:240px"></canvas></div>
   <div class="card stack"><h3>At the bedside</h3><p style="margin:0">Benzodiazepines strengthen and lengthen GABA-A inhibition; in prolonged status, GABA-A receptors are internalized and NMDA receptors added, which is why benzodiazepines lose power with time and why early treatment matters. Na⁺-channel blockers limit how fast neurons can fire. Sleep and drowsiness lower cortical drive, which is one reason interictal spikes multiply in sleep.</p>${patBtns(['temporal_spikes','sw3','seizure','ncse','benzo','propofol','lpd'])}</div>`;
  const ctl=$('#sCtl',host),S={};S.A=slider(ctl,'Excitatory gain (glutamate)',{min:2.8,max:4.6,step:.01,val:st.A,fmt:v=>v.toFixed(2)+' mV'},v=>{st.A=v;run()});S.B=slider(ctl,'Inhibitory gain (GABA-A)',{min:10,max:45,step:.5,val:st.B,fmt:v=>v.toFixed(1)+' mV'},v=>{st.B=v;run()});
  S.b=slider(ctl,'Inhibition speed',{min:25,max:80,step:1,val:st.b,fmt:v=>(1000/v).toFixed(0)+' ms IPSP'},v=>{st.b=v;run()});S.p=slider(ctl,'Input drive (arousal)',{min:60,max:300,step:5,val:st.p,fmt:v=>Math.round(v)+' /s'},v=>{st.p=v;run()});S.e0=slider(ctl,'Maximum firing rate',{min:1.6,max:3,step:.05,val:st.e0,fmt:v=>(v*2).toFixed(1)+' /s'},v=>{st.e0=v;run()});
  const set=o=>{Object.assign(st,o);Object.keys(S).forEach(k=>S[k].set(st[k]));run()};
  const PRE=[['Resting awake cortex',P0],['Drowsy, low drive',{A:3.25,B:22,b:50,p:90,e0:2.5}],['Irritable cortex, drowsy',{A:3.55,B:22,b:50,p:90,e0:2.5}],['Seizing cortex',{A:3.75,B:22,b:50,p:90,e0:2.5}]];
  $('#sPre',host).innerHTML='<span class="lbl">Start from</span>'+PRE.map(([t],i)=>`<button class="chip" type="button" data-pre="${i}">${t}</button>`).join('');$$('[data-pre]',host).forEach(b=>b.addEventListener('click',()=>set(Object.assign({},PRE[+b.dataset.pre][1]))));
  const DRG=[['Benzodiazepine',()=>({B:st.B*1.27,b:Math.max(25,st.b*.8)}),'Strengthens and prolongs GABA-A inhibition.'],['Na⁺-channel blocker',()=>({e0:2.2}),'Limits sustained high-frequency firing (phenytoin, carbamazepine, lacosamide).'],['Propofol (anesthetic dose)',()=>({B:40,b:35,p:Math.min(st.p,130)}),'Massive GABA-A potentiation with less drive.'],['More excitation (low Mg²⁺, high K⁺)',()=>({A:st.A+.15}),'Raises effective excitatory gain.']];
  $('#sDrug',host).innerHTML='<span class="lbl">Apply</span>'+DRG.map(([t,,d],i)=>`<button class="chip" type="button" data-drg="${i}" title="${d}">${t}</button>`).join('');$$('[data-drg]',host).forEach(b=>b.addEventListener('click',()=>set(DRG[+b.dataset.drg][1]())));
  let out=null,sts=null,seed=3;function run(){seed++;out=jansenRit(st,seed);sts=jrStats(out);draw()}
  function draw(){const c=$('.scv',host);let m=0;for(const v of out)m+=v;m/=N;const d=new Float32Array(N);for(let i=0;i<N;i++)d[i]=(out[i]-m);drawRows(c,[{data:d,label:'Model EEG'}],{rowH:124,t0:0,dur:10,norm:false,pxUv:5,labelW:80,bars:false,lw:1.2});
    $('#sRead',host).innerHTML=`<b>${sts.lab[0]}.</b> ${sts.lab[1]} <span class="lbl" style="text-transform:none;letter-spacing:0">Dominant frequency ${sts.bf} Hz · ${sts.pk} spikes in 10 s · excitation/inhibition gain ratio ${(st.A/st.B*10).toFixed(2)}.</span>`;
    const pc=$('.pcv',host),S_=cvSetup(pc);if(S_){const{g:x,w,h,C}=S_,n=500,t=i=>i/n*.8-.1,top=h*.08,mid=h*.48,mono=getComputedStyle(document.body).getPropertyValue('--font-mono'),L=110,X=i=>L+i/(n-1)*(w-L-10);x.font='11px '+mono;x.fillStyle=C.muted;x.textBaseline='middle';x.fillText('Neuron (intracellular)',4,top+30);x.fillText('Scalp EEG',4,mid+60);
      x.strokeStyle=C.trace;x.lineWidth=1.3;x.beginPath();for(let i=0;i<n;i++){const tt=t(i);let v=-70;if(tt>0&&tt<.12)v=-70+35*Math.min(1,tt/.008)*(tt<.1?1:1-(tt-.1)/.02);if(tt>=.12&&tt<.5)v=-70-12*Math.sin(Math.PI*(tt-.12)/.38);if(tt>.006&&tt<.09&&((tt*1000)%14)<2.2)v=+15;const yy=top+70-(v+80)/100*90;i?x.lineTo(X(i),yy):x.moveTo(X(i),yy)}x.stroke();
      x.beginPath();for(let i=0;i<n;i++){const tt=t(i),e=Math.exp(-((tt-.04)**2)/(2*.022**2))-.35*Math.exp(-((tt-.27)**2)/(2*.1**2));const yy=mid+70-e*55;i?x.lineTo(X(i),yy):x.moveTo(X(i),yy)}x.stroke();
      const band=(a,b,c,lab)=>{x.fillStyle=c;x.globalAlpha=.12;x.fillRect(X((a+.1)/.8*n),4,X((b+.1)/.8*n)-X((a+.1)/.8*n),h-8);x.globalAlpha=1;x.fillStyle=c;x.textAlign='center';x.fillText(lab,(X((a+.1)/.8*n)+X((b+.1)/.8*n))/2,h-10);x.textAlign='left'};
      band(0,.12,C.mark,'PDS → spike');band(.12,.5,C.accent,'hyperpolarization → slow wave')}}
  run();return{draw}}
/* ---- 4. blood flow and energy ---- */
function cbfLab(host){const st={cbf:50,mode:'focal',t:0,cpr:false,map:85,icp:10,co2:40,imp:false};
  host.innerHTML=`<div class="card stack"><h2>Blood flow and energy</h2><p style="margin:0;max-width:86ch">Synapses are the brain’s most energy-hungry machinery, so they fail first when flow falls, long before cells die. That makes the EEG a real-time perfusion monitor. Thresholds below are approximate, from primate and human studies (Astrup, Jones and colleagues), and depend on duration.</p>
   <div class="row" id="cMode"></div><div id="cCtl" class="stack" style="gap:8px"></div>
   <div class="labg"><div class="stack" style="gap:6px"><span class="lbl">EEG over the affected cortex</span><canvas class="ccv" style="display:block;width:100%;height:200px"></canvas></div><div class="stack" style="gap:6px"><span class="lbl">Cellular state</span><div id="cBars" class="stack" style="gap:6px"></div></div></div>
   <div class="note" id="cRead"></div><div><span class="lbl">Tolerated duration versus flow</span><canvas class="tcv2" style="display:block;width:100%;height:170px"></canvas></div></div>
   <div class="card stack"><h2>Autoregulation, pressure and CO₂</h2><p style="margin:0;max-width:86ch">Flow depends on perfusion pressure (CPP = MAP − ICP) and on vessel tone. With intact autoregulation, arterioles dilate or constrict to hold flow steady over roughly 50–150 mmHg (right-shifted in chronic hypertension). CO₂ resets vessel tone. After cardiac arrest, trauma or SAH, autoregulation can fail and flow follows pressure passively.</p>
   <div id="aCtl" class="stack" style="gap:8px"></div><canvas class="acv" style="display:block;width:100%;height:220px"></canvas><div class="row"><button class="btn small" type="button" id="aSend">Use this flow in the EEG panel above</button><span class="lbl" id="aOut" style="text-transform:none;letter-spacing:0"></span></div></div>
   <div class="card stack"><h3>At the bedside</h3><p style="margin:0">Falling alpha/delta ratio warns of delayed cerebral ischemia after SAH; carotid clamping that drops flow below about 20 mL/100 g/min flattens the ipsilateral EEG within seconds; after cardiac arrest the EEG goes isoelectric in about 15–20 s, and what returns reflects which neurons survived.</p>${patBtns(['focal_slow','asym','lowvolt','bs_ident','supp_pd','hvresp'])}</div>`;
  const ctl=$('#cCtl',host);let fs,ts,cs;segment($('#cMode',host),[['focal','Regional flow'],['arrest','Cardiac arrest timeline']],'focal',v=>{st.mode=v;fs.input.closest('.sl').hidden=v!=='focal';ts.input.closest('.sl').hidden=v!=='arrest';cs.hidden=v!=='arrest';run()});
  fs=slider(ctl,'Cerebral blood flow',{min:0,max:80,step:1,val:st.cbf,fmt:v=>v+' mL/100 g/min'},v=>{st.cbf=v;run()});ts=slider(ctl,'Time since circulation stopped',{min:0,max:600,step:1,val:0,fmt:v=>v<120?Math.round(v)+' s':(v/60).toFixed(1)+' min'},v=>{st.t=v;run()});ts.input.closest('.sl').hidden=true;
  cs=el('label','row lbl','<input type="checkbox"> CPR in progress (about 20–30% of normal flow)');cs.style.cssText='gap:6px;text-transform:none;letter-spacing:0';cs.hidden=true;ctl.appendChild(cs);$('input',cs).addEventListener('change',e=>{st.cpr=e.target.checked;run()});
  const actl=$('#aCtl',host),am=slider(actl,'Mean arterial pressure',{min:30,max:180,step:1,val:st.map,fmt:v=>v+' mmHg'},v=>{st.map=v;drawA()}),ai=slider(actl,'Intracranial pressure',{min:0,max:60,step:1,val:st.icp,fmt:v=>v+' mmHg'},v=>{st.icp=v;drawA()}),ac=slider(actl,'PaCO₂',{min:20,max:80,step:1,val:st.co2,fmt:v=>v+' mmHg'},v=>{st.co2=v;drawA()});
  const ib=el('label','row lbl','<input type="checkbox"> Autoregulation impaired');ib.style.cssText='gap:6px;text-transform:none;letter-spacing:0';actl.appendChild(ib);$('input',ib).addEventListener('change',e=>{st.imp=e.target.checked;drawA()});
  const cbfOf=(cpp,co2,imp)=>{const k=clamp(1+.03*(co2-40),.45,2);if(imp)return clamp(50*cpp/80,0,140)*k;let f=cpp<50?50*cpp/50:cpp<=150?50:50+(cpp-150)*.6;return clamp(f*k,0,140)};
  $('#aSend',host).addEventListener('click',()=>{st.mode='focal';const v=Math.round(cbfOf(st.map-st.icp,st.co2,st.imp));st.cbf=Math.min(80,v);fs.set(st.cbf);$$('#cMode button',host)[0].click();host.scrollIntoView({behavior:'smooth'})});
  let rec=null,seed=1;
  function flowNow(){if(st.mode==='focal')return st.cbf;if(st.cpr)return 12;return 0}
  function cell(){if(st.mode==='arrest'){const t=st.t,f=st.cpr?.25:0,sec=t;const eeg=sec<8?1-sec/14:sec<20?Math.max(0,.45*(1-(sec-8)/12)):0,atp=Math.max(st.cpr?.25:0,1-sec/(st.cpr?400:240)),dep=sec>120&&!st.cpr?Math.min(1,(sec-120)/120):st.cpr&&sec>300?Math.min(.6,(sec-300)/400):0;return{eeg:st.cpr?Math.min(eeg+.0,eeg):eeg,slow:sec>3&&sec<20?1:0,atp,pump:atp,k:dep,ca:dep,glu:dep}}
    const f=st.cbf,eeg=f>=35?1:f>=18?.25+.75*(f-18)/17:f>=12?.25*(f-12)/6:0,fast=clamp((f-22)/18,0,1),atp=f>=15?1:f>=8?.4+.6*(f-8)/7:f/8*.4,dep=f<10?clamp((10-f)/6,0,1):0;return{eeg,fast,slow:clamp((40-f)/20,0,1)*(f>15?1:.6),atp,pump:atp,k:dep,ca:dep,glu:Math.max(dep,f<15?.3:0)}}
  function run(){seed++;const c=cell(),r=mkRand(seed),R=newRec();if(st.mode==='focal'){addBg(R,r,{rms:1.2,lo:1,hi:30});if(c.eeg>0){const fast=c.fast;const P=phaseOf(r,9.5,.04);addOsc(R,W.all,P,waxwane(r,.4),30*fast*c.eeg,0);addBand(R,r,W.all,14,25,6*fast*c.eeg);addBand(R,r,W.all,4,7,9*c.eeg*(.4+.6*c.slow));addBand(R,r,W.all,.8,3,26*c.eeg*c.slow)}}
    else{addBg(R,r,{rms:1,lo:1,hi:30});const e=new Float32Array(N);for(let i=0;i<N;i++){const sec=st.t+i/FS;e[i]=sec<8?1-sec/14:sec<20?Math.max(0,.45*(1-(sec-8)/12)):0}const P=phaseOf(r,9.5,.04),sl=new Float32Array(N);for(let i=0;i<N;i++){const sec=st.t+i/FS;sl[i]=e[i]*(sec>3?1:sec/3)}addOsc(R,W.all,P,e,28,0);addBand(R,r,W.all,.8,3,30,sl)}rec=R;draw()}
  function draw(){const c=cell();drawRows($('.ccv',host),['Fp1','C3','O1'].map(k=>({data:runbq(Float32Array.from(rec.V[IX[k]]),bq('hp',1,.707)),label:k})),{rowH:58,t0:0,dur:10,norm:false,pxUv:.5,labelW:40,lw:1.1});
    const bars=[['ATP',c.atp,'good'],['Na⁺/K⁺ pump',c.pump,'good'],['K⁺ leaving cells',c.k,'bad'],['Ca²⁺ entering cells',c.ca,'bad'],['Glutamate release',c.glu,'bad']];$('#cBars',host).innerHTML=bars.map(([t,v,col])=>`<div class="bar" style="grid-template-columns:150px 1fr 48px"><span>${t}</span><div class="track"><div class="fill" style="width:${Math.round(v*100)}%;background:var(--${col})"></div></div><span class="v">${Math.round(v*100)}%</span></div>`).join('');
    const f=flowNow();let tx;if(st.mode==='arrest'){const s=st.t;tx=s<8?'Seconds after circulation stops, oxygen in the tissue is used up: the EEG begins to slow.':s<20?'By about 15–20 s synaptic transmission fails everywhere: the EEG becomes isoelectric. Neurons are still alive.':s<120?'Silent EEG, ATP falling. Restoring flow now usually restores the EEG.':s<300?'ATP depletion stops the Na⁺/K⁺ pump: anoxic depolarization, K⁺ floods out, Ca²⁺ and glutamate flood in. Injury has begun in the most vulnerable neurons.':'Prolonged anoxia: the selective vulnerability of cortex layers 3, 5 and 6, hippocampal CA1, Purkinje cells and the thalamic reticular nucleus decides the post-arrest EEG.';if(st.cpr)tx+=' CPR delivers only a fraction of normal flow: it slows the energy crash but rarely restores synaptic function.'}
    else tx=f>=35?'Normal or near-normal flow: synapses have the ATP they need; the EEG is normal.':f>=25?'Flow below about 30–35: fast activity starts to fade first, as the most energy-demanding synaptic activity suffers.':f>=18?'Flow about 18–25: fast activity is lost and delta grows (the alpha/delta ratio falls). Function, not structure, is failing.':f>=12?'Flow about 12–18: synaptic transmission fails and the EEG is nearly flat, yet the ion pumps still run: the ischemic penumbra. Restore flow and function returns.':'Flow below about 10–12: the pumps fail, cells depolarize and Ca²⁺ and glutamate flood in. Whether cells die now depends on how long this lasts.';
    $('#cRead',host).innerHTML=tx;const tc=$('.tcv2',host),S_=cvSetup(tc);if(S_){const{g:x,w,h,C}=S_,L=44,B=22,Xf=v=>L+v/40*(w-L-8),Yt=t=>h-B-Math.min(1,Math.log10(t)/Math.log10(600))*(h-B-8),TP=[[0,4],[5,15],[8,45],[10,100],[12,180],[15,360],[17.5,600]],tol=v=>{if(v>=17.5)return 600;for(let i=0;i<TP.length-1;i++)if(v<=TP[i+1][0]){const[a0,b0]=TP[i],[a1,b1]=TP[i+1],u=(v-a0)/(a1-a0);return Math.exp(Math.log(b0)+u*(Math.log(b1)-Math.log(b0)))}return 600};x.strokeStyle=C.line;x.strokeRect(L,8,w-L-8,h-B-8);
      x.font='10px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.fillStyle=C.muted;[0,10,20,30,40].forEach(v=>{x.fillText(v,Xf(v)-6,h-6)});[[5,'5 min'],[60,'1 h'],[300,'5 h']].forEach(([t,l])=>{x.fillText(l,2,Yt(t)+3)});x.fillText('flow →',w-60,h-6);
      x.fillStyle=C.bad;x.globalAlpha=.12;x.beginPath();x.moveTo(Xf(0),h-B);for(let v=0;v<=40;v+=.5)x.lineTo(Xf(v),Yt(tol(v)));x.lineTo(Xf(40),h-B);x.fill();x.globalAlpha=1;x.strokeStyle=C.bad;x.lineWidth=2;x.beginPath();for(let v=0;v<=40;v+=.5)v?x.lineTo(Xf(v),Yt(tol(v))):x.moveTo(Xf(v),Yt(tol(v)));x.stroke();x.lineWidth=1;
      const cf=Math.min(40,f);x.fillStyle=C.accent;x.beginPath();x.arc(Xf(cf),Yt(tol(cf)),5,0,6.29);x.fill();x.fillStyle=C.ink;x.fillText(cf>=18?'no infarction expected at this flow':`infarction after roughly ${tol(cf)<60?Math.round(tol(cf))+' min':(tol(cf)/60).toFixed(1)+' h'}`,Math.min(w-230,Xf(cf)+8),Math.max(16,Yt(tol(cf))-8))}
    drawA()}
  function drawA(){const ac2=$('.acv',host),S_=cvSetup(ac2);const cpp=st.map-st.icp,f=cbfOf(cpp,st.co2,st.imp);$('#aOut',host).textContent=`CPP ${cpp} mmHg → flow about ${Math.round(f)} mL/100 g/min`;if(!S_)return;const{g:x,w,h,C}=S_,L=44,B=22,Xp=v=>L+v/200*(w-L-8),Yf=v=>h-B-v/120*(h-B-8);x.strokeStyle=C.line;x.strokeRect(L,8,w-L-8,h-B-8);x.font='10px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.fillStyle=C.muted;[0,50,100,150,200].forEach(v=>x.fillText(v,Xp(v)-8,h-6));[0,25,50,100].forEach(v=>x.fillText(v,4,Yf(v)+3));x.fillText('CPP (mmHg) →',w-110,h-6);
    [[18,'synaptic failure'],[30,'slowing']].forEach(([v,l])=>{x.strokeStyle=C.grid;x.setLineDash([3,3]);x.beginPath();x.moveTo(L,Yf(v));x.lineTo(w-8,Yf(v));x.stroke();x.setLineDash([]);x.fillStyle=C.muted;x.fillText(l,w-120,Yf(v)-4)});
    [[false,C.good],[true,C.bad]].forEach(([imp,col])=>{x.strokeStyle=col;x.globalAlpha=imp===st.imp?1:.3;x.lineWidth=2;x.beginPath();for(let v=0;v<=200;v+=2){const yy=Yf(cbfOf(v,st.co2,imp));v?x.lineTo(Xp(v),yy):x.moveTo(Xp(v),yy)}x.stroke();x.globalAlpha=1;x.lineWidth=1});x.fillStyle=C.accent;x.beginPath();x.arc(Xp(clamp(cpp,0,200)),Yf(f),6,0,6.29);x.fill()}
  run();return{draw}}
/* ---- 5. regions and semiology ---- */
const REG={
 mtl:{n:'Mesial temporal lobe',c:[-.78,.3],e:['F7','T3','Fp1'],f:'Hippocampus and amygdala: memory encoding, emotion, autonomic and visceral integration.',s:'Rising epigastric sensation, fear, déjà vu, smell or taste; then staring and unresponsiveness, oral automatisms (lip smacking, chewing) and hand automatisms; contralateral dystonic arm posturing; post-ictal confusion, and aphasia when the dominant side is involved. Often 1–2 minutes.',eeg:'Anterior temporal (F7/T3 or F8/T4; best with inferior temporal T1/T2 or sphenoidal electrodes). Ictal onset is often rhythmic 5–9 Hz theta. Interictal: anterior temporal spikes, TIRDA.',vis:'Deep and partly tangential: a focal aware seizure (aura) is often invisible on scalp EEG; scalp onset can lag the true onset.',pats:['temporal_spikes','tirda','seizure']},
 ltl:{n:'Lateral temporal neocortex',c:[-.9,-.25],e:['T3','T5'],f:'Auditory cortex and, on the dominant side, language comprehension (Wernicke’s area).',s:'Auditory hallucinations (buzzing, voices), vertigo, receptive language disturbance on the dominant side; earlier spread and shorter auras than mesial temporal seizures.',eeg:'Mid and posterior temporal (T3/T5, T4/T6).',vis:'Lateral convexity: usually well seen.',pats:['seizure','temporal_spikes']},
 m1:{n:'Primary motor cortex',c:[-.45,.05],e:['C3','F3','Cz'],f:'Voluntary movement of the opposite body, mapped from foot (medial) to face (lateral).',s:'Clonic jerking of the opposite face, hand or limb, sometimes marching from one body part to the next (Jacksonian march); post-ictal weakness of that limb (Todd paresis).',eeg:'Central (C3/C4), often obscured by muscle artifact. Epilepsia partialis continua can show little on scalp EEG.',vis:'Convexity: visible, but small foci or muscle can hide it.',pats:['seizure','mu']},
 sma:{n:'Supplementary motor area (mesial frontal)',c:[-.12,.32],e:['Fz','Cz','F3'],f:'Planning and initiating movement; bilateral postural control.',s:'Abrupt, brief (often under 30–40 s) asymmetric tonic posturing (one arm extended, the other flexed, “fencing”), vocalization or speech arrest, often with preserved awareness and in clusters from sleep.',eeg:'Midline (Fz/Cz); frequently obscured by movement or nearly normal, and can even appear maximal over the opposite side because the mesial generator faces across the midline.',vis:'Mesial and tangential: scalp EEG is often unhelpful; do not mistake a normal EEG for a non-epileptic event.',pats:['gpfa','seizure']},
 fef:{n:'Frontal eye field',c:[-.5,.55],e:['F3','F7','Fz'],f:'Voluntary gaze to the opposite side.',s:'Forced, sustained turning of eyes and head to the opposite side (version), often before secondary generalization.',eeg:'Frontal (F3/F4).',vis:'Convexity: usually seen.',pats:['seizure']},
 ofc:{n:'Orbitofrontal and frontopolar cortex',c:[-.28,.85],e:['Fp1','F7','F3'],f:'Reward, social behavior, olfaction, autonomic control.',s:'Hypermotor (hyperkinetic) automatisms: bicycling, thrashing, screaming; brief, nocturnal, often bizarre and mistaken for psychogenic events; olfactory sensations; autonomic changes.',eeg:'Frontopolar and anterior temporal (Fp1/Fp2, F7/F8), often swamped by movement and eye artifact.',vis:'Basal surface: poorly seen.',pats:['seizure','blink']},
 ins:{n:'Insula',c:[-.7,.12],e:['T3','F7','C3'],f:'Interoception, taste, viscero-sensory and autonomic integration (including heart rate).',s:'Laryngeal constriction or choking, perioral or widespread unpleasant paresthesias (often opposite side), hypersalivation, autonomic signs including heart-rate change; may mimic temporal or frontal seizures.',eeg:'Deep, under the operculum: scalp EEG often normal or misleading (temporal or frontal).',vis:'Buried: frequently invisible on scalp.',pats:['seizure','ecgart']},
 par:{n:'Parietal lobe',c:[-.42,-.52],e:['P3','C3','T5'],f:'Somatosensation, spatial attention, body image.',s:'Tingling, numbness or warmth on the opposite side, distorted body image, vertigo; spread produces frontal (motor) or temporal (automatism) features that can mislead.',eeg:'Parietal (P3/P4), often poorly localizing; spread patterns dominate.',vis:'Convexity: visible, but onset can look distant.',pats:['seizure']},
 occ:{n:'Occipital lobe',c:[-.3,-.92],e:['O1','T5','P3'],f:'Vision.',s:'Elementary visual hallucinations (colored circles, flashes) in the opposite visual field, ictal blindness, eye deviation or nystagmus, blinking; post-ictal headache that mimics migraine.',eeg:'Occipital (O1/O2) and posterior temporal (T5/T6); spread to temporal regions is common.',vis:'Visible; mesial occipital may look bilateral.',pats:['seizure','lambda','photic']},
 cing:{n:'Cingulate cortex',c:[0,.0],e:['Fz','Cz','Pz'],f:'Emotion, motivation, motor planning (anterior); memory and self-reference (posterior).',s:'Anterior: hypermotor seizures, fear, autonomic changes. Posterior: may mimic temporal lobe seizures.',eeg:'Midline and often bilateral; poorly localizing.',vis:'Mesial: poorly seen.',pats:['seizure']}};
const DP={mtl:[-.9,.05],ltl:[-.86,-.32],m1:[-.36,.08],sma:[-.12,.45],fef:[-.55,.55],ofc:[-.3,.84],ins:[-.62,.25],par:[-.42,-.5],occ:[-.25,-.86],cing:[-.04,-.14]};
const LSIGN=['Dystonic posturing of one arm: seizure in the opposite hemisphere.','Unilateral hand automatisms: usually the same side as the seizure (the free hand).','Forced head version late in a seizure: toward the side opposite the seizure.','Figure-of-4 posture: the extended arm is opposite the seizure.','Post-ictal weakness (Todd): opposite hemisphere.','Post-ictal aphasia: dominant (usually left) hemisphere; speech preserved during a seizure suggests non-dominant.','Post-ictal nose wiping: usually the hand on the same side as the seizure.'];
function mapLab(host){const st={reg:'mtl',side:-1},V={v:null};
  host.innerHTML=`<div class="card stack"><h2>Regions and semiology</h2><p style="margin:0;max-width:86ch">A seizure produces the symptoms of whatever cortex it activates, in order. Semiology therefore tells you where the seizure starts and where it travels, and the 10–20 electrodes over that region tell you where to look on the EEG. Deep and mesial regions are the great exceptions: they can seize with an almost normal scalp EEG.</p>
   <div class="labg"><div class="stack" style="gap:8px"><div class="row"><span class="lbl">Side</span><span id="mSide"></span></div><div id="mSvg"></div></div><div class="stack" style="gap:8px" id="mInfo"></div></div></div>
   <div class="card stack"><div class="row" style="justify-content:space-between"><h2 id="mVt">A seizure from here</h2><button class="btn small" type="button" id="mNew">Another example</button></div><div id="mView"></div></div>
   <div class="card stack"><h3>Lateralizing signs</h3><ul class="f">${LSIGN.map(x=>`<li>${x}</li>`).join('')}</ul></div>`;
  segment($('#mSide',host),[['-1','Left'],['1','Right']],'-1',v=>{st.side=+v;render()});
  V.v=Viewer($('#mView',host));$('#mNew',host).addEventListener('click',()=>show(Math.floor(Math.random()*1e9)));
  function svg(){return`<svg viewBox="-1.15 -1.15 2.3 2.3" style="width:100%;max-width:380px;display:block" role="group" aria-label="Brain regions seen from above, nose up"><circle cx="0" cy="0" r="1.02" fill="var(--panel)" stroke="var(--line)" stroke-width=".02"/><path d="M-.1 -1.02 L0 -1.12 L.1 -1.02" fill="none" stroke="var(--line)" stroke-width=".02"/>
    ${Object.entries(REG).map(([k,r])=>{const d=DP[k],cx2=st.side<0?d[0]:-d[0],cy=-d[1];return`<g class="rg" data-rg="${k}" tabindex="0" role="button" aria-label="${r.n}"><circle cx="${cx2}" cy="${cy}" r=".13" fill="${k===st.reg?'color-mix(in srgb,var(--mark) 45%,var(--panel))':'color-mix(in srgb,var(--accent) 12%,var(--panel))'}" stroke="${k===st.reg?'var(--mark)':'var(--line)'}" stroke-width=".02"/><text x="${cx2}" y="${cy+.03}" text-anchor="middle" font-size=".075" fill="var(--ink)">${r.n.split(' ')[0].replace(/(Mesial|Lateral|Primary|Supplementary|Frontal|Orbitofrontal)/,m=>({Mesial:'Mesial T',Lateral:'Lateral T',Primary:'M1',Supplementary:'SMA',Frontal:'FEF',Orbitofrontal:'OFC'})[m])}</text></g>`}).join('')}
    ${EL.map(([n,x,y])=>{const hit=REG[st.reg].e.map(e=>mirror(e)).includes(n);return`<text x="${x}" y="${-y+.03}" text-anchor="middle" font-size=".07" font-family="monospace" fill="${hit?'var(--mark)':'var(--muted)'}" font-weight="${hit?700:400}">${n}</text>`}).join('')}</svg>`}
  const mirror=e=>{if(st.side<0)return e;const m={Fp1:'Fp2',F7:'F8',F3:'F4',T3:'T4',C3:'C4',T5:'T6',P3:'P4',O1:'O2'};return m[e]||e};
  function render(){$('#mSvg',host).innerHTML=svg();$$('[data-rg]',host).forEach(g=>{const f=()=>{st.reg=g.dataset.rg;render()};g.addEventListener('click',f);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();f()}})});
    const r=REG[st.reg];$('#mInfo',host).innerHTML=`<h3>${st.side<0?'Left':'Right'} ${r.n.toLowerCase()}</h3><p style="margin:0"><b>Function.</b> ${r.f}</p><p style="margin:0"><b>Seizures from here.</b> ${r.s}</p><p style="margin:0"><b>Where to look.</b> ${r.eeg.replace(/\b(F7|T3|T5|C3|F3|P3|O1|Fp1)\b/g,m=>st.side<0?m:mirror(m))}</p><p class="note" style="margin:0"><b>Visibility.</b> ${r.vis}</p>${patBtns(r.pats)}`;show(7)}
  function show(seed){const r=REG[st.reg],cx=st.side<0?r.c[0]:-r.c[0],deep=['ins','sma','cing','ofc'].includes(st.reg),st0=mkState({pdr:9.5,alpha:18,theta:2.5,delta:2.5,beta:3}),R=composeRec(st0,seed,{sz:{t0:2,t1:DUR+1,on:2,len:40,f0:deep?7:5.5,f1:4,side:st.side,cx,cy:r.c[1],sw:deep?.7:.33,amp:deep?.5:1.6}});
    V.v.setRec(R);V.v.setAnn(true);$('#mVt',host).textContent=`A seizure from the ${st.side<0?'left':'right'} ${r.n.toLowerCase()}${deep?' (deep source: small, widespread scalp field)':''}`}
  render();return{draw:()=>V.v.draw()}}
/* ---- shell ---- */
function build(host){host.innerHTML='';const nav=el('div','row');host.appendChild(nav);const box=el('div','stack');host.appendChild(box);const made={},fns={field:fieldLab,thal:thalLab,syn:synLab,cbf:cbfLab,map:mapLab};let cur='field';
  const show=k=>{cur=k;$$('.mpane',box).forEach(p=>p.hidden=p.dataset.k!==k);if(!made[k]){const p=el('div','stack mpane');p.dataset.k=k;box.appendChild(p);made[k]=fns[k](p)}AX.draws.mech=[()=>made[cur]&&made[cur].draw()];setTimeout(()=>made[k].draw(),0)};
  const sg=segment(nav,LAB,'field',show);sg.style.flexWrap='wrap';show('field');AX.labShow=k=>{const b=$$('button',sg).find(x=>x.dataset.v===k);if(b)b.click()}}
return{build,drawTopo}})();
function buildLabs(host){return LABS.build(host)}
function drawTopo(cv,vals,o){return LABS.drawTopo(cv,vals,o)}
function openLab(k){setTab('atlas');setSub('mech');if(AX.labShow)AX.labShow(k);window.scrollTo({top:0,behavior:'smooth'})}
