/* ============ EEG curriculum: tracks → modules → six stages ============ */
const TRACKS=[
 {id:'A',name:'Foundations: from synapse to scalp',sum:'Where the signal comes from, how montages see it, and when it lies.',mods:['gen','mont','tech']},
 {id:'B',name:'States and rhythms',sum:'Thalamocortical modes, sleep, age and the variants that fool readers.',mods:['thal','sleep','age','variant']},
 {id:'C',name:'Excitability and epilepsy',sum:'From the paroxysmal depolarization shift to networks that seize.',mods:['ied','gge','focal','encep']},
 {id:'D',name:'Critical care EEG',sum:'ACNS language, the ictal–interictal continuum and hours-long trends.',mods:['acns','iic','trend']},
 {id:'E',name:'Flow, energy, drugs and coma',sum:'Blood flow thresholds, metabolism, sedation, temperature and prognosis.',mods:['flow','enc','drug','coma']},
 {id:'F',name:'Integration and synthesis',sum:'Brain and heart together, then everything mixed and timed.',mods:['integ','synth']}];
const MODS={
 gen:{name:'Where the EEG comes from',sum:'Synaptic currents, dipoles, synchrony and the skull.',intro:'The scalp EEG is the summed postsynaptic current of pyramidal neurons that stand in parallel, filtered and smeared by the skull. Amplitude reports synchrony and the distance to the electrode; frequency reports the circuit that is driving the cortex. Every later module uses these rules.',
  con:['psp','pyr','sync','dipole','volcond','orient'],pats:['awake','reactivity','breach','asym','lowvolt','eci'],labs:[['field','Dipoles & fields lab'],['rhy','Rhythms']]},
 mont:{name:'Montages, polarity and localization',sum:'Phase reversals, field maxima and the end of the chain.',intro:'Each bipolar channel is the difference between two neighbours; each referential channel compares one electrode with a reference. A field maximum therefore appears as a phase reversal in a chain, or as the tallest channel against a quiet reference. Radial and tangential generators produce different maps.',
  con:['montage','dipole','orient','eyedip'],pats:['temporal_spikes','cts','pop','blink','lateye','focal_slow','lpd'],labs:[['field','Dipoles & fields lab'],['lead','Leads & montages']]},
 tech:{name:'Artifacts and the ICU environment',sum:'Know when the tracing is lying.',intro:'Before any brain reading, identify every non-cerebral signal. Each artifact has a generator with its own frequency, timing and field: eyes and tongue are dipoles, muscles fire fast, the heart and pulse are time-locked to the ECG, and machines repeat at machine rates. Single-electrode signals have no physiological field.',
  con:['eyedip','physart','techart','filter'],pats:['blink','lateye','muscle','glosso','ecgart','pulse','pop','line','sweat','vent','drip'],labs:[['sig','Signal & filters']]},
 thal:{name:'Thalamocortical rhythms and arousal',sum:'Alpha, mu, reactivity and the arousal systems.',intro:'Brainstem and basal forebrain arousal systems keep thalamic relay neurons depolarized (tonic mode), so the cortex is desynchronized and responsive. When input stops (eyes closed, rest) the loops idle: posterior alpha, central mu. Reactivity tests that whole pathway.',
  con:['thal','alpha','aras','sensmotor','react','statedep','visual'],pats:['awake','reactivity','drowsy','mu','lambda','photic','hvresp','child'],labs:[['thal','Thalamus & rhythms lab'],['rhy','Rhythms']]},
 sleep:{name:'Sleep architecture',sum:'How the thalamus builds spindles, K-complexes and slow waves.',intro:'As arousal input falls, thalamic neurons hyperpolarize; T-type Ca²⁺ channels recover and the reticular nucleus paces spindles; deeper still, cortex and thalamus fall into slow oscillations. REM reverses this with cholinergic drive. Sleep features are both normal landmarks and markers of intact circuits.',
  con:['trn','ttype','slowosc','aras','statedep'],pats:['drowsy','n2','n3','rem','posts','hypnhyp','dexmed'],labs:[['thal','Thalamus & rhythms lab']]},
 age:{name:'Development: newborn to adult',sum:'Judge every tracing against age.',intro:'The EEG matures with myelination, synaptogenesis and the chloride switch: bursts in prematurity, tracé alternant at term, a posterior rhythm that speeds from about 4 Hz to 10 Hz through childhood. Immature inhibition also makes the young brain seizure-prone.',
  con:['devel','chloride','slowosc'],pats:['child','trace_alt','trace_disc','dbrush','hypnhyp','neosz','hyps']},
 variant:{name:'Benign variants: the over-call traps',sum:'Sharp, rhythmic and harmless.',intro:'Many sharp or rhythmic patterns lack the mechanism of an epileptic discharge: no paroxysmal depolarization shift, no after-going inhibition, no evolution. Learning why they are benign is the best protection against misdiagnosing epilepsy.',
  con:['pds','network','statedep','volcond'],pats:['wicket','posts','bets','sixfourteen','phantom','rmtd','sreda','breach','mu','lambda']},
 ied:{name:'From PDS to spike',sum:'What makes a discharge epileptiform.',intro:'An interictal spike is the scalp sign of a paroxysmal depolarization shift: giant glutamatergic and Ca²⁺-driven depolarization, a burst of action potentials, then inhibition (the after-going slow wave). Only a large enough synchronized patch reaches the scalp, and its geometry decides the field.',
  con:['pds','ei','sync','montage','orient'],pats:['temporal_spikes','cts','tirda','bets','wicket','focal_slow'],labs:[['syn','Synapses & drugs lab'],['field','Dipoles & fields lab']]},
 gge:{name:'Generalized epilepsies',sum:'Corticothalamic spike-and-wave.',intro:'In genetic generalized epilepsies, a hyperexcitable cortex recruits the thalamic reticular nucleus into a loop of firing (spike) and synchronized inhibition (wave). T-type Ca²⁺ channels and GABA-B receptors set the 3 Hz rhythm; photic stimulation and hyperventilation provoke it.',
  con:['swmech','ttype','trn','ei','visual','co2'],pats:['sw3','jme','ppr','phantom','hvresp','photic'],labs:[['thal','Thalamus & rhythms lab']]},
 focal:{name:'Focal seizures: networks and evolution',sum:'Onset, spread, termination and the brain region.',intro:'A focal seizure begins where excitation escapes inhibition and recruits connected cortex; frequency, amplitude and field evolve. Semiology follows the regions it reaches. Termination involves active inhibition, ion shifts and energy depletion, seen as post-ictal slowing or suppression.',
  con:['network','ei','kion','autonomic'],pats:['seizure','tirda','birds','rmtd','sreda','gtc'],labs:[['map','Regions & semiology lab']]},
 encep:{name:'Developmental and epileptic encephalopathies',sum:'When the epileptic activity itself harms development.',intro:'In the developing brain, depolarizing GABA and immature networks allow diffuse hyperexcitability: hypsarrhythmia, slow spike-wave, paroxysmal fast activity and sleep-activated spike-wave can each disturb learning as well as cause seizures.',
  con:['devel','chloride','ei','swmech'],pats:['hyps','lgs','gpfa','eswas','neosz']},
 acns:{name:'ACNS language: PDs, RDA, SW',sum:'Describe before you interpret.',intro:'The ACNS 2021 terminology names where (main term 1: G, L, BI, UI, Mf) and what (main term 2: PDs, RDA, SW), then adds modifiers: frequency, plus features (+F, +R, +S), prevalence, evolution, and the SI- prefix. Shared words make serial reports comparable and link patterns to seizure risk.',
  con:['pdmech','rdmech','iic'],pats:['lpd','gpd','bipd','lrda','grda','firda','gsw','lpdplus','triphasic','cjd']},
 iic:{name:'The ictal–interictal continuum',sum:'When a pattern becomes a seizure.',intro:'Periodic and rhythmic patterns lie on a spectrum from injury markers to seizures. Above 2.5 Hz for 10 s, or with definite evolution, it is a seizure; between, plus features, fluctuation, stimulus-induction and response to treatment decide. Prolonged seizures change their own receptors, which is why time matters.',
  con:['iic','pdmech','network','gabaa','nmda','sirp'],pats:['lpdplus','lpdevol','gsw','ncse','sirpids','birds','triphasic','cape'],scn:['statusEp'],labs:[['syn','Synapses & drugs lab'],['evo','Trends & evolution']]},
 trend:{name:'cEEG trends: hours on one screen',sum:'Spectrograms, amplitude trends and rhythmicity.',intro:'Quantitative trends compress hours into one screen: seizures appear as flames, suppression as dark columns, sleep as bands, ischemia as a falling alpha/delta ratio. A trend is a map to the raw EEG, never a replacement: always open the page behind the change.',
  con:['iic','dci','sedation','statedep'],pats:['seizure','lpdevol','bs','focal_slow','asym','n2'],scn:['statusEp','sedation','sahDCI','sleepNight'],labs:[['evo','Trends & evolution']]},
 flow:{name:'Blood flow, ischemia and pressure',sum:'The EEG as a real-time perfusion monitor.',intro:'Neurons fail electrically before they die: as flow falls below about 25–30 mL/100 g/min fast activity fades, below about 15–20 synapses stop and the EEG flattens, below about 10–12 pumps fail and injury becomes time-dependent. Autoregulation, CO₂ and intracranial pressure decide the flow.',
  con:['cbf','energy','autoreg','co2','icp','dci','deaff'],pats:['focal_slow','asym','hvresp','firda','lowvolt','enc_sev'],scn:['sahDCI','icpRise'],labs:[['cbf','Blood flow lab']]},
 enc:{name:'Encephalopathy: metabolic, toxic, septic',sum:'Grading severity and watching it change.',intro:'Metabolic and toxic insults depress synapses and thalamocortical drive along a common pathway, so the EEG grades severity (mild theta, then delta, then discontinuity) better than it names the cause. A few signatures help: GPDs with triphasic morphology, extreme delta brush, cyclic alternating patterns.',
  con:['metab','thal','deaff','react','rdmech'],pats:['enc_mild','gen_slow','enc_sev','triphasic','firda','grda','cape','edb'],scn:['hepatic','hypogly'],labs:[['cbf','Blood flow lab']]},
 drug:{name:'Drugs, sedation and temperature',sum:'Pharmacology you can see.',intro:'Drugs act on the same receptors that make the rhythms: GABA-A modulators add beta then slow and suppress; propofol anteriorizes alpha; dexmedetomidine imitates sleep; ketamine releases fast activity. Cold slows everything. Drug and temperature must be excluded before calling injury.',
  con:['gabaa','nmda','sedation','temp','aras'],pats:['benzo','propofol','ketamine','dexmed','bs','hypotherm'],scn:['sedation','hypothermCourse'],labs:[['syn','Synapses & drugs lab']]},
 coma:{name:'Coma and post-arrest prognosis',sum:'Continuity, voltage, reactivity, discharges, time.',intro:'After cardiac arrest, the most vulnerable neurons die first and the surviving circuitry sets the EEG. Continuous, normal-voltage, reactive activity within the first day is favourable; suppression, burst-suppression (especially identical bursts) and periodic discharges on a suppressed background are malignant. Timing and confounders matter, and EEG is one of several modalities.',
  con:['anoxia','prog','react','slowosc','energy'],pats:['react_coma','unreact','lowvolt','discont','bs','bs_ident','bs_epi','supp_pd','gpd','alphacoma','eci'],scn:['paGood','paPoor'],labs:[['cbf','Blood flow lab']]},
 integ:{name:'Brain and heart',sum:'Shared ions, shared oxygen, shared nerves.',intro:'The same ions (K⁺, Na⁺, Ca²⁺, Mg²⁺), the same oxygen supply and the same autonomic nerves link EEG and ECG. Cardiac arrest starves the brain within seconds; seizures speed or stop the heart; SAH floods the heart with catecholamines; cold, toxins and electrolytes change both tracings at once. The combined post-arrest case follows both over three days.',
  con:['autonomic','anoxia','energy','metab','temp','kion'],pats:['ecgart','gtc','hypotherm','supp_pd','react_coma','enc_sev','triphasic'],scn:['paGood','paPoor','hypogly'],labs:[['case','Post-arrest case (both tracings)'],['cbf','Blood flow lab']]},
 synth:{name:'Putting it together',sum:'Everything, mixed, timed and evolving.',intro:'The capstone draws on every module: names, mechanisms, ACNS descriptions, localization, background reads, application and trends. It reflects how EEG arrives in practice: unlabeled, in context, and changing over time.',
  con:['psp','thal','pds','iic','cbf','prog'],pats:[],scn:[],labs:[['evo','Trends & evolution']]}};
MODS.synth.pats=[...new Set(Object.values(MODS).flatMap(m=>m.pats||[]))];MODS.synth.scn=typeof SCNL!=='undefined'?[...SCNL]:[];
const CORE={student:null,clin:null,
 ems:['gen','mont','tech','thal','ied','focal','acns','iic','flow','drug','coma','integ','synth'],
 icu:['gen','mont','tech','thal','sleep','ied','focal','acns','iic','trend','flow','enc','drug','coma','integ','synth'],
 tech:['gen','mont','tech','thal','sleep','age','variant','ied','gge','focal','acns','trend','synth']};

/* ---- stage question makers ---- */
function pickItem(list,prefix,used){const d=DB.srs||{},t=Date.now();const w=list.map(x=>{const it=d[prefix+x];let v=it?(it.b<2?3:it.due<=t?2:1/(1+it.b)):2.5;if(used&&used.has(x))v*=.08;return v});let s=w.reduce((a,b)=>a+b,0)*Math.random();for(let i=0;i<list.length;i++){s-=w[i];if(s<=0)return list[i]}return list[0]}
function cumulPats(mid){const all=[...(MODS[mid].pats||[])],d=DB.path||{};Object.keys(MODS).forEach(m=>{if(m!==mid&&m!=='synth'&&d[m]&&d[m].rec&&d[m].rec.done)all.push(...(MODS[m].pats||[]))});return[...new Set(all)]}
const withDiff=(d,f)=>{const o=S.diff;S.diff=d;try{return f()}finally{S.diff=o}};
function stageQ(mid,sk,i,sess){const m=MODS[mid],r=mkRand(Date.now()+i*977),used=sess.used||(sess.used=new Set()),pats=m.pats||[],take=(list,pre)=>{const x=pickItem(list,pre,used);used.add(x);return x};
  const scn=(m.scn||[]).filter(s=>typeof SCN!=='undefined'&&SCN[s]);
  if(sk==='mech'){for(let k=0;k<6;k++){const q=mechQ(take(pats,'mech:'),'why');if(q)return q}return null}
  if(sk==='rec')return newQ(take(pats,'dx:'),'dx');
  if(sk==='ana'){const ap=pats.filter(p=>Object.values(can).some(f=>f(p)));for(let k=0;k<8;k++){const q=anaQ(take(ap.length?ap:pats,'meas:'));if(q)return q}return withDiff('hard',()=>newQ(take(pats,'dx:'),'dx'))}
  if(sk==='app'){const bp=pats.filter(can.bg);if(bp.length&&r.u()<.3)return bgQ(take(bp,'bg:'));if(scn.length&&r.u()<.25)return newTrajQ(Math.floor(Math.random()*1e9),'dir',scn[Math.floor(r.u()*scn.length)]);return caseQ(take(pats,'case:'))}
  if(sk==='int'){const mode=i%3;if(mode===0&&scn.length)return newTrajQ(Math.floor(Math.random()*1e9),null,scn[Math.floor(r.u()*scn.length)]);
    if(mode<=1){for(let k=0;k<6;k++){const q=mechQ(take(pats,'mech:'),'link');if(q&&q.m.type==='link')return q}}return withDiff('hard',()=>newQ(take(pats,'dx:'),'dx'))}
  if(sk==='mas'){const pl=cumulPats(mid),src=r.u()<.6?pats:pl,pid=take(src.length?src:pats,'dx:'),k=['dx','dx','ana','mech','case','traj'][i%6];
    if(k==='traj'&&typeof newTrajQ==='function'){return newTrajQ(Math.floor(Math.random()*1e9),null,scn.length?scn[Math.floor(r.u()*scn.length)]:null)}
    if(k==='case')return caseQ(pid);if(k==='mech'){const q=mechQ(pid,'why');if(q)return q}if(k==='ana'){const q=anaQ(pid);if(q)return q}return withDiff('hard',()=>newQ(pid,'dx'))}
  return null}
function reviewQ(key){const[k,id]=key.split(':');if(k==='traj')return typeof SCN!=='undefined'&&SCN[id]?newTrajQ(Math.floor(Math.random()*1e9),null,id):null;if(!PM[id])return null;
  if(k==='mech')return mechQ(id,'why')||newQ(id,'dx');if(k==='case')return caseQ(id);if(k==='desc'&&can.desc(id))return descQ(id);if(k==='loc'&&can.loc(id))return locQ(id)||newQ(id,'dx');if(k==='bg'&&can.bg(id))return bgQ(id);if(k==='meas'){const q=anaQ(id);if(q)return q}return newQ(id,'dx')}
const qLabel=q=>{const n=q.pid&&PM[q.pid]?PM[q.pid].name:'';if(q.kind==='traj'||q.kind==='trend')return`${TT[q.tt]} · ${q.scn&&SCN[q.scn]?SCN[q.scn].name:'stable pattern'}`;return`${qName(q)} · ${n}`};

/* ---- adapter for the shared path engine ---- */
const LCFG={app:'eeg',key:'eegrr.v1',other:{key:'ecgrr.v1',name:'ECG Reading Room',href:'ecg/'},tracks:TRACKS,mods:MODS,core:CORE,
 db:()=>DB,save:()=>store.save(DB),patName:id=>PM[id]?PM[id].name:id,scnName:id=>typeof SCN!=='undefined'&&SCN[id]?SCN[id].name:id,conName:c=>CON[c]?CON[c].n:c,conText:c=>CON[c]?CON[c].s:'',conLab:c=>CON[c]&&CON[c].lab,
 keysOf:q=>{if(q.kind==='traj'||q.kind==='trend')return q.scn?['traj:'+q.scn]:[];if(!q.pid)return[];const k={dx:'dx',mech:'mech',meas:'meas',case:'case',desc:'desc',loc:'loc',click:'loc',bg:'bg'}[q.kind];return k?[k+':'+q.pid]:[]},
 validKey:k=>{const[a,b]=k.split(':');return a==='traj'?typeof SCN!=='undefined'&&!!SCN[b]:!!PM[b]},label:qLabel,stageQ,reviewQ,
 beginSession:()=>{S.exam=null;S.drill=null;$('#qDrill').hidden=true},
 show:q=>{setTab('quiz');$('#qIntro').hidden=true;$('#qStage').hidden=false;$('#qMeta').hidden=false;showQ(q);window.scrollTo({top:0})},
 timeout:q=>{if(q.chosen!==null&&q.chosen!==undefined)return;if(q.kind==='dx'||q.kind==='loc')choose('__timeout__');else if(q.kind==='desc'||q.kind==='bg')choose('done');else if((q.kind==='traj'||q.kind==='trend')&&q.tt==='seq')choose([]);else choose(-1)},
 showResult:(html,cb)=>{setTab('quiz');S.q=null;$('#qIntro').hidden=true;$('#qStage').hidden=false;$('#qViewer').hidden=true;$('#qMeta').hidden=true;const c=$('#qCard');c.innerHTML=html;$$('[data-lrn]',c).forEach(b=>b.addEventListener('click',()=>{$('#qViewer').hidden=false;$('#qMeta').hidden=false;cb(b.dataset.lrn)}));window.scrollTo({top:0})},
 openPath:mid=>{setTab('path');if(mid){const b=$(`#tab-path [data-mid="${mid}"]`);if(b)b.click()}},openScn:id=>{if(typeof openEvo==='function')openEvo(id)},
 openSection:k=>{if(['field','thal','syn','cbf','map'].includes(k)&&typeof openLab==='function')openLab(k);else if(k==='case'&&typeof openCase==='function')openCase();else{setTab('atlas');setSub(k)}},
 redraw:()=>{if(!$('#tab-path').hidden)LRN.render($('#tab-path'));if(S.q)qViewer.draw();if(!$('#tab-atlas').hidden)redrawSub()}};
