/* ============ open a recording: EDF / EDF+ / BDF reader, pager and CSA trend (all local) ============ */
const EDF=(()=>{
const SYN={T7:'T3',T8:'T4',P7:'T5',P8:'T6'},ELN=EL.map(e=>e[0]),ELU=ELN.map(n=>n.toUpperCase());
function mapLabel(l){let s=l.trim().replace(/^(EEG|EKG|ECG)\s+/i,'');const ecg=/^(ECG|EKG)/i.test(l.trim())||/^(ECG|EKG)/i.test(s);if(ecg)return{ecg:true};
  s=s.replace(/[-_ ](REF|LE|RE|AVG|AV|A1|A2|M1|M2|CZ|AR|LINKED)$/i,'').replace(/[-_ ](REF|LE|AVG)$/i,'').trim();if(/[-–]/.test(s)&&!/^[A-Za-z]+\d*$/.test(s))return{bip:true};const u=s.toUpperCase(),m=SYN[s]||SYN[u.charAt(0)+u.slice(1).toLowerCase()]||(ELU.indexOf(u)>=0?ELN[ELU.indexOf(u)]:null);return m?{el:m}:{}}
function txt(b,o,n){let s='';for(let i=0;i<n;i++)s+=String.fromCharCode(b[o+i]);return s}
async function readHeader(file){const b0=new Uint8Array(await file.slice(0,256).arrayBuffer());const bdf=b0[0]===255,ns=parseInt(txt(b0,252,4)),hb=parseInt(txt(b0,184,8)),b=new Uint8Array(await file.slice(0,256+ns*256).arrayBuffer());
  const H={bdf,bps:bdf?3:2,ns,hb,plus:/EDF\+/.test(txt(b,192,44)),disc:/EDF\+D/.test(txt(b,192,44)),nrec:parseInt(txt(b,236,8)),dur:parseFloat(txt(b,244,8))||1,sig:[]};let o=256;const f=(len)=>{const a=[];for(let i=0;i<ns;i++)a.push(txt(b,o+i*len,len).trim());o+=ns*len;return a};
  const lab=f(16),tr=f(80),dim=f(8),pmin=f(8).map(Number),pmax=f(8).map(Number),dmin=f(8).map(Number),dmax=f(8).map(Number),pre=f(80),spr=f(8).map(Number);
  let off=0;for(let i=0;i<ns;i++){const u=dim[i].replace('µ','u').toLowerCase(),sc=u==='uv'?1:u==='mv'?1e3:u==='v'?1e6:u==='nv'?1e-3:1;H.sig.push({lab:lab[i],dim:dim[i],pmin:pmin[i],pmax:pmax[i],dmin:dmin[i],dmax:dmax[i],spr:spr[i],fs:spr[i]/H.dur,off,sc,ann:/EDF Annotations|BDF Annotations/i.test(lab[i]),map:mapLabel(lab[i])});off+=spr[i]}H.recSamp=off;H.recBytes=off*H.bps;
  if(H.nrec<0)H.nrec=Math.floor((file.size-hb)/H.recBytes);H.total=H.nrec*H.dur;return H}
async function readRecs(file,H,r0,r1){r0=Math.max(0,r0);r1=Math.min(H.nrec,r1);if(r1<=r0)return null;const buf=new Uint8Array(await file.slice(H.hb+r0*H.recBytes,H.hb+r1*H.recBytes).arrayBuffer());return{r0,r1,buf}}
function chan(H,R,i){const s=H.sig[i],n=(R.r1-R.r0)*s.spr,o=new Float32Array(n),k=(s.pmax-s.pmin)/(s.dmax-s.dmin||1);let w=0;for(let r=0;r<R.r1-R.r0;r++){let p=(r*H.recSamp+s.off)*H.bps;for(let j=0;j<s.spr;j++,p+=H.bps){let d;if(H.bps===2){d=R.buf[p]|(R.buf[p+1]<<8);if(d>32767)d-=65536}else{d=R.buf[p]|(R.buf[p+1]<<8)|(R.buf[p+2]<<16);if(d>8388607)d-=16777216}o[w++]=((d-s.dmin)*k+s.pmin)*s.sc}}return o}
function bqf(type,f,Q,fs){const w0=2*Math.PI*Math.min(f,fs*.45)/fs,c=Math.cos(w0),s=Math.sin(w0),al=s/(2*Q),a0=1+al;return type==='lp'?[(1-c)/2/a0,(1-c)/a0,(1-c)/2/a0,-2*c/a0,(1-al)/a0]:[(1+c)/2/a0,-(1+c)/a0,(1+c)/2/a0,-2*c/a0,(1-al)/a0]}
function resamp(x,fs,t0,n,fo){let y=x;if(fs>fo*1.05){const k=bqf('lp',fo*.35,.707,fs);y=runbq(runbq(x,k).reverse(),k).reverse()}const o=new Float32Array(n);for(let i=0;i<n;i++){const t=t0+i/fo,p=t*fs,a=Math.floor(p),u=p-a;o[i]=a+1<y.length?y[a]*(1-u)+y[a+1]*u:a<y.length&&a>=0?y[a]:0}return o}
function parseTAL(H,R,i){const s=H.sig[i],out=[];for(let r=0;r<R.r1-R.r0;r++){const p=(r*H.recSamp+s.off)*H.bps,b=R.buf.subarray(p,p+s.spr*H.bps);let str='';for(const c of b)str+=String.fromCharCode(c);str.split('\x00').forEach(tal=>{if(!tal)return;const parts=tal.split('\x14'),hd=parts[0].split('\x15'),on=parseFloat(hd[0]);parts.slice(1).forEach(t=>{if(t.trim())out.push({t:on,d:parseFloat(hd[1])||0,txt:t.trim()})})})}return out}
/* ---- sample EDF+ writer (synthetic) ---- */
function sampleEdf(){const seq=['awake','awake','reactivity','drowsy','drowsy','temporal_spikes','temporal_spikes','awake','seizure','seizure','gen_slow','awake'],fsO=256,dur=1,nrec=seq.length*10,EEGL=ELN.map(n=>'EEG '+(n==='T3'?'T7':n==='T4'?'T8':n)+'-REF'),annSpr=40;
  const recs=seq.map((pid,i)=>generate(pid,100+i)),sigs=[...EEGL,'ECG','EDF Annotations'],ns=sigs.length,hb=256+ns*256,spr=sigs.map((s,i)=>i<ns-1?fsO*dur:annSpr),recBytes=spr.reduce((a,b)=>a+b,0)*2,buf=new Uint8Array(hb+nrec*recBytes);
  const put=(o,s,len)=>{for(let i=0;i<len;i++)buf[o+i]=i<s.length?s.charCodeAt(i):32};put(0,'0',8);put(8,'X X X X',80);put(88,'Startdate X X X X',80);put(168,'01.01.26',8);put(176,'00.00.00',8);put(184,String(hb),8);put(192,'EDF+C',44);put(236,String(nrec),8);put(244,String(dur),8);put(252,String(ns),4);
  let o=256;const field=(vals,len)=>{vals.forEach((v,i)=>put(o+i*len,String(v),len));o+=ns*len};field(sigs,16);field(sigs.map(()=>''),80);field(sigs.map((s,i)=>i<ns-1?'uV':''),8);field(sigs.map((s,i)=>i<ns-1?-3276.8:-1),8);field(sigs.map((s,i)=>i<ns-1?3276.7:1),8);field(sigs.map(()=>-32768),8);field(sigs.map(()=>32767),8);field(sigs.map(()=>'HP:0.1Hz LP:100Hz'),80);field(spr,8);field(sigs.map(()=>''),32);
  const dv=new DataView(buf.buffer),anns={0:'Recording start',30:'Eyes open',40:'Drowsy',50:'Sharp transients left?',80:'Patient reports odd smell'};let p=hb;
  for(let r=0;r<nrec;r++){const pg=Math.floor(r/10),R=recs[pg],tin=(r%10)*dur;for(let c=0;c<ns-1;c++){const src=c<NE?R.V[c]:R.ecg.map(x=>x*900);for(let j=0;j<fsO;j++){const t=tin+j/fsO,q=t*FS,a=Math.min(N-2,Math.floor(q)),u=q-a;let v=src[a]*(1-u)+src[a+1]*u;dv.setInt16(p,clamp(Math.round(v*10),-32768,32767),true);p+=2}}
    let tal=`+${r*dur}\x14\x14\x00`;if(anns[r*dur]!=null)tal+=`+${r*dur}\x14${anns[r*dur]}\x14\x00`;for(let j=0;j<annSpr*2;j++)buf[p+j]=j<tal.length?tal.charCodeAt(j):0;p+=annSpr*2}
  return new Blob([buf],{type:'application/octet-stream'})}
/* ---- page ---- */
function build(host){host.innerHTML='';const S={file:null,H:null,t:0,ann:[],trend:null,busy:false,cancel:false};
  host.innerHTML=`<div class="card stack"><h2>Open a recording</h2><p style="margin:0;max-width:86ch">Read your own EEG (EDF, EDF+ or BDF) with the same montages, filters and calipers as the rest of the app. <b>The file is read inside this browser and never leaves your device.</b> Identification fields in the file header are not shown. Referential recordings (each electrode against a common reference) can be re-montaged; a recording stored only as bipolar pairs cannot.</p>
   <div class="row"><label class="btn primary" style="cursor:pointer">Choose a file<input type="file" accept=".edf,.bdf,.EDF,.BDF" id="eFile" hidden></label><button class="btn" type="button" id="eSample">Try a sample recording</button><button class="btn small" type="button" id="eDl" hidden>Download the sample .edf</button></div><p class="lbl" id="eInfo" style="text-transform:none;letter-spacing:0;margin:0"></p></div>
   <div class="card stack" id="eMain" hidden><div class="row" style="justify-content:space-between"><div class="row" style="gap:6px"><button class="btn small" type="button" id="ePrev">◀ 10 s</button><button class="btn small" type="button" id="eNext">10 s ▶</button><input type="range" id="eSlide" min="0" max="0" step="10" style="width:min(320px,50vw)"><span class="lbl" id="eT" style="text-transform:none;letter-spacing:0"></span></div><span class="lbl" id="eMiss" style="text-transform:none;letter-spacing:0"></span></div>
    <div id="eView"></div><div class="row" id="eAnn" style="gap:6px"></div></div>
   <div class="card stack" id="eTr" hidden><div class="row" style="justify-content:space-between"><h2>Compressed spectral array</h2><div class="row"><button class="btn small" type="button" id="eTrGo">Compute trend</button><button class="btn small" type="button" id="eTrX" hidden>Cancel</button><span class="lbl" id="eTrP" style="text-transform:none;letter-spacing:0"></span></div></div><p style="margin:0;max-width:86ch">Power from 0.5 to 20 Hz over time, left and right hemispheres (average reference). Seizures appear as bright flames, sleep spindles as a 12–14 Hz band, suppression as dark columns. Click the trend to open that page.</p><canvas id="eTrC" style="display:block;width:100%;height:190px;cursor:crosshair"></canvas></div>
   <div class="card stack" id="eMap" hidden><h3>Channels</h3><div class="tw" id="eMapT"></div></div>`;
  const q=s=>host.querySelector(s),V=Viewer(q('#eView'));
  async function open(file,name){try{S.file=file;S.H=await readHeader(file);S.t=0;S.trend=null;const H=S.H,eeg=H.sig.filter(s=>s.map.el),miss=ELN.filter(n=>!eeg.some(s=>s.map.el===n)),bip=H.sig.filter(s=>s.map.bip).length;
    q('#eInfo').innerHTML=`<b>${name}</b> · ${H.bdf?'BDF (24-bit)':H.plus?'EDF+':'EDF'} · ${H.ns} signals · ${fmtHMS(H.total)} · ${[...new Set(eeg.map(s=>Math.round(s.fs)))].join(', ')||'?'} Hz${H.disc?' · discontinuous EDF+D: times are approximate':''}${bip>3&&eeg.length<6?' · <b>looks bipolar: montages need referential data</b>':''}`;
    q('#eMiss').textContent=miss.length?`Missing: ${miss.join(', ')} (shown flat)`:'All 19 electrodes found';
    q('#eMapT').innerHTML=`<table><thead><tr><th>Label in file</th><th>Mapped to</th><th>Rate</th><th>Units</th></tr></thead><tbody>${H.sig.map(s=>`<tr><td>${s.lab}</td><td>${s.ann?'annotations':s.map.el||(s.map.ecg?'ECG row':s.map.bip?'bipolar (not used)':'—')}</td><td>${s.ann?'':Math.round(s.fs)+' Hz'}</td><td>${s.dim}</td></tr>`).join('')}</tbody></table>`;
    const ai=H.sig.findIndex(s=>s.ann);S.ann=[];if(ai>=0){for(let r=0;r<H.nrec;r+=600){const R=await readRecs(file,H,r,r+600);S.ann.push(...parseTAL(H,R,ai))}}
    q('#eAnn').innerHTML=S.ann.length?'<span class="lbl">Annotations</span>'+S.ann.slice(0,60).map((a,i)=>`<button class="chip" type="button" data-an="${i}">${fmtHMS(a.t)} ${a.txt.replace(/</g,'&lt;')}</button>`).join(''):'';$$('[data-an]',host).forEach(b=>b.addEventListener('click',()=>go(Math.floor(S.ann[+b.dataset.an].t/10)*10)));
    q('#eSlide').max=Math.max(0,Math.floor((H.total-10)/10)*10);['#eMain','#eTr','#eMap'].forEach(k=>q(k).hidden=false);await go(0);drawTr()}catch(e){q('#eInfo').textContent='Could not read this file as EDF/BDF: '+e.message}}
  async function go(t){const H=S.H;if(!H)return;t=clamp(t,0,Math.max(0,H.total-10));S.t=t;const r0=Math.floor(t/H.dur),r1=Math.ceil((t+10)/H.dur)+1,R=await readRecs(S.file,H,r0,r1),rec=newRec(),t0=t-r0*H.dur;
    H.sig.forEach((s,i)=>{if(!s.map.el&&!s.map.ecg)return;const x=resamp(chan(H,R,i),s.fs,t0,N,FS);let m=0;for(const v of x)m+=v;m/=N;for(let k=0;k<N;k++)x[k]-=m;if(s.map.el)rec.V[IX[s.map.el]]=x;else{let mx=1e-9;for(const v of x)mx=Math.max(mx,Math.abs(v));rec.ecg=x.map(v=>v/mx*.9)}});
    rec.ann=S.ann.filter(a=>a.t>=t&&a.t<t+10).map(a=>({t0:a.t-t,t1:a.t-t+Math.max(.3,Math.min(9,a.d||.5)),txt:a.txt.slice(0,60)}));rec._c={};const keep={...V.v};V.setRec(rec);V.v=keep;$$('#eView [data-k]',host).forEach(c=>{const k=c.dataset.k;if(k==='reset')return;if(c.type==='checkbox')c.checked=V.v[k];else c.value=String(V.v[k])});V.setAnn(true);
    q('#eSlide').value=t;q('#eT').textContent=`${fmtHMS(t)} – ${fmtHMS(t+10)} of ${fmtHMS(H.total)}`;drawTr()}
  const fmtHMS=s=>{s=Math.max(0,Math.round(s));return`${Math.floor(s/3600)}:${String(Math.floor(s/60)%60).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
  q('#eFile').addEventListener('change',e=>{const f=e.target.files&&e.target.files[0];if(f)open(f,f.name.replace(/</g,''))});
  let sampleBlob=null;q('#eSample').addEventListener('click',()=>{sampleBlob=sampleBlob||sampleEdf();q('#eDl').hidden=false;open(sampleBlob,'Sample recording (synthetic)')});
  q('#eDl').addEventListener('click',()=>{if(!sampleBlob)return;const a=document.createElement('a');a.href=URL.createObjectURL(sampleBlob);a.download='reading-room-sample.edf';document.body.appendChild(a);a.click();a.remove()});
  q('#ePrev').addEventListener('click',()=>go(S.t-10));q('#eNext').addEventListener('click',()=>go(S.t+10));q('#eSlide').addEventListener('change',e=>go(+e.target.value));
  host.addEventListener('keydown',e=>{if(!S.H||/INPUT|SELECT/.test(document.activeElement.tagName))return;if(e.key==='ArrowRight')go(S.t+10);if(e.key==='ArrowLeft')go(S.t-10)});host.tabIndex=-1;
  /* ---- trend ---- */
  const LEFT=['Fp1','F3','C3','P3','O1','F7','T3','T5'],RIGHT=['Fp2','F4','C4','P4','O2','F8','T4','T6'],FQ_=[];for(let f=.5;f<=20;f+=.5)FQ_.push(f);
  async function trend(){const H=S.H;if(!H||S.busy)return;S.busy=true;S.cancel=false;q('#eTrX').hidden=false;const ep=H.total>3*3600?60:H.total>1800?30:10,ne=Math.floor(H.total/ep),out=[],fo=64;
    for(let e=0;e<ne&&!S.cancel;e++){const t=e*ep,r0=Math.floor(t/H.dur),r1=Math.ceil((t+ep)/H.dur),R=await readRecs(S.file,H,r0,r1);if(!R)break;const n=Math.floor(ep*fo),sig={};H.sig.forEach((s,i)=>{if(s.map.el)sig[s.map.el]=resamp(chan(H,R,i),s.fs,t-r0*H.dur,n,fo)});
      const els=Object.keys(sig),avg=new Float32Array(n);els.forEach(k=>{for(let j=0;j<n;j++)avg[j]+=sig[k][j]/els.length});
      const spec=grp=>{const g=grp.filter(k=>sig[k]),P=FQ_.map(()=>0);if(!g.length)return P;const W=128;let nw=0;for(let w0=0;w0+W<=n;w0+=W){nw++;g.forEach(k=>{const x=sig[k];FQ_.forEach((f,fi)=>{let re=0,im=0;for(let j=0;j<W;j++){const v=(x[w0+j]-avg[w0+j])*(.5-.5*Math.cos(2*Math.PI*j/(W-1)));re+=v*Math.cos(2*Math.PI*f*j/fo);im+=v*Math.sin(2*Math.PI*f*j/fo)}P[fi]+=(re*re+im*im)/g.length})})}return P.map(p=>p/Math.max(1,nw))};
      out.push({t,L:spec(LEFT),R:spec(RIGHT)});if(e%5===0){q('#eTrP').textContent=`${Math.round(e/ne*100)}%`;S.trend={ep,pts:out.slice()};drawTr();await new Promise(r=>setTimeout(r))}}
    S.trend={ep,pts:out};S.busy=false;q('#eTrX').hidden=true;q('#eTrP').textContent=S.cancel?'Cancelled':`${out.length} epochs of ${ep} s`;drawTr()}
  function drawTr(){const cv=q('#eTrC'),S_=cvSetup(cv);if(!S_)return;const{g:x,w,h,C}=S_,L=48,H=S.H;x.fillStyle=C.muted;x.font='10.5px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.textBaseline='middle';
    if(!S.trend||!S.trend.pts.length){x.fillText('Press “Compute trend” to scan the whole file.',L,h/2);return}const pts=S.trend.pts,ph=(h-24)/2-4,db=[];pts.forEach(p=>[...p.L,...p.R].forEach(v=>db.push(10*Math.log10(v+1e-9))));db.sort((a,b)=>a-b);const lo=db[Math.floor(db.length*.05)],hi=db[Math.floor(db.length*.995)],cw=(w-L-6)/Math.max(1,H.total/S.trend.ep);
    [['L','Left',2],['R','Right',ph+8]].forEach(([k,lab,y0])=>{x.fillStyle=C.muted;x.textAlign='right';x.fillText(lab,L-5,y0+ph/2);pts.forEach(p=>{const X=L+p.t/H.total*(w-L-6);p[k].forEach((v,j)=>{x.fillStyle=cmap((10*Math.log10(v+1e-9)-lo)/(hi-lo));x.fillRect(X,y0+ph-(j+1)*ph/FQ_.length,cw+.6,ph/FQ_.length+.6)})})});
    const X=L+S.t/H.total*(w-L-6);x.strokeStyle=C.accent;x.lineWidth=2;x.beginPath();x.moveTo(X,2);x.lineTo(X,h-20);x.stroke();x.lineWidth=1;x.fillStyle=C.muted;x.textAlign='left';x.fillText('0:00:00',L,h-8);x.textAlign='right';x.fillText(fmtHMS(H.total),w-6,h-8);cv._L=L}
  q('#eTrGo').addEventListener('click',trend);q('#eTrX').addEventListener('click',()=>S.cancel=true);q('#eTrC').addEventListener('click',e=>{if(!S.H)return;const b=e.currentTarget.getBoundingClientRect(),L=48,t=clamp((e.clientX-b.left-L)/(b.width-L-6),0,1)*S.H.total;go(Math.floor(t/10)*10)});
  AX.draws.edf=[()=>V.draw(),drawTr]}
return{build,readHeader,sampleEdf,mapLabel}})();
function buildEdf(host){return EDF.build(host)}
