/* ============ neurofeedback trainer: operant conditioning of EEG rhythms (simulated) ============ */
const NFB=(()=>{
const PROT={alpha:{n:'Alpha up-training',site:'Pz',t:[8,12],inh:[],why:'Posterior alpha reflects visual thalamocortical loops idling: relaxed, eyes closed, not processing visual input.'},
 smr:{n:'SMR up-training',site:'C4',t:[12,15],inh:[[4,7],[22,30]],why:'The sensorimotor rhythm appears over sensorimotor cortex when the body is still and alert; it is produced by thalamocortical (ventral posterolateral) bursting, the same circuitry that makes sleep spindles.'},
 tbr:{n:'Theta/beta down-training',site:'Cz',t:[4,8],t2:[13,21],inh:[[22,30]],why:'More frontocentral theta relative to beta accompanies drowsy, under-aroused states; the ratio falls with alert, focused attention.'}};
function Biq(type,f,Q){const k=bq(type,f,Q);let x1=0,x2=0,y1=0,y2=0;return v=>{const y=k[0]*v+k[1]*x1+k[2]*x2-k[3]*y1-k[4]*y2;x2=x1;x1=v;y2=y1;y1=y;return y}}
function BP(a,b){const h1=Biq('hp',a,.707),h2=Biq('hp',a,.707),l1=Biq('lp',b,.707),l2=Biq('lp',b,.707);return v=>l2(l1(h2(h1(v))))}
function build(host){host.innerHTML='';const S={prot:'smr',src:'you',arousal:.55,eyes:'open',still:.8,run:false,fast:false,len:180,t:0,thr:null,thrI:[],auto:true,skill:0,lat:0,art:[],log:[],buf:new Float32Array(1200),bi:0,ph:{a:0,s:0,t:0,b:0},pink:0,rew:0,rewN:0,amp:{},hist:[]};
  host.innerHTML=`<div class="card stack"><div class="row" style="justify-content:space-between;align-items:flex-start"><div class="stack" style="gap:6px;max-width:86ch"><h2>Neurofeedback: training a rhythm</h2>
   <p style="margin:0">Neurofeedback is operant conditioning of the EEG. A filter extracts one rhythm from one electrode, its power is compared with a threshold many times a second, and the brain is rewarded when the rhythm is strong and artifact-prone bands stay quiet. What can be trained depends on what generates the rhythm, so each protocol below starts from its physiology.</p></div><span class="pill">Simulator</span></div>
   <div class="note"><b>Evidence.</b> Results are mixed. The best-studied uses (theta/beta and SMR protocols for attention problems) have trials whose effects shrink once blinding and sham feedback are used well. This page is an educational simulator, not a treatment.</div>
   <div class="row" style="gap:6px"><span class="lbl">Related patterns</span>${['awake','reactivity','drowsy','n2','mu','muscle','blink','benzo'].filter(i=>PM[i]).map(i=>`<button class="chip" type="button" data-pat="${i}">${PM[i].name}</button>`).join('')}</div></div>
   <div class="card stack"><div class="row" id="nP"></div><p id="nWhy" style="margin:0"></p><div class="row" id="nS"></div>
   <div class="labg"><div class="stack" style="gap:8px" id="nCtl"></div><div class="stack" style="gap:8px"><div class="row" style="gap:6px"><button class="btn primary" type="button" id="nGo">Start</button><button class="btn small" type="button" id="nBl">Blink</button><button class="btn small" type="button" id="nJaw">Clench jaw</button><button class="btn small" type="button" id="nMv">Move</button><label class="row lbl" style="gap:6px;text-transform:none;letter-spacing:0"><input type="checkbox" id="nFast"> ×10 speed</label><label class="row lbl" style="gap:6px;text-transform:none;letter-spacing:0"><input type="checkbox" id="nAuto" checked> Auto-threshold</label></div>
    <canvas class="nraw" style="display:block;width:100%;height:120px"></canvas><div class="nfbrow"><canvas class="nfv" style="display:block;width:150px;height:150px"></canvas><canvas class="nbar" style="display:block;width:100%;height:150px"></canvas></div></div></div>
   <div class="note" id="nRead"></div><span class="lbl">Session</span><canvas class="nses" style="display:block;width:100%;height:150px"></canvas></div>`;
  const q=s=>host.querySelector(s);segment(q('#nP'),Object.entries(PROT).map(([k,p])=>[k,`${p.n} · ${p.site}`]),S.prot,v=>{S.prot=v;reset()});
  segment(q('#nS'),[['you','You control the state'],['sim','Simulated learner']],'you',v=>{S.src=v;ctlVis()});
  const ctl=q('#nCtl'),sa=slider(ctl,'Alertness',{min:0,max:1,step:.01,val:S.arousal,fmt:v=>v<.3?'drowsy':v<.7?'relaxed, alert':'tense, aroused'},v=>S.arousal=v),
   ss=slider(ctl,'Body stillness',{min:0,max:1,step:.01,val:S.still,fmt:v=>v<.4?'fidgeting':v<.8?'mostly still':'very still'},v=>S.still=v);
  const eg=el('div','row');ctl.appendChild(eg);segment(eg,[['open','Eyes open'],['closed','Eyes closed']],'open',v=>S.eyes=v);
  const lg=el('label','sl');lg.innerHTML='<span class="sn">Session length</span><select><option value="180">3 min</option><option value="600">10 min</option><option value="1200">20 min</option></select><output></output>';ctl.appendChild(lg);$('select',lg).addEventListener('change',e=>S.len=+e.target.value);
  const ctlVis=()=>{[sa,ss].forEach(x=>x.input.disabled=S.src==='sim');eg.style.opacity=S.src==='sim'?.5:1};
  let F={};function reset(){const p=PROT[S.prot];q('#nWhy').innerHTML=`<b>${p.n} at ${p.site}:</b> reward ${p.t[0]}–${p.t[1]} Hz${p.t2?` relative to ${p.t2[0]}–${p.t2[1]} Hz (lower ratio rewarded)`:''}${p.inh.length?`; inhibit ${p.inh.map(b=>b[0]+'–'+b[1]+' Hz').join(' and ')}`:''}. ${p.why}`;
    F={t:BP(p.t[0],p.t[1]),t2:p.t2?BP(p.t2[0],p.t2[1]):null,inh:p.inh.map(b=>BP(b[0],b[1]))};S.pw={t:1,t2:1,inh:p.inh.map(()=>1)};S.thr=null;S.t=0;S.log=[];S.rew=0;S.rewN=0;S.skill=0;S.hist=[];draw()}
  /* signal model: amplitudes follow state */
  function amps(){let ar=S.arousal,st=S.still,ec=S.eyes==='closed';if(S.src==='sim'){S.lat+=(.04*(Math.random()-.5))-.002*S.lat;const p=S.prot,sk=S.skill;ar=clamp(.5+S.lat*.6+(p==='tbr'?.25*sk:0),0,1);st=clamp(.6+.35*sk+.2*S.lat,0,1);ec=p==='alpha'}
    const A={};A.alpha=(ec?30:7)*(1-Math.abs(ar-.45)*1.2)*(S.prot==='alpha'&&S.src==='sim'?1+.6*S.skill:1);A.smr=(4+10*st*(1-Math.abs(ar-.6)))*(S.prot==='smr'&&S.src==='sim'?1+.5*S.skill:1);A.theta=4+14*Math.max(0,.55-ar);A.beta=3+9*ar;Object.keys(A).forEach(k=>A[k]=Math.max(1,A[k]));S.amp=A;return A}
  function sample(dt){const A=amps(),ph=S.ph;ph.a+=2*Math.PI*10*dt*(1+.02*Math.random());ph.s+=2*Math.PI*13.5*dt;ph.t+=2*Math.PI*6*dt;ph.b+=2*Math.PI*19*dt*(1+.1*(Math.random()-.5));S.pink=.97*S.pink+.25*(Math.random()-.5)*10;
    const site=PROT[S.prot].site,wA=site==='Pz'?1:.45,wS=site==='C4'?1:.4,wT=site==='Cz'?1:.7;let v=S.pink+wA*A.alpha*Math.sin(ph.a)*(.7+.3*Math.sin(ph.a*.031))+wS*A.smr*Math.sin(ph.s)*(.5+.5*Math.sin(ph.s*.023))+wT*A.theta*Math.sin(ph.t)+A.beta*.5*Math.sin(ph.b)+3*(Math.random()-.5);
    S.art=S.art.filter(a=>S.t<a.end);for(const a of S.art){const u=S.t-a.t0;if(a.k==='blink')v+=-90*Math.exp(-((u-.2)**2)/(2*.08*.08))*(site==='Cz'?.5:.25);if(a.k==='jaw')v+=40*(Math.random()-.5)*2;if(a.k==='move')v+=60*Math.sin(2*Math.PI*1.5*u)*Math.exp(-u)}return v}
  const tau=.8;function step(dt){const v=sample(dt);S.t+=dt;S.buf[S.bi%S.buf.length]=v;S.bi++;const k=dt/tau,p=PROT[S.prot];let y=F.t(v);S.pw.t+=k*(y*y-S.pw.t);if(F.t2){y=F.t2(v);S.pw.t2+=k*(y*y-S.pw.t2)}F.inh.forEach((f,i)=>{const z=f(v);S.pw.inh[i]+=k*(z*z-S.pw.inh[i])});
    const tv=F.t2?Math.sqrt(S.pw.t)/Math.sqrt(S.pw.t2):Math.sqrt(S.pw.t),iv=S.pw.inh.map(Math.sqrt);if(S.thr==null&&S.t>2){S.thr=tv*(F.t2?1.05:.95);S.thrI=iv.map(x=>x*1.8)}
    let rw=false;if(S.thr!=null){const ok=F.t2?tv<S.thr:tv>S.thr,inhOk=iv.every((x,i)=>x<S.thrI[i]);rw=ok&&inhOk;S.rewN+=dt;if(rw)S.rew+=dt;if(S.auto){const err=(rw?1:0)-.65;S.thr*=F.t2?(1+.04*err*dt):(1+.04*err*dt)}if(rw&&S.src==='sim')S.skill=Math.min(1,S.skill+.0016*dt)}
    S.cur={tv,iv,rw};if(Math.floor(S.t/5)>S.hist.length-1&&S.t>2)S.hist.push({t:S.t,tv,rr:S.rewN?S.rew/S.rewN:0})}
  let raf=0,last=0;function loop(ts){if(!S.run)return;if(host.offsetParent===null){stop();return}const dtw=Math.min(.1,(ts-(last||ts))/1000)*(S.fast?10:1);last=ts;const n=Math.round(dtw*FS);for(let i=0;i<n;i++)step(1/FS);draw();if(S.t>=S.len){stop();summary();return}raf=requestAnimationFrame(loop)}
  function start(){if(S.t>=S.len||S.t===0)reset();S.run=true;last=0;q('#nGo').textContent='Stop';raf=requestAnimationFrame(loop)}
  function stop(){S.run=false;cancelAnimationFrame(raf);q('#nGo').textContent=S.t>0&&S.t<S.len?'Resume':'Start'}
  function summary(){const h=S.hist,first=h.slice(0,Math.max(1,Math.floor(h.length/4))),lastq=h.slice(-Math.max(1,Math.floor(h.length/4))),m=a=>a.reduce((s,x)=>s+x.tv,0)/a.length;q('#nRead').innerHTML=`<b>Session complete.</b> Reward ${Math.round(S.rew/S.rewN*100)}% of the time. Target ${F.t2?'ratio':'amplitude'} moved from ${m(first).toFixed(2)} to ${m(lastq).toFixed(2)}${S.src==='sim'?` as the simulated learner’s skill reached ${Math.round(S.skill*100)}%`:''}. Remember the auto-threshold keeps reward near 65%, so learning shows up as rising target power, not rising reward.`}
  q('#nGo').addEventListener('click',()=>S.run?stop():start());q('#nFast').addEventListener('change',e=>S.fast=e.target.checked);q('#nAuto').addEventListener('change',e=>S.auto=e.target.checked);
  const art=(k,d)=>{S.art.push({k,t0:S.t,end:S.t+d});if(!S.run){for(let i=0;i<d*FS;i++)step(1/FS);draw()}};q('#nBl').addEventListener('click',()=>art('blink',.6));q('#nJaw').addEventListener('click',()=>art('jaw',1.5));q('#nMv').addEventListener('click',()=>art('move',2));
  function draw(){const C=cssv(),p=PROT[S.prot];let c=cvSetup(q('.nraw'));if(c){const{g:x,w,h}=c,n=Math.min(S.bi,1200),L=40;x.fillStyle=C.muted;x.font='10px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.fillText(p.site,4,14);x.strokeStyle=C.trace;x.lineWidth=1;x.beginPath();for(let i=0;i<n;i++){const v=S.buf[(S.bi-n+i+1200)%1200],X=L+(1200-n+i)/1199*(w-L-4),Y=h/2-v*.9;i?x.lineTo(X,Y):x.moveTo(X,Y)}x.stroke();x.fillText('last 6 s',w-60,h-4)}
    c=cvSetup(q('.nfv'));if(c){const{g:x,w,h}=c,rw=S.cur&&S.cur.rw,rr=S.rewN?S.rew/S.rewN:0;x.fillStyle=rw?C.good:C.soft;x.globalAlpha=rw?.85:1;x.beginPath();x.arc(w/2,h/2,(rw?.42:.3)*w,0,6.29);x.fill();x.globalAlpha=1;x.fillStyle=C.ink;x.textAlign='center';x.font='600 13px '+getComputedStyle(document.body).fontFamily;x.fillText(rw?'reward':'—',w/2,h/2+4);x.font='11px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.fillStyle=C.muted;x.fillText(`${Math.round(rr*100)}% rewarded`,w/2,h-6)}
    c=cvSetup(q('.nbar'));if(c&&S.cur){const{g:x,w,h}=c,items=[[F.t2?'θ/β ratio':`${p.t[0]}–${p.t[1]} Hz`,S.cur.tv,S.thr,F.t2?'below':'above',F.t2?3:30],...p.inh.map((b,i)=>[`inhibit ${b[0]}–${b[1]} Hz`,S.cur.iv[i],S.thrI[i],'below',40])],bw=(w-20)/items.length;x.font='10.5px '+getComputedStyle(document.body).getPropertyValue('--font-mono');
      items.forEach(([lab,v,t,dir,mx],i)=>{const x0=10+i*bw+bw*.2,ww=bw*.6,Y=u=>h-24-Math.min(1,u/mx)*(h-40),ok=t==null?false:dir==='above'?v>t:v<t;x.fillStyle=ok?C.good:C.mark;x.globalAlpha=.75;x.fillRect(x0,Y(v),ww,h-24-Y(v));x.globalAlpha=1;if(t!=null){x.strokeStyle=C.ink;x.setLineDash([4,3]);x.beginPath();x.moveTo(x0-6,Y(t));x.lineTo(x0+ww+6,Y(t));x.stroke();x.setLineDash([])}x.fillStyle=C.muted;x.textAlign='center';x.fillText(lab,x0+ww/2,h-8);x.fillText(v.toFixed(F.t2&&i===0?2:1),x0+ww/2,Y(v)-4)})}
    c=cvSetup(q('.nses'));if(c){const{g:x,w,h}=c,H=S.hist,L=40;x.strokeStyle=C.line;x.strokeRect(L,6,w-L-6,h-26);x.fillStyle=C.muted;x.font='10px '+getComputedStyle(document.body).getPropertyValue('--font-mono');x.fillText('0',L,h-6);x.textAlign='right';x.fillText(Math.round(S.len/60)+' min',w-6,h-6);x.textAlign='left';
      if(H.length>1){const mx=Math.max(...H.map(a=>a.tv))*1.15,X=t=>L+t/S.len*(w-L-6);x.strokeStyle=C.accent;x.lineWidth=1.6;x.beginPath();H.forEach((a,i)=>{const Y=h-20-a.tv/mx*(h-30);i?x.lineTo(X(a.t),Y):x.moveTo(X(a.t),Y)});x.stroke();x.strokeStyle=C.good;x.beginPath();H.forEach((a,i)=>{const Y=h-20-a.rr*(h-30);i?x.lineTo(X(a.t),Y):x.moveTo(X(a.t),Y)});x.stroke();x.lineWidth=1;x.fillStyle=C.accent;x.fillText('target',L+4,16);x.fillStyle=C.good;x.fillText('reward rate',L+60,16)}}
    if(S.run||S.t)q('#nRead').innerHTML=S.cur?`${S.cur.rw?'<b>Rewarding.</b>':'<b>Not rewarding.</b>'} ${S.art.length?S.art[0].k==='jaw'?'Jaw EMG floods the fast bands: the inhibit band stops a false reward.':S.art[0].k==='blink'?'A blink is a large slow potential: it inflates low frequencies (theta) and can fake success in a theta/beta protocol.':'Movement artifact: broadband and slow.':S.src==='sim'?`Simulated learner, skill ${Math.round(S.skill*100)}%: rewarded states become more likely as the session goes on.`:'Change alertness, stillness or eyes to see which state the protocol rewards.'} <span class="lbl" style="text-transform:none;letter-spacing:0">${Math.floor(S.t/60)}:${String(Math.floor(S.t%60)).padStart(2,'0')} of ${S.len/60} min</span>`:''}
  ctlVis();reset();AX.draws.nfb=[draw];q('#nRead').textContent='Press Start. Nothing runs until you do.'}
return{build}})();
function buildNfb(host){return NFB.build(host)}
