
/* ============ pattern generators, set 2: specialty, staged electrolytes, pacing, technical ============ */
const stB=(A,d,qt,off=.095)=>{const tp=qt-.097;return{sh:'p',a:off-.012,ra:.03,b:tp,fb:qt-tp,A,d}};
const spike=(A,d)=>({sh:'sp',c:0,A,d:d||nrm([.35,-.4,-.85])});
function irregular(R,hrMean,lo,hi,mk,o={}){const r=R.r,rr=60/hrMean;let t=-r.r(0,.5),i=0;while(t<DUR+.6){addV(R,t,mk(i,t));t+=Math.max(o.min??.2,rr*(lo+(hi-lo)*r.u()));i++}}
function fwaves(R,A){const r=R.r;addCont(R,bandNoise(r,4,9,A),nrm([-.3,.35,.9]));addCont(R,bandNoise(r,4,9,A*.6),nrm([.4,-.3,.4]))}
function sawtooth(R,cyc,A,d){const f=new Float64Array(N),F=[];let ph=R.r.u();for(let i=0;i<N;i++){ph+=1/(cyc*FS);if(ph>=1){ph-=1;F.push(i/FS)}f[i]=(ph<.72?ph/.72:1-(ph-.72)/.28)-.5}
  const fs=Float32Array.from(ff(f,bq('lp',22,.707)));for(let i=0;i<N;i++)fs[i]*=A;addCont(R,fs,d);let tf=F[0]-cyc;while(tf>-1.2){F.unshift(tf);tf-=cyc}let tl=F[F.length-1];while(tl<DUR+.8){tl+=cyc;F.push(tl)}return F}
/* ---- ischemia: subtle occlusion and equivalents ---- */
GEN.hyperT=R=>{const r=R.r,hr=r.r(70,95),pr=r.r(.13,.17),vm=corMorph(OCC.mLAD.segs,occStage(r.r(10,16),null),qtF(hr,.41)),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';
  hl(R,['V2','V3','V4'],'Broad, bulky T waves out of proportion to the QRS');hl(R,['V1','V2'],'Minimal ST elevation','b')};
GEN.saflag=R=>{const r=R.r,hr=r.r(72,98),pr=r.r(.13,.17),qt=qtF(hr,.41),d=nrm([.38,-.92,0]),vm=V({axis:r.r(40,65),qt,stA:r.r(.28,.32),std:d,stra:.025,t:[{c:qt-.097,wl:.068,wr:.042,A:.4,d:fv(43,.6)},{c:qt-.12,wl:.08,wr:.055,A:.3,d}],loc:[{sh:'p',a:.09,ra:.025,b:qt-.12,fb:.1,A:.24,lm:{V2:1,V1:.3}}]}),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';R.autoST=1};
GEN.swirl=R=>{const r=R.r,hr=r.r(75,100),pr=r.r(.13,.17),qt=qtF(hr,.42),d=nrm([-.28,-.72,.64]),vm=V({axis:r.r(40,70),qt,stA:r.r(.26,.32),std:d,stra:.025,t:[{c:qt-.097,wl:.068,wr:.042,A:.35,d:fv(43,.6)},{c:qt-.12,wl:.08,wr:.055,A:.35,d}]}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';R.autoST=1};
GEN.aslanger=R=>{const r=R.r,hr=r.r(70,95),pr=r.r(.14,.18),qt=qtF(hr,.42),vm=V({axis:r.r(50,75),qt,stA:r.r(.2,.25),std:nrm([-.25,1,-.05]),stra:.025,xst:[stB(-.2,nrm([.65,.6,.3]),qt)],tA:.42}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['III'],'ST elevation in III only');hl(R,['V4','V5','V6'],'ST depression with upright T','b')};
GEN.rvmi=R=>{const r=R.r,hr=r.r(48,66),pr=r.r(.19,.24),vm=corMorph(occSegs('pRCA','right',false),occStage(r.r(60,240),null),qtF(hr,.42)),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus bradycardia';R.autoST=1;hl(R,['V1'],'ST elevation in V1: right ventricle involved','b')};
GEN.stemirbbb=R=>{const r=R.r,hr=r.r(78,105),pr=r.r(.14,.18),qt=qtF(hr,.43),d=nrm([.45,-.35,.8]),vm=rbbbM(r,{qt,stA:r.r(.28,.34),std:d,stra:.025,t:[{c:qt-.11,wl:.08,wr:.05,A:.45,d}]}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm with RBBB';R.autoST=1;hl(R,['V1'],'RBBB: rsR′ (new)','b')};
GEN.shark=R=>{const r=R.r,hr=r.r(90,120),pr=r.r(.13,.16),qt=qtF(hr,.44),d=nrm([.3,-.15,.95]),vm=V({axis:r.r(30,60),s:1.3,qt,stA:r.r(.62,.78),std:d,stra:.012,stb:qt-.16,t:[{c:qt-.13,wl:.05,wr:.06,A:.2,d}]}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus tachycardia';R.autoST=1;hl(R,['V2','V3','V4'],'QRS, ST and T fused into one triangle','b')};
GEN.antsubtle=R=>{const r=R.r,hr=r.r(65,90),pr=r.r(.13,.17),qt=qtF(hr,.41),d=nrm([.2,-.05,1]),vm=V({axis:r.r(40,70),qt,stA:r.r(.11,.14),std:d,stra:.05,xst:[stB(-.05,nrm([-.2,1,0]),qt)],t:[{c:qt-.1,wl:.072,wr:.048,A:.62,d:nrm([.35,.1,.9])}],loc:[{c:.062,wl:.012,A:.28,lm:{V2:1,V3:.85}}]}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['V2','V3'],'No S wave and no J notch (terminal QRS distortion)');hl(R,['III','aVF'],'Subtle reciprocal depression','b')};
GEN.takotsubo=R=>{const r=R.r,hr=r.r(78,100),pr=r.r(.13,.17),qt=r.r(.47,.52)*Math.cbrt(60/hr),d=nrm([.55,.3,.8]),vm=V({axis:r.r(40,70),qt,tfix:1,stA:.04,std:d,t:[{c:qt-.13,wl:.08,wr:.065,A:-.75,d}]}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['V2','V3','V4','V5','V6','I','aVL','II'],'Deep, wide T inversion with long QT, no Q waves')};
/* ---- tachycardias, wide and narrow ---- */
GEN.svtab=R=>{const r=R.r,hr=r.r(165,205),lb=r.chance(.5),qt=qtF(hr),vm=lb?lbbbM(r,{qt}):rbbbM(r,{qt});sinus(R,{hr,vm,jit:.003});R.tm={vm,pm:null,pr:null};R.meta.rhy=`SVT with ${lb?'LBBB':'RBBB'} aberrancy`;R.meta.prq='none';R.meta.variant=lb?'LBBB':'RBBB';
  hl(R,lb?['V1','V6']:['V1','I','V6'],lb?'Typical LBBB shape: rapid initial deflection':'Typical RBBB shape: rsR′, slurred S')};
const wpwM=(r,f,dir)=>{const d=dir||nrm([-.35,.5,.8]);return V({q:[{c:.07,wl:.03*(.7+.8*f),wr:.014,A:1.3*f+.2,d},{c:.098+.02*f,wl:.016+.01*f,A:1.3*(1-.6*f),d:fv(60,-.25)},{c:.125+.02*f,wl:.012,A:.3*(1-.5*f),d:nrm([-.35,-.55,-.75])}],qt:.32,td:neg(d),tA:.25+.15*f})};
GEN.preaf=R=>{const r=R.r,hr=r.r(190,250),mk=[.25,.5,.75,1].map(f=>wpwM(r,f));irregular(R,hr,.6,1.45,()=>mk[Math.floor(r.u()*4)],{min:.19});fwaves(R,.04);
  R.tm={vm:mk[2],pm:null,pr:null};R.meta.rhy='Pre-excited atrial fibrillation';R.meta.reg='irr';R.meta.prq='none';R.meta.noMeas=['qtc','axis','qrs'];hl(R,['II','V1'],'Fast, broad, irregular, with QRS width changing beat to beat')};
GEN.antidromic=R=>{const r=R.r,hr=r.r(200,240),d=nrm([-.35,.5,.8]),vm=V({q:[{c:.065,wl:.038,wr:.03,A:1.35,d},{c:.13,wl:.028,A:.45,d:nrm([.2,.6,.4])}],qt:.26,t:[{c:.2,wl:.04,wr:.035,A:.45,d:neg(d)}],kind:'x'});
  sinus(R,{hr,vm,jit:.002});R.tm={vm,pm:null,pr:null};R.meta.rhy='Antidromic AVRT (pre-excited tachycardia)';R.meta.prq='none';hl(R,['II','V1'],'Regular, very fast, fully pre-excited QRS')};
GEN.fascvt=R=>{const r=R.r,hr=r.r(150,185),qt=Math.min(.34,60/hr*.9),vm=V({axis:r.r(-75,-55),s:1.12,sepd:nrm([-.2,.85,.45]),sep:1.2,z:-.3,xq:[{c:.095,wl:.018,A:.7,d:nrm([-.6,.1,.78])}],term:.3,qt,td:nrm([.65,.45,-.45]),tA:.35,kind:'v'}),pm=nP(r);
  sinus(R,{hr,vm,jit:.003});let tp=-r.r(0,.8);const pa=60/r.r(70,90);while(tp<DUR){addP(R,tp,pm,{cond:false});tp+=pa}R.tm={vm,pm:null,pr:null};R.meta.rhy='Fascicular VT (idiopathic, left posterior fascicle)';R.meta.prq='none';
  hl(R,['V1'],'RBBB-like, relatively narrow');hl(R,['II','III','aVF'],'Superior (left) axis','b')};
GEN.rvotvt=R=>{const r=R.r,hr=r.r(160,200),qt=Math.min(.34,60/hr*.9),vm=V({q:[{c:.05,wl:.03,A:1.4,d:nrm([.15,.85,-.5])},{c:.112,wl:.025,A:.7,d:nrm([.45,.6,-.65])}],qt,t:[{c:qt-.09,wl:.06,wr:.04,A:.32,d:nrm([-.3,-.75,.55])}],kind:'v'}),pm=nP(r);
  sinus(R,{hr,vm,jit:.003});let tp=-r.r(0,.8);const pa=60/r.r(70,90);while(tp<DUR){addP(R,tp,pm,{cond:false});tp+=pa}R.tm={vm,pm:null,pr:null};R.meta.rhy='Right ventricular outflow tract VT';R.meta.prq='none';hl(R,['V1'],'LBBB-like');hl(R,['II','III','aVF'],'Inferior axis: tall R inferiorly','b')};
GEN.bidir=R=>{const r=R.r,hr=r.r(140,170),qt=Math.min(.34,60/hr*.88),a=V({axis:-60,s:1.15,amp:1.35,sepd:nrm([-.2,.85,.45]),sep:1.3,z:-.3,xq:[{c:.098,wl:.018,A:.7,d:nrm([-.6,.1,.78])}],term:.3,qt,td:nrm([.6,.4,-.4]),tA:.32,kind:'v'}),b=V({axis:115,s:1.15,amp:1.35,sepd:nrm([.45,-.75,.3]),sep:1.3,z:-.3,xq:[{c:.098,wl:.018,A:.7,d:nrm([-.6,.1,.78])}],term:.3,qt,td:nrm([.3,-.5,-.4]),tA:.32,kind:'v'});
  sinus(R,{hr,vm:i=>i%2?b:a,jit:.003});R.tm={vm:a,pm:null,pr:null};R.meta.rhy='Bidirectional VT';R.meta.prq='none';R.meta.reg='reg';R.meta.noMeas=['axis'];hl(R,['II','aVF','I'],'QRS axis flips every beat')};
GEN.pmvt=R=>{const r=R.r,hr=r.r(75,95),rr=60/hr,qt=qtF(hr,.41),vm=V({axis:55,qt,stA:-.18,std:fv(55,.3)}),pm=nP(r),pr=.15;let t=r.r(.2,.35);for(let k=0;k<3;k++){const pi=addP(R,t-pr,pm);addV(R,t,vm,pi);t+=rr}
  const ts=t-rr+qt*.75;let tt=ts,i=0;const base=nrm([.3,.85,.4]),nb=Math.floor(r.r(16,22));while(i<nb){const a=(.7+.5*r.u())*(r.u()<.5?1:-1),d=rot(base,r.r(-90,90)),A=1.4*a;addV(R,tt,{q:[{c:.05,wl:.034,A,d},{c:.13,wl:.036,A:-.5*A,d}],st:[],t:[],loc:[],kind:'v',on:0,off:.2,qt:.22,qrsd:.2});tt+=r.r(.19,.26);i++}
  span(R,ts,tt,'Polymorphic VT');let t3=tt+r.r(.9,1.3);while(t3<DUR+.6){const p2=addP(R,t3-pr,pm);addV(R,t3,vm,p2);t3+=rr}R.tm={vm,pm,pr};R.meta.rhy='Polymorphic VT with a normal QT';R.meta.noMeas=['rate','axis','qrs','pr','qtc'];R.meta.prq='none';hl(R,['II','V5'],'Normal QT with ischemic ST depression on sinus beats','b')};
GEN.vflutter=R=>{const r=R.r,hr=r.r(250,300),rr=60/hr,d=nrm([.3,.85,.35]),vm={q:[{c:rr*.3,wl:rr*.2,A:1.35,d},{c:rr*.8,wl:rr*.2,A:-1.2,d}],st:[],t:[],loc:[],kind:'v',on:0,off:rr,qt:rr,qrsd:rr};sinus(R,{hr,vm,jit:.002});R.tm=null;R.meta.rhy='Ventricular flutter';R.meta.noMeas=['axis','qrs','pr','qtc'];R.meta.prq='none';hl(R,['II','V2'],'Regular sine wave at about 300/min, no isoelectric line')};
GEN.atypflut=R=>{const r=R.r,cyc=1/r.r(4,4.8),F=sawtooth(R,cyc,r.r(.32,.38),nrm([.1,.85,-.45])),mode=r.pick([2,2,3,4]),hr=60/(cyc*mode),vm=sinMorph(r,{qt:qtF(Math.min(hr,140))});
  for(let i=Math.floor(r.u()*mode);i<F.length;i+=mode)addV(R,F[i]+.24,vm);R.tm={vm,pm:null,pr:null};R.meta.rhy=`Atypical (clockwise) atrial flutter, ${mode}:1`;R.meta.prq='none';R.meta.arate=Math.round(60/cyc);hl(R,['II','III','aVF'],'Upright (positive) flutter waves');hl(R,['V1'],'Negative flutter waves','b')};
GEN.eat=R=>{const r=R.r,hr=r.r(130,170),pr=r.r(.13,.17),pd=r.pick([nrm([-.6,.55,.35]),nrm([.2,-.9,.3])]),pm=Pw('ect',.15,pd),vm=sinMorph(r,{qt:qtF(hr)});sinus(R,{hr,pr,vm,pm,jit:.004});R.tm={vm,pm,pr};R.meta.rhy='Ectopic atrial tachycardia';
  hl(R,pd[0]<0?['I','aVL']:['II','III','aVF'],pd[0]<0?'P negative in I and aVL (left atrial focus)':'P inverted inferiorly (low atrial focus)')};
GEN.atblock=R=>{const r=R.r,hra=r.r(160,200),pp=60/hra,pr=r.r(.16,.2),pm=Pw('ect',.14,nrm([.45,.75,.35])),vm=sinMorph(r,{qt:qtF(hra/2)});let t=-r.r(0,pp),k=0;
  while(t<DUR+.5){if(k%2===0){const pi=addP(R,t,pm);addV(R,t+pr,vm,pi)}else addP(R,t,pm,{cond:false});t+=pp;k++}R.tm={vm,pm,pr};R.meta.rhy='Atrial tachycardia with 2:1 block';R.meta.arate=Math.round(hra);
  R.ev.p.filter(p=>p.t>.4&&p.t<4).forEach(p=>pt(R,p.t+.04,'P'));hl(R,['II','V1'],'Discrete P waves at 150–250/min with a flat baseline between them')};
GEN.wap=R=>{const r=R.r,hr=r.r(62,92),rr=60/hr,vm=sinMorph(r,{qt:qtF(hr)}),dirs=[nrm([.3,.9,.4]),nrm([-.35,.9,.25]),nrm([.45,-.55,.5]),nrm([.05,.95,-.35])];let t=-r.r(0,.5);
  while(t<DUR+.6){const k=Math.floor(r.u()*dirs.length),pr=r.r(.11,.2);addP(R,t-pr,Pw('ect',r.r(.1,.18),dirs[k]),{k:'e'+k});addV(R,t,vm,R.ev.p.length-1);t+=rr*r.r(.85,1.2)}R.tm={vm,pm:nP(r),pr:.15};R.meta.rhy='Wandering atrial pacemaker';R.meta.reg='irr';R.meta.prq='var';hl(R,['II'],'Three or more P shapes, rate under 100')};
GEN.orthoavrt=R=>{const r=R.r,hr=r.r(170,215),qt=qtF(hr),ax=r.r(40,70),a=V({axis:ax,qt,stA:-.08,std:fv(55,-.3),amp:1.08}),b=V({axis:ax,qt,stA:-.08,std:fv(55,-.3),amp:.8}),pm=Pw('retro',.12),rp=r.r(.1,.13);
  sinus(R,{hr,vm:i=>i%2?b:a,jit:.002});R.ev.q.slice().forEach(q=>addP(R,q.t+rp,pm,{k:'r'}));R.tm={vm:a,pm:null,pr:null};R.meta.rhy='Orthodromic AVRT';R.meta.prq='none';hl(R,['II','III','aVF'],'Retrograde P in the ST segment (RP over 70 ms)');hl(R,['V2','V3'],'QRS alternans','b')};
GEN.pjrt=R=>{const r=R.r,hr=r.r(120,165),pr=r.r(.11,.14),pm=Pw('retro',.14),vm=sinMorph(r,{qt:qtF(hr)});sinus(R,{hr,pr,vm,pm,jit:.003});R.ev.p.forEach(p=>p.k='r');R.tm={vm,pm,pr};R.meta.rhy='Long-RP tachycardia (PJRT)';
  const b=beatNear(R,5);span(R,b.t-pr,b.t,'Inverted P closer to the next QRS (RP > PR)');hl(R,['II','III','aVF'],'Inverted P waves')};
GEN.accjunct=R=>{const r=R.r,hr=r.r(68,100),vm=sinMorph(r,{qt:qtF(hr)}),pm=Pw('retro',.12),before=r.chance(.5);sinus(R,{hr,vm,jit:.006});R.ev.q.slice().forEach(q=>addP(R,q.t+(before?-.07:.09),pm,{k:'r'}));
  R.tm={vm,pm:before?pm:null,pr:before?.07:null};R.meta.rhy='Accelerated junctional rhythm';R.meta.prq=before?'short':'none';hl(R,['II','III','aVF'],'Retrograde P, narrow QRS, rate 60–100')};
GEN.sinusarrest=R=>{const r=R.r,hr=r.r(62,80),rr=60/hr,pr=r.r(.14,.18),vm=sinMorph(r,{qt:qtF(hr)}),pm=nP(r);let t=r.r(.2,.5);const tp=r.r(3.2,4.2),gap=r.r(2.9,3.6);
  while(t<tp){const pi=addP(R,t-pr,pm);addV(R,t,vm,pi);t+=rr*(1+.01*r.n())}const te=t-rr+gap;addV(R,te,vm);span(R,t-rr+.1,te-.05,'Pause: no P wave, not a multiple of the P–P');pt(R,te,'Junctional escape');let t2=te+rr*1.05;while(t2<DUR+.5){const pi=addP(R,t2-pr,pm);addV(R,t2,vm,pi);t2+=rr}
  R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm with sinus arrest';R.meta.reg='irr';R.meta.noMeas=['rate']};
GEN.saexit=R=>{const r=R.r,hr=r.r(62,82),rr=60/hr,pr=r.r(.14,.18),vm=sinMorph(r,{qt:qtF(hr)}),pm=nP(r);let t=r.r(.2,.5),k=0;const drop=Math.floor(r.r(4,6));
  while(t<DUR+.5){if(k===drop){span(R,t-rr+.08,t+rr-.08,'Pause exactly two P–P intervals');t+=rr;k++;continue}const pi=addP(R,t-pr,pm);addV(R,t,vm,pi);t+=rr;k++}R.tm={vm,pm,pr};R.meta.rhy='Sinoatrial exit block (type II)';R.meta.reg='regirr'};
GEN.hgavb=R=>{const r=R.r,hra=r.r(96,115),pp=60/hra,pr=r.r(.16,.2),g=3,vm=rbbbM(r,{qt:qtF(hra/g)}),pm=nP(r);let t=-r.r(0,pp)-pp*Math.floor(r.u()*g),k=0;
  while(t<DUR+.5){if(k%g===0){const pi=addP(R,t,pm);addV(R,t+pr,vm,pi)}else{addP(R,t,pm,{cond:false});if(t>.3&&t<5.2&&k%g===1)pt(R,t+.04,'Blocked')}t+=pp;k++}R.tm={vm,pm,pr};R.meta.rhy=`High-grade AV block (${g}:1)`;hl(R,['II'],'Two or more consecutive P waves not conducted; constant PR when conducted')};
GEN.isodiss=R=>{const r=R.r,hrs=r.r(56,64),hrj=hrs*r.r(1.02,1.06),vm=sinMorph(r,{qt:qtF(hrj)}),pm=nP(r);let t=r.r(.1,.4);while(t<DUR+.6){addV(R,t,vm);t+=60/hrj}let tp=r.r(-.1,.15);while(tp<DUR){addP(R,tp,pm,{cond:false});tp+=60/hrs}
  R.tm={vm,pm:null,pr:null};R.meta.rhy='Isorhythmic AV dissociation';R.meta.prq='none';hl(R,['II'],'P waves drift into and out of the QRS at a similar rate')};
GEN.ashman=R=>{const r=R.r,hr=r.r(90,120),rr=60/hr,vm=sinMorph(r,{qt:qtF(hr)}),ab=rbbbM(r,{qt:qtF(hr)});ab.kind='a';let t=-r.r(0,.4),i=0;
  while(t<DUR+.6){const isAb=(i===7||i===14);let d=Math.max(.34,rr*(.7+.6*r.u()));if(i===5||i===12)d=rr*1.6;if(i===6||i===13)d=Math.max(.3,rr*.52);addV(R,t,isAb?ab:vm);if(isAb&&t>.2&&t<9.8)pt(R,t,'Aberrant (Ashman)');t+=d;i++}
  fwaves(R,.06);R.opt.strip='V1';R.tm={vm,pm:null,pr:null};R.meta.rhy='Atrial fibrillation with Ashman aberrancy';R.meta.reg='irr';R.meta.prq='none';hl(R,['V1'],'RBBB-shaped beat ending a long–short cycle')};
GEN.altbbb=R=>{const r=R.r,hr=r.r(62,82),pr=r.r(.18,.22),a=rbbbM(r,{qt:qtF(hr,.43)}),b=lbbbM(r,{qt:qtF(hr,.45)}),pm=nP(r);R.opt.strip='V1';sinus(R,{hr,pr,vm:i=>i%2?b:a,pm});R.tm={vm:a,pm,pr};R.meta.rhy='Sinus rhythm with alternating bundle branch block';R.meta.noMeas=['axis'];hl(R,['V1'],'RBBB and LBBB shapes alternate')};
GEN.ivcd=R=>{const r=R.r,hr=r.r(62,85),pr=r.r(.15,.19),vm=V({axis:r.r(-10,40),s:1.42,amp:r.r(.9,1.05),z:-.35,qt:qtF(hr,.44),tA:.25,td:fv(150,.1)}),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm with intraventricular conduction delay';hl(R,['V1','V6','I'],'Wide QRS without a typical RBBB or LBBB shape')};
/* ---- pacing ---- */
GEN.aai=R=>{const r=R.r,hr=r.r(60,75),pr=r.r(.18,.22),vm=sinMorph(r,{qt:qtF(hr)}),pm=[spike(r.r(.6,1),nrm([.3,.85,.3])),...Pw('n',.12).map(b=>({...b,c:b.c+.015}))];sinus(R,{hr,pr,vm,pm,jit:.001});R.tm={vm,pm:null,pr:null};R.meta.rhy='Atrial paced rhythm';R.meta.paced=1;R.meta.prq='long';
  const b=beatNear(R,5);pt(R,b.t-pr,'Atrial spike');hl(R,['II'],'Spike before each P; narrow native QRS')};
GEN.crt=R=>{const r=R.r,hr=r.r(62,78),av=.12,vm=V({q:[spike(r.r(.6,1)),{sh:'sp',c:.008,A:.6,d:nrm([.7,.2,-.3])},{c:.042,wl:.022,A:1.05,d:nrm([-.65,.15,.72])},{c:.09,wl:.02,A:.45,d:nrm([-.3,.5,.6])}],qt:.42,stA:-.08,std:nrm([-.6,.2,.7]),t:[{c:.31,wl:.07,wr:.05,A:.35,d:nrm([.6,-.2,-.6])}],kind:'p'}),pm=nP(r);
  sinus(R,{hr,pr:av,vm,pm});R.tm={vm,pm,pr:av};R.meta.rhy='Biventricular (CRT) pacing';R.meta.paced=1;R.meta.prq='none';hl(R,['V1'],'Dominant R in V1 (LV lead activates first)');hl(R,['I'],'Negative or QS in I','b')};
GEN.undersense=R=>{const r=R.r,hrs=r.r(68,82),pr=.16,vm=sinMorph(r,{qt:qtF(hrs)}),pm=nP(r),pv=pacedM(r),sp={q:[spike(1)],st:[],t:[],loc:[],kind:'s'},iv=60/r.r(56,62);
  const ev=[];let tp=-r.r(0,.6);while(tp<DUR+.5){ev.push({t:tp+pr,k:'n',p:tp});tp+=60/hrs*(1+.01*r.n())}let ts=r.r(.1,.9);while(ts<DUR+.3){ev.push({t:ts,k:'s'});ts+=iv}ev.sort((a,b)=>a.t-b.t);
  let last=-9,nl=0;ev.forEach(e=>{const free=e.t-last>.3;if(e.k==='n'){const pi=addP(R,e.p,pm,{cond:free});if(free){addV(R,e.t,vm,pi);last=e.t}}else if(free){addV(R,e.t,pv);last=e.t}else{addV(R,e.t,sp);if(e.t>.2&&e.t<9.8&&nl++<2)pt(R,e.t,'Spike in refractory period: no capture')}});
  R.tm={vm,pm,pr};R.meta.rhy='Pacemaker undersensing (asynchronous spikes competing with sinus rhythm)';R.meta.paced=1;R.meta.reg='irr';R.meta.noMeas=['rate','pr','qtc','rhythm'];hl(R,['II'],'Spikes fire on their own schedule, ignoring native beats')};
GEN.oversense=R=>{const r=R.r,hr=r.r(65,72),iv=60/hr,vm=pacedM(r);let t=r.r(.2,.5);const p0=r.r(3,4.5),p1=p0+r.r(2,2.8);while(t<DUR+.5){if(t>p0&&t<p1){t+=iv;continue}addV(R,t,vm);t+=iv}
  const a=new Float32Array(N),m=bandNoise(r,25,120,1);for(let i=0;i<N;i++){const tt=i/FS;if(tt>p0-.3&&tt<p1)a[i]=m[i]*.12}R.ela.LA=a;span(R,p0,p1,'Pause: muscle noise sensed as beats, pacing inhibited');
  R.tm={vm,pm:null,pr:null};R.meta.rhy='Pacemaker oversensing (inhibition by myopotentials)';R.meta.paced=1;R.meta.prq='none';R.meta.noMeas=['rate','pr','qtc']};
GEN.pmt=R=>{const r=R.r,hr=r.r(118,128),vm=pacedM(r),pm=Pw('retro',.12);sinus(R,{hr,vm,jit:.001});R.ev.q.slice().forEach(q=>addP(R,q.t+.22,pm,{k:'r'}));R.tm={vm,pm:null,pr:null};R.meta.rhy='Pacemaker-mediated tachycardia';R.meta.paced=1;R.meta.prq='none';
  hl(R,['II','III','aVF'],'Retrograde P after each paced QRS triggers the next beat');hl(R,['V1'],'Paced at the upper rate limit','b')};
/* ---- structure and channelopathy ---- */
GEN.arvc=R=>{const r=R.r,hr=r.r(60,82),pr=r.r(.14,.18),vm=sinMorph(r,{qt:qtF(hr),loc:[{c:.072,wl:.018,A:-.12,lm:{V1:1,V2:.8,V3:.5}},{c:.106,wl:.006,A:.17,lm:{V1:1,V2:.9,V3:.6}},{c:.28,wl:.06,wr:.05,A:-.5,lm:{V1:.8,V2:1,V3:.8}}]}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['V1','V2','V3'],'Epsilon wave after the QRS; T inversion V1–V3')};
GEN.brugada2=R=>{const r=R.r,hr=r.r(58,80),pr=r.r(.15,.19),vm=sinMorph(r,{qt:qtF(hr),loc:[{c:.09,wl:.006,wr:.016,A:.14,lm:{V2:1,V1:.7}},{sh:'p',a:.08,ra:.012,b:.2,fb:.12,A:.13,lm:{V2:1,V1:.6}},{c:.31,wl:.05,wr:.045,A:.22,lm:{V2:1,V1:.4}}]}),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['V2'],'Saddleback: J point up, ST dips, T upright')};
GEN.shortqt=R=>{const r=R.r,hr=r.r(60,80),pr=r.r(.14,.17),qt=.27*Math.cbrt(60/hr),vm=V({axis:r.r(40,70),qt,tfix:1,twl:.038,twr:.03,tA:.75}),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';const b=beatNear(R,5);span(R,b.t,b.t+qt,'QT under 340 ms');hl(R,['V2','V3'],'Tall, peaked T with no ST segment')};
GEN.lqt3=R=>{const r=R.r,hr=r.r(48,60),pr=r.r(.15,.18),qt=r.r(.56,.6)*Math.cbrt(60/hr),vm=V({axis:r.r(40,70),qt,tfix:1,twl:.045,twr:.035,tA:.45}),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus bradycardia';const b=beatNear(R,5);span(R,b.t+.1,b.t+qt-.13,'Long isoelectric ST, late narrow T');hl(R,['II','V3'],'Late-onset, peaked T (LQT3 pattern)')};
GEN.apicalhcm=R=>{const r=R.r,hr=r.r(58,80),pr=r.r(.15,.18),qt=qtF(hr,.44),vm=V({axis:r.r(10,45),amp:r.r(1.5,1.8),z:-.5,qt,stA:-.08,std:nrm([.5,.3,.8]),t:[{c:qt-.11,wl:.06,wr:.055,A:-1.05,d:nrm([.5,.3,.8])}]}),pm=Pw('mitrale',.14);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['V2','V3','V4','V5'],'Giant T inversion (often over 10 mm)')};
GEN.amyloid=R=>{const r=R.r,af=r.chance(.35),hr=r.r(68,92),vm=V({axis:r.r(-20,30),amp:r.r(.28,.36),sep:0,xq:[{c:.022,wl:.012,A:.12,d:nrm([-.2,.05,-.95])}],qt:qtF(hr,.43),tA:.12}),pm=Pw('n',.09);
  if(af){irregular(R,hr,.6,1.4,()=>vm);fwaves(R,.03);R.tm={vm,pm:null,pr:null};R.meta.reg='irr';R.meta.prq='none';R.meta.rhy='Atrial fibrillation'}else{sinus(R,{hr,pr:.24,vm,pm});R.tm={vm,pm,pr:.24};R.meta.rhy='Sinus rhythm with first-degree AV block'}
  hl(R,['I','II','III','aVR','aVL','aVF'],'Low voltage despite thick walls on echo');hl(R,['V1','V2','V3'],'Pseudo-infarct QS pattern','b')};
GEN.asd=R=>{const r=R.r,hr=r.r(65,90),pr=r.r(.16,.21),vm=V({axis:r.r(95,115),xq:[{c:.08,wl:.011,A:.35,d:nrm([-.6,-.05,.78])}],term:.4,qt:qtF(hr),td:nrm([.55,.45,-.2]),loc:[{c:.036,wl:.004,A:-.12,lm:{II:1,III:1,aVF:1}}]}),pm=Pw('n',.17);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['V1'],'Incomplete RBBB (rSr′)');hl(R,['II','III','aVF'],'Notch near the R peak (crochetage); right axis','b')};
GEN.copd=R=>{const r=R.r,hr=r.r(92,112),pr=r.r(.13,.16),vm=V({axis:r.r(88,105),amp:r.r(.45,.55),maind:nrm([.2,.8,-.7]),sep:.6,qt:qtF(hr),tA:.22}),pm=Pw('pulm',.13);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus tachycardia';
  hl(R,['I','aVL','V5','V6'],'Low voltage, poor R-wave progression');hl(R,['II','III','aVF'],'Tall P waves (P pulmonale), rightward axis','b')};
GEN.cerebralT=R=>{const r=R.r,hr=r.r(46,60),pr=r.r(.15,.19),qt=r.r(.56,.62)*Math.cbrt(60/hr),d=nrm([.5,.35,.8]),vm=V({axis:r.r(40,70),qt,tfix:1,t:[{c:qt-.15,wl:.1,wr:.08,A:-.95,d}],uA:.12}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus bradycardia';hl(R,['V2','V3','V4','V5','V6','I','II'],'Giant, wide T inversion with very long QT')};
/* ---- normal variants ---- */
GEN.athlete=R=>{const r=R.r,hr=r.r(42,54),pr=r.r(.21,.25),ax=r.r(55,75),vm=V({axis:ax,amp:r.r(1.45,1.7),qt:qtF(hr,.4),tA:.6,td:fv(ax-10,.75),stA:.14,std:nrm([.25,.25,1]),stra:.07,xst:[{c:.088,wl:.006,wr:.012,A:.12,d:fv(ax,.25)}]}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm,resp:.06});R.tm={vm,pm,pr};R.meta.rhy='Sinus bradycardia with first-degree AV block';hl(R,['V2','V5','V6'],'High voltage with early repolarization: training-related');hl(R,['II'],'Slow rate, long PR: high vagal tone','b')};
GEN.child=R=>{const r=R.r,hr=r.r(100,125),pr=r.r(.1,.13),vm=V({axis:r.r(95,110),z:.25,amp:r.r(1,1.2),qt:qtF(hr,.4),td:nrm([.5,.6,-.3]),loc:[{c:.24,wl:.05,wr:.045,A:-.2,lm:{V1:1,V2:.9,V3:.5}}]}),pm=nP(r);
  sinus(R,{hr,pr,vm,pm,resp:.05});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm (age-appropriate rate)';hl(R,['V1','V2','V3'],'T inversion V1–V3: normal juvenile pattern');hl(R,['V1'],'Prominent R in V1: right-ventricular dominance of childhood','b')};
/* ---- electrolytes and drugs, staged ---- */
GEN.hyperk1=R=>{const r=R.r,hr=r.r(62,88),pr=r.r(.15,.18),vm=V({axis:r.r(40,70),qt:r.r(.36,.39),tfix:1,twl:.036,twr:.032,tA:r.r(.8,.95),td:fv(45,.8)}),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['V2','V3','V4','II'],'Narrow-based, symmetric, peaked T; everything else normal')};
GEN.hyperk3=R=>{const r=R.r,hr=r.r(38,52),vm=V({axis:r.r(30,70),s:1.85,qt:.44,tfix:1,twl:.04,twr:.035,tA:.9,td:fv(45,.7)});sinus(R,{hr,vm,jit:.008});R.tm={vm,pm:null,pr:null};R.meta.rhy='Slow wide-complex rhythm, no P waves';R.meta.prq='none';hl(R,['II','V2'],'No P waves, very wide QRS, peaked T')};
GEN.brash=R=>{const r=R.r,hr=r.r(32,44),vm=V({axis:r.r(40,70),qt:.44,tfix:1,twl:.04,twr:.035,tA:.7,td:fv(45,.7),s:1.1});sinus(R,{hr,vm,jit:.006});R.tm={vm,pm:null,pr:null};R.meta.rhy='Junctional bradycardia (BRASH)';R.meta.prq='none';hl(R,['II'],'Slow junctional rhythm, no P waves');hl(R,['V2','V3'],'Only moderately peaked T','b')};
GEN.hypok2=R=>{const r=R.r,hr=r.r(70,95),rr=60/hr,pr=r.r(.16,.2),qt=r.r(.38,.41),vm=V({axis:r.r(40,70),qt,tfix:1,tA:.05,uA:r.r(.28,.34),stA:-.12,std:fv(55,.5)}),pm=Pw('n',.2),pv=V({q:[{c:.05,wl:.03,A:1.3,d:nrm([.15,.85,-.5])},{c:.112,wl:.025,A:.7,d:nrm([.45,.6,-.65])}],qt:.43,t:[{c:.33,wl:.075,wr:.05,A:.5,d:nrm([-.3,-.75,.55])}],kind:'v'});
  let t=r.r(.2,.5),k=0;while(t<DUR+.6){const pi=addP(R,t-pr,pm);addV(R,t,vm,pi);if(k%3===2){addV(R,t+rr*.62,pv);t+=2*rr}else t+=rr;k++}R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm with PVCs';R.meta.reg='regirr';R.meta.uw=1;hl(R,['V2','V3'],'Large U waves, T almost absent');hl(R,['II','V5'],'ST depression; frequent PVCs','b')};
GEN.hypomg=R=>{const r=R.r,hr=r.r(62,80),rr=60/hr,pr=r.r(.15,.19),qt=r.r(.5,.54)*Math.cbrt(60/hr),vm=V({axis:r.r(40,70),qt,tA:.36,twl:.11,twr:.06,uA:.16}),pm=nP(r),pv=V({q:[{c:.05,wl:.03,A:1.3,d:nrm([-.3,.75,.6])},{c:.12,wl:.028,A:.6,d:nrm([-.5,.3,.65])}],qt:.42,t:[{c:.31,wl:.075,wr:.05,A:.45,d:nrm([.4,-.6,-.6])}],kind:'v'});
  let t=r.r(.2,.5),k=0;while(t<DUR+.6){const pi=addP(R,t-pr,pm);addV(R,t,vm,pi);if(k===4){const tv=t+qt*.92;addV(R,tv,pv);pt(R,tv,'R-on-T PVC');t+=2*rr}else t+=rr;k++}R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm with a PVC';R.meta.reg='irr';hl(R,['II','V3'],'Long QT with broad T and U')};
GEN.renal=R=>{const r=R.r,hr=r.r(68,90),pr=r.r(.17,.21),qt=r.r(.48,.52)*Math.cbrt(60/hr),vm=V({axis:r.r(0,35),amp:r.r(1.4,1.6),z:-.55,qt,tfix:1,twl:.036,twr:.032,tA:.85,td:fv(40,.8)}),pm=Pw('mitrale',.13);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';
  const b=beatNear(R,5);span(R,b.t+.1,b.t+qt-.12,'Long ST segment (low Ca²⁺)');hl(R,['V2','V3','V4'],'Peaked, narrow T (high K⁺)');hl(R,['V1','V5'],'LVH voltage','b')};
GEN.digtox=R=>{const r=R.r,hr=r.r(48,60),ax=r.r(40,70),vm=V({axis:ax,qt:.34,tfix:1,tA:.12,twl:.05,twr:.04,xst:[{c:.17,wl:.06,wr:.05,A:.17,d:neg(fv(ax,-.25))}]});sinus(R,{hr,vm,jit:.002});fwaves(R,.05);R.tm={vm,pm:null,pr:null};R.meta.rhy='Atrial fibrillation with a regular junctional rhythm ("regularized AF")';R.meta.prq='none';R.meta.reg='reg';
  hl(R,['V1'],'Fibrillatory baseline');hl(R,['II'],'But the ventricular rhythm is perfectly regular: complete block with junctional escape','b')};
/* ---- technical ---- */
GEN.v1v2high=R=>{const r=R.r,hr=r.r(62,88),pr=r.r(.14,.18),vm=sinMorph(r,{qt:qtF(hr)}),pm=nP(r);R.opt.pv={V1:nrm([-.32,-.5,.8]),V2:nrm([-.05,-.5,.86])};sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';hl(R,['V1','V2'],'Negative P, rSr′, T inversion: electrodes too high')};
GEN.lallrev=R=>{const r=R.r,hr=r.r(62,88),pr=r.r(.14,.18),vm=sinMorph(r,{qt:qtF(hr)}),pm=nP(r);R.opt.swap=['LA','LL'];sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm (LA/LL reversed)';hl(R,['III'],'Lead III inverted');hl(R,['I','II'],'P wave taller in I than in II','b')};
GEN.rarl=R=>{const r=R.r,hr=r.r(62,88),pr=r.r(.14,.18),vm=sinMorph(r,{qt:qtF(hr)}),pm=nP(r);R.opt.swap=['RA','RL'];sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm (RA/RL reversed)';R.meta.noMeas=['axis'];hl(R,['II'],'Nearly flat line');hl(R,['aVR','aVF'],'Identical leads','b')};
GEN.cpr=R=>{const r=R.r,cr=r.r(100,118),A=new Float32Array(N),B=new Float32Array(N),C=new Float32Array(N),stop=r.r(6.2,7),m=bandNoise(r,.2,1,1);let ph=0;
  for(let i=0;i<N;i++){const t=i/FS;ph+=2*Math.PI*cr/60/FS;if(t<stop){const w=Math.pow(Math.max(0,Math.sin(ph)),1.6)*(1+.15*m[i]);A[i]=w*1.1;B[i]=-w*.7;C[i]=w*.4}}R.ela.RA=A;R.ela.LA=B;R.ela.LL=C;
  const vf=bandNoise(r,3.5,8,.12);addCont(R,vf,nrm([.3,.85,.35]));span(R,0,stop,'Compressions (about '+Math.round(cr)+'/min)');span(R,stop,DUR,'Pause for rhythm check');R.tm=null;R.meta.rhy='CPR artifact; fine VF during the pause';R.meta.noMeas=['rate','axis','qrs','pr','qtc'];R.meta.prq='none'};
GEN.tremor=R=>{const r=R.r,hr=r.r(64,84),pr=r.r(.14,.18),vm=sinMorph(r,{qt:qtF(hr)}),pm=nP(r);sinus(R,{hr,pr,vm,pm});const a=new Float32Array(N),f=r.r(4.6,5.6),m=bandNoise(r,.2,1,1);for(let i=0;i<N;i++)a[i]=.22*(1+.25*m[i])*Math.sin(2*Math.PI*f*i/FS);R.ela.LA=a;
  R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm with tremor artifact';hl(R,['I','III','aVL'],'Regular 4–6 Hz oscillation resembling flutter waves');hl(R,['II','V1'],'Sinus P waves visible where the artifact is absent','b')};
GEN.tcp=R=>{const r=R.r,hr=r.r(68,78),iv=60/hr,cap=V({q:[{c:.05,wl:.032,A:1.3,d:nrm([.3,-.6,-.6])},{c:.115,wl:.03,A:.75,d:nrm([.5,-.4,-.7])}],qt:.44,t:[{c:.33,wl:.08,wr:.05,A:.5,d:nrm([-.35,.6,.6])}],kind:'p'}),art={c:.012,wl:.004,wr:.035,A:1.4,d:nrm([.6,.5,.6])},spk={q:[spike(2.5,nrm([.6,.5,.6])),art],st:[],t:[],loc:[],kind:'s'};
  const capQ={...cap,q:[spike(2.5,nrm([.6,.5,.6])),art,...cap.q]};const t1=r.r(3.2,4.6);let t=r.r(.2,.5);while(t<DUR+.5){addV(R,t,t<t1?spk:capQ);t+=iv}const e1=R.ev.q.find(q=>q.t>.4),e2=R.ev.q.find(q=>q.t>t1);if(e1&&e1.t<t1)pt(R,e1.t,'Spike, no capture');if(e2)pt(R,e2.t,'Capture: wide QRS and T');
  R.tm={vm:cap,pm:null,pr:null};R.meta.rhy='Transcutaneous pacing: loss then gain of capture';R.meta.paced=1;R.meta.prq='none';R.meta.noMeas=['rate','pr','qtc','axis']};
GEN.flec=R=>{const r=R.r,hr=r.r(48,66),pr=r.r(.25,.32),vm=V({axis:r.r(-10,40),s:r.r(1.5,1.7),qt:qtF(hr,.46),tA:.28,loc:[{c:.13,wl:.008,wr:.06,A:.2,lm:{V1:1,V2:.8}}]}),pm=Pw('n',.12);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus bradycardia with first-degree AV block';
  hl(R,['II','V1','V5'],'Long PR and wide QRS: slowed conduction everywhere');hl(R,['V1','V2'],'Brugada-like coved ST','b')};
GEN.wraplad=R=>{const r=R.r,hr=r.r(78,104),pr=r.r(.13,.17),vm=corMorph(occSegs('mLAD','right',true),occStage(r.r(60,200),null),qtF(hr,.41)),pm=nP(r);sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';R.autoST=1};
GEN.pacedmi=R=>{const r=R.r,hr=r.r(64,80),vm=pacedM(r);vm.st.push({sh:'p',a:.14,ra:.03,b:.3,fb:.12,A:.38,d:nrm([.82,-.55,-.15])});sinus(R,{hr,pr:.16,vm,pm:nP(r)});R.tm={vm,pm:nP(r),pr:.16};R.meta.rhy='Atrial-sensed, ventricular-paced rhythm';R.meta.paced=1;R.meta.prq='normal';
  hl(R,['I','aVL'],'Concordant ST elevation (same direction as the paced QRS)');hl(R,['III','aVF'],'Reciprocal depression','b')};
GEN.vswap=R=>{const r=R.r,hr=r.r(62,88),pr=r.r(.14,.18),vm=sinMorph(r,{qt:qtF(hr)}),pm=nP(r);R.opt.pv={V2:PV.V4.d,V4:PV.V2.d};sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm (V2 and V4 cables swapped)';hl(R,['V2','V3','V4'],'R wave rises, falls, then rises again: progression breaks')};
