
/* ============ pattern catalogue ============ */
const CAT={normal:"Normal & variants",rhythm:"Rhythms & ectopy",cond:"Conduction & blocks",pace:"Pacing & devices",isch:"Ischemia & infarction",struct:"Chamber & structure",chan:"Channelopathies & cardiomyopathies",meta:"Electrolytes, drugs & temperature",mimic:"Mimics & technical"};
const CULPRIT=["Proximal LAD (before the first diagonal)","Right coronary artery","Left circumflex (or obtuse marginal)","First diagonal / high lateral branch","Left main or multivessel disease"];
const P=[
/* ---- normal & variants ---- */
{id:"nsr",cat:"normal",name:"Normal sinus rhythm",
 feats:["Rate 60–100, regular","Upright P in I and II, negative in aVR, before every QRS","PR 120–200 ms and constant; QRS under 110 ms","Axis −30° to +90°; R-wave transition by V3–V4","ST segments at baseline; T upright where the QRS is upright (aVR, often V1 and III excepted)"],
 sig:"The reference everything else is judged against. A normal ECG does not exclude ACS, PE or a channelopathy, and a single tracing can miss dynamic change. Compare with prior ECGs and repeat when symptoms change.",
 hints:["Check for a P before every QRS and a QRS after every P.","Is any interval or axis outside normal limits?"],sim:["sarr","sbrady","stach","erp"],
 vs:{sarr:"Sinus arrhythmia has the same P waves but R–R intervals that lengthen and shorten with breathing (variation over 120 ms).",erp:"Early repolarization adds J-point notching and concave ST elevation, usually in V2–V5."}},
{id:"sarr",cat:"normal",name:"Sinus arrhythmia",
 feats:["Identical sinus P waves with a constant PR","R–R varies phasically by more than 120 ms","Rate speeds with inspiration and slows with expiration","Otherwise normal ECG"],
 sig:"Normal, most pronounced in the young and fit, and a sign of healthy vagal tone. Loss of respiratory variation is more worrying than its presence. Non-respiratory (ventriculophasic) sinus arrhythmia occurs in high-grade AV block.",
 hints:["Measure several R–R intervals: do they cycle?","Does the P wave ever change shape?"],sim:["nsr","af","pac","mat"],
 vs:{af:"AF has no P waves at all; sinus arrhythmia has a normal P before every QRS.",pac:"A PAC is one early beat with a different P; sinus arrhythmia changes gradually and the P never changes shape.",mat:"MAT has at least three different P-wave shapes and a rate over 100."}},
{id:"erp",cat:"normal",name:"Benign early repolarization",
 feats:["J-point notching or slurring at the end of the QRS (lateral and inferior leads)","Concave (“smiley”) ST elevation, usually under 2 mm, most in V2–V5","Tall, broad T waves in proportion to the QRS","No reciprocal ST depression except aVR","Often young, fit, bradycardic, with high precordial voltage"],
 sig:"Common and usually benign, but a diagnosis of exclusion in chest pain: compare with old ECGs, look for reciprocal change, terminal QRS distortion and evolution. An inferolateral J-wave pattern with horizontal or descending ST segments carries a small association with ventricular arrhythmia.",
 hints:["Look at the end of the QRS in the lateral leads.","Is there any reciprocal ST depression?"],sim:["peric","antstemi","brugada","nsr"],
 vs:{peric:"Pericarditis has widespread ST elevation with PR depression, often tachycardia, and an ST/T ratio in V6 above 0.25.",antstemi:"Anterior STEMI has reciprocal inferior depression, straighter or convex ST segments, larger T waves relative to the QRS, and evolves on serial tracings.",brugada:"Brugada type 1 is coved and confined to V1–V2, falling into an inverted T."}},
/* ---- rhythms ---- */
{id:"sbrady",cat:"rhythm",name:"Sinus bradycardia",
 feats:["Sinus P waves before every QRS","Rate under 60 (under 50 in some newer definitions)","Normal PR and narrow QRS","Regular"],
 sig:"Normal in sleep and athletes. Pathologic causes include beta-blockers, calcium-channel blockers, digoxin, amiodarone, hypothyroidism, hypothermia, raised intracranial pressure, inferior MI (the RCA supplies the SA node in about 60%) and sick sinus syndrome. Symptoms and perfusion decide treatment, not the number.",
 hints:["Count big boxes between R waves (300 ÷ boxes).","Is there a P before every QRS?"],sim:["junct","avb21","avb3","hypothermia"],
 vs:{junct:"Junctional rhythm lacks a normal upright P (absent or retrograde), at 40–60.",avb21:"In 2:1 AV block, a second P hides between QRS complexes; march out the P waves.",avb3:"Complete heart block has P waves marching through at their own faster rate, with no fixed PR."}},
{id:"stach",cat:"rhythm",name:"Sinus tachycardia",
 feats:["Sinus P waves (upright in II) before every QRS","Rate over 100, rarely above 150 at rest (maximum about 220 − age)","At fast rates the P may merge with the preceding T","Gradual onset and offset; rate drifts over time"],
 sig:"Almost always a response: pain, fever, hypovolemia, hypoxia, sepsis, anemia, PE, thyrotoxicosis, stimulants or withdrawal. Treat the cause; slowing a compensatory tachycardia can be harmful.",
 hints:["Can you find a P wave for every QRS?","Is the rate fixed or drifting?"],sim:["svt","flutter","af","mat"],
 vs:{svt:"AVNRT starts and stops abruptly, usually 150–250, is metronomic, and has no visible P before the QRS (look for a pseudo r′ in V1).",flutter:"Flutter with 2:1 block runs near 150 with a flutter wave hidden in the T; look for a second “P” in the inferior leads or V1.",mat:"MAT has at least three P-wave shapes and an irregular rhythm."}},
{id:"af",cat:"rhythm",name:"Atrial fibrillation",
 feats:["Irregularly irregular R–R intervals","No P waves; chaotic fibrillatory baseline (best seen in V1)","Narrow QRS unless aberrancy or pre-existing block","Ventricular rate set by AV-node conduction (rapid ventricular response if over 100)"],
 sig:"The commonest sustained arrhythmia. Key questions: stability, rate, duration (48 hours or unknown raises embolic risk with cardioversion), anticoagulation, and triggers (sepsis, thyrotoxicosis, alcohol, PE). An irregular wide-complex tachycardia over 250 suggests pre-excited AF: avoid AV-nodal blockers.",
 hints:["Measure several R–R intervals: is there any pattern?","Look at V1 for organized atrial activity."],sim:["flutter","mat","sarr","pac"],
 vs:{flutter:"Flutter has regular sawtooth waves near 300/min and usually a regular or patterned ventricular response.",mat:"MAT has a discrete P before each QRS, in at least three shapes.",sarr:"Sinus arrhythmia has a normal P wave before every QRS."}},
{id:"flutter",cat:"rhythm",name:"Atrial flutter",
 feats:["Sawtooth flutter (F) waves at 250–350/min with no flat baseline between them","Typical (counterclockwise) flutter: negative F waves in II, III, aVF; positive in V1","Fixed block (2:1 gives a ventricular rate near 150) or variable block","Narrow QRS"],
 sig:"A regular narrow-complex tachycardia at 150 is flutter with 2:1 block until proven otherwise. Vagal maneuvers or adenosine increase the block and unmask F waves. Manage stroke risk as for AF; typical flutter is highly curable by cavotricuspid isthmus ablation.",
 hints:["Look at the inferior leads for a sawtooth baseline.","What is the atrial rate?"],sim:["af","svt","stach","mat"],
 vs:{af:"AF has no organized atrial waves and a completely irregular ventricular rhythm.",svt:"AVNRT has no atrial waves between QRS complexes; flutter waves continue through the ST and TP segments.",stach:"Sinus tachycardia has one discrete P before each QRS with a flat baseline."}},
{id:"svt",cat:"rhythm",name:"Supraventricular tachycardia (AVNRT)",
 feats:["Regular narrow-complex tachycardia, usually 150–250/min","No P waves before the QRS","Retrograde P at the end of the QRS: pseudo r′ in V1, pseudo S in II, III, aVF","Abrupt onset and offset; rate-related ST depression is common"],
 sig:"Re-entry within the AV node (AVNRT) or via an accessory pathway (orthodromic AVRT). Modified Valsalva then adenosine terminate most episodes; synchronized cardioversion if unstable. ST depression during SVT does not reliably indicate coronary disease.",
 hints:["Is the rhythm perfectly regular?","Look at the end of the QRS in V1."],sim:["stach","flutter","af","vt"],
 vs:{stach:"Sinus tachycardia has visible P waves before each QRS and rarely exceeds 150 at rest.",flutter:"Flutter waves continue between complexes at about 300/min, often visible in II, III, aVF.",vt:"VT is wide (QRS 120 ms or more) with AV dissociation, fusion or capture beats."}},
{id:"mat",cat:"rhythm",name:"Multifocal atrial tachycardia",
 feats:["Rate over 100","At least three different P-wave shapes","Varying PR, P–P and R–R intervals (irregularly irregular)","Flat baseline between P waves"],
 sig:"Typically severe lung disease, hypoxia, low magnesium or potassium, theophylline or sepsis. Treat the cause and correct electrolytes. Cardioversion does not work.",
 hints:["Compare the P waves in front of each QRS.","Is there a flat baseline between beats?"],sim:["af","stach","pac","sarr"],
 vs:{af:"AF has no discrete P waves; MAT has a distinct P before each QRS, of varying shape.",pac:"PACs are occasional early beats on a sinus rhythm with one P shape.",stach:"Sinus tachycardia has a single, uniform P morphology."}},
{id:"junct",cat:"rhythm",name:"Junctional rhythm",
 feats:["Narrow QRS at 40–60/min (accelerated junctional 60–100)","P waves absent, or retrograde: inverted in II, III, aVF","A retrograde P may sit just before the QRS (PR under 120 ms), hide inside it, or follow it","Regular"],
 sig:"An escape rhythm when the sinus node fails (sick sinus, drugs, inferior MI, hypothermia), or an accelerated rhythm in digoxin toxicity, myocarditis or after cardiac surgery. Review medications and look for sinus node disease.",
 hints:["Where are the P waves, and which way do they point in II?"],sim:["sbrady","avb3","sarr","pac"],
 vs:{sbrady:"Sinus bradycardia has an upright P in II with a normal PR.",avb3:"In complete heart block, sinus P waves continue at a faster rate, dissociated from the escape rhythm."}},
{id:"pac",cat:"rhythm",name:"Premature atrial complexes",
 feats:["Early beat preceded by a P wave that differs from the sinus P","QRS usually identical to sinus (may be aberrant or blocked if very early)","Non-compensatory pause: the sinus node resets","Underlying sinus rhythm"],
 sig:"Very common and usually benign: caffeine, alcohol, stress, stimulants, structural heart disease. Frequent PACs predict later AF. A blocked PAC hidden in a T wave is a common cause of an unexplained pause.",
 hints:["Which beats come early?","Compare the P before the early beat with the others."],sim:["pvc","sarr","mat","wenck"],
 vs:{pvc:"A PVC is wide and bizarre with no P and is usually followed by a full compensatory pause.",sarr:"Sinus arrhythmia changes gradually with breathing and keeps one P shape.",wenck:"In Wenckebach, the P that fails to conduct is on time and the PR lengthens first."}},
{id:"pvc",cat:"rhythm",name:"Premature ventricular complexes (bigeminy)",
 feats:["Every other beat is a wide (120 ms or more), bizarre QRS without a preceding P","ST-T discordant to the PVC","Full compensatory pause (the sinus P still fires, hidden in the PVC)","One morphology suggests a single focus"],
 sig:"Often benign in a structurally normal heart (outflow-tract origin: LBBB pattern with inferior axis, as here). Concerning: frequent or multiform PVCs, R-on-T, couplets or runs, structural disease, ischemia, electrolyte disturbance or long QT. A high burden (over 10–15%) can cause cardiomyopathy. Pulse oximeters may count bigeminy at half rate.",
 hints:["Look at alternate beats.","Is there a P before the wide beats?"],sim:["pac","vt","aivr","wpw"],
 vs:{pac:"A PAC has a P wave and usually a narrow QRS identical to sinus.",vt:"VT is three or more consecutive ventricular beats over 100/min.",aivr:"AIVR is a sustained run of wide beats at 50–110/min, not alternating with sinus."}},
{id:"vt",cat:"rhythm",name:"Monomorphic ventricular tachycardia",
 feats:["Wide (often over 140 ms), regular tachycardia at 120–250/min","AV dissociation: P waves march independently; capture and fusion beats prove it","Extreme (“northwest”) axis: dominant R in aVR","R/S under 1 in V6; precordial concordance also favors VT"],
 sig:"Treat any regular wide-complex tachycardia as VT, especially with structural heart disease or prior MI. Unstable: synchronized cardioversion; pulseless: defibrillate. Stable: procainamide or amiodarone and expert input. Verapamil given for presumed SVT can be lethal.",
 hints:["Look for P waves between complexes on the rhythm strip.","Check aVR and the axis."],sim:["svt","aivr","vpace","tdp"],
 vs:{svt:"SVT is narrow unless aberrant; aberrancy has a typical bundle-branch morphology and no AV dissociation.",aivr:"AIVR is wide but slow (50–110/min).",vpace:"Paced rhythms have a pacing spike before each QRS.",tdp:"Torsades is polymorphic with twisting amplitude and long QT on the surrounding beats."},
 q2:{q:"Which finding on this tracing proves the rhythm is ventricular?",opts:["A capture beat (AV dissociation)","QRS wider than 120 ms","Rate above 150","A regular rhythm"],a:0,why:"Capture and fusion beats show that the atria and ventricles are dissociated. Width, rate and regularity also occur in SVT with aberrancy."}},
{id:"tdp",cat:"rhythm",name:"Torsades de pointes",
 feats:["Polymorphic VT whose QRS amplitude and axis twist around the baseline","Rate 200–250","Marked QT prolongation on the sinus beats before it","Often triggered by an R-on-T beat after a long–short cycle; may self-terminate"],
 sig:"IV magnesium sulfate (2 g), defibrillation if sustained or pulseless, correct potassium and magnesium, stop QT-prolonging drugs, and raise the heart rate (isoproterenol or overdrive pacing) if bradycardia-dependent. Avoid amiodarone and procainamide, which lengthen the QT.",
 hints:["Look at the QT of the beats before the run.","Does the amplitude change in a pattern?"],sim:["vt","vf","artifact","lqt"],
 vs:{vt:"Monomorphic VT has identical beats.",vf:"VF has no organized complexes and no twisting pattern.",artifact:"Artifact spares at least one lead, and native QRS complexes march through it."},
 q2:{q:"First-line drug?",opts:["IV magnesium sulfate","Amiodarone","Procainamide","Adenosine"],a:0,why:"Magnesium suppresses the early afterdepolarizations that trigger torsades; amiodarone and procainamide prolong the QT further."}},
{id:"vf",cat:"rhythm",name:"Ventricular fibrillation",
 feats:["Chaotic deflections of varying amplitude and shape","No identifiable P waves, QRS complexes or T waves","Coarse VF degrades to fine VF over minutes","No pulse"],
 sig:"Cardiac arrest: CPR and immediate defibrillation, the single most time-critical intervention. Epinephrine after the second shock; amiodarone or lidocaine for refractory VF. Confirm the patient first: loose leads and movement can look identical.",
 hints:["Can you find a single organized QRS?"],sim:["tdp","artifact","vt","af"],
 vs:{tdp:"Torsades has organized complexes whose amplitude twists sinusoidally.",artifact:"Artifact spares some leads, and the patient has a pulse.",af:"AF has narrow, organized QRS complexes at irregular intervals."}},
{id:"aivr",cat:"rhythm",name:"Accelerated idioventricular rhythm",
 feats:["Wide QRS rhythm at 50–110/min","Regular, without preceding P waves (dissociated from the sinus rhythm)","Fusion beats at the hand-off between sinus and ventricular rhythm","Rate close to the sinus rate"],
 sig:"Classically a reperfusion rhythm after thrombolysis or PCI; also digoxin toxicity, cardiomyopathy and cocaine. Usually benign and self-limited. Do not suppress it with antiarrhythmics, because the underlying sinus rhythm is slower.",
 hints:["Compare the rate with VT.","Look for a fusion beat."],sim:["vt","avb3","pvc","vpace"],
 vs:{vt:"VT is faster than about 120/min.",avb3:"In complete heart block, the ventricular escape is slower (20–40) and the P waves are faster than the ventricles.",vpace:"Paced beats have a spike."}},
/* ---- conduction ---- */
{id:"avb1",cat:"cond",name:"First-degree AV block",
 feats:["PR interval over 200 ms","Constant PR; every P conducts","Usually narrow QRS (AV-nodal delay)","Regular sinus rhythm"],
 sig:"Usually benign: high vagal tone, athletes, AV-nodal drugs, inferior MI, Lyme carditis, rheumatic fever. A very long PR (over 300 ms) can cause symptoms through AV dyssynchrony. With a wide QRS the delay may be infranodal.",
 hints:["Measure from the start of the P to the start of the QRS."],sim:["nsr","wenck","avb21","hyperk"],
 vs:{wenck:"In Mobitz I the PR progressively lengthens until a P fails to conduct.",avb21:"In 2:1 block, every second P wave is not followed by a QRS."}},
{id:"wenck",cat:"cond",name:"Second-degree AV block, Mobitz I (Wenckebach)",
 feats:["PR progressively lengthens until a P wave is not conducted","Biggest PR increment is on the second conducted beat","R–R intervals shorten before the pause (grouped beating)","The PR after the pause is the shortest; QRS usually narrow"],
 sig:"The block is almost always in the AV node: usually benign (sleep, athletes, drugs, inferior MI) and rarely progresses. Atropine usually improves conduction. Wenckebach with a wide QRS, or with anterior MI, needs closer monitoring.",
 hints:["Compare the PR just before and just after the pause."],sim:["mob2","avb21","pac","avb1"],
 vs:{mob2:"In Mobitz II the PR is constant before and after the dropped beat.",pac:"A blocked PAC comes early with a different P; the dropped P in Wenckebach is on time.",avb21:"2:1 block cannot show progressive PR prolongation."},
 q2:{q:"Where is the block most likely?",opts:["AV node","His–Purkinje system (infranodal)","Sinoatrial node","Accessory pathway"],a:0,why:"Progressive PR prolongation is decremental AV-nodal conduction; infranodal tissue conducts all-or-none."}},
{id:"mob2",cat:"cond",name:"Second-degree AV block, Mobitz II",
 feats:["Constant PR in conducted beats","Sudden non-conducted P wave without prior PR lengthening","PR after the pause equals the PR before","Often a wide QRS (bundle-branch block): infranodal disease"],
 sig:"His–Purkinje disease with a real risk of sudden complete heart block. Atropine is unlikely to help and may worsen the block. Prepare transcutaneous pacing; most patients need a permanent pacemaker.",
 hints:["Is the PR the same before and after the pause?"],sim:["wenck","avb21","avb3","pac"],
 vs:{wenck:"In Mobitz I the PR lengthens before the drop and shortens after it.",avb3:"In complete block no P waves conduct and the PR varies at random."},
 q2:{q:"Where is the block most likely?",opts:["AV node","His–Purkinje system (infranodal)","Sinoatrial node","Accessory pathway"],a:1,why:"All-or-none failure with a constant PR, especially with a bundle-branch block, points below the AV node."}},
{id:"avb21",cat:"cond",name:"Second-degree AV block, 2:1",
 feats:["Every other P wave is not conducted","Conducted PR is constant","Atrial rate is twice the ventricular rate","Cannot be classed as Mobitz I or II from this strip alone"],
 sig:"Look for clues to the level: narrow QRS with a long PR favors the AV node; wide QRS with a normal PR favors infranodal disease. A longer strip showing 3:2 conduction may reveal the type. Atropine helps nodal block and can worsen infranodal block.",
 hints:["March out the P waves with calipers.","Is a P wave hiding in the T wave?"],sim:["wenck","mob2","sbrady","avb3"],
 vs:{sbrady:"Sinus bradycardia has one P per QRS; look for a second P halfway between beats.",avb3:"In complete heart block the PR changes from beat to beat."}},
{id:"avb3",cat:"cond",name:"Third-degree (complete) AV block",
 feats:["P waves at a regular atrial rate, unrelated to the QRS complexes (AV dissociation)","Regular escape rhythm slower than the atrial rate","Junctional escape: narrow, 40–60; ventricular escape: wide, 20–40","PR varies at random; P waves land anywhere, including in the QRS or T"],
 sig:"Unstable or wide-escape complete heart block needs pacing and usually a permanent pacemaker. Consider reversible causes: inferior MI (often nodal and transient), hyperkalemia, AV-nodal drugs, Lyme disease. Atropine may help nodal block but often fails with a wide escape.",
 hints:["March out the P waves; then march out the QRS complexes."],sim:["avb21","mob2","sbrady","aivr"],
 vs:{avb21:"In 2:1 block, every second P conducts with a constant PR.",mob2:"In Mobitz II most P waves conduct with a constant PR."},
 q2:{q:"Where does the escape rhythm on this tracing arise?",opts:["AV junction (narrow QRS, 40–60/min)","Ventricle (wide QRS, 20–40/min)"],a:R=>/ventricular/.test(R.meta.rhy)?1:0,why:"Narrow escape complexes arise above the bifurcation of the His bundle; wide, slow ones arise in the ventricle and are less reliable."}},
{id:"rbbb",cat:"cond",name:"Right bundle branch block",
 feats:["QRS 120 ms or more","rsR′ (“M” or rabbit ears) in V1–V2","Wide, slurred S wave in I, aVL and V6","Secondary T inversion in V1–V3, discordant to the terminal R′"],
 sig:"Common and often benign in isolation. New RBBB can accompany PE, proximal LAD occlusion, myocarditis or right heart strain. RBBB does not hide STEMI: read the ST segments as usual. Look for a coexisting fascicular block.",
 hints:["Look at V1 and the terminal part of the QRS in I and V6."],sim:["lbbb","bifasc","brugada","wpw"],
 vs:{lbbb:"LBBB has a deep QS or rS in V1 and broad monophasic R waves in I and V6.",brugada:"Brugada has coved ST elevation in V1–V2 without a wide S wave in I and V6.",wpw:"WPW has a short PR and an initial delta wave."}},
{id:"lbbb",cat:"cond",name:"Left bundle branch block",
 feats:["QRS 120 ms or more (Strauss: 130 women, 140 men, with mid-QRS notching)","Broad notched or slurred R in I, aVL, V5–V6 with no septal q waves","Deep QS or rS in V1–V2","Discordant ST-T: elevation in V1–V3; depression and T inversion in I, aVL, V5–V6"],
 sig:"Usually means underlying heart disease (hypertension, cardiomyopathy, ischemia, aortic stenosis). In suspected ACS apply Sgarbossa or Smith-modified criteria; new LBBB alone is no longer treated as a STEMI equivalent.",
 hints:["Is there a septal q in I or V6?","Look at V1."],sim:["rbbb","vpace","lvh","sgarb"],
 vs:{rbbb:"RBBB has rsR′ in V1 and a wide S in I and V6.",vpace:"A paced rhythm has a spike before each QRS.",lvh:"LVH has tall voltage but a QRS under 120 ms, with septal q waves preserved.",sgarb:"LBBB with acute occlusion shows ST deviation in the same direction as the QRS, or excessive discordance."}},
{id:"lafb",cat:"cond",name:"Left anterior fascicular block",
 feats:["Left axis deviation, −45° to −90°","qR in I and aVL; rS in II, III, aVF","QRS under 120 ms","Late R-wave peak in aVL (45 ms or more)"],
 sig:"The commonest fascicular block: hypertension, coronary disease, aortic valve disease, age. No treatment on its own; with RBBB it forms bifascicular block. LAFB shrinks inferior R waves and can mimic or mask inferior MI.",
 hints:["Work out the axis from I, II and aVF."],sim:["lpfb","oldimi","bifasc","lvh"],
 vs:{lpfb:"LPFB gives right axis deviation with rS in I and qR in III.",oldimi:"Inferior MI gives Q waves (qR or QS) in II, III, aVF; LAFB starts with a small r (rS)."}},
{id:"lpfb",cat:"cond",name:"Left posterior fascicular block",
 feats:["Right axis deviation, +90° to +180°","rS in I and aVL; qR in II, III, aVF","QRS under 120 ms","A diagnosis of exclusion: rule out RVH, lateral MI, PE and lead reversal"],
 sig:"Rare in isolation because the posterior fascicle is broad with a dual blood supply, so it implies substantial conduction disease. With RBBB it is a bifascicular block with real risk of progression.",
 hints:["Is the axis rightward, and is there another cause for it?"],sim:["lafb","rvh","pe","lrrev"],
 vs:{rvh:"RVH has a dominant R in V1 and right atrial enlargement.",pe:"PE gives sinus tachycardia, S1Q3T3 and T inversion V1–V4.",lrrev:"Arm-lead reversal inverts P, QRS and T in lead I."}},
{id:"bifasc",cat:"cond",name:"Bifascicular block (RBBB + LAFB)",
 feats:["RBBB: QRS 120 ms or more, rsR′ in V1, wide S in I and V6","LAFB: left axis deviation (−45° to −90°) with rS in II, III, aVF","With first-degree AV block it is often called “trifascicular” (more accurately bifascicular block plus PR prolongation)"],
 sig:"Disease of two of the three fascicles. Progression in asymptomatic patients is slow, but syncope with bifascicular block warrants evaluation for intermittent complete heart block (monitoring, EP study, often a pacemaker).",
 hints:["Check V1, then the axis."],sim:["rbbb","lafb","lbbb","mob2"],
 vs:{rbbb:"Isolated RBBB has a normal axis.",lafb:"Isolated LAFB has a narrow QRS."}},
{id:"wpw",cat:"cond",name:"Wolff–Parkinson–White pattern",
 feats:["Short PR (under 120 ms)","Delta wave: slurred initial upstroke of the QRS","QRS widened (over 110 ms)","Secondary ST-T changes; delta polarity can mimic Q waves or RBBB"],
 sig:"An accessory pathway bypasses the AV node. Risks: AVRT, and AF conducted rapidly down the pathway (irregular, wide, very fast, can degenerate to VF). In pre-excited AF avoid AV-nodal blockers; use procainamide or cardioversion. Ablation is curative.",
 hints:["Measure the PR and look at the start of the QRS."],sim:["rbbb","avb1","lbbb","poststemi"],
 vs:{rbbb:"RBBB has a normal PR and terminal (not initial) slurring.",poststemi:"Posterior MI has a normal PR, no delta wave and ST depression in V1–V3."},
 q2:{q:"If this patient develops AF, which treatment is dangerous?",opts:["AV-nodal blockers (adenosine, verapamil, diltiazem, beta-blockers)","Procainamide","Synchronized cardioversion","Ablation of the accessory pathway"],a:0,why:"Blocking the AV node leaves the accessory pathway as the only route, allowing extremely rapid ventricular rates and VF."}},
{id:"vpace",cat:"pace",name:"Paced rhythm",
 feats:["Pacing spike immediately before each QRS","Wide QRS (120 ms or more) with an LBBB-like shape from right-ventricular pacing","Superior axis with RV apical pacing (negative II, III, aVF)","Discordant ST-T; sensed P waves or atrial spikes may precede it"],
 sig:"Expected discordance makes ischemia hard to read; modified Sgarbossa criteria apply to RV-paced rhythms. Check capture, sensing and the programmed rate. Bipolar spikes are small and are easily lost with the 40 Hz monitor filter.",
 hints:["Look just before the QRS."],sim:["lbbb","vt","fcap","aivr"],
 vs:{lbbb:"LBBB has no spikes and usually a normal or left axis.",fcap:"Failure to capture shows spikes without a following QRS."}},
{id:"fcap",cat:"pace",name:"Pacemaker failure to capture",
 feats:["Pacing spikes not followed by a QRS","Captured beats are wide and paced","Pauses filled by slow native escape beats","Spikes at the programmed interval"],
 sig:"Lead dislodgement or fracture, rising threshold (MI, hyperkalemia, acidosis, drugs), battery depletion or programming. If symptomatic, transcutaneous pacing and device interrogation. Contrast with undersensing (spikes in the wrong place) and oversensing (missing spikes).",
 hints:["Is every spike followed by a QRS?"],sim:["vpace","mob2","avb3","artifact"],
 vs:{vpace:"In a normally functioning paced rhythm, every spike captures.",mob2:"Mobitz II drops QRS complexes after P waves, not after pacing spikes."}},
/* ---- ischemia & infarction ---- */
{id:"antstemi",cat:"isch",name:"Anterior STEMI (proximal LAD)",
 feats:["ST elevation in V1–V4 (often V5–V6) with hyperacute T waves","ST elevation in I and aVL: occlusion above the first diagonal","Reciprocal ST depression in III and aVF","Loss of septal r waves (QS in V1–V3) as infarction evolves"],
 sig:"Activate the cath lab. Thresholds: 1 mm in two contiguous leads, except V2–V3 (2 mm men 40 and over, 2.5 mm men under 40, 1.5 mm women). Proximal LAD occlusion threatens a large territory with high risk of shock and VF.",
 hints:["Which contiguous leads are elevated?","Where is the reciprocal depression?"],sim:["latstemi","lvan","erp","dewinter"],
 vs:{lvan:"LV aneurysm has QS waves with ST elevation but small T waves (T/QRS under 0.36) and does not evolve.",erp:"Early repolarization lacks reciprocal depression and has concave ST segments with J-point notching.",latstemi:"Lateral STEMI involves I, aVL and V5–V6 and spares V1–V3."},
 q2:{q:"Most likely culprit artery?",opts:CULPRIT.slice(0,4),a:0,why:"Elevation spans V1–V4 plus I and aVL (the first diagonal's territory), with inferior reciprocal depression: occlusion before the first diagonal."}},
{id:"infstemi",cat:"isch",name:"Inferior STEMI",
 feats:["ST elevation in II, III and aVF, with III greater than II","Reciprocal ST depression in aVL (and I)","Hyperacute T waves inferiorly","Watch for bradycardia and AV block (the RCA usually supplies the AV node)"],
 sig:"RCA in about 80%. III over II with depression in I suggests RCA; isoelectric or elevated I and aVL suggest circumflex. Record V4R: 1 mm elevation means RV infarction (preload dependent, avoid nitrates). Depression in V1–V3 suggests posterior extension.",
 hints:["Compare III with II.","Which lead shows the reciprocal change?"],sim:["peric","poststemi","oldimi","erp"],
 vs:{peric:"Pericarditis has diffuse elevation without reciprocal depression (except aVR) and PR depression.",oldimi:"An old inferior MI has Q waves with isoelectric ST segments."},
 q2:{q:"Most likely culprit artery?",opts:CULPRIT.slice(0,4),a:1,why:"Elevation greater in III than II with reciprocal depression in I and aVL points to the right coronary artery."}},
{id:"latstemi",cat:"isch",name:"Lateral STEMI",
 feats:["ST elevation in I, aVL, V5 and V6","Reciprocal ST depression in III and aVF","V1–V3 spared","High-lateral elevation may be small because the QRS in aVL is small"],
 sig:"Usually circumflex, obtuse marginal or first diagonal occlusion. Circumflex infarcts are the most often electrically subtle; small elevation in aVL with inferior reciprocal depression should raise suspicion. Posterior leads help.",
 hints:["Which leads look at the lateral wall?","Any inferior reciprocal change?"],sim:["antstemi","poststemi","lvh","peric"],
 vs:{antstemi:"Anterior STEMI elevates V1–V4.",lvh:"LVH strain gives lateral depression, not elevation."},
 q2:{q:"Most likely culprit artery?",opts:CULPRIT.slice(0,4),a:2,why:"Lateral elevation (I, aVL, V5–V6) sparing the anterior leads fits the circumflex or an obtuse marginal branch; a first diagonal is the alternative."}},
{id:"poststemi",cat:"isch",name:"Posterior STEMI",
 feats:["Horizontal ST depression in V1–V3 (deepest V2–V3)","Tall, broad R waves in V1–V2 (R/S over 1 in V2)","Upright T waves in V1–V3","Confirm with posterior leads V7–V9 (0.5 mm elevation)"],
 sig:"An occlusion-MI equivalent: the anterior leads see the posterior wall from the front, so elevation appears as depression. Usually circumflex or a dominant RCA, often with inferior or lateral STEMI. Treat as STEMI when posterior leads or the clinical picture confirm it.",
 hints:["Imagine V1–V3 upside down."],sim:["avr","rvh","wpw","latstemi"],
 vs:{avr:"Diffuse subendocardial ischemia depresses many leads (I, II, V4–V6) with aVR elevation, not just V1–V3.",rvh:"RVH has right axis deviation and T inversion in V1–V3.",wpw:"WPW has a short PR and a delta wave."},
 q2:{q:"Most likely culprit artery?",opts:CULPRIT.slice(0,4),a:2,why:"The posterior (inferobasal) wall is usually supplied by the circumflex, or by a dominant RCA."}},
{id:"dewinter",cat:"isch",name:"de Winter T waves",
 feats:["Upsloping ST depression of 1–3 mm at the J point in the precordial leads","Tall, prominent, symmetric T waves","Often 0.5–2 mm ST elevation in aVR","No precordial ST elevation"],
 sig:"A STEMI-equivalent pattern in about 2% of acute LAD occlusions. It may persist until reperfusion or evolve into classic STEMI. Treat as acute coronary occlusion with emergent angiography despite the absence of ST elevation.",
 hints:["Where does the ST segment start relative to the baseline in V2–V4?"],sim:["hyperk","antstemi","wellens","avr"],
 vs:{hyperk:"Hyperkalemic T waves are narrow-based and tented without J-point depression, with flattened P waves.",wellens:"Wellens shows T inversion (biphasic or deep) in V2–V3 when the patient is pain-free."},
 q2:{q:"Most likely culprit artery?",opts:CULPRIT.slice(0,4),a:0,why:"de Winter T waves are an LAD-occlusion equivalent, usually proximal."}},
{id:"wellens",cat:"isch",name:"Wellens syndrome",
 feats:["Type A (about 25%): biphasic T waves in V2–V3, up then down","Type B (about 75%): deep, symmetric T inversion in V2–V3 (often V1–V6)","Isoelectric or minimally raised ST (under 1 mm), preserved R waves, no Q waves","Seen in the pain-free interval after angina"],
 sig:"Critical proximal LAD stenosis with high risk of extensive anterior MI within days to weeks. Needs angiography; avoid stress testing. During pain the T waves may pseudo-normalize or ST elevation appear.",
 hints:["Which leads carry the T changes, and are the R waves preserved?"],sim:["dewinter","pe","lvh","hypok"],
 vs:{pe:"PE inverts T waves in V1–V4 and III, usually with sinus tachycardia and right axis.",lvh:"LVH strain is asymmetric T inversion in lateral leads with tall voltage."},
 q2:{q:"What does this pattern imply?",opts:["Critical proximal LAD stenosis","Pulmonary embolism","Benign persistent juvenile T pattern","Hypokalemia"],a:0,why:"Wellens T waves reflect reperfused myocardium downstream of a critical, unstable proximal LAD lesion."}},
{id:"avr",cat:"isch",name:"aVR elevation with diffuse ST depression",
 feats:["ST elevation in aVR (often V1) of 1 mm or more","Widespread ST depression, deepest in I, II and V4–V6","Often tachycardic","The aVR elevation is largely reciprocal to the diffuse depression"],
 sig:"Diffuse subendocardial ischemia: left main, proximal LAD or three-vessel disease, or supply–demand mismatch (anemia, hypotension, tachyarrhythmia, aortic stenosis, after resuscitation). High risk; treat the cause and involve cardiology early. Not by itself a STEMI equivalent in current guidance unless the patient is unstable.",
 hints:["Is one lead elevated while most are depressed?"],sim:["poststemi","dig","lvh","svt"],
 vs:{dig:"Digoxin effect gives scooped ST depression with a short QT.",poststemi:"Posterior MI depression is confined to V1–V3, with tall R and upright T."},
 q2:{q:"Most likely mechanism?",opts:["Diffuse subendocardial ischemia (left main or multivessel)","Isolated RCA occlusion","Acute pericarditis","Benign early repolarization"],a:0,why:"Diffuse depression with reciprocal aVR elevation reflects global subendocardial ischemia rather than a single occluded territory."}},
{id:"sgarb",cat:"isch",name:"LBBB with concordant ST elevation (Sgarbossa)",
 feats:["Underlying LBBB (wide QRS, broad R in I, aVL, V5–V6)","Concordant ST elevation of 1 mm or more in leads with a positive QRS","Reciprocal depression inferiorly","Concordance never occurs in uncomplicated LBBB"],
 sig:"Sgarbossa and Smith-modified Sgarbossa identify acute occlusion in LBBB and RV pacing: concordant ST elevation of 1 mm in any lead, concordant ST depression of 1 mm in V1–V3, or excessive discordance (ST/S ratio −0.25 or less). Any one is highly specific.",
 hints:["In LBBB, which way should the ST segment go relative to the QRS?"],sim:["lbbb","latstemi","vpace","lvh"],
 vs:{lbbb:"Uncomplicated LBBB has only discordant ST deviation, opposite the main QRS deflection."},
 q2:{q:"Which Sgarbossa criterion is met?",opts:["Concordant ST elevation of 1 mm or more","Concordant ST depression of 1 mm or more in V1–V3","Excessive discordant ST elevation (ST/S −0.25 or less)","None; this is uncomplicated LBBB"],a:0,why:"The ST segments in I, aVL, V5 and V6 rise in the same direction as their positive QRS complexes."}},
{id:"oldimi",cat:"isch",name:"Old inferior MI (Q waves)",
 feats:["Pathologic Q waves in II, III and aVF (40 ms or more, or 25% of the R height)","Isoelectric ST segments","Inferior T waves flat, inverted or normalized","Axis shifts leftward as inferior forces are lost"],
 sig:"A marker of prior infarction. A Q wave in III alone is often normal; pathologic Q waves need two contiguous leads. LAFB shrinks inferior R waves but produces rS, not Q waves.",
 hints:["How wide are the inferior Q waves?"],sim:["infstemi","lafb","hcm","wpw"],
 vs:{infstemi:"Acute inferior STEMI has ST elevation and reciprocal change.",lafb:"LAFB has small initial r waves (rS) inferiorly.",hcm:"HCM Q waves are deep but narrow (under 40 ms) with LVH.",wpw:"A negative delta wave can mimic inferior Q waves; check the PR."}},
{id:"lvan",cat:"isch",name:"Left ventricular aneurysm",
 feats:["QS or deep Q waves in V1–V4","ST elevation persisting weeks after an anterior MI","Small T waves relative to the QRS (T/QRS ratio under 0.36)","No evolution on serial ECGs, little reciprocal change"],
 sig:"Persistent elevation from dyskinetic scar. Echocardiography confirms. Telling it apart from acute STEMI hinges on old tracings, T-wave size (acute STEMI has large T waves relative to the QRS) and the story.",
 hints:["How big are the T waves compared with the QRS?"],sim:["antstemi","erp","lbbb","brugada"],
 vs:{antstemi:"Acute anterior STEMI has large, often hyperacute T waves and reciprocal change."}},
/* ---- chamber & structure ---- */
{id:"lvh",cat:"struct",name:"Left ventricular hypertrophy with strain",
 feats:["Voltage: S V1 + R V5 or V6 of 35 mm or more (Sokolow–Lyon); R aVL + S V3 over 28 mm men, 20 mm women (Cornell)","Strain: asymmetric ST depression and T inversion in I, aVL, V5–V6","Left atrial enlargement: broad notched P in II, deep terminal P in V1","Slight QRS widening and leftward axis"],
 sig:"Hypertension, aortic stenosis, HCM, athletes. Voltage criteria are specific but insensitive. Strain implies higher risk and can mask or mimic ischemia: compare with old tracings.",
 hints:["Add the S in V1 to the R in V5 or V6."],sim:["hcm","lbbb","latstemi","dig"],
 vs:{hcm:"HCM adds deep narrow Q waves laterally and inferiorly.",lbbb:"LBBB has a QRS of 120 ms or more and no septal q waves."}},
{id:"rvh",cat:"struct",name:"Right ventricular hypertrophy",
 feats:["Right axis deviation (beyond +90°)","Dominant R in V1 (R/S over 1, R of 7 mm or more)","Deep S waves in V5–V6","RV strain: T inversion in V1–V3; right atrial enlargement (P of 2.5 mm or more in II)"],
 sig:"Pulmonary hypertension, chronic lung disease, congenital heart disease, mitral or pulmonary stenosis. A dominant R in V1 also occurs with RBBB, posterior MI, WPW, HCM, dextrocardia, lead misplacement, and normally in children.",
 hints:["What is the axis, and what dominates V1?"],sim:["poststemi","rbbb","lpfb","pe"],
 vs:{poststemi:"Posterior MI has ST depression with upright T waves in V1–V3 and no right axis.",rbbb:"RBBB has a QRS of 120 ms or more with rsR′."}},
{id:"hcm",cat:"chan",name:"Hypertrophic cardiomyopathy",
 feats:["Deep, narrow (“dagger”) Q waves in lateral (I, aVL, V5–V6) and inferior leads","LVH voltage","Left atrial enlargement","Variable repolarization changes; the apical form gives giant T inversion in V2–V5"],
 sig:"The commonest inherited cardiomyopathy and a cause of sudden death in young athletes; the ECG is abnormal in over 90%. Refer for echocardiography and screen first-degree relatives. Exertional syncope or a family history of sudden death is a red flag.",
 hints:["Compare the width and depth of the lateral Q waves."],sim:["lvh","oldimi","wpw","latstemi"],
 vs:{lvh:"Hypertensive LVH lacks the deep narrow septal Q waves.",oldimi:"Infarct Q waves are wide (40 ms or more)."}},
{id:"pe",cat:"struct",name:"Acute pulmonary embolism (RV strain)",
 feats:["Sinus tachycardia (the most common finding)","S1Q3T3: S wave in I, Q wave and inverted T in III","T inversion in V1–V4 and right axis deviation","New RBBB (complete or incomplete) and tall P waves may appear"],
 sig:"The ECG is neither sensitive nor specific for PE, but RV strain signs (T inversion V1–V4 with III, new RBBB, S1Q3T3) identify higher-risk patients. Simultaneous T inversion in V1–V4 and III favors PE over anterior ischemia.",
 hints:["Look at lead I, lead III and the right precordial T waves."],sim:["wellens","rvh","lpfb","stach"],
 vs:{wellens:"Wellens T inversion in V2–V3 occurs without tachycardia, right axis or S1Q3T3.",rvh:"Chronic RVH has a dominant R in V1 and no acute tachycardia."}},
{id:"effusion",cat:"struct",name:"Pericardial effusion with alternans",
 feats:["Low voltage: QRS under 5 mm in all limb leads (under 10 mm precordial)","Electrical alternans: QRS amplitude alternates beat to beat","Sinus tachycardia","PR depression or diffuse ST elevation if pericarditis coexists"],
 sig:"Low voltage, tachycardia and alternans together suggest a large effusion with tamponade: check blood pressure, neck veins and pulsus paradoxus, and confirm with bedside echo. Treatment is pericardiocentesis. Other low-voltage causes: obesity, COPD, hypothyroidism, infiltrative disease.",
 hints:["Measure QRS height in the limb leads.","Compare adjacent beats."],sim:["peric","stach","pe","dextro"],
 vs:{peric:"Pericarditis has normal voltage with diffuse ST elevation and PR depression."},
 q2:{q:"Most useful next step?",opts:["Bedside echocardiography","Thrombolysis","Adenosine","Synchronized cardioversion"],a:0,why:"The triad suggests tamponade; echocardiography confirms the effusion and guides pericardiocentesis."}},
{id:"dextro",cat:"struct",name:"Dextrocardia",
 feats:["Lead I: inverted P, QRS and T","Positive aVR","Reverse R-wave progression: dominant S waves with complexes shrinking from V1 to V6","Right-sided chest leads restore normal progression"],
 sig:"Mirror-image dextrocardia, often with situs inversus. Distinguish from limb-lead reversal, which inverts lead I but leaves the chest leads normal. Repeat with reversed limb leads and right-sided chest leads.",
 hints:["Is the precordial progression normal?"],sim:["lrrev","lpfb","rvh","lafb"],
 vs:{lrrev:"Limb-lead reversal inverts lead I but leaves V1–V6 normal."}},
/* ---- electrolytes, drugs & temperature ---- */
{id:"hyperk",cat:"meta",name:"Hyperkalemia",
 feats:["Tall, narrow-based, peaked (“tented”) T waves, best in V2–V4 and II","Flattened, wide P waves and PR prolongation","QRS widening","Progression: loss of P waves, sine wave, then VF or asystole"],
 sig:"An emergency when the ECG shows changes. IV calcium stabilizes the membrane; insulin with glucose and inhaled salbutamol (albuterol) shift potassium into cells; dialysis, binders or diuretics remove it. The ECG can look nearly normal at dangerous levels, so treat the number and the patient.",
 hints:["Look at the shape and the base of the T waves."],sim:["dewinter","erp","antstemi","hyperk2"],
 vs:{dewinter:"de Winter T waves rise from an upsloping, depressed J point.",erp:"Early repolarization T waves are broad-based, with concave ST elevation."},
 q2:{q:"First treatment?",opts:["IV calcium","Furosemide","Amiodarone","Sodium bicarbonate alone"],a:0,why:"Calcium works within minutes to stabilize the cardiac membrane; it does not lower potassium, so it must be followed by shifting and removal."}},
{id:"hyperk2",cat:"meta",name:"Severe hyperkalemia (sine wave)",
 feats:["Extremely wide QRS merging with the T wave into a sinusoidal pattern","No visible P waves","Slow and regular","A pre-arrest rhythm"],
 sig:"Imminent arrest. Give IV calcium immediately (repeat as needed), insulin with glucose, bicarbonate if acidotic, and arrange emergent dialysis. Sodium-channel blocker toxicity can look similar but is usually tachycardic.",
 hints:["Can you separate the QRS from the T wave?"],sim:["vt","tca","aivr","hyperk"],
 vs:{vt:"VT is fast with distinct QRS complexes.",tca:"Sodium-channel blocker toxicity has a tall terminal R in aVR, usually with sinus tachycardia."}},
{id:"hypok",cat:"meta",name:"Hypokalemia",
 feats:["Prominent U waves (largest in V2–V3), may exceed the T wave","T-wave flattening or inversion","ST depression","Apparent QT prolongation (really a long QU)"],
 sig:"Raises arrhythmia risk, especially with digoxin or QT-prolonging drugs. Replace potassium and magnesium; low magnesium makes potassium hard to correct.",
 hints:["What is the wave after the T wave?"],sim:["lqt","dig","hypoca","wellens"],
 vs:{lqt:"In long QT the T wave itself is late and broad; in hypokalemia a separate U wave follows a flat T."}},
{id:"hyperca",cat:"meta",name:"Hypercalcemia",
 feats:["Short QT interval (QTc often under 360 ms)","Short or absent ST segment: the T starts right after the QRS","Occasionally J waves at very high levels","Bradycardia and AV block when severe"],
 sig:"Malignancy and hyperparathyroidism are the commonest causes. Severe hypercalcemia causes arrhythmias. Treat with IV fluids, then bisphosphonates or calcitonin.",
 hints:["How long is the ST segment?"],sim:["hypoca","dig","nsr","lqt"],
 vs:{dig:"Digoxin also shortens the QT but adds scooped ST depression.",hypoca:"Hypocalcemia does the opposite: a long, flat ST segment."}},
{id:"hypoca",cat:"meta",name:"Hypocalcemia",
 feats:["Prolonged QT from a long, flat ST segment","The T wave itself is normal in shape and width","Rate and QRS unaffected"],
 sig:"Hypoparathyroidism (including after thyroidectomy), vitamin D deficiency, massive transfusion (citrate), pancreatitis, renal failure. Torsades risk when severe. Look for tetany and Chvostek or Trousseau signs.",
 hints:["Is it the ST segment or the T wave that is long?"],sim:["lqt","hypok","hyperca","hypothermia"],
 vs:{lqt:"Drug-induced or congenital long QT usually broadens or notches the T wave itself."}},
{id:"lqt",cat:"meta",name:"Long QT",
 feats:["QTc over 470 ms (men) or 480 ms (women); over 500 ms is high risk","Broad, notched or late T waves","Measure in the lead with the longest QT (often II or V5) and exclude U waves","Bazett overcorrects at fast rates: consider Fridericia"],
 sig:"Drug-induced (antiarrhythmics, antipsychotics, macrolides, fluoroquinolones, methadone, ondansetron), electrolyte-related (low K, Mg, Ca) or congenital (LQT1–3). Risk of torsades: stop offending drugs, correct electrolytes and avoid bradycardia.",
 hints:["Is the QT more than half the R–R interval?"],sim:["hypoca","hypok","tdp","hypothermia"],
 vs:{hypoca:"Hypocalcemia lengthens the ST segment with a normal-shaped T.",hypok:"Hypokalemia adds a separate U wave after a flat T."},
 q2:{q:"Which drug class is a classic cause?",opts:["Antipsychotics and macrolide antibiotics","Beta-blockers","ACE inhibitors","Loop diuretics alone"],a:0,why:"They block the rapid delayed rectifier potassium current (IKr), delaying repolarization."}},
{id:"dig",cat:"meta",name:"Digoxin effect",
 feats:["Sagging, scooped ST depression (“reverse tick”)","Flattened or inverted T waves","Short QT","Possible PR prolongation and U waves"],
 sig:"Effect indicates therapy, not toxicity. Toxicity causes frequent PVCs or bigeminy, atrial tachycardia with block, accelerated junctional rhythm, bidirectional VT and AV block. Hypokalemia worsens toxicity; high potassium signals severe acute poisoning. Treat with digoxin-specific antibody fragments.",
 hints:["Describe the shape of the ST depression."],sim:["avr","lvh","hypok","hyperca"],
 vs:{avr:"Ischemic depression is horizontal or downsloping with aVR elevation, not scooped with a short QT.",lvh:"LVH strain comes with tall voltage."}},
{id:"tca",cat:"meta",name:"Sodium-channel blocker toxicity (e.g., TCA)",
 feats:["Sinus tachycardia","QRS widening over 100 ms (over 160 ms: seizure and arrhythmia risk)","Tall terminal R in aVR (over 3 mm) with R/S over 0.7","Deep terminal S in I and aVL; QTc prolongation"],
 sig:"Tricyclic antidepressants, diphenhydramine, cocaine, flecainide, propafenone, carbamazepine and others. Sodium bicarbonate boluses (target pH 7.45–7.55), hyperventilation if intubated, benzodiazepines for seizures; hypertonic saline or lipid emulsion in refractory cases.",
 hints:["Look closely at aVR."],sim:["rbbb","hyperk2","stach","vt"],
 vs:{rbbb:"RBBB has rsR′ in V1 at a normal rate; toxicity combines tachycardia with a tall terminal R in aVR."},
 q2:{q:"First-line antidote?",opts:["Sodium bicarbonate","Amiodarone","Procainamide","Physostigmine"],a:0,why:"Sodium loading and alkalinization overcome sodium-channel blockade; class Ia and Ic drugs and physostigmine are harmful."}},
{id:"hypothermia",cat:"meta",name:"Hypothermia (Osborn waves)",
 feats:["Osborn (J) waves: a positive hump at the J point, clearest in II and V3–V6","Bradycardia with long PR, QRS and QT","Shivering artifact","Atrial fibrillation and VF become likely as temperature falls"],
 sig:"Osborn-wave size roughly tracks severity. Handle gently (VF risk) and rewarm actively; arrhythmias may resist treatment below 30 °C. J waves also occur with hypercalcemia, brain injury and Brugada syndrome.",
 hints:["Look at the junction between the QRS and the ST segment."],sim:["erp","sbrady","brugada","hyperca"],
 vs:{erp:"Early repolarization J notching is small, without bradycardia or long intervals."}},
/* ---- mimics & technical ---- */
{id:"peric",cat:"mimic",name:"Acute pericarditis",
 feats:["Diffuse concave ST elevation not confined to one coronary territory","PR depression in multiple leads; PR elevation and ST depression in aVR","No reciprocal ST depression (except aVR and sometimes V1)","Sinus tachycardia; downsloping TP segment (Spodick sign)"],
 sig:"Diagnosis needs two of: pleuritic chest pain eased by sitting forward, friction rub, typical ECG, effusion. Distinguish from STEMI (reciprocal depression, convex ST, territorial, Q waves) and early repolarization (ST/T ratio in V6 under 0.25). NSAIDs plus colchicine; check for effusion.",
 hints:["Is the elevation territorial?","Look at the PR segment in II and aVR."],sim:["erp","infstemi","antstemi","effusion"],
 vs:{erp:"Early repolarization has no PR depression, is usually bradycardic, and the ST/T ratio in V6 is under 0.25.",infstemi:"Inferior STEMI is territorial with reciprocal depression in aVL."}},
{id:"brugada",cat:"chan",name:"Brugada pattern (type 1)",
 feats:["Coved ST elevation of 2 mm or more in V1–V2","The ST segment descends into an inverted T wave","RBBB-like terminal r′ without a wide S in I and V6","Unmasked by fever, sodium-channel blockers or high chest-lead placement"],
 sig:"An inherited sodium-channel disorder with risk of polymorphic VT/VF and sudden death, often at rest or with fever. Spontaneous type 1 with syncope warrants an ICD. Treat fever promptly and avoid sodium-channel blockers. Type 2 (saddleback) is not diagnostic alone.",
 hints:["Look at the ST shape in V1–V2 only."],sim:["rbbb","antstemi","erp","peric"],
 vs:{rbbb:"RBBB has a wide S wave in I and V6 and no coved ST elevation.",antstemi:"STEMI involves contiguous leads beyond V2 with reciprocal change."}},
{id:"lrrev",cat:"mimic",name:"Limb lead reversal (LA/RA)",
 feats:["Lead I: P, QRS and T all inverted","aVR upright (looks like a normal aVL); II and III swapped","aVF unchanged","Chest leads normal: R-wave progression preserved"],
 sig:"The commonest technical error. Clue: an inverted P in lead I with normal chest leads. Dextrocardia also inverts lead I but disturbs precordial progression. Re-record after checking electrode positions before acting on an axis change or apparent infarct.",
 hints:["Is everything in lead I negative?","Are the chest leads normal?"],sim:["dextro","lpfb","rvh","latstemi"],
 vs:{dextro:"Dextrocardia inverts lead I and also reverses precordial progression.",lpfb:"LPFB keeps an upright P in lead I."},
 q2:{q:"Best next step?",opts:["Re-record after checking the limb electrodes","Activate the cath lab","Treat as dextrocardia","Start an antiarrhythmic"],a:0,why:"An inverted P, QRS and T in lead I with normal chest leads is a placement error until proven otherwise."}},
{id:"artifact",cat:"mimic",name:"Motion artifact mimicking VT",
 feats:["Rapid irregular deflections resembling VT or VF","Native narrow QRS complexes continue on time within the artifact","One limb lead is clean: the lead that does not use the moving electrode (III when the right arm moves)","The patient is awake with a pulse"],
 sig:"Tremor, shivering, brushing teeth, CPR, or a loose electrode. Check the patient before treating. Einthoven helps: artifact in I, II and aVR but not III localizes to the right-arm electrode.",
 hints:["Is any limb lead clean?","Can you march native QRS complexes through it?"],sim:["vt","vf","tdp","af"],
 vs:{vt:"VT replaces the native QRS complexes; artifact rides on top of them.",vf:"VF has no organized complexes in any lead, and no pulse."}}
];
const PM={};P.forEach(p=>PM[p.id]=p);
/* extra comparisons: key "a>b" = shown when the answer is a and b was chosen */
const VSX={
'nsr>sbrady':'Sinus bradycardia is the same rhythm below 60/min; this one is 60–100.',
'nsr>stach':'Sinus tachycardia is the same rhythm above 100/min.',
'sbrady>hypothermia':'Hypothermia adds Osborn (J) waves, long intervals and shivering artifact.',
'stach>af':'AF is irregularly irregular with no P waves; here a P precedes every QRS.',
'af>pac':'PACs interrupt an otherwise regular sinus rhythm, and each has a P wave.',
'flutter>mat':'MAT has discrete, varied P waves separated by a flat baseline, not a continuous sawtooth.',
'svt>af':'AF is irregular; AVNRT is metronomic.',
'junct>sarr':'Sinus arrhythmia has normal upright P waves with a varying rate.',
'junct>pac':'A PAC is a single early beat with its own P wave; junctional rhythm is a sustained slow rhythm without normal P waves.',
'pvc>wpw':'WPW widens every QRS with a short PR and delta wave; PVCs are early beats without a P.',
'tdp>lqt':'Long QT is the substrate; this tracing shows the polymorphic VT itself.',
'vf>vt':'VT has regular, identical wide complexes; VF has no organized complexes.',
'avb1>nsr':'Normal PR is 120–200 ms; here it is longer than 200 ms.',
'avb1>hyperk':'Hyperkalemia lengthens the PR too, but with peaked T waves and flattened P waves.',
'mob2>avb21':'2:1 block drops every other P; here several P waves conduct in a row before one drops.',
'mob2>pac':'A blocked PAC comes early; the dropped P in Mobitz II arrives exactly on time.',
'avb21>mob2':'Mobitz II needs two consecutive conducted beats to prove a constant PR; 2:1 block never shows that.',
'lafb>lvh':'LVH is a voltage diagnosis; LAFB is an axis diagnosis (−45° or beyond) with qR in aVL and rS inferiorly.',
'bifasc>lbbb':'LBBB has a broad R in I and V6 with QS in V1; here V1 shows an RBBB rsR′ with left axis deviation.',
'bifasc>mob2':'Mobitz II is defined by dropped beats; this tracing conducts every P.',
'wpw>avb1':'First-degree block lengthens the PR; WPW shortens it.',
'wpw>lbbb':'LBBB has a normal PR and no delta wave.',
'fcap>avb3':'In complete heart block P waves march through; here the problem is pacing spikes without capture.',
'fcap>artifact':'Artifact is irregular noise; pacing spikes are sharp, regular and at the programmed interval.',
'antstemi>dewinter':'de Winter shows upsloping J-point depression with tall T waves and no ST elevation.',
'infstemi>poststemi':'Posterior STEMI shows ST depression with tall R and upright T in V1–V3; here the elevation is inferior.',
'infstemi>erp':'Early repolarization has no reciprocal depression in aVL.',
'latstemi>poststemi':'Posterior STEMI shows depression in V1–V3; here I, aVL and V5–V6 are elevated.',
'latstemi>peric':'Pericarditis is diffuse, without reciprocal inferior depression.',
'poststemi>latstemi':'Lateral STEMI elevates I, aVL and V5–V6; here the main change is V1–V3 depression.',
'dewinter>antstemi':'An anterior STEMI has ST elevation; de Winter T waves sit on depressed, upsloping J points.',
'dewinter>avr':'The aVR pattern has diffuse horizontal or downsloping depression with flat T waves, not tall symmetric precordial T waves.',
'wellens>hypok':'Hypokalemia flattens T waves diffusely and adds U waves; Wellens inverts T waves in V2–V3.',
'avr>lvh':'LVH strain is confined to leads with tall R waves and comes with high voltage.',
'avr>svt':'SVT can cause rate-related depression, but the rhythm here is sinus with visible P waves.',
'sgarb>latstemi':'The wide QRS with broad R in I and V6 shows an underlying LBBB; judge the ST against the QRS direction.',
'sgarb>vpace':'There are no pacing spikes; this is native LBBB.',
'sgarb>lvh':'LVH strain depresses the ST in leads with tall R; here the ST rises with the R (concordant).',
'lvan>erp':'Early repolarization has normal R waves; here V1–V4 show QS complexes.',
'lvan>lbbb':'LBBB has a QRS of 120 ms or more; this QRS is narrow.',
'lvan>brugada':'Brugada is confined to V1–V2 with a coved ST into an inverted T, without QS waves through V4.',
'hcm>wpw':'WPW has a short PR and a slurred delta wave; HCM Q waves are sharp and the PR is normal.',
'hcm>latstemi':'There is no ST elevation; the abnormality is the deep, narrow Q waves with LVH.',
'pe>stach':'Sinus tachycardia alone lacks the S1Q3T3 and right precordial T inversion.',
'effusion>stach':'Plain sinus tachycardia has normal voltage and no alternans.',
'effusion>pe':'PE has normal voltage with right-heart strain signs.',
'effusion>dextro':'Dextrocardia inverts lead I; here every lead is small but correctly oriented.',
'dextro>lpfb':'LPFB keeps an upright P in lead I and normal precordial progression.',
'dextro>rvh':'RVH has a tall R in V1 with T inversion and an upright P in lead I.',
'dextro>lafb':'LAFB has a leftward axis with upright P waves in lead I.',
'hyperk>antstemi':'Anterior STEMI has ST elevation and reciprocal depression; hyperkalemic T waves are narrow-based without ST elevation.',
'hyperk>hyperk2':'The sine-wave pattern has no P waves and a QRS merging into the T; here P waves and a defined QRS remain.',
'hyperk2>aivr':'AIVR has distinct wide QRS complexes with isoelectric segments; sine-wave hyperkalemia has none.',
'hyperk2>hyperk':'Early hyperkalemia keeps P waves and a distinct QRS; here they have merged into a sine wave.',
'hypok>dig':'Digoxin scoops the ST segment and shortens the QT without large U waves.',
'hypok>hypoca':'Hypocalcemia lengthens a flat ST segment before a normal T; hypokalemia flattens the T and adds a U wave.',
'hypok>wellens':'Wellens is localized T inversion in V2–V3; hypokalemia is diffuse T flattening with U waves.',
'hyperca>nsr':'Here the QT is short, with the T starting almost straight off the QRS.',
'hyperca>lqt':'Long QT is the opposite: a late, broad T wave.',
'hypoca>hypok':'Hypokalemia flattens the T and adds a U wave; here the T is normal but late.',
'hypoca>hypothermia':'Hypothermia adds Osborn waves and bradycardia.',
'lqt>tdp':'Torsades is the arrhythmia; this tracing shows the long QT without it.',
'lqt>hypothermia':'Hypothermia lengthens the QT too, but with Osborn waves, bradycardia and shivering.',
'dig>hypok':'Hypokalemia shows prominent U waves and a long QU; digoxin shortens the QT.',
'tca>stach':'Plain sinus tachycardia has a narrow QRS without a tall terminal R in aVR.',
'tca>vt':'VT lacks P waves and has AV dissociation; here sinus P waves precede each widened QRS.',
'hypothermia>sbrady':'Plain sinus bradycardia has no J waves and normal intervals.',
'hypothermia>brugada':'Brugada J-point elevation is coved and limited to V1–V2; Osborn waves are widespread humps.',
'hypothermia>hyperca':'Hypercalcemia shortens the QT; hypothermia lengthens it.',
'peric>antstemi':'Anterior STEMI is territorial with reciprocal inferior depression; pericarditis is diffuse with PR depression.',
'brugada>peric':'Pericarditis is diffuse concave elevation with PR depression, not coved elevation confined to V1–V2.',
'lrrev>rvh':'RVH keeps an upright P in lead I and shows a tall R in V1.',
'lrrev>latstemi':'A lateral STEMI elevates the ST in I and aVL; here lead I is simply inverted throughout.',
'artifact>af':'AF has organized narrow QRS complexes at irregular intervals; artifact has native QRS complexes marching on time through noise.'};
Object.entries(VSX).forEach(([k,t])=>{const[a,b]=k.split('>');if(PM[a]){PM[a].vs=PM[a].vs||{};if(!PM[a].vs[b])PM[a].vs[b]=t}});
