
/* ============ pattern catalogue, set 2: subtle occlusion, specialty rhythms, pacing, channelopathies, staged electrolytes ============ */
P.push(
/* ---- subtle occlusion & equivalents ---- */
{id:"hyperT",cat:"isch",name:"Hyperacute T waves (early LAD occlusion)",
 feats:["Broad-based, bulky, symmetric T waves in V2–V4","T wave large relative to the preceding QRS","ST elevation absent or below STEMI criteria","Evolves into ST elevation over minutes on serial tracings"],
 sig:"The first ECG sign of coronary occlusion, within minutes and before ST elevation. Missed because it does not meet STEMI criteria. Compare with a prior ECG and repeat every 15–30 minutes: occlusion MI (OMI) can exist without STEMI criteria.",
 hints:["Compare the size of each precordial T wave with its QRS.","Is the base of the T wave broad or narrow?"],sim:["hyperk1","erp","antstemi","dewinter"],
 vs:{hyperk1:"Hyperkalemic T waves are narrow-based and tented, diffuse rather than territorial.",erp:"Early repolarization T waves are proportional to tall QRS complexes, with J-point notching and no evolution.",antstemi:"Anterior STEMI has progressed to frank ST elevation with reciprocal inferior depression.",dewinter:"de Winter adds 1–3 mm of upsloping J-point depression before the tall T."},
 q2:{q:"Ongoing chest pain with this tracing. Best next step?",opts:["Serial ECGs every 15–30 minutes and urgent cardiology review","Discharge if the first troponin is normal","Treat as hyperkalemia","No action: it does not meet STEMI criteria"],a:0,why:"Hyperacute T waves are an occlusion sign. Serial tracings capture the evolution; many centers activate the cath lab on OMI findings without STEMI criteria."}},
{id:"saflag",cat:"isch",name:"High lateral occlusion (“South African flag”)",
 feats:["ST elevation in I, aVL and V2","Reciprocal ST depression in III (often aVF and II)","V3–V6 show little change","Small absolute elevation, because I and aVL are low-voltage leads"],
 sig:"First diagonal (or obtuse marginal) occlusion. The elevation is small; the inferior reciprocal depression is often the more obvious clue. Named for the shape the involved leads make on the 12-lead layout.",
 hints:["Start with lead III: is the ST depressed?","Which leads look at the high lateral wall?"],sim:["latstemi","infstemi","peric","antstemi"],
 vs:{latstemi:"A larger lateral STEMI elevates V5–V6 too; here V2 is involved and V3–V6 are spared.",infstemi:"Inferior STEMI elevates II, III and aVF; here they are depressed.",peric:"Pericarditis elevates the inferior leads too and lacks reciprocal depression."},
 q2:{q:"Which artery is most likely occluded?",opts:CULPRIT,a:3,why:"Elevation in I, aVL and V2 with inferior reciprocity localizes to the first diagonal and the high lateral wall."}},
{id:"swirl",cat:"isch",name:"Septal LAD occlusion (“precordial swirl”)",
 feats:["ST elevation in V1–V2 (V1 often largest) and in aVR","ST depression in V5–V6 and the inferior leads","Elevation fades from V1 toward V4","Injury vector points rightward, anterior and superior"],
 sig:"Occlusion of the LAD at or before the first septal perforator: the injured septum points the vector toward V1 and aVR. Often mistaken for RV infarction or Brugada. Treat as an anterior occlusion.",
 hints:["Follow the ST elevation from V1 to V4: does it grow or fade?","Where is the ST depression?"],sim:["antstemi","avr","rvmi","brugada"],
 vs:{antstemi:"Typical anterior STEMI peaks in V2–V4 and spreads leftward; here V1 is largest with lateral depression.",avr:"Diffuse subendocardial ischemia elevates aVR but not V1–V3.",rvmi:"RV infarction comes with inferior ST elevation; here the inferior leads are depressed.",brugada:"Brugada is a fixed coved shape in V1–V2 without reciprocal depression or evolution."},
 q2:{q:"Which artery is most likely occluded?",opts:CULPRIT,a:0,why:"Septal injury (V1, aVR) with inferior and lateral reciprocity points to the proximal LAD at the septal branches."}},
{id:"aslanger",cat:"isch",name:"Aslanger pattern (inferior OMI with multivessel disease)",
 feats:["ST elevation in III but not in II or aVF","ST depression in V4–V6 with an upright T","ST in V1 higher than in V2","One inferior injury vector summed with diffuse subendocardial ischemia"],
 sig:"An inferior occlusion masked by simultaneous subendocardial ischemia from multivessel disease: the two vectors add up to elevation only in III. High mortality; treat as an occlusion equivalent.",
 hints:["Compare lead III with II and aVF.","What is happening in V4–V6?"],sim:["infstemi","avr","poststemi","lvh"],
 vs:{infstemi:"A typical inferior STEMI elevates II, III and aVF together.",avr:"The aVR pattern is diffuse depression with aVR elevation, not isolated elevation in III.",poststemi:"Posterior MI depresses V1–V3, not V4–V6."}},
{id:"rvmi",cat:"isch",name:"Inferior STEMI with right ventricular infarction",
 feats:["ST elevation in II, III, aVF with III greater than II","ST elevation in V1 (and in V4R on right-sided leads)","Reciprocal depression in I and aVL","Often bradycardia or AV block"],
 sig:"Proximal RCA occlusion. The infarcted RV is preload dependent: nitrates, diuretics and opioids can cause profound hypotension; give fluids if hypotensive. Record V4R in every inferior STEMI.",
 hints:["Compare the ST elevation in III with II.","Is V1 elevated?"],sim:["infstemi","swirl","poststemi","peric"],
 vs:{infstemi:"Without RV involvement, V1 is isoelectric or depressed.",swirl:"Septal LAD occlusion elevates V1 but depresses the inferior leads.",poststemi:"Posterior extension depresses V1–V3."},
 q2:{q:"Which treatment is most likely to cause hypotension here?",opts:["Nitroglycerin","IV fluid bolus","Aspirin","Heparin"],a:0,why:"An infarcted right ventricle depends on venous return; venodilation drops RV filling and output."}},
{id:"stemirbbb",cat:"isch",name:"Anterior STEMI with new RBBB",
 feats:["RBBB: rsR′ in V1, wide S in I and V6","ST elevation in V1–V4 (RBBB alone causes ST depression there)","Elevation in I and aVL, reciprocal depression inferiorly","A new RBBB implies a large territory"],
 sig:"RBBB does not hide ST elevation: only the terminal QRS is delayed, so the ST is still interpretable. New RBBB with anterior STEMI means proximal LAD occlusion and a higher risk of complete block and shock.",
 hints:["In RBBB the ST in V1–V3 should be slightly depressed. What is it here?","Which artery supplies the right bundle?"],sim:["rbbb","antstemi","brugada","bifasc"],
 vs:{rbbb:"Uncomplicated RBBB has secondary ST depression and T inversion in V1–V3.",antstemi:"Without RBBB there is no rsR′ in V1 or wide terminal S in I and V6.",brugada:"Brugada mimics incomplete RBBB with coved elevation confined to V1–V2 and no reciprocal change."},
 q2:{q:"Which artery is most likely occluded?",opts:CULPRIT,a:0,why:"The right bundle is supplied by septal perforators of the proximal LAD."}},
{id:"shark",cat:"isch",name:"“Shark fin” (giant R / lambda wave)",
 feats:["QRS, ST and T fused into one large triangle","The J point cannot be identified","The fused complex looks like a wide QRS","Massive elevation with reciprocal depression"],
 sig:"An extreme injury current from large-territory occlusion, associated with cardiogenic shock and VF. Misread as a wide-complex rhythm or hyperkalemia; P waves before each complex and reciprocal depression give it away.",
 hints:["Where does the QRS end?","Do other leads show the mirror image?"],sim:["vt","hyperk2","antstemi","tca"],
 vs:{vt:"VT has AV dissociation and no P before each complex.",hyperk2:"Sine-wave hyperkalemia is diffuse with no reciprocal depression.",antstemi:"A typical STEMI keeps a visible J point."}},
{id:"antsubtle",cat:"isch",name:"Subtle anterior OMI (terminal QRS distortion)",
 feats:["Minimal ST elevation in V2–V3","No S wave and no J notch in V2 or V3 (terminal QRS distortion)","T waves bulky relative to the QRS","Subtle reciprocal depression in III or aVF"],
 sig:"Loss of the S wave in V2–V3 separates subtle anterior occlusion from early repolarization. Any inferior reciprocal depression argues strongly for occlusion.",
 hints:["Is there an S wave in V2 and V3?","Is there any inferior ST depression?"],sim:["erp","hyperT","antstemi","nsr"],
 vs:{erp:"Early repolarization keeps the S wave, often shows J notching, and has no reciprocal depression.",hyperT:"Hyperacute T waves dominate there; here the key is the missing S wave.",antstemi:"Anterior STEMI has unequivocal ST elevation."}},
{id:"wraplad",cat:"isch",name:"Anterior STEMI from a wraparound LAD",
 feats:["ST elevation in V1–V6 and in II, III, aVF","No inferior reciprocal depression","aVR depressed","Apex and inferior apical segments injured"],
 sig:"A long LAD wrapping around the apex supplies the inferior apical wall. Anterior plus inferior elevation without reciprocity can mimic pericarditis; the territorial distribution, larger T waves and evolution say otherwise.",
 hints:["Is there ST depression anywhere other than aVR?","Which single artery could reach both walls?"],sim:["peric","antstemi","infstemi","erp"],
 vs:{peric:"Pericarditis adds PR depression, spares V1, and has concave ST with smaller T waves.",antstemi:"A proximal LAD occlusion without wraparound shows inferior reciprocal depression.",infstemi:"Inferior STEMI does not elevate V1–V4."},
 q2:{q:"Why is there no inferior reciprocal depression?",opts:["The LAD wraps around the apex, so the inferior wall is injured too","A second, RCA occlusion","Pericarditis","Limb lead reversal"],a:0,why:"The inferior apical injury vector cancels the reciprocal change that an anterior injury normally produces in II, III and aVF."}},
{id:"pacedmi",cat:"isch",name:"Paced rhythm with acute MI (Sgarbossa)",
 feats:["Ventricular pacing: wide, LBBB-like QRS after each spike","Concordant ST elevation in I and aVL (same direction as the QRS)","Reciprocal depression inferiorly","Excessively discordant ST (25% or more of the preceding S) also counts"],
 sig:"RV pacing makes secondary ST-T changes the norm, so judge the ST against the QRS direction. Concordant elevation, concordant depression in V1–V3, or disproportionate discordance indicate acute occlusion.",
 hints:["In each lead, is the ST going the same way as the QRS?","Compare the ST deviation with the QRS size."],sim:["vpace","sgarb","latstemi","lbbb"],
 vs:{vpace:"Uncomplicated paced rhythm has ST and T opposite the QRS in every lead.",sgarb:"Same principle; there the wide QRS is native LBBB without spikes.",latstemi:"Without pacing the QRS is narrow."}},
/* ---- wide and narrow tachycardias ---- */
{id:"svtab",cat:"rhythm",name:"SVT with aberrant conduction",
 feats:["Regular wide-complex tachycardia","Textbook bundle-branch shape: LBBB with a rapid initial deflection, or RBBB with rsR′ in V1","QRS usually 120–140 ms","No AV dissociation, fusion or capture beats"],
 sig:"Aberrancy is functional bundle-branch block at a fast rate. Separating it from VT is hard; when in doubt treat a wide regular tachycardia as VT, especially with structural heart disease. Adenosine is reasonable only for a regular, monomorphic tachycardia in a stable patient.",
 hints:["Does the QRS look like a textbook bundle-branch block?","Any sign of AV dissociation?"],sim:["vt","antidromic","svt","rvotvt"],
 vs:{vt:"VT is bizarre rather than textbook BBB, may have a northwest axis, and may show AV dissociation, fusion or capture beats.",antidromic:"Antidromic AVRT is fully pre-excited: slurred onset, very wide, often over 200/min.",svt:"Without aberrancy the same rhythm has a narrow QRS.",rvotvt:"RVOT VT is LBBB-like with tall inferior R waves and arises in a normal heart."},
 q2:{q:"Which finding would most strongly favor VT instead?",opts:["AV dissociation (independent P waves)","Rate over 160","QRS of 130 ms","A regular rhythm"],a:0,why:"Dissociated P waves, fusion or capture beats prove a ventricular origin."}},
{id:"preaf",cat:"rhythm",name:"Pre-excited atrial fibrillation (WPW with AF)",
 feats:["Irregularly irregular wide-complex tachycardia","Very fast: shortest R–R under 250 ms at times","QRS width and shape change beat to beat (variable fusion)","No P waves"],
 sig:"AF conducting down an accessory pathway that lacks the AV node's decremental protection. AV-nodal blockers (adenosine, beta-blockers, calcium-channel blockers, digoxin, IV amiodarone) can precipitate VF. Use procainamide or synchronized cardioversion.",
 hints:["Is it irregular? Is it wide?","Is every QRS the same shape?"],sim:["af","vt","pmvt","svtab"],
 vs:{af:"Ordinary AF conducts through the AV node: narrow QRS, rates rarely above 200.",vt:"Monomorphic VT is regular with identical complexes.",pmvt:"Polymorphic VT twists without the recognizable pre-excited complexes.",svtab:"Aberrancy keeps one fixed bundle-branch shape."},
 q2:{q:"Which drug is appropriate?",opts:["Procainamide","Adenosine","Diltiazem","Digoxin"],a:0,why:"Procainamide slows accessory-pathway conduction; AV-nodal blockers divert more impulses down the pathway."}},
{id:"antidromic",cat:"rhythm",name:"Antidromic AVRT",
 feats:["Regular wide-complex tachycardia, often over 200/min","Fully pre-excited QRS with a slurred onset","No visible P before the QRS","Sinus-rhythm ECG (if available) shows WPW"],
 sig:"The circuit runs down the accessory pathway and back up the AV node, so the ventricles are activated entirely through the pathway. Indistinguishable from VT on one tracing; treat as VT if unsure (procainamide or cardioversion).",
 hints:["Look at the onset of each QRS.","Is it perfectly regular?"],sim:["vt","svtab","wpw","preaf"],
 vs:{vt:"VT may show AV dissociation or capture beats; a prior ECG with a delta wave favors antidromic AVRT.",preaf:"Pre-excited AF is irregular with varying QRS width.",wpw:"Sinus rhythm with WPW has a short PR at a normal rate.",svtab:"Aberrancy has a crisp bundle-branch shape, not a slurred delta onset."}},
{id:"fascvt",cat:"rhythm",name:"Fascicular VT (idiopathic left VT)",
 feats:["RBBB-like QRS, relatively narrow (120–140 ms)","Left (superior) axis: exit near the left posterior fascicle","Regular, 150–200/min; AV dissociation may be visible","Young patient, structurally normal heart"],
 sig:"Re-entry within the Purkinje network, verapamil sensitive. Often misdiagnosed as SVT with RBBB and LAFB. Calcium-channel blockers are dangerous in other VT, so the diagnosis must be confident.",
 hints:["What is the axis?","Is the QRS as wide as typical VT?"],sim:["svtab","bifasc","vt","rvotvt"],
 vs:{svtab:"SVT with RBBB aberrancy usually keeps a normal axis and shows no AV dissociation.",bifasc:"Bifascicular block is the same QRS shape at a sinus rate with P waves.",rvotvt:"RVOT VT is LBBB-like with an inferior axis.",vt:"Scar VT is broader and more bizarre, in a diseased heart."},
 q2:{q:"Which drug typically terminates this rhythm?",opts:["Verapamil","Adenosine","Digoxin","Lidocaine"],a:0,why:"The circuit includes slow-response, calcium-dependent Purkinje tissue."}},
{id:"rvotvt",cat:"rhythm",name:"Right ventricular outflow tract VT",
 feats:["LBBB-like QRS (dominant S in V1)","Inferior axis: tall R in II, III and aVF","Regular; often repetitive monomorphic runs","Usually a structurally normal heart"],
 sig:"Triggered activity (cAMP-mediated delayed afterdepolarizations) from the outflow tract, provoked by exercise or catecholamines; often adenosine and beta-blocker sensitive. Exclude ARVC, which favors the same region.",
 hints:["What is the QRS shape in V1?","What is the axis?"],sim:["fascvt","svtab","vt","pvc"],
 vs:{fascvt:"Fascicular VT is RBBB-like with a superior axis.",svtab:"SVT with LBBB aberrancy typically has a normal or left axis.",vt:"Scar VT is wider and bizarre, in a diseased heart.",pvc:"Single outflow-tract PVCs share the shape; this is a sustained run."}},
{id:"bidir",cat:"rhythm",name:"Bidirectional VT",
 feats:["Wide-complex tachycardia whose frontal axis flips every beat","Alternating left and right axis, often with RBBB shape","Regular overall rate","Classic causes: digoxin toxicity, catecholaminergic polymorphic VT"],
 sig:"Two alternating foci driven by calcium overload and delayed afterdepolarizations. Think digoxin toxicity (digoxin-specific antibodies) or CPVT (beta-blockade, flecainide).",
 hints:["Compare consecutive beats in the limb leads.","Which drug overloads cells with calcium?"],sim:["altbbb","pvc","effusion","tdp"],
 vs:{altbbb:"Alternating BBB occurs at a sinus rate with a P before each QRS.",effusion:"Electrical alternans in effusion changes amplitude, not axis, of narrow complexes.",tdp:"Torsades twists gradually over many beats rather than flipping each beat.",pvc:"Bigeminy alternates normal and ventricular beats, with P waves on the normal ones."},
 q2:{q:"Which drug toxicity classically causes this?",opts:["Digoxin","Amiodarone","Metoprolol","Furosemide"],a:0,why:"Na⁺/K⁺-ATPase inhibition raises intracellular calcium, producing delayed afterdepolarizations from alternating foci."}},
{id:"pmvt",cat:"rhythm",name:"Polymorphic VT with a normal QT (ischemic)",
 feats:["Polymorphic VT: changing QRS shape and axis","Sinus beats before and after have a normal QT","Ischemic ST depression on the sinus beats","Not pause-dependent"],
 sig:"Usually acute ischemia, and not torsades: magnesium is not the main treatment. Defibrillate if pulseless; treat the ischemia urgently, plus amiodarone or lidocaine and beta-blockade.",
 hints:["Measure the QT on the sinus beats.","What is the ST doing on the sinus beats?"],sim:["tdp","vf","preaf","vt"],
 vs:{tdp:"Torsades arises from a long QT, often after a pause, twisting around the baseline; magnesium is first line.",vf:"VF has no recognizable QRS complexes.",preaf:"Pre-excited AF is irregular but each complex is a recognizable pre-excited QRS.",vt:"Monomorphic VT has identical complexes."},
 q2:{q:"What is the most likely cause?",opts:["Acute myocardial ischemia","Congenital long QT","Hypokalemia with long QT","Digoxin toxicity"],a:0,why:"A normal QT with ischemic ST changes points to ischemic re-entry rather than EAD-triggered torsades."}},
{id:"vflutter",cat:"rhythm",name:"Ventricular flutter",
 feats:["Regular sine-wave oscillation near 250–300/min","QRS, ST and T cannot be separated","No isoelectric baseline","Usually degenerates into VF"],
 sig:"An extremely fast ventricular re-entry, usually pulseless. Treat as VF or pulseless VT: defibrillate.",
 hints:["Can you separate QRS from T?","Is it regular?"],sim:["vt","vf","hyperk2","artifact"],
 vs:{vt:"Monomorphic VT at 150–220/min keeps a distinguishable QRS and T.",vf:"VF varies in rate and amplitude.",hyperk2:"Sine-wave hyperkalemia is slow, usually under 100/min.",artifact:"Artifact lets native QRS complexes march through."}},
{id:"atypflut",cat:"rhythm",name:"Atypical (clockwise) atrial flutter",
 feats:["Continuous flutter waves at 250–350/min","Upright F waves in II, III, aVF","Negative F waves in V1","Fixed or variable AV block"],
 sig:"Clockwise flutter runs the cavotricuspid circuit in reverse; other atypical flutters circle surgical or ablation scars. Rate control and stroke prevention follow AF; non-isthmus circuits are harder to ablate.",
 hints:["Which way do the flutter waves point in II?","What is the atrial rate?"],sim:["flutter","atblock","af","stach"],
 vs:{flutter:"Typical (counterclockwise) flutter has negative sawtooth waves in II, III and aVF and positive waves in V1.",atblock:"Atrial tachycardia has discrete P waves separated by a flat baseline, at 150–250/min.",af:"AF has no organized atrial activity.",stach:"Sinus tachycardia has one P per QRS with a flat baseline."},
 q2:{q:"Why are the flutter waves upright in the inferior leads?",opts:["The wavefront descends the septum toward the inferior leads (clockwise)","The atrial rate is slower","There is AV block","The atria are enlarged"],a:0,why:"A wavefront heading toward a lead's positive pole is positive; reversing the circuit reverses the F-wave polarity."}},
{id:"eat",cat:"rhythm",name:"Ectopic atrial tachycardia",
 feats:["Regular narrow-complex tachycardia, 120–220/min","One P before each QRS, with an abnormal P axis","Warm-up at onset and cool-down at offset","PR normal or slightly long"],
 sig:"An automatic focus outside the sinus node: children, after cardiac surgery, digoxin toxicity, stimulants. Adenosine causes transient AV block (revealing the P waves) but rarely terminates it. Treat the trigger; rate control or ablation.",
 hints:["Compare the P axis with sinus rhythm.","Is there a P before every QRS?"],sim:["stach","pjrt","svt","flutter"],
 vs:{stach:"Sinus tachycardia has a normal P axis: upright in I, II and aVF.",pjrt:"PJRT also inverts the inferior P, but starts and stops abruptly (re-entry).",svt:"AVNRT shows no P before the QRS.",flutter:"Flutter waves continue with no flat baseline."}},
{id:"atblock",cat:"rhythm",name:"Atrial tachycardia with block",
 feats:["Discrete P waves at 150–250/min with a flat baseline between them","2:1 (or variable) AV conduction","Narrow QRS","A second P often hides in the T wave"],
 sig:"Classic for digoxin toxicity: enhanced atrial automaticity from calcium overload plus vagally mediated AV-node block. Check digoxin and potassium; also seen with structural atrial disease.",
 hints:["March out the P waves: is one hidden in each T?","Is there a flat baseline between P waves?"],sim:["flutter","avb21","stach","atypflut"],
 vs:{flutter:"Flutter has no flat baseline and the atrial rate is usually near 300.",avb21:"2:1 AV block has a normal sinus atrial rate (60–100).",stach:"Sinus tachycardia conducts every P.",atypflut:"Atypical flutter waves are continuous, without an isoelectric baseline."},
 q2:{q:"Which drug toxicity should you suspect first?",opts:["Digoxin","Metoprolol","Amiodarone","Verapamil"],a:0,why:"Digoxin raises atrial automaticity (delayed afterdepolarizations) and slows AV-node conduction through vagal tone."}},
{id:"wap",cat:"rhythm",name:"Wandering atrial pacemaker",
 feats:["Three or more P-wave shapes","Rate under 100","Varying PR and slightly irregular R–R","Narrow QRS"],
 sig:"The dominant pacemaker shifts between the sinus node, atrial sites and the junction, usually with high vagal tone; benign. The same picture over 100/min is MAT.",
 hints:["Count the P-wave shapes.","What is the rate?"],sim:["mat","sarr","pac","af"],
 vs:{mat:"MAT is the same picture over 100/min, usually with lung disease.",sarr:"Sinus arrhythmia keeps one P shape.",pac:"PACs are occasional early beats with one dominant P shape.",af:"AF has no discrete P waves."}},
{id:"orthoavrt",cat:"rhythm",name:"Orthodromic AVRT",
 feats:["Regular narrow-complex tachycardia, 150–250/min","Retrograde P in the ST segment, RP over 70 ms","QRS alternans in some leads","Rate-related ST depression common"],
 sig:"The commonest tachycardia with an accessory pathway: down the AV node, up the pathway. The ventricles must activate before the pathway can conduct back, so the retrograde P falls later than in AVNRT. Vagal maneuvers and adenosine terminate it.",
 hints:["Where is the retrograde P relative to the QRS?","Does QRS amplitude alternate?"],sim:["svt","pjrt","stach","flutter"],
 vs:{svt:"In typical AVNRT the retrograde P sits at the very end of the QRS (pseudo r′), RP under 70 ms.",pjrt:"In PJRT the P sits closer to the next QRS (long RP).",stach:"Sinus tachycardia has upright P waves before each QRS.",flutter:"Flutter waves are continuous at about 300/min."}},
{id:"pjrt",cat:"rhythm",name:"Long-RP tachycardia (PJRT)",
 feats:["Regular narrow-complex tachycardia, often incessant","Inverted P waves in II, III, aVF","RP longer than PR: the P sits closer to the next QRS","Narrow QRS"],
 sig:"Permanent junctional reciprocating tachycardia uses a slowly conducting accessory pathway near the coronary sinus. Incessant tachycardia can cause cardiomyopathy. Long-RP differential: sinus tachycardia, atrial tachycardia, atypical AVNRT, PJRT.",
 hints:["Is the P closer to the QRS before it or after it?","Which way does the P point in II?"],sim:["eat","orthoavrt","stach","svt"],
 vs:{eat:"Low atrial tachycardia looks the same; abrupt onset and offset favor PJRT.",orthoavrt:"Orthodromic AVRT over a fast pathway has a short RP.",stach:"Sinus P waves are upright in II.",svt:"Typical AVNRT hides the P at the end of the QRS."}},
{id:"accjunct",cat:"rhythm",name:"Accelerated junctional rhythm",
 feats:["Narrow QRS at 60–100/min","P waves absent or retrograde (just before, inside or after the QRS)","Regular","May compete with the sinus node"],
 sig:"Enhanced junctional automaticity: digoxin toxicity, inferior MI, myocarditis, after cardiac surgery, catecholamines. Usually harmless itself but a pointer to its cause.",
 hints:["Find the P waves: which way do they point in II?","What rate would an escape rhythm have?"],sim:["junct","stach","nsr","svt"],
 vs:{junct:"A junctional escape rhythm runs at 40–60.",nsr:"Sinus rhythm has upright P waves before each QRS.",svt:"AVNRT runs over 150 and starts abruptly.",stach:"Sinus tachycardia has upright P waves."}},
/* ---- conduction ---- */
{id:"sinusarrest",cat:"cond",name:"Sinus pause (sinus arrest)",
 feats:["Sudden absence of P waves and QRS complexes","Pause is not a multiple of the P–P interval","Pause may end with a junctional escape","Sinus rhythm before and after"],
 sig:"Failure of impulse formation in the sinus node: sick sinus syndrome, drugs, vagal surges, hyperkalemia, ischemia. Pauses over 3 seconds while awake, or symptoms, warrant pacing evaluation.",
 hints:["Measure the pause against the P–P interval.","What ends the pause?"],sim:["saexit","mob2","pac","avb21"],
 vs:{saexit:"In SA exit block the pause is an exact multiple of the P–P: the node fired but the impulse could not exit.",mob2:"In Mobitz II a P wave arrives on time without a QRS.",pac:"A blocked PAC leaves a premature P (often in the T) before the pause.",avb21:"2:1 block has a P between every pair of QRS complexes."}},
{id:"saexit",cat:"cond",name:"Sinoatrial exit block",
 feats:["Pause exactly two (or more) P–P intervals long","No P wave during the pause","Regular sinus rhythm otherwise","The Wenckebach form shows shortening P–P before the pause"],
 sig:"The sinus node keeps firing but the impulse fails to reach the atrium; the P–P arithmetic proves it. Causes overlap with sinus arrest: vagal tone, drugs, ischemia, fibrosis.",
 hints:["Measure the pause with calipers against two normal P–P intervals."],sim:["sinusarrest","mob2","avb21","sarr"],
 vs:{sinusarrest:"Sinus arrest pauses bear no relation to the P–P interval.",mob2:"In Mobitz II the P wave is present; only the QRS is missing.",sarr:"Sinus arrhythmia changes gradually with breathing.",avb21:"In 2:1 block P waves keep coming; only the QRS drops."}},
{id:"hgavb",cat:"cond",name:"High-grade (advanced) AV block",
 feats:["Two or more consecutive P waves fail to conduct (3:1 or higher)","Constant PR when conduction occurs","Slow ventricular rate","Often a wide QRS: infranodal disease"],
 sig:"More dangerous than Mobitz II and one step from complete block. Prepare transcutaneous pacing; most need a permanent pacemaker unless a reversible cause is found (inferior MI, drugs, hyperkalemia, Lyme disease).",
 hints:["Count P waves per QRS.","Is the PR constant on the conducted beats?"],sim:["avb3","avb21","mob2","sbrady"],
 vs:{avb3:"In complete block no P conducts: the PR varies at random.",avb21:"2:1 block conducts every other P.",mob2:"Mobitz II drops single P waves between runs of conducted beats.",sbrady:"Sinus bradycardia has one P per QRS."}},
{id:"isodiss",cat:"cond",name:"Isorhythmic AV dissociation",
 feats:["Sinus and junctional rhythms at nearly the same rate","P waves drift into, through and out of the QRS","Narrow QRS","Not AV block: well-timed P waves would conduct"],
 sig:"The sinus node slows just below the junction (vagal tone, drugs, inferior MI) and the junction takes over. Usually benign; distinguish from complete block, where the atrial rate is faster than the ventricular rate.",
 hints:["Compare atrial and ventricular rates.","Where does the P sit relative to the QRS across the strip?"],sim:["avb3","accjunct","junct","sarr"],
 vs:{avb3:"In complete block the atrial rate exceeds the ventricular rate and even well-timed P waves fail.",accjunct:"Accelerated junctional rhythm alone has retrograde or absent P waves, not drifting sinus P waves.",junct:"A junctional escape rhythm runs slower than the sinus rate would."}},
{id:"ashman",cat:"cond",name:"Ashman phenomenon (aberrancy in AF)",
 feats:["Atrial fibrillation","An RBBB-shaped beat ending a long–short R–R sequence","Same initial vector as the normal beats","Usually isolated, sometimes short runs"],
 sig:"Refractoriness follows the previous cycle: a long cycle lengthens the right bundle's refractory period, so the next early impulse finds it still refractory. Not a PVC; no treatment needed.",
 hints:["Measure the two R–R intervals before the odd beat.","What shape is it in V1?"],sim:["pvc","af","rbbb","svtab"],
 vs:{pvc:"PVCs have a bizarre QRS unrelated to the preceding cycle lengths.",svtab:"Aberrancy there is sustained at a fast rate.",af:"Ordinary AF beats share one narrow shape.",rbbb:"Fixed RBBB affects every beat."},
 q2:{q:"Why does the preceding long cycle matter?",opts:["Refractoriness lengthens after a long cycle, so the next early beat finds the bundle refractory","The atria fire faster","The AV node blocks","Potassium rises"],a:0,why:"Action potential duration, and so refractoriness, adapts to the preceding cycle length."}},
{id:"altbbb",cat:"cond",name:"Alternating bundle branch block",
 feats:["RBBB and LBBB shapes alternating beat to beat (or tracing to tracing)","Sinus rhythm with a P before each QRS","Both bundles diseased","PR may vary too"],
 sig:"Disease of both bundles: a Class I indication for a permanent pacemaker because complete heart block is imminent.",
 hints:["Compare consecutive beats in V1."],sim:["bidir","bifasc","rbbb","lbbb"],
 vs:{bidir:"Bidirectional VT has no P waves and a fast rate.",bifasc:"Bifascicular block keeps one fixed pattern.",rbbb:"Isolated RBBB never changes shape.",lbbb:"Isolated LBBB never changes shape."},
 q2:{q:"Appropriate management?",opts:["Permanent pacemaker","Observation","Beta-blocker","Repeat ECG in a year"],a:0,why:"Failure of both bundles predicts complete heart block."}},
{id:"ivcd",cat:"cond",name:"Nonspecific intraventricular conduction delay",
 feats:["QRS 110 ms or more","Shape fits neither RBBB nor LBBB","Slurring throughout, often low amplitude","Cardiomyopathy, scar or drugs"],
 sig:"Slow cell-to-cell conduction through diseased myocardium rather than one failed bundle. Exclude sodium-channel drugs and hyperkalemia; it predicts worse outcomes in heart failure.",
 hints:["Is there an rsR′ in V1?","A broad notched R in I and V6?"],sim:["lbbb","rbbb","hyperk","tca"],
 vs:{lbbb:"LBBB has a broad monophasic R in I and V6 with QS or rS in V1.",rbbb:"RBBB has rsR′ in V1 and a wide S in I and V6.",tca:"TCA toxicity adds a tall terminal R in aVR and tachycardia.",hyperk:"Hyperkalemia widens the QRS with peaked T and flattened P."}},
/* ---- pacing ---- */
{id:"aai",cat:"pace",name:"Atrial pacing",
 feats:["Pacing spike before each P wave","Paced P may differ in shape from sinus","Native AV conduction: narrow QRS after a normal or long PR","Rate at the programmed lower rate"],
 sig:"For sinus node disease with intact AV conduction. Bipolar atrial spikes are tiny: look at the start of each P.",
 hints:["What precedes each P wave?"],sim:["vpace","nsr","avb1","wap"],
 vs:{vpace:"Ventricular pacing gives a wide QRS after the spike.",nsr:"No spikes and normal sinus P waves.",avb1:"First-degree block has a long PR without spikes.",wap:"Wandering pacemaker has changing P shapes without spikes."}},
{id:"crt",cat:"pace",name:"Biventricular (CRT) pacing",
 feats:["Spikes (often two close together) before each QRS","Paced QRS narrower than RV-only pacing","Dominant R in V1: the LV activates early","Negative or QS in lead I"],
 sig:"Resynchronization pacing restores simultaneous LV contraction in heart failure with LBBB. Loss of LV capture turns the QRS RV-paced (positive in I, negative in V1): arrange a device check.",
 hints:["Compare V1 with a standard RV-paced QRS.","What is lead I doing?"],sim:["vpace","rbbb","lbbb","pacedmi"],
 vs:{vpace:"RV apical pacing gives an LBBB-like QRS: negative V1, positive I.",rbbb:"Native RBBB has no spikes and a triphasic rsR′.",lbbb:"LBBB has a positive I and negative V1.",pacedmi:"Look for concordant ST change, not QRS direction."}},
{id:"undersense",cat:"pace",name:"Pacemaker undersensing",
 feats:["Spikes at the programmed interval regardless of native beats","Spikes land in ST segments or T waves","Some spikes capture, others fall in refractory tissue","Native rhythm present"],
 sig:"The device fails to see native activity (lead dislodgement, small signals, programming, magnet). Spikes on T waves risk R-on-T ventricular arrhythmia. Arrange interrogation.",
 hints:["Do the spikes reset after a native beat?","Where do the spikes land?"],sim:["fcap","oversense","pvc","vpace"],
 vs:{fcap:"Failure to capture: well-timed spikes with no QRS; sensing is intact.",oversense:"Oversensing causes missing spikes and pauses, not extra spikes.",pvc:"PVCs have no spike.",vpace:"Normal pacing inhibits after each native beat."},
 q2:{q:"What is the main danger?",opts:["A spike on a T wave (R-on-T) triggering VF","Hyperkalemia","Heart block","Pacing too slowly"],a:0,why:"A stimulus in the vulnerable period of repolarization can start polymorphic VT or VF."}},
{id:"oversense",cat:"pace",name:"Pacemaker oversensing",
 feats:["Unexpected pause with no pacing spikes","Noise or myopotentials visible during the pause","Pacing resumes after the noise","Native escape may appear"],
 sig:"The device mistakes non-cardiac signals (pectoral myopotentials, lead-fracture noise, electromagnetic interference, T waves) for beats and withholds pacing. Dangerous if pacemaker dependent.",
 hints:["Is there electrical noise during the pause?","Should the pacemaker have fired?"],sim:["sinusarrest","fcap","undersense","artifact"],
 vs:{sinusarrest:"Without a device, a pause has no spikes before or after.",fcap:"In failure to capture spikes are present but no QRS follows.",undersense:"Undersensing adds spikes; oversensing removes them.",artifact:"Artifact alone does not stop the rhythm."}},
{id:"pmt",cat:"pace",name:"Pacemaker-mediated tachycardia",
 feats:["Ventricular-paced tachycardia at or near the upper rate limit","Retrograde P after each paced QRS","Each retrograde P is sensed and triggers the next paced beat","Starts after a PVC or loss of atrial capture"],
 sig:"An endless loop: the device is the antegrade limb and the AV node the retrograde limb. A magnet (asynchronous mode) stops it; lengthening the post-ventricular atrial refractory period prevents it.",
 hints:["What follows each paced QRS?","At what rate is it pacing?"],sim:["vt","vpace","antidromic","stach"],
 vs:{vt:"VT lacks pacing spikes.",vpace:"Normal tracking follows sinus P waves at a physiologic rate.",antidromic:"Antidromic AVRT has no spikes.",stach:"Sinus tachycardia conducts natively."},
 q2:{q:"What terminates it immediately?",opts:["A magnet over the device","Adenosine","Amiodarone","Carotid massage"],a:0,why:"A magnet forces asynchronous pacing, atrial sensing stops and the loop breaks."}},
{id:"tcp",cat:"pace",name:"Transcutaneous pacing: confirming capture",
 feats:["Large pacing artifacts at the set rate","No capture: artifact without a following wide QRS and T","Capture: each artifact followed by a wide QRS and broad T","Confirm mechanical capture with a femoral pulse"],
 sig:"The external artifact is huge and can mimic a QRS. Electrical capture is a wide QRS with a T after every spike; mechanical capture is a pulse at the paced rate. Increase output until both are present.",
 hints:["After each spike, is there a T wave?"],sim:["fcap","vpace","artifact","avb3"],
 vs:{fcap:"Implanted devices produce tiny spikes.",vpace:"A permanent pacemaker gives small spikes with consistent capture.",artifact:"Motion artifact is irregular, not at a set rate.",avb3:"Complete block without pacing shows P waves marching through."}},
/* ---- channelopathies & cardiomyopathies ---- */
{id:"takotsubo",cat:"chan",name:"Takotsubo (stress) cardiomyopathy",
 feats:["Deep, wide, symmetric T inversion across precordial and limb leads","Markedly prolonged QT","No pathologic Q waves (ST elevation early, then T inversion)","Not confined to one coronary territory"],
 sig:"A catecholamine surge (emotional or physical stress, often postmenopausal women; also stroke or seizure) stuns the apical myocardium. Angiography is needed to exclude occlusion. The long QT carries torsades risk.",
 hints:["Do the T waves follow a single coronary territory?","Measure the QT."],sim:["wellens","cerebralT","apicalhcm","antstemi"],
 vs:{wellens:"Wellens T inversion stays in V2–V3 (LAD territory) with a normal QT.",cerebralT:"Cerebral T waves share the catecholamine mechanism; the trigger is an intracranial event.",apicalhcm:"Apical HCM T inversion is chronic, with tall precordial voltage.",antstemi:"Acute STEMI has territorial ST elevation with reciprocal change."}},
{id:"arvc",cat:"chan",name:"Arrhythmogenic right ventricular cardiomyopathy",
 feats:["Epsilon wave: a small notch after the QRS in V1–V3","T inversion in V1–V3 (beyond age 14, without RBBB)","Prolonged terminal activation in V1–V3","PVCs or VT with LBBB shape"],
 sig:"Fibrofatty replacement of RV muscle slows conduction (the epsilon wave is late RV activation) and creates re-entry. A cause of sudden death in young athletes; exertion accelerates the disease. Refer for imaging; avoid competitive sport.",
 hints:["Look just after the QRS in V1.","What are the T waves doing in V1–V3?"],sim:["brugada","rbbb","child","wellens"],
 vs:{brugada:"Brugada is coved ST elevation in V1–V2, not a late notch with T inversion.",rbbb:"RBBB has a wide terminal R′ in V1 and a wide S in I.",child:"Juvenile T inversion in V1–V3 is normal before adolescence and has no epsilon wave.",wellens:"Wellens follows chest pain, in V2–V3, without an epsilon wave."}},
{id:"brugada2",cat:"chan",name:"Brugada type 2 (saddleback)",
 feats:["Saddleback ST in V1–V2: high J point, ST dips, then rises into an upright T","J point elevated 2 mm or more","Not diagnostic alone","May convert to type 1 with fever, sodium-channel blockers, or V1–V2 placed one space higher"],
 sig:"Only the coved type 1 pattern is diagnostic. Type 2 needs high-lead recording or provocation. Treat fever early and avoid sodium-channel blockers (brugadadrugs.org).",
 hints:["Describe the ST shape in V2.","Coved or saddle?"],sim:["brugada","rbbb","erp","v1v2high"],
 vs:{brugada:"Type 1 is coved, falling into an inverted T.",erp:"Early repolarization is lateral or inferior with concave elevation.",v1v2high:"High electrodes give negative P waves and rSr′ without a saddle ST.",rbbb:"RBBB has a wide terminal R′ and wide S in I and V6."}},
{id:"shortqt",cat:"chan",name:"Short QT syndrome",
 feats:["QTc under 340–360 ms","Little or no ST segment: the T starts right after the QRS","Tall, peaked, symmetric precordial T waves","QT barely changes with rate"],
 sig:"Gain-of-function potassium-channel mutations (or loss of calcium current) shorten atrial and ventricular refractoriness: AF and sudden death. Exclude hypercalcemia, hyperkalemia, digoxin and hyperthermia.",
 hints:["Measure the QT and compare it with half the R–R."],sim:["hyperca","hyperk1","dig","nsr"],
 vs:{hyperca:"Hypercalcemia shortens the ST segment while the T itself stays normal.",hyperk1:"Hyperkalemic T waves peak, but the QT is not as short and it reverses.",dig:"Digoxin scoops the ST instead of peaking the T.",nsr:"A normal QTc is 360–450 ms."}},
{id:"lqt3",cat:"chan",name:"Long QT type 3 pattern (late sodium current)",
 feats:["Long, flat, isoelectric ST segment","Late, narrow, often peaked T","Marked QTc prolongation, worst at slow rates","Events at rest or during sleep"],
 sig:"An SCN5A mutation leaves a persistent inward sodium current during the plateau, lengthening it. Mexiletine (late-sodium blocker) shortens the QT; beta-blockers help less than in LQT1.",
 hints:["Is the ST long and flat, or is the T broad?"],sim:["lqt","hypoca","cerebralT","hypothermia"],
 vs:{lqt:"LQT1 has a broad-based T and LQT2 a low, notched T; here the ST is long and the T narrow.",hypoca:"Hypocalcemia gives the same shape; check the calcium.",cerebralT:"Cerebral T waves are giant and inverted.",hypothermia:"Hypothermia adds Osborn waves and shivering."},
 q2:{q:"Which drug specifically shortens the QT in LQT3?",opts:["Mexiletine","Sotalol","Erythromycin","Ondansetron"],a:0,why:"Mexiletine blocks the late sodium current that prolongs the plateau."}},
{id:"apicalhcm",cat:"chan",name:"Apical hypertrophic cardiomyopathy",
 feats:["Giant negative T waves in V2–V5 (often over 10 mm)","High precordial QRS voltage","No Q waves","Chronic and stable on serial tracings"],
 sig:"Hypertrophy confined to the apex (Yamaguchi syndrome). Mistaken for ischemia; echo or MRI shows the spade-shaped LV cavity.",
 hints:["How tall is the QRS?","Do the T waves change over time?"],sim:["wellens","takotsubo","lvh","cerebralT"],
 vs:{wellens:"Wellens T inversion is in V2–V3 without high voltage and evolves after chest pain.",takotsubo:"Takotsubo is acute, with long QT and normal voltage.",lvh:"Typical LVH strain is asymmetric lateral T inversion.",cerebralT:"Cerebral T waves come with a very long QT and a neurologic event."}},
{id:"amyloid",cat:"chan",name:"Cardiac amyloidosis",
 feats:["Low QRS voltage in the limb leads","Pseudo-infarct pattern: QS or poor R progression in V1–V3","Thick walls on echo despite low voltage (voltage–mass mismatch)","AV block or AF common"],
 sig:"Amyloid infiltrates and replaces myocytes: mass rises but electrically active tissue falls. Low voltage with thick walls should prompt testing for transthyretin or light-chain amyloidosis.",
 hints:["Check the limb lead voltages.","What voltage would thick walls normally produce?"],sim:["effusion","copd","oldimi","lvh"],
 vs:{effusion:"Effusion lowers voltage with tachycardia and alternans; the walls are not thick.",copd:"Emphysema lowers voltage with a rightward axis and P pulmonale.",lvh:"True hypertrophy raises voltage.",oldimi:"A true infarct Q is localized with a matching wall-motion defect."}},
/* ---- structure ---- */
{id:"asd",cat:"struct",name:"Atrial septal defect (secundum)",
 feats:["Incomplete RBBB (rSr′ in V1, QRS under 120 ms)","Right axis deviation","Notch near the R-wave peak in II, III, aVF (crochetage)","First-degree AV block or atrial arrhythmias in adults"],
 sig:"A left-to-right shunt volume-loads the right ventricle and delays activation of its outflow tract. Crochetage in all three inferior leads is highly specific.",
 hints:["Look at V1.","Look closely at the top of the inferior R waves."],sim:["rbbb","rvh","brugada2","nsr"],
 vs:{rbbb:"Complete RBBB has a QRS of 120 ms or more.",rvh:"RVH has a dominant R in V1 with strain and a tall P.",brugada2:"Brugada type 2 adds a saddleback ST.",nsr:"A normal V1 is rS."}},
{id:"copd",cat:"struct",name:"Chronic lung disease (emphysema) pattern",
 feats:["Low QRS voltage, especially in the limb leads and V5–V6","Right or indeterminate axis","P pulmonale: tall, peaked P in II, III, aVF","Poor R progression; often sinus tachycardia or MAT"],
 sig:"Hyperinflated lungs insulate the heart and push it down and vertical; pulmonary hypertension adds right atrial and ventricular strain.",
 hints:["Compare P height with QRS height in II.","Why might the voltage be low?"],sim:["effusion","amyloid","rvh","pe"],
 vs:{effusion:"Effusion lowers voltage with alternans and no P pulmonale.",amyloid:"Amyloid lowers voltage with pseudo-infarct Q waves and a normal P.",pe:"PE is acute: S1Q3T3 with T inversion V1–V4.",rvh:"RVH has a dominant R in V1 and normal or high voltage."}},
/* ---- normal variants ---- */
{id:"athlete",cat:"normal",name:"Athlete's heart",
 feats:["Sinus bradycardia (often 40–50)","First-degree AV block","High QRS voltage meeting LVH criteria","Early repolarization"],
 sig:"Training raises vagal tone and muscle mass. Not explained by training and needing work-up: lateral T inversion, pathologic Q waves, LBBB, epsilon waves, Brugada type 1, long or short QT, pre-excitation.",
 hints:["What does high vagal tone do to rate and PR?"],sim:["lvh","erp","sbrady","avb1"],
 vs:{lvh:"Pathologic LVH adds strain (lateral ST depression, T inversion) and left atrial enlargement.",erp:"The same repolarization without the bradycardia and voltage.",sbrady:"Plain sinus bradycardia lacks the voltage and repolarization changes.",avb1:"Isolated first-degree block without the training picture."}},
{id:"child",cat:"normal",name:"Normal pediatric ECG",
 feats:["Faster rate and shorter intervals than adults","Right axis and prominent R in V1 (RV dominance from fetal life)","T inversion in V1–V3 is normal from the first week to adolescence","Prominent sinus arrhythmia"],
 sig:"The fetal right ventricle pumps against systemic pressure, so it starts as thick as the left; the adult pattern emerges through childhood. An upright T in V1 after the first week (before adolescence) suggests RVH.",
 hints:["Which ventricle dominates at birth?"],sim:["rvh","wellens","arvc","stach"],
 vs:{rvh:"In an adult, a dominant R in V1 with right axis is RVH.",arvc:"In an adult, T inversion in V1–V3 raises concern for ARVC.",wellens:"Wellens is an adult ischemic pattern after chest pain.",stach:"The rate is normal for age."}},
/* ---- electrolytes & drugs, staged ---- */
{id:"hyperk1",cat:"meta",name:"Hyperkalemia, early: peaked T",
 feats:["Tall, narrow-based, symmetric, tented T waves","Most visible in V2–V4 and II","Normal P, PR and QRS","QT normal or short"],
 sig:"Often around K⁺ 5.5–6.5 mmol/L, though the ECG correlates loosely with the level. Stop potassium sources, shift with insulin and glucose, treat the cause; give calcium as soon as the P or QRS changes.",
 hints:["Is the base of the T narrow or broad?"],sim:["hyperT","erp","hyperk","shortqt"],
 vs:{hyperT:"Hyperacute T waves are broad-based and territorial.",hyperk:"Moderate hyperkalemia adds P flattening, PR lengthening and QRS widening.",erp:"Early repolarization T waves are broad and come with J notching.",shortqt:"Short QT syndrome is lifelong, with a very short QT."}},
{id:"hyperk3",cat:"meta",name:"Hyperkalemia, severe: no P waves, wide QRS",
 feats:["P waves lost","Very wide QRS","Peaked T","Slow, regular rhythm approaching a sine wave"],
 sig:"Usually K⁺ above 8 mmol/L and pre-arrest. IV calcium immediately, then insulin-glucose, beta-agonist and dialysis. Atropine works poorly.",
 hints:["Can you find P waves?","How wide is the QRS?"],sim:["hyperk2","aivr","avb3","junct"],
 vs:{hyperk2:"The sine wave is the next stage: QRS and T merge.",aivr:"AIVR has normal T waves at 60–100.",avb3:"Complete block shows P waves marching through.",junct:"Junctional rhythm has a narrow QRS."},
 q2:{q:"First treatment?",opts:["IV calcium","Atropine","Amiodarone","Adenosine"],a:0,why:"Calcium raises the threshold potential, restoring the gap between resting and threshold potential within minutes."}},
{id:"brash",cat:"meta",name:"BRASH syndrome",
 feats:["Bradycardia, often junctional, without visible P waves","Only moderately peaked T waves","Renal failure, AV-nodal blockers and hyperkalemia together","Narrow or mildly wide QRS"],
 sig:"Bradycardia, Renal failure, AV-nodal blockade, Shock, Hyperkalemia: modest hyperkalemia and AV blockers act synergistically in a vicious cycle. Treat every part: calcium, insulin-glucose, fluids, stop blockers, epinephrine if needed.",
 hints:["Is the potassium effect alone enough to explain this?"],sim:["junct","hyperk3","sbrady","avb3"],
 vs:{junct:"A benign junctional rhythm lacks the metabolic context and peaked T.",hyperk3:"Severe hyperkalemia alone widens the QRS markedly.",sbrady:"Sinus bradycardia has P waves.",avb3:"Complete block shows dissociated P waves."}},
{id:"hypok2",cat:"meta",name:"Hypokalemia, severe",
 feats:["Large U waves exceeding the T","T flat or inverted, ST depression","Apparent long QT (really QU)","Frequent PVCs; risk of torsades and VF"],
 sig:"Usually K⁺ under 2.5 mmol/L. Replace potassium and magnesium with monitoring. Repolarization reserve is low, so QT-prolonging drugs are hazardous.",
 hints:["What is the wave after the T?","What is the rhythm doing?"],sim:["hypok","lqt","dig","hypomg"],
 vs:{hypok:"Milder hypokalemia shows a small U wave without ectopy.",lqt:"In long QT the T itself is long; here the T is small and the U large.",dig:"Digoxin scoops the ST and shortens the QT.",hypomg:"Hypomagnesemia lengthens the T itself."}},
{id:"hypomg",cat:"meta",name:"Hypomagnesemia",
 feats:["QT prolongation with broad T and U waves","PVCs, R-on-T","Usually with low potassium and calcium","Torsades risk"],
 sig:"Magnesium is a cofactor for the Na⁺/K⁺-ATPase and steadies L-type calcium channels. Low magnesium lowers potassium and promotes early afterdepolarizations. Give IV magnesium; potassium will not correct until magnesium does.",
 hints:["Measure the QT.","Where does the PVC fall?"],sim:["lqt","hypok2","hypoca","tdp"],
 vs:{lqt:"The ECG alone cannot separate them; check magnesium in every long QT.",hypoca:"Hypocalcemia lengthens the ST with a normal T.",hypok2:"Severe hypokalemia shrinks the T and enlarges the U.",tdp:"Torsades is the arrhythmia this substrate produces."}},
{id:"renal",cat:"meta",name:"Renal failure: high K⁺ with low Ca²⁺",
 feats:["Peaked, narrow T waves (hyperkalemia)","Long, flat ST segment (hypocalcemia)","LVH voltage from hypertension","Long QT ending in a peaked T"],
 sig:"Kidney failure pairs hyperkalemia with hypocalcemia, and both are visible at once because each acts on a different phase of the action potential: K⁺ on phase 3, Ca²⁺ on phase 2.",
 hints:["Look at the ST segment and the T wave separately."],sim:["hyperk1","hypoca","lvh","lqt"],
 vs:{hyperk1:"Hyperkalemia alone has a normal or short QT.",hypoca:"Hypocalcemia alone has a normal T shape.",lvh:"LVH alone has asymmetric lateral strain.",lqt:"Long QT syndromes broaden or notch the T."}},
{id:"digtox",cat:"meta",name:"Digoxin toxicity: “regularized” AF",
 feats:["Fibrillatory atrial baseline","Regular ventricular rhythm: complete AV block with a junctional escape","Scooped ST depression","Rate often 40–70"],
 sig:"In AF the ventricular rhythm should be irregular; regularity means the AV node is blocked and an escape focus has taken over. Check potassium, renal function and the digoxin level; give digoxin-specific antibody fragments for dangerous rhythms.",
 hints:["AF should be irregular. Is it?"],sim:["af","junct","dig","avb3"],
 vs:{af:"Ordinary AF is irregularly irregular.",dig:"Therapeutic digoxin effect: scooped ST with an expected rhythm.",junct:"A junctional rhythm without fibrillatory waves.",avb3:"Complete block from other causes shows sinus P waves."},
 q2:{q:"What explains the regular rhythm?",opts:["Complete AV block with a junctional escape","Conversion to sinus rhythm","Atrial flutter","Good rate control"],a:0,why:"Digoxin's vagal effect plus direct toxicity blocks the AV node while enhancing junctional automaticity."}},
{id:"flec",cat:"meta",name:"Class IC (flecainide) toxicity",
 feats:["Long PR and wide QRS (worse at faster rates)","Brugada-like coved ST in V1–V2 possible","Bradycardia, or a wide-complex tachycardia","QT long mainly from QRS widening"],
 sig:"Sodium-channel block with slow unbinding. Treat with sodium bicarbonate (sodium load plus alkalinization) and avoid other sodium blockers; flutter on flecainide can conduct 1:1 with a wide QRS.",
 hints:["Is every conduction interval longer?"],sim:["tca","hyperk","ivcd","brugada"],
 vs:{tca:"TCA toxicity is tachycardic with a tall R in aVR (anticholinergic).",hyperk:"Hyperkalemia peaks the T and flattens the P.",ivcd:"IVCD from scar leaves the PR normal.",brugada:"Congenital Brugada has a normal PR and QRS."},
 q2:{q:"Which treatment counters the sodium-channel block?",opts:["Sodium bicarbonate","Amiodarone","Procainamide","Magnesium"],a:0,why:"A sodium load and alkalinization reduce drug binding and restore phase 0 current."}},
/* ---- mimics & technical ---- */
{id:"cerebralT",cat:"mimic",name:"Cerebral T waves",
 feats:["Giant, wide, inverted T waves, often over 10 mm","Markedly prolonged QT","Bradycardia, U waves","Widespread, not territorial"],
 sig:"Subarachnoid or intracerebral hemorrhage, or raised intracranial pressure, triggers a catecholamine and autonomic storm on the myocardium. Recognize it before sending a neurologic emergency to the cath lab.",
 hints:["What is the QT?","Do the T waves follow a coronary territory?"],sim:["takotsubo","wellens","apicalhcm","lqt"],
 vs:{takotsubo:"Takotsubo shares the catecholamine mechanism; the trigger and wall-motion pattern differ.",wellens:"Wellens stays in V2–V3 with a normal QT.",lqt:"Congenital long QT does not produce giant inverted T waves.",apicalhcm:"Apical HCM has high voltage and a normal QT."},
 q2:{q:"Which event most likely explains this tracing?",opts:["Subarachnoid hemorrhage","Hypokalemia","Pericarditis","Pulmonary embolism"],a:0,why:"The sympathetic surge from the brain injures myocardium and delays repolarization."}},
{id:"v1v2high",cat:"mimic",name:"V1 and V2 placed too high",
 feats:["Negative or biphasic P in V1 and V2","rSr′ resembling incomplete RBBB","T inversion in V1–V2","Normal limb leads"],
 sig:"Electrodes in the second intercostal space look down on the atria and outflow tract. Mimics RBBB, Brugada type 2, old anterior MI or Wellens; check placement before acting.",
 hints:["What is the P doing in V1?"],sim:["brugada2","rbbb","oldimi","wellens"],
 vs:{brugada2:"Brugada type 2 has a saddleback ST with a normal P.",rbbb:"RBBB widens the QRS and slurs the S in I and V6.",oldimi:"Infarct Q waves persist with correct placement.",wellens:"Wellens follows chest pain and does not invert the P."}},
{id:"lallrev",cat:"mimic",name:"LA/LL electrode reversal",
 feats:["Lead III inverted","I and II swap; aVL and aVF swap","P taller in I than in II (normally II is larger)","Precordial leads unaffected"],
 sig:"Easy to miss; it can create or hide inferior Q waves. A P wave larger in I than in II is the clue.",
 hints:["Compare the P wave in I with II."],sim:["lrrev","oldimi","lafb","nsr"],
 vs:{lrrev:"LA/RA reversal inverts lead I.",oldimi:"True inferior Q waves come without a P-wave swap.",lafb:"LAFB changes the QRS axis, not the P.",nsr:"Normally the P is tallest in II."}},
{id:"rarl",cat:"mimic",name:"RA/RL electrode reversal",
 feats:["Lead II almost flat","aVR and aVF nearly identical","Lead I looks like an inverted III","Precordial leads normal"],
 sig:"One flat limb lead is the giveaway: it records between the left-leg electrode and the ground electrode, both on the legs.",
 hints:["Which lead is flat?"],sim:["lrrev","lallrev","effusion","dextro"],
 vs:{lrrev:"LA/RA reversal inverts lead I without a flat lead.",effusion:"Low voltage in every lead, not one.",lallrev:"LA/LL reversal inverts III without a flat lead.",dextro:"Dextrocardia also changes the precordial leads."}},
{id:"cpr",cat:"mimic",name:"CPR artifact",
 feats:["Large regular waves at the compression rate (100–120/min)","Disappear the moment compressions stop","True rhythm visible only in the pause","Identical in leads sharing an electrode"],
 sig:"Compressions move electrodes and change impedance. Pause briefly (under 10 seconds) to see the real rhythm; here fine VF in the pause means defibrillate.",
 hints:["What happens when compressions stop?"],sim:["vt","vf","artifact","vflutter"],
 vs:{vt:"VT persists without compressions.",vf:"VF is the true rhythm here; the large waves are artifact.",artifact:"Motion artifact without compressions is irregular.",vflutter:"Ventricular flutter is faster and continues without compressions."},
 q2:{q:"What does the pause show, and what next?",opts:["Fine VF: defibrillate","Asystole: epinephrine only","Organized rhythm: check a pulse","Sinus rhythm: stop CPR"],a:0,why:"Low-amplitude chaotic activity is a shockable rhythm."}},
{id:"tremor",cat:"mimic",name:"Tremor artifact (pseudo-flutter)",
 feats:["Regular 4–6 Hz oscillation","Present in leads using the affected limb, absent in others","Sinus P waves and QRS complexes march on time","Mimics flutter waves near 300/min"],
 sig:"Parkinsonian or essential tremor can imitate flutter or AF. Find a lead that does not use the trembling limb (here II, which skips the left arm) and confirm sinus P waves.",
 hints:["Is the oscillation in every lead?"],sim:["flutter","af","artifact","atypflut"],
 vs:{flutter:"Flutter waves appear in every lead facing the atria and the QRS follows them.",af:"In AF the R–R is irregular.",artifact:"Motion artifact is irregular.",atypflut:"Atypical flutter is present in all inferior leads and V1."}},
{id:"vswap",cat:"mimic",name:"Precordial cable swap (V2/V4)",
 feats:["R-wave progression breaks: V2 looks like V4 and vice versa","QRS and T jump abruptly between neighbors","Limb leads normal","Mimics infarction or poor R progression"],
 sig:"Precordial leads should change gradually from V1 to V6. A reversal that then returns to normal points to swapped cables, not disease.",
 hints:["Does the R wave grow smoothly from V1 to V6?"],sim:["oldimi","lvan","dextro","v1v2high"],
 vs:{dextro:"Dextrocardia shows R waves shrinking steadily across all six leads plus an inverted lead I.",lvan:"Aneurysm has QS waves with persistent ST elevation.",oldimi:"Infarct changes follow a territory.",v1v2high:"High electrodes affect only V1–V2 and invert the P."}}
);
P.forEach(p=>PM[p.id]=p);
