
/* ============ shared UI helpers for the deep-dive sections ============ */
const AX={built:{},cur:'pat',draws:{}};
const cssx=()=>{const s=getComputedStyle(document.documentElement),v=n=>s.getPropertyValue(n).trim();return{ink:v('--ink'),muted:v('--muted'),line:v('--line'),grid:v('--grid'),major:v('--grid-major'),trace:v('--trace'),accent:v('--accent'),mark:v('--mark'),panel:v('--panel'),good:v('--good'),bad:v('--bad'),warn:v('--warn'),soft:v('--soft'),paper:v('--paper'),gmin:v('--gmin'),gmaj:v('--gmaj'),mono:v('--font-mono'),ui:v('--font-ui')}};
function cvSetup(c,hpx){const r=c.getBoundingClientRect();if(r.width<2)return null;const d=window.devicePixelRatio||1,w=Math.round(r.width),h=hpx||Math.round(r.height);if(hpx)c.style.height=hpx+'px';if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}const g=c.getContext('2d');g.setTransform(d,0,0,d,0,0);g.clearRect(0,0,w,h);return{g,w,h,C:cssx()}}
function mkCanvas(host,h){const c=el('canvas');c.style.cssText='display:block;width:100%;height:'+h+'px';host.appendChild(c);return c}
function slider(host,label,o,on){const L=!!o.log,toV=x=>L?o.min*Math.pow(o.max/o.min,x/1000):x,toX=v=>L?1000*Math.log(v/o.min)/Math.log(o.max/o.min):v;
  const w=el('label','sl');w.innerHTML=`<span class="sn">${label}</span><input type="range" min="${L?0:o.min}" max="${L?1000:o.max}" step="${L?1:o.step}" value="${toX(o.val)}"><output></output>`;
  const i=$('input',w),out=$('output',w);const upd=()=>{out.textContent=o.fmt?o.fmt(toV(+i.value)):toV(+i.value)};
  i.addEventListener('input',()=>{upd();on(toV(+i.value))});upd();host.appendChild(w);return{get:()=>toV(+i.value),set:v=>{i.value=toX(v);upd()},input:i}}
function segment(host,opts,cur,on){const s=el('div','seg');s.setAttribute('role','group');opts.forEach(([v,t])=>{const b=el('button',null,t);b.type='button';b.dataset.v=v;b.setAttribute('aria-pressed',String(v===cur));b.addEventListener('click',()=>{$$('button',s).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));on(v)});s.appendChild(b)});host.appendChild(s);return s}
function fmtSI(v,u){const a=Math.abs(v),p=[[1e9,'G'],[1e6,'M'],[1e3,'k'],[1,''],[1e-3,'m'],[1e-6,'µ'],[1e-9,'n'],[1e-12,'p']];for(const[s,x]of p)if(a>=s*.9995)return(+(v/s).toPrecision(3))+' '+x+u;return(+v.toPrecision(3))+' '+u}
/* single-lead ECG strip on paper. rows: [{data,label,color?}]; o: {t0,dur,gain,speed,rowMM,minPm,overlay(g,geo)} */
function drawStrip(cv,rows,o={}){const r0={width:(cv.parentElement&&cv.parentElement.clientWidth)||cv.getBoundingClientRect().width||600};const s=o.speed||25,gain=o.gain||10,rowMM=o.rowMM||26,LM=o.cal===false?2:3+.2*s+2,Wmm=LM+o.dur*s+2,pm=Math.min(o.maxPm||5.2,Math.max(o.minPm||2.6,(r0.width||600)/Wmm)),W=Math.round(Wmm*pm),Hmm=rowMM*rows.length+(o.foot?5:2)+(o.extra||0),H=Math.round(Hmm*pm+(o.top||0));
  cv.style.width=W+'px';const S=cvSetup(cv,H);if(!S)return null;const{g,C}=S,TOP=o.top||0,X=t=>(LM+(t-o.t0)*s)*pm;
  g.fillStyle=C.panel;g.fillRect(0,0,W,H);g.fillStyle=C.paper;g.fillRect(0,TOP,W,H-TOP);
  if(pm>=2.4){g.strokeStyle=C.gmin;g.lineWidth=1;g.beginPath();for(let m=0;m<=Wmm;m++){if(m%5===0)continue;const x=Math.round(m*pm)+.5;g.moveTo(x,TOP);g.lineTo(x,H)}for(let m=0;m<=Hmm;m++){if(m%5===0)continue;const y=Math.round(TOP+m*pm)+.5;g.moveTo(0,y);g.lineTo(W,y)}g.stroke()}
  g.strokeStyle=C.gmaj;g.beginPath();for(let m=0;m<=Wmm;m+=5){const x=Math.round(m*pm)+.5;g.moveTo(x,TOP);g.lineTo(x,H)}for(let m=0;m<=Hmm;m+=5){const y=Math.round(TOP+m*pm)+.5;g.moveTo(0,y);g.lineTo(W,y)}g.stroke();
  const geo={pm,X,LM,s,gain,rows:[],TOP,W,H,rowMM};
  rows.forEach((rw,k)=>{const base=TOP+(k*rowMM+rowMM*(o.base??.6))*pm;geo.rows.push({base,top:TOP+k*rowMM*pm,bot:TOP+(k+1)*rowMM*pm});const d=rw.data,i0=Math.max(0,Math.floor(o.t0*FS)),i1=Math.min(d.length-1,Math.ceil((o.t0+o.dur)*FS));
    if(o.cal!==false){g.strokeStyle=C.trace;g.lineWidth=Math.max(1,pm*.32);g.beginPath();g.moveTo(.5*pm,base);g.lineTo(2*pm,base);g.lineTo(2*pm,base-gain*pm);g.lineTo((2+.2*s)*pm,base-gain*pm);g.lineTo((2+.2*s)*pm,base);g.lineTo((3+.2*s)*pm,base);g.stroke()}
    g.save();g.beginPath();g.rect(LM*pm-1,TOP,W,H-TOP);g.clip();g.strokeStyle=rw.color||C.trace;g.lineWidth=rw.lw||Math.max(1,pm*.34);g.lineJoin='round';g.beginPath();for(let i=i0;i<=i1;i++){const x=X(i/FS),y=base-d[i]*gain*pm;i===i0?g.moveTo(x,y):g.lineTo(x,y)}g.stroke();g.restore();
    if(rw.label){g.font='600 12px '+C.ui;const tw=g.measureText(rw.label).width;g.fillStyle=C.panel;g.globalAlpha=.85;g.fillRect(LM*pm+3,TOP+k*rowMM*pm+3,tw+8,17);g.globalAlpha=1;g.fillStyle=rw.lc||C.ink;g.textAlign='left';g.fillText(rw.label,LM*pm+7,TOP+k*rowMM*pm+16)}});
  if(o.foot){g.fillStyle=C.muted;g.font='11px '+C.mono;g.textAlign='right';g.fillText(o.foot,W-6,H-5)}
  if(o.overlay)o.overlay(g,geo,C);return geo}
/* simple rhythm-strip helper: render one lead of a record with no noise filtering beyond diagnostic */
function stripLead(rec,lead,filt='diag'){return leadData(rec,{filt,notch:false})[lead]}
const leadTerr=k=>({I:'lateral',aVL:'lateral',V5:'lateral',V6:'lateral',II:'inferior',III:'inferior',aVF:'inferior',V1:'septal',V2:'septal',V3:'anterior',V4:'anterior',aVR:'aVR'})[k];

/* ============ atlas: systematic read ============ */
function boxLeads(g,G,C,leads,col,lw=2.2){leads.forEach(l=>{const c=G.cellOf[l];if(!c)return;g.strokeStyle=col;g.lineWidth=lw;g.globalAlpha=.9;g.strokeRect(c.x0+1.5,c.y0+2.5,c.x1-c.x0-3,c.y1-c.y0-5);g.globalAlpha=.08;g.fillStyle=col;g.fillRect(c.x0+1.5,c.y0+2.5,c.x1-c.x0-3,c.y1-c.y0-5);g.globalAlpha=1})}
function stripRow(G){const c=G.rows[G.rows.length-1].cells[0];return{top:c.y0,bot:c.y1}}
function bracket(g,G,C,t0,t1,y,txt,col){const x0=G.X(t0),x1=G.X(t1);g.strokeStyle=col;g.fillStyle=col;g.lineWidth=2;g.beginPath();g.moveTo(x0,y-5);g.lineTo(x0,y+5);g.moveTo(x0,y);g.lineTo(x1,y);g.moveTo(x1,y-5);g.lineTo(x1,y+5);g.stroke();g.font='600 11px '+C.ui;g.textAlign='center';const tw=g.measureText(txt).width;g.globalAlpha=.9;g.fillStyle=C.panel;g.fillRect((x0+x1)/2-tw/2-4,y-19,tw+8,15);g.globalAlpha=1;g.fillStyle=col;g.fillText(txt,(x0+x1)/2,y-8)}
function tick(g,G,C,t,y0,y1,col,txt){const x=G.X(t);g.strokeStyle=col;g.lineWidth=2;g.beginPath();g.moveTo(x,y0);g.lineTo(x,y1);g.stroke();if(txt){g.fillStyle=col;g.font='600 10px '+C.ui;g.textAlign='center';g.fillText(txt,x,y0-3)}}
function pickBeat(R,lo=2.6,hi=7.4){const qs=R.ev.q.filter(q=>q.t>lo&&q.t<hi&&q.k!=='s'),c=qs.filter(q=>q.from!=null);return(c.length?c:qs)[Math.floor((c.length?c:qs).length/2)]||R.ev.q[0]}
const SYS=[
{t:'Technical check',how:'Before interpreting, confirm the calibration pulse (10 mm = 1 mV), paper speed (25 mm/s), filter setting, and that the tracing is clean. Then screen for lead reversal: an inverted P, QRS and T in lead I with an upright aVR means arm leads reversed (or dextrocardia if the chest leads also lose progression).',
 ov:(R)=>(g,G,C)=>{G.rows.forEach(rw=>{const b=rw.cells[0].base;g.strokeStyle=C.mk;g.lineWidth=2;g.strokeRect(1.2*G.pm,b-(G.g+2)*G.pm,(1.5+.2*G.s)*G.pm,(G.g+4)*G.pm)})},
 on:(R)=>{const m=R.ms;if(!m)return'No organized complexes: check the patient, then the leads. A flat or chaotic trace in every lead may be arrest, or a disconnected cable.';const I=m.leads.I,aVR=m.leads.aVR;const inv=I.area<0&&(I.pmin<-.03||I.pa<.02)&&aVR.area>0;let s=`Calibration 10 mm/mV at 25 mm/s. Lead I: P ${I.pa>.03?'upright':I.pmin<-.03?'inverted':'flat'}, net QRS ${I.area>=0?'positive':'negative'}. aVR: net QRS ${aVR.area>=0?'positive':'negative'}.`;
   if(inv)s+=' <b>Lead I is globally inverted with a positive aVR: suspect arm-lead reversal, or dextrocardia if the chest leads also look abnormal.</b>';if(Object.keys(R.ela).length)s+=' <b>There is large artifact on part of the tracing: work out which electrode it involves.</b>';return s}},
{t:'Rate',how:'Regular rhythm: 300 ÷ the number of large boxes between two R waves (or 1500 ÷ small boxes). Irregular rhythm: count QRS complexes on the 10-second strip and multiply by 6. Memorize the sequence 300, 150, 100, 75, 60, 50 for consecutive heavy lines.',
 ov:(R)=>(g,G,C)=>{const qs=R.ev.q.filter(q=>q.t>3&&q.t<8.5&&q.k!=='s');if(qs.length<2)return;const a=qs[0],b=qs[1],sr=stripRow(G);bracket(g,G,C,a.t+.04,b.t+.04,sr.top+10,`R–R ${Math.round((b.t-a.t)*1000)} ms = ${((b.t-a.t)/.2).toFixed(1)} large boxes`,C.mk)},
 on:(R)=>{const M=R.meta;if(!M.hr)return'No measurable ventricular rate.';const qs=R.ev.q.filter(q=>q.t>=0&&q.t<DUR&&q.k!=='s');const qq=R.ev.q.filter(q=>q.t>3&&q.t<8.5&&q.k!=='s');const rr=qq.length>1?qq[1].t-qq[0].t:60/M.hr;
   return`Marked R–R ${Math.round(rr*1000)} ms: 300 ÷ ${(rr/.2).toFixed(1)} = <b>${Math.round(300/(rr/.2))}/min</b>. 1500 ÷ ${(rr/.04).toFixed(0)} small boxes = ${Math.round(1500/(rr/.04))}/min. Ten-second count: ${qs.length} complexes × 6 = <b>${qs.length*6}/min</b>. Mean ventricular rate ${M.hr}/min${M.arate?`; atrial rate about ${M.arate}/min`:''}.`}},
{t:'Rhythm',how:'Is the R–R regular? Is there a P wave before every QRS, a QRS after every P, and is the PR constant? Are the P waves upright in II (sinus) or inverted (retrograde)? Use calipers to march out P waves and R waves separately; dissociation, dropped beats and hidden P waves appear when you do.',
 ov:(R)=>(g,G,C)=>{const sr=stripRow(G);R.ev.p.filter(p=>p.t>-.05&&p.t<DUR).forEach(p=>tick(g,G,C,p.t+.04,sr.top+18,sr.top+30,p.cond?C.mk:C.bad,'P'));R.ev.q.filter(q=>q.t>0&&q.t<DUR&&q.k!=='s').forEach(q=>tick(g,G,C,q.t+.03,sr.bot-14,sr.bot-4,C.ac))},
 on:(R)=>{const qs=R.ev.q.filter(q=>q.t>=0&&q.t<DUR&&q.k!=='s'),ps=R.ev.p.filter(p=>p.t>=0&&p.t<DUR),rr=qs.slice(1).map((q,i)=>q.t-qs[i].t);if(!qs.length)return'No QRS complexes.';
   const v=rr.length?Math.round((Math.max(...rr)-Math.min(...rr))*1000):0,cond=qs.filter(q=>q.from!=null).length,blocked=ps.filter(p=>!p.cond).length;
   let s=`R–R varies by ${v} ms across the strip (${v<120?'regular':'irregular'}). ${ps.length} P waves, ${qs.length} QRS complexes. `;
   if(!ps.length)s+='No discrete P waves: look at V1 and II for fibrillatory or flutter waves, or retrograde P waves near the QRS.';else if(cond===qs.length&&!blocked)s+='Every QRS is preceded by a P wave.';else if(cond===0)s+='No P wave consistently precedes a QRS: the atria and ventricles are dissociated or the P waves are retrograde.';else s+=`${cond} of ${qs.length} QRS complexes follow a P wave; ${blocked} P wave${blocked===1?' is':'s are'} not followed by a QRS or are dissociated.`;
   const ws=qs.filter(q=>q.k==='v').length;if(ws&&ws<qs.length)s+=` ${ws} beat${ws>1?'s are':' is'} wide and premature without a P.`;return s+' (Red P ticks are not conducted.)'}},
{t:'Axis',how:'Look at the net QRS in lead I and aVF. Both positive: normal. I positive, aVF negative: check lead II; positive means normal (to −30°), negative means left axis deviation. I negative, aVF positive: right axis deviation. Both negative: extreme axis. The lead with an equiphasic QRS is perpendicular to the axis.',
 ov:()=>(g,G,C)=>boxLeads(g,G,C,['I','aVF','II'],C.mk),
 on:(R)=>{const m=R.ms;if(!m)return'No organized QRS.';const sg=v=>v>=0?'positive':'negative',a=m.axis;return`Net QRS: I ${sg(m.leads.I.area)}, aVF ${sg(m.leads.aVF.area)}, II ${sg(m.leads.II.area)}. Axis about <b>${a}°</b>: ${['normal','left axis deviation','right axis deviation','extreme ("northwest") axis'][axisCat(a)]}.`}},
{t:'Intervals',how:'PR 120–200 ms (start of P to start of QRS). QRS under 110 ms; 120 ms or more means bundle-branch block, ventricular origin, pacing, pre-excitation or toxicity. QT from QRS onset to the end of the T wave (tangent method), corrected for rate: Bazett QT/√RR, Fridericia QT/∛RR. A QT more than half the R–R interval is usually long.',
 ov:(R)=>(g,G,C)=>{if(!R.tm)return;const b=pickBeat(R),m=b.m,sr=stripRow(G),y=sr.bot-8;if(b.from!=null&&R.tm.pr!=null){const p=R.ev.p[b.from];bracket(g,G,C,p.t,b.t+m.on,y-30,'PR',C.mk)}bracket(g,G,C,b.t+m.on,b.t+m.off,y-14,'QRS',C.ac);bracket(g,G,C,b.t+m.on,b.t+m.qt,y,'QT',C.good)},
 on:(R)=>{const M=R.meta;if(!R.tm)return'No intervals to measure.';return`PR ${M.pr!=null&&!['var','none'].includes(M.prq)?'<b>'+M.pr+' ms</b>':'<b>not fixed</b>'} · QRS <b>${M.qrs} ms</b> · QT <b>${M.qt} ms</b>${M.qtcB?`, QTc Bazett <b>${M.qtcB}</b>, Fridericia <b>${M.qtcF}</b> ms`:''}.${M.qrs>=120?' The QRS is wide.':''}${M.qtcF>470||M.qtcB>480?' The QTc is prolonged.':''}${M.qtcB&&M.qtcB<350?' The QTc is short.':''}${M.pr>200&&M.prq==='long'?' First-degree AV delay.':''}${M.prq==='short'?' Short PR: look for a delta wave or a junctional origin.':''}`}},
{t:'P waves',how:'Lead II and V1 tell most of the story. Normal P: under 120 ms and under 2.5 mm in II, upright in I and II. Tall peaked P (2.5 mm or more) suggests right atrial enlargement; a broad notched P in II (120 ms or more) with a deep, wide terminal negative component in V1 suggests left atrial enlargement.',
 ov:()=>(g,G,C)=>boxLeads(g,G,C,['II','V1'],C.mk),
 on:(R)=>{if(!R.tm||!R.tm.pm||R.tm.pr==null)return'No consistent P waves to assess.';const L=R.ms.leads,pm=R.tm.pm,on=Math.min(...pm.map(b=>b.c-2.4*b.wl)),off=Math.max(...pm.map(b=>b.c+2.4*(b.wr??b.wl))),dur=Math.round((off-on)*1000);
   let s=`P in II ${(L.II.pa*10).toFixed(1)} mm tall, about ${dur} ms long. V1 terminal negativity ${(-L.V1.pmin*10).toFixed(1)} mm. Lead I P ${L.I.pa>.02?'upright':'not upright'}.`;if(L.II.pa>=.25)s+=' <b>Tall P: right atrial enlargement.</b>';if(dur>=118||L.V1.pmin<-.1)s+=' <b>Broad P with deep terminal V1 component: left atrial enlargement.</b>';if(L.II.pa<.05)s+=' <b>Flat or tiny P waves.</b>';return s}},
{t:'QRS complex',how:'Look for pathologic Q waves (40 ms or more, or a quarter of the R height, in two contiguous leads), voltage for hypertrophy (Sokolow–Lyon S V1 + R V5/V6 of 35 mm or more; Cornell R aVL + S V3), R-wave progression (transition by V3–V4), and bundle-branch shapes (rsR′ in V1 for RBBB; broad R in I and V6 with QS in V1 for LBBB).',
 ov:(R)=>(g,G,C)=>{if(!R.ms)return;boxLeads(g,G,C,sysQ(R),C.mk)},
 on:(R)=>{if(!R.ms)return'No organized QRS.';const L=R.ms.leads,q=sysQ(R),sok=(L.V1.S+Math.max(L.V5.R,L.V6.R))*10,cor=(L.aVL.R+L.V3.S)*10,tr=PREC.find(k=>L[k].R>=L[k].S);
   return`Pathologic-looking Q waves: <b>${q.length?q.join(', '):'none'}</b>. Sokolow–Lyon ${sok.toFixed(0)} mm${sok>=35?' (meets LVH voltage)':''}; Cornell ${cor.toFixed(0)} mm. R-wave transition at <b>${tr||'none (no lead with R ≥ S)'}</b>. QRS ${R.meta.qrs} ms${R.meta.qrs>=120?`; V1 is ${L.V1.area>0?'predominantly positive (RBBB-like or ventricular)':'predominantly negative (LBBB-like or ventricular)'}`:''}.`}},
{t:'ST segments',how:'Measure the J point and the ST segment 60–80 ms later against the PR or TP baseline. STEMI thresholds: 1 mm in two contiguous leads (V2–V3: 2 mm men 40+, 2.5 mm men under 40, 1.5 mm women). Look for reciprocal depression, ST depression in V1–V3 (posterior), STEMI equivalents, and shape (concave, straight, convex, coved).',
 ov:(R)=>(g,G,C)=>{if(!R.ms)return;const[u,d]=sysST(R);boxLeads(g,G,C,u,C.mk);boxLeads(g,G,C,d,C.ac)},
 on:(R)=>{if(!R.ms)return'Nothing to measure.';const[u,d]=sysST(R),L=R.ms.leads,f=k=>`${k} ${(L[k].st40*10>0?'+':'')+(L[k].st40*10).toFixed(1)}`;
   if(!u.length&&!d.length)return'No significant ST deviation at J+40 ms (orange boxes would show elevation, blue depression).';
   const groups={};u.forEach(k=>{const t=leadTerr(k);(groups[t]=groups[t]||[]).push(k)});return`<b>Elevation</b> (orange, mm at J+40 ms): ${u.map(f).join(', ')||'none'}. <b>Depression</b> (blue): ${d.map(f).join(', ')||'none'}. ${Object.keys(groups).length?'Elevated territories: '+Object.entries(groups).map(([t,ks])=>`${t} (${ks.join(', ')})`).join('; ')+'.':''} ${u.length&&d.length?'Elevation with depression elsewhere suggests reciprocal change.':''}${R.meta.qrs>=120?' With a wide QRS, judge ST deviation against the QRS direction (Sgarbossa logic).':''}`}},
{t:'T and U waves',how:'T waves should be upright in I, II and V3–V6 and inverted in aVR. Note inversion (ischemia, strain, Wellens, PE, CNS events), hyperacute or peaked T waves (occlusion, hyperkalemia), flattening (hypokalemia), and U waves (hypokalemia, bradycardia).',
 ov:(R)=>(g,G,C)=>{if(!R.ms)return;const[inv,pk]=sysT(R);boxLeads(g,G,C,inv,C.ac);boxLeads(g,G,C,pk,C.mk)},
 on:(R)=>{if(!R.ms)return'Nothing to assess.';const[inv,pk]=sysT(R);return`Inverted where it should be upright (blue): <b>${inv.join(', ')||'none'}</b>. Tall or peaked T waves (orange): <b>${pk.join(', ')||'none'}</b>.${R.meta.uw?' <b>Prominent U waves.</b>':''}`}},
{t:'Put it together',how:'Combine the findings into one impression, rank the dangerous possibilities first, and compare with a previous ECG. If ischemia is possible and the first tracing is not diagnostic, repeat it every 15–30 minutes and with any change in symptoms.',ov:()=>null,on:null}];
function sysQ(R){const L=R.ms.leads;return LEADS.filter(k=>k!=='aVR'&&k!=='V1'&&L[k].qd>=.039||(L[k].qd>=.028&&-L[k].qa>=.25*Math.max(L[k].R,.2)&&k!=='aVR'&&k!=='V1'&&k!=='III'))}
function sysST(R){const L=R.ms.leads,u=[],d=[];LEADS.forEach(k=>{const s=L[k].st40;if(s>=stThr(k))u.push(k);else if(s<=-.05)d.push(k)});return[u,d]}
function sysT(R){const L=R.ms.leads,inv=[],pk=[];['I','II','V3','V4','V5','V6'].forEach(k=>{if(L[k].tmin<-.08&&L[k].tmax<.05)inv.push(k)});['V1','V2'].forEach(k=>{if(L[k].tmin<-.12&&R.meta.qrs<120)inv.push(k)});LEADS.forEach(k=>{if(L[k].tmax>(PREC.includes(k)?.85:.55))pk.push(k)});return[inv,pk]}
function buildSys(){const H=$('#aSys');H.innerHTML='';const st={pid:null,seed:0,step:0,rev:false,rec:null};
  const top=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Read it systematically</h2><div class="row" id="sysCtl"></div></div><p style="max-width:84ch">The same ten steps on every ECG, the way you would read a 12-lead in the field: technical check, rate, rhythm, axis, intervals, P, QRS, ST, T, then synthesis. Each step marks the relevant part of the tracing and gives you the measurements for this example. The diagnosis stays hidden until the last step.</p>`);H.appendChild(top);
  const sel=el('select');sel.appendChild(new Option('Random tracing','*'));Object.keys(CAT).forEach(c=>{const og=document.createElement('optgroup');og.label=CAT[c];P.filter(p=>p.cat===c).forEach(p=>og.appendChild(new Option(p.name,p.id)));sel.appendChild(og)});
  const lb=el('label','row lbl','Tracing');lb.style.cssText='gap:6px;text-transform:none;letter-spacing:0';lb.appendChild(sel);$('#sysCtl',top).appendChild(lb);const nb=el('button','btn small','New tracing');nb.type='button';$('#sysCtl',top).appendChild(nb);
  const vh=el('div');H.appendChild(vh);const vw=Viewer(vh,{foot:'Marks follow the current step. Drag to measure.'});
  const body=el('div','card sysg',`<ol class="steps" id="sysList"></ol><div class="stack" id="sysPane" style="gap:10px;min-width:0"></div>`);H.appendChild(body);
  SYS.forEach((s,i)=>{const li=el('li');const b=el('button',null,s.t);b.type='button';b.addEventListener('click',()=>{st.step=i;render()});li.appendChild(b);$('#sysList',body).appendChild(li)});
  function load(){const ids=P.filter(p=>!['vf'].includes(p.id)).map(p=>p.id);st.pid=sel.value==='*'?ids[Math.floor(Math.random()*ids.length)]:sel.value;st.seed=Math.floor(Math.random()*1e9);st.rec=generate(st.pid,st.seed);st.step=0;vw.setRec(st.rec);render()}
  function render(){const s=SYS[st.step],R=st.rec,p=PM[st.pid];$$('#sysList button',body).forEach((b,i)=>{b.setAttribute('aria-current',String(i===st.step));b.classList.toggle('done',i<st.step)});
    vw.setOverlay(s.ov(R));const last=st.step===SYS.length-1;
    $('#sysPane',body).innerHTML=`<div class="row" style="justify-content:space-between"><h2>${st.step+1}. ${s.t}</h2><span class="lbl">Step ${st.step+1} of ${SYS.length}</span></div><p>${s.how}</p>${last?`<div class="note"><b>${p.name}.</b> ${R.meta.rhy}. ${p.feats.slice(0,3).join('. ')}.</div><p>${p.sig}</p><div class="row"><button class="btn small" id="sysAtlas" type="button">Open in Atlas</button></div>`:`<div class="note"><b>On this tracing.</b> ${s.on(R)}</div>`}<div class="row"><button class="btn small" id="sysPrev" type="button" ${st.step?'':'disabled'}>Back</button><button class="btn small primary" id="sysNext" type="button" ${last?'disabled':''}>Next step</button></div>`;
    $('#sysPrev',body).onclick=()=>{st.step--;render()};$('#sysNext',body).onclick=()=>{st.step++;render()};const oa=$('#sysAtlas',body);if(oa)oa.onclick=()=>openAtlas(st.pid,st.seed)}
  sel.addEventListener('change',load);nb.addEventListener('click',load);load();AX.draws.sys=[()=>vw.draw()]}
