
/* ============ atlas: leads & axis ============ */
const LEADINFO=[
['I','Left arm (LA)','Right arm (RA)','0°','High lateral wall','Circumflex or first diagonal'],
['II','Left leg (LL)','Right arm (RA)','+60°','Inferior wall','RCA (or circumflex)'],
['III','Left leg (LL)','Left arm (LA)','+120°','Inferior wall, rightward','RCA'],
['aVR','Right arm (RA)','Average of LA + LL (Goldberger)','−150°','Right upper side, looking into the LV cavity and base of the septum','Left main or proximal LAD (as reciprocal of diffuse ischemia)'],
['aVL','Left arm (LA)','Average of RA + LL','−30°','High lateral wall','First diagonal or circumflex'],
['aVF','Left leg (LL)','Average of RA + LA','+90°','Inferior wall','RCA or circumflex'],
['V1','4th intercostal space, right sternal border','Wilson central terminal (RA + LA + LL) ÷ 3','Anterior and rightward','Septum and right ventricle','LAD septal branches; RV branches of RCA'],
['V2','4th intercostal space, left sternal border','Wilson central terminal','Anterior','Septum and anterior wall','LAD'],
['V3','Midway between V2 and V4','Wilson central terminal','Anterior, slightly leftward','Anterior wall','LAD'],
['V4','5th intercostal space, midclavicular line','Wilson central terminal','Anterior-left','Anterior wall and apex','LAD'],
['V5','Anterior axillary line, level with V4','Wilson central terminal','Left lateral','Low lateral wall','LAD diagonals or circumflex'],
['V6','Midaxillary line, level with V4','Wilson central terminal','Lateral','Low lateral wall','Circumflex'],
['V4R','5th intercostal space, right midclavicular line','Wilson central terminal','Right anterior','Right ventricle','Proximal RCA'],
['V7','Posterior axillary line, level with V6','Wilson central terminal','Left posterolateral','Posterior wall','Circumflex or RCA (PDA)'],
['V8','Tip of the left scapula','Wilson central terminal','Posterior','Posterior wall','Circumflex'],
['V9','Left paraspinal border','Wilson central terminal','Posterior','Posterior wall','Circumflex or RCA']];
const TERR=[
{k:'Inferior',leads:['II','III','aVF'],rec:['aVL','I'],art:'Right coronary artery in about 80%; circumflex in the rest.',tip:'III greater than II with depression in I favors RCA. Record V4R for RV involvement and look at V1–V3 for posterior extension.'},
{k:'Lateral',leads:['I','aVL','V5','V6'],rec:['III','aVF'],art:'Circumflex, obtuse marginal or diagonal branches.',tip:'Often subtle. Small elevation in aVL with inferior reciprocal depression is enough to raise concern.'},
{k:'High lateral',leads:['I','aVL'],rec:['III','aVF'],art:'First diagonal (or obtuse marginal).',tip:'Elevation in I, aVL and V2 with depression in III is the “South African flag” pattern of a first diagonal occlusion.'},
{k:'Septal',leads:['V1','V2'],rec:[],art:'LAD septal perforators.',tip:'Isolated septal elevation is uncommon; usually part of an anterior infarct.'},
{k:'Anterior',leads:['V3','V4'],rec:[],art:'LAD.',tip:'Anterior plus septal (V1–V4) is “anteroseptal”; add I, aVL, V5–V6 for an extensive anterior (proximal LAD) infarct.'},
{k:'Extensive anterior',leads:['V1','V2','V3','V4','V5','V6','I','aVL'],rec:['III','aVF'],art:'Proximal LAD, before the first diagonal.',tip:'Large territory with high risk of shock and VF.'},
{k:'Posterior',leads:['V1','V2','V3'],rec:[],art:'Circumflex or a dominant RCA (posterior descending).',tip:'Seen as ST depression with tall R and upright T in V1–V3. Confirm with V7–V9 (0.5 mm elevation).',dep:true},
{k:'Right ventricle',leads:['V1'],rec:[],art:'Proximal RCA.',tip:'V1 elevation in an inferior STEMI; confirm with V4R (1 mm). Preload dependent: avoid nitrates.'},
{k:'Diffuse (aVR pattern)',leads:['aVR'],rec:['I','II','V4','V5','V6'],art:'Left main, proximal LAD or three-vessel disease, or demand ischemia.',tip:'ST elevation in aVR with widespread depression reflects global subendocardial ischemia.'}];
/* mini complex for one lead from a morph */
function miniBeat(vm,lead){const R=newRec(1,360);R.opt={noise:0};addV(R,.08,vm);const L=deriveLeads(R,false);return L[lead]}
function miniProj(vm,leads){const R=newRec(1,360);R.opt={noise:0};addV(R,.08,vm);const X=R.v[0],Y=R.v[1],Z=R.v[2],o={};leads.forEach(l=>{const L=LV[l],a=new Float32Array(R.n);for(let i=0;i<R.n;i++)a[i]=X[i]*L[0]+Y[i]*L[1]+Z[i]*L[2];o[l]=a});return o}
function drawMini(cv,data,label,C,hl,kk){const S=cvSetup(cv,104);if(!S)return;const{g,w,h}=S,pm=w/(.6*25),b=h*.6;g.fillStyle=C.paper;g.fillRect(0,0,w,h);
  g.strokeStyle=C.gmin;g.lineWidth=1;g.beginPath();for(let m=0;m*pm<w;m++){const x=Math.round(m*pm)+.5;g.moveTo(x,0);g.lineTo(x,h)}for(let m=0;m*pm<h;m++){const y=Math.round(b-m*pm)+.5,y2=Math.round(b+m*pm)+.5;g.moveTo(0,y);g.lineTo(w,y);g.moveTo(0,y2);g.lineTo(w,y2)}g.stroke();
  g.strokeStyle=C.gmaj;g.beginPath();for(let m=0;m*pm<w;m+=5){const x=Math.round(m*pm)+.5;g.moveTo(x,0);g.lineTo(x,h)}g.moveTo(0,Math.round(b)+.5);g.lineTo(w,Math.round(b)+.5);g.stroke();
  g.strokeStyle=C.trace;g.lineWidth=1.8;g.lineJoin='round';g.beginPath();const k=kk||(h*.42)/Math.max(.3,...Array.from(data).map(Math.abs));for(let i=0;i<data.length;i++){const x=(i/FS)*25*pm+4,y=b-data[i]*k;i?g.lineTo(x,y):g.moveTo(x,y)}g.stroke();
  g.fillStyle=hl?C.mark:C.ink;g.font='700 13px '+C.ui;g.textAlign='left';g.fillText(label,6,16);
  let net=0;for(let i=0;i<Math.min(data.length,90);i++)net+=data[i];g.font='11px '+C.ui;g.fillStyle=C.muted;g.textAlign='right';g.fillText(Math.abs(net)<.6?'equiphasic':net>0?'mostly +':'mostly −',w-6,16)}
function buildLead(){const H=$('#aLead');H.innerHTML='';const st={fa:55,ha:38,test:null,score:[0,0],sel:null};
  // ---- frontal plane ----
  const fc=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Frontal plane: the six limb leads</h2><div class="row" id="fCtl"></div></div>
   <p style="max-width:86ch">Each lead is a pair of poles. Depolarization moving <b>toward the positive pole</b> writes an upright deflection, moving <b>away</b> writes a negative one, and moving <b>at right angles</b> writes a small equiphasic complex. Drag the arrow (the mean QRS vector) and watch all six limb leads respond. The lead pointing along the arrow has the tallest R; the lead at 90° to it is equiphasic.</p>
   <div class="axg"><div><svg id="fSvg" viewBox="-1.45 -1.4 2.9 2.8" role="img" aria-label="Hexaxial reference system; drag to set the QRS axis" style="width:100%;max-width:400px;display:block;margin:auto;touch-action:none;cursor:grab"></svg><p id="fTx" class="note" style="margin-top:8px"></p></div><div class="minis" id="fMini"></div></div>`);H.appendChild(fc);
  segment($('#fCtl',fc),[['explore','Explore'],['test','Test me']],'explore',v=>{if(v==='test'){st.test={a:Math.round(-150+Math.random()*330),done:false};st.fa=0}else st.test=null;drawF()});
  const chk=el('button','btn small primary','Check my axis');chk.type='button';chk.hidden=true;$('#fCtl',fc).appendChild(chk);chk.addEventListener('click',()=>{if(!st.test||st.test.done)return;st.test.done=true;const e=Math.abs(((st.fa-st.test.a+540)%360)-180);st.score[1]++;if(e<=20)st.score[0]++;st.test.err=e;drawF()});
  const nxt=el('button','btn small','Next');nxt.type='button';nxt.hidden=true;$('#fCtl',fc).appendChild(nxt);nxt.addEventListener('click',()=>{st.test={a:Math.round(-150+Math.random()*330),done:false};drawF()});
  const fmc={};LIMB.forEach(l=>{const d=el('div','mini');fmc[l]=mkCanvas(d,104);$('#fMini',fc).appendChild(d)});
  const LA={I:0,II:60,III:120,aVR:-150,aVL:-30,aVF:90};
  function drawF(){const svg=$('#fSvg',fc),C=cssx(),test=st.test,showA=!test||test.done,a=test?test.a:st.fa;
    let s=`<circle r="1" fill="none" stroke="var(--line)" stroke-width=".012"/>`;
    [['Normal',-30,90,'var(--good)'],['Left axis',-90,-30,'var(--warn)'],['Right axis',90,180,'var(--accent)'],['Extreme',-180,-90,'var(--bad)']].forEach(([n,a0,a1,c])=>{const p=(t,r)=>[Math.cos(t*D2R)*r,Math.sin(t*D2R)*r];const[x0,y0]=p(a0,1),[x1,y1]=p(a1,1);s+=`<path d="M0 0L${x0} ${y0}A1 1 0 0 1 ${x1} ${y1}Z" fill="${c}" opacity=".07"/>`;const[mx,my]=p((a0+a1)/2,.62);s+=`<text x="${mx}" y="${my}" font-size=".075" text-anchor="middle" fill="${c}" font-family="var(--font-ui)" opacity=".9">${n}</text>`});
    Object.entries(LA).forEach(([l,t])=>{const x=Math.cos(t*D2R),y=Math.sin(t*D2R),on=st.sel===l;s+=`<line x1="${-x*1.05}" y1="${-y*1.05}" x2="0" y2="0" stroke="var(--muted)" stroke-width=".008" stroke-dasharray=".03 .03"/><line x1="0" y1="0" x2="${x*1.05}" y2="${y*1.05}" stroke="${on?'var(--mark)':'var(--ink)'}" stroke-width="${on?.03:.014}"/><text x="${x*1.2}" y="${y*1.2+.03}" font-size=".1" text-anchor="middle" font-weight="600" fill="${on?'var(--mark)':'var(--ink)'}" font-family="var(--font-ui)">${l}</text><text x="${x*1.2}" y="${y*1.2+.12}" font-size=".065" text-anchor="middle" fill="var(--muted)" font-family="var(--font-mono)">${t>0?'+':''}${t}°</text>`});
    if(showA){const x=Math.cos(a*D2R)*.85,y=Math.sin(a*D2R)*.85;s+=`<line x1="0" y1="0" x2="${x}" y2="${y}" stroke="var(--accent)" stroke-width=".04" stroke-linecap="round"/><circle cx="${x}" cy="${y}" r=".07" fill="var(--accent)"/>`}
    if(test&&!test.done){const x=Math.cos(st.fa*D2R)*.85,y=Math.sin(st.fa*D2R)*.85;s+=`<line x1="0" y1="0" x2="${x}" y2="${y}" stroke="var(--mark)" stroke-width=".035" stroke-dasharray=".06 .03"/><circle cx="${x}" cy="${y}" r=".065" fill="var(--mark)"/>`}
    if(test&&test.done){const x=Math.cos(st.fa*D2R)*.85,y=Math.sin(st.fa*D2R)*.85;s+=`<line x1="0" y1="0" x2="${x}" y2="${y}" stroke="var(--mark)" stroke-width=".03" stroke-dasharray=".06 .03"/>`}
    s+=`<circle r=".03" fill="var(--ink)"/>`;svg.innerHTML=s;
    const vm=V({axis:a,z:-.42}),pr=miniProj(vm,LIMB),kk=104*.42/Math.max(.3,...LIMB.map(l=>Math.max(...Array.from(pr[l]).map(Math.abs))));LIMB.forEach(l=>drawMini(fmc[l],pr[l],l,C,st.sel===l,kk));
    const cat=['normal axis','left axis deviation','right axis deviation','extreme axis'][axisCat(a)],iso=Object.entries(LA).map(([l,t])=>[l,Math.abs(Math.abs(((a-t+540)%360)-180)-90)]).sort((p,q)=>p[1]-q[1])[0][0];
    chk.hidden=!test||test.done;nxt.hidden=!test||!test.done;
    $('#fTx',fc).innerHTML=test?(test.done?`True axis <b>${test.a}°</b> (${cat}); your arrow ${Math.round(st.fa)}°, off by <b>${Math.round(test.err)}°</b>${test.err<=20?' — within 20°, good.':'.'} Score ${st.score[0]} of ${st.score[1]}.`:'Read the six complexes, then drag the orange arrow to where you think the axis is and press <b>Check my axis</b>.'):`Axis <b>${Math.round(a)}°</b>: ${cat}. Most equiphasic lead: <b>${iso}</b> (perpendicular to the axis). Lead I ${Math.cos(a*D2R)>=0?'positive':'negative'}, aVF ${Math.sin(a*D2R)>=0?'positive':'negative'}.`}
  const fsvg=$('#fSvg',fc);let fd=false;const fang=e=>{const b=fsvg.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*2.9-1.45,y=(e.clientY-b.top)/b.height*2.8-1.4;return Math.atan2(y,x)/D2R};
  fsvg.addEventListener('pointerdown',e=>{if(st.test&&st.test.done)return;fd=true;fsvg.setPointerCapture(e.pointerId);st.fa=fang(e);drawF()});fsvg.addEventListener('pointermove',e=>{if(fd){st.fa=fang(e);drawF()}});fsvg.addEventListener('pointerup',()=>fd=false);
  // ---- horizontal plane ----
  const hc=el('div','card stack',`<h2>Horizontal plane: the six chest leads</h2><p style="max-width:86ch">Seen from the feet (like a CT slice): front of the chest at the top, the patient's left on your right. The chest leads all use Wilson's central terminal, the average of the three limb electrodes, as their negative pole near the center of the heart; each positive electrode looks inward from its spot on the chest. Drag the arrow to see R-wave progression: small r and deep S in V1, growing R toward V6, with the transition (R = S) normally at V3–V4.</p>
   <div class="axg"><div><svg id="hSvg" viewBox="-1.45 -1.25 2.9 2.5" role="img" aria-label="Horizontal plane with chest-lead directions; drag to set the vector" style="width:100%;max-width:400px;display:block;margin:auto;touch-action:none;cursor:grab"></svg><p id="hTx" class="note" style="margin-top:8px"></p></div><div class="minis" id="hMini"></div></div>`);H.appendChild(hc);
  const hmc={};PREC.forEach(l=>{const d=el('div','mini');hmc[l]=mkCanvas(d,104);$('#hMini',hc).appendChild(d)});
  function drawH(){const svg=$('#hSvg',hc),C=cssx(),a=st.ha;let s=`<ellipse rx="1.15" ry=".85" fill="none" stroke="var(--line)" stroke-width=".015"/><text x="-1.4" y="-1.12" font-size=".075" fill="var(--muted)" font-family="var(--font-mono)">ANTERIOR ↑</text><text x="0" y="1.02" font-size=".075" text-anchor="middle" fill="var(--muted)" font-family="var(--font-mono)">POSTERIOR</text><text x="1.42" y=".02" font-size=".07" text-anchor="end" fill="var(--muted)" font-family="var(--font-mono)">L</text><text x="-1.42" y=".02" font-size=".07" fill="var(--muted)" font-family="var(--font-mono)">R</text>`;
    PREC.forEach(l=>{const d=PV[l].d,n=Math.hypot(d[0],d[2]),x=d[0]/n,y=-d[2]/n,on=st.sel===l;s+=`<line x1="0" y1="0" x2="${x}" y2="${y}" stroke="${on?'var(--mark)':'var(--ink)'}" stroke-width="${on?.03:.012}"/><circle cx="${x*1.04}" cy="${y*1.04}" r=".085" fill="${on?'var(--mark)':'var(--panel)'}" stroke="var(--ink)" stroke-width=".012"/><text x="${x*1.04}" y="${y*1.04+.028}" font-size=".07" text-anchor="middle" font-weight="600" fill="${on?'#fff':'var(--ink)'}" font-family="var(--font-ui)">${l}</text>`});
    const x=Math.cos(a*D2R)*.8,y=Math.sin(a*D2R)*.8;s+=`<line x1="0" y1="0" x2="${x}" y2="${y}" stroke="var(--accent)" stroke-width=".04" stroke-linecap="round"/><circle cx="${x}" cy="${y}" r=".07" fill="var(--accent)"/><circle r=".03" fill="var(--ink)"/>`;svg.innerHTML=s;
    const hx=Math.cos(a*D2R),hz=-Math.sin(a*D2R),vm=V({maind:nrm([hx,.75,hz])}),pr=miniProj(vm,PREC),kk=104*.42/Math.max(.3,...PREC.map(l=>Math.max(...Array.from(pr[l]).map(Math.abs))));PREC.forEach(l=>drawMini(hmc[l],pr[l],l,C,st.sel===l,kk));
    const tr=PREC.find(l=>{const d=pr[l];let mx=0,mn=0;for(let i=0;i<90;i++){mx=Math.max(mx,d[i]);mn=Math.min(mn,d[i])}return mx>=-mn});
    $('#hTx',hc).innerHTML=`R-wave transition at <b>${tr||'none (all leads mostly negative)'}</b>. ${!tr?'A vector pointing right and backward gives dominant S waves everywhere, as in dextrocardia or some VT.':['V1','V2'].includes(tr)?'Early transition: the vector points forward. Consider RVH, posterior MI, RBBB, WPW or a normal variant.':['V5','V6'].includes(tr)?'Late transition (poor R-wave progression): consider anterior infarction, LVH, LBBB, COPD or lead misplacement.':'Normal progression.'}`}
  const hsvg=$('#hSvg',hc);let hd=false;const hang=e=>{const b=hsvg.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*2.9-1.45,y=(e.clientY-b.top)/b.height*2.5-1.25;return Math.atan2(y,x)/D2R};
  hsvg.addEventListener('pointerdown',e=>{hd=true;hsvg.setPointerCapture(e.pointerId);st.ha=hang(e);drawH()});hsvg.addEventListener('pointermove',e=>{if(hd){st.ha=hang(e);drawH()}});hsvg.addEventListener('pointerup',()=>hd=false);
  // ---- poles table ----
  const tc=el('div','card stack',`<h2>Where each lead looks from: positive and negative poles</h2><p style="max-width:86ch">A bipolar limb lead (I, II, III) records one limb electrode against another. The augmented leads (aVR, aVL, aVF) compare one limb with the average of the other two (Goldberger). The chest leads compare each chest electrode with Wilson's central terminal, the average of all three limbs, which sits electrically near the center of the heart. The right-leg electrode is the ground (or driven reference) and is part of no lead. Select a row to highlight that lead on the diagrams above.</p>
   <div class="tw"><table class="lt"><thead><tr><th>Lead</th><th>Positive pole (+)</th><th>Negative pole (−)</th><th>Direction</th><th>Looks at</th><th>Usual artery</th></tr></thead><tbody>${LEADINFO.map(r=>`<tr data-l="${r[0]}" tabindex="0"><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td></tr>`).join('')}</tbody></table></div>`);H.appendChild(tc);
  $$('tr[data-l]',tc).forEach(tr=>{const go=()=>{st.sel=tr.dataset.l;$$('tr[data-l]',tc).forEach(x=>x.setAttribute('aria-current',String(x===tr)));drawF();drawH();if(LIMB.includes(st.sel))fc.scrollIntoView({behavior:'smooth',block:'nearest'});else if(PREC.includes(st.sel))hc.scrollIntoView({behavior:'smooth',block:'nearest'})};tr.addEventListener('click',go);tr.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});
  // ---- placement ----
  const pc=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Electrode placement</h2><div class="row" id="pCtl"></div></div><div class="lead2"><div id="pSvg"></div><div id="pTx" class="stack" style="gap:10px"></div></div>`);H.appendChild(pc);
  const PL={V1:[-.15,.0,'4th intercostal space at the right sternal border. Find the sternal angle (angle of Louis), slide to the 2nd intercostal space beside it, then count down to the 4th.','Placing V1–V2 too high (2nd–3rd space) creates an rSr′, inverted P and T waves, and can mimic or unmask a Brugada pattern.'],
    V2:[.15,0,'4th intercostal space at the left sternal border.','Too high: same artifacts as V1. Too far apart from V1: loss of septal r.'],V3:[.31,.08,'Midway between V2 and V4.','Place V4 first, then V3 between V2 and V4.'],V4:[.5,.16,'5th intercostal space in the midclavicular line.','In women, place under the breast at the 5th space; placing on the breast lowers amplitude.'],
    V5:[.74,.16,'Anterior axillary line, level with V4 (horizontally, not following the rib).','Following the rib upward shifts V5–V6 and changes R-wave progression.'],V6:[.95,.16,'Midaxillary line, level with V4 and V5.','Too low or too far forward changes lateral amplitudes.'],
    V4R:[-.5,.16,'Mirror of V4: 5th intercostal space, right midclavicular line.','Record early in inferior STEMI; RV elevation fades within hours.']};
  const show={r:false,sel:'V1'};segment($('#pCtl',pc),[['std','Standard'],['r','Add right-sided V4R']],'std',v=>{show.r=v==='r';drawP()});
  function drawP(){let s=`<svg viewBox="-1.3 -1.05 2.6 2.1" style="width:100%;max-width:440px;display:block;margin:auto" role="img" aria-label="Chest with precordial electrode positions">
    <path d="M-1.05 -.6 C-.95 -.95 -.45 -.98 -.25 -.9 L.25 -.9 C.45 -.98 .95 -.95 1.05 -.6 L1.1 .95 L-1.1 .95 Z" fill="var(--soft)" stroke="var(--muted)" stroke-width=".012"/>
    <path d="M-.85 -.72 Q-.45 -.62 -.05 -.68 M.85 -.72 Q.45 -.62 .05 -.68" fill="none" stroke="var(--muted)" stroke-width=".02"/>
    <rect x="-.07" y="-.7" width=".14" height=".95" rx=".05" fill="var(--panel)" stroke="var(--muted)" stroke-width=".012"/><line x1="-.08" y1="-.47" x2=".08" y2="-.47" stroke="var(--muted)" stroke-width=".015"/>
    ${[-.47,-.3,-.13,.0,.14,.27,.4].map((y,i)=>`<path d="M-.08 ${y} Q-.6 ${y-.06} -1.0 ${y+.25} M.08 ${y} Q.6 ${y-.06} 1.0 ${y+.25}" fill="none" stroke="var(--line)" stroke-width=".01"/><text x="-.98" y="${y+.2}" font-size=".05" fill="var(--muted)" font-family="var(--font-mono)">${i===0?'1st':i===1?'2nd':i===2?'3rd':(i+1)+'th'}</text>`).join('')}
    <line x1=".5" y1="-.7" x2=".5" y2=".9" stroke="var(--muted)" stroke-width=".008" stroke-dasharray=".03 .03"/><line x1=".74" y1="-.55" x2=".74" y2=".9" stroke="var(--muted)" stroke-width=".008" stroke-dasharray=".03 .03"/><line x1=".95" y1="-.5" x2=".95" y2=".9" stroke="var(--muted)" stroke-width=".008" stroke-dasharray=".03 .03"/>
    <text x=".5" y=".97" font-size=".05" text-anchor="middle" fill="var(--muted)" font-family="var(--font-mono)">MCL</text><text x=".74" y=".97" font-size=".05" text-anchor="middle" fill="var(--muted)" font-family="var(--font-mono)">AAL</text><text x=".95" y=".97" font-size=".05" text-anchor="middle" fill="var(--muted)" font-family="var(--font-mono)">MAL</text>
    <text x="-.12" y="-.5" font-size=".045" text-anchor="end" fill="var(--muted)" font-family="var(--font-mono)">sternal angle</text>
    <text x="-1.2" y="-.82" font-size=".06" fill="var(--muted)" font-family="var(--font-ui)">patient's right</text><text x="1.2" y="-.82" font-size=".06" text-anchor="end" fill="var(--muted)" font-family="var(--font-ui)">patient's left</text>`;
    Object.entries(PL).forEach(([k,[x,y]])=>{if(k==='V4R'&&!show.r)return;const on=show.sel===k;s+=`<g class="el" tabindex="0" role="button" data-k="${k}" aria-label="${k}"><circle cx="${x}" cy="${y}" r=".075" fill="${on?'var(--mark)':'var(--accent)'}" stroke="var(--panel)" stroke-width=".015"/><text x="${x}" y="${y+.022}" font-size=".055" text-anchor="middle" fill="#fff" font-weight="700" font-family="var(--font-ui)" pointer-events="none">${k}</text></g>`});
    s+='</svg>';$('#pSvg',pc).innerHTML=s;$$('#pSvg .el',pc).forEach(g=>{const go=()=>{show.sel=g.dataset.k;drawP()};g.addEventListener('click',go);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});
    const p=PL[show.sel];$('#pTx',pc).innerHTML=`<h2>${show.sel}</h2><p>${p[2]}</p><div class="note"><b>Common error.</b> ${p[3]}</div><p><b>Limb electrodes</b> go on the wrists and ankles (or upper arms and thighs). Torso placement (Mason–Likar, used for monitoring) shifts the axis rightward, enlarges inferior voltages and can hide inferior Q waves, so a diagnostic 12-lead should use limb positions. The right-leg electrode is the ground.</p><p><b>Posterior leads</b> V7–V9 sit on the back at the level of V6: posterior axillary line, tip of the scapula, and left paraspinal border. Use them when V1–V3 show ST depression.</p>`}
  // ---- territories ----
  const trc=el('div','card stack',`<h2>Contiguous leads and coronary territories</h2><p style="max-width:86ch">ST elevation must appear in two <b>contiguous</b> leads: leads that look at the same wall. Choose a territory to see its leads (orange), its usual reciprocal leads (blue) and the artery most often responsible.</p><div class="row" id="tChips"></div><div class="lead2"><div class="tgrid" id="tGrid"></div><div id="tTx" class="note"></div></div>`);H.appendChild(trc);
  let tsel=TERR[0];TERR.forEach(t=>{const b=el('button','chip',t.k);b.type='button';b.setAttribute('aria-pressed',String(t===tsel));b.addEventListener('click',()=>{tsel=t;$$('#tChips .chip',trc).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));drawT()});$('#tChips',trc).appendChild(b)});
  function drawT(){$('#tGrid',trc).innerHTML=[0,1,2].map(r=>LAYOUT['3x4'][r].map(l=>`<div class="tcell ${tsel.leads.includes(l)?(tsel.dep?'dep':'on'):tsel.rec.includes(l)?'rec':''}">${l}</div>`).join('')).join('');
    $('#tTx',trc).innerHTML=`<b>${tsel.k}.</b> Leads: ${tsel.leads.join(', ')}${tsel.dep?' (seen as ST depression)':''}. ${tsel.rec.length?`Reciprocal: ${tsel.rec.join(', ')}. `:''}<br><b>Usual artery:</b> ${tsel.art}<br>${tsel.tip}`}
  drawF();drawH();drawP();drawT();AX.draws.lead=[drawF,drawH]}
