
/* ============ atlas: rate & intervals ============ */
const CMP={av:{name:'AV blocks',ids:['avb1','wenck','mob2','avb21','avb3'],ladder:1},narrow:{name:'Narrow-complex tachycardias',ids:['stach','svt','flutter','af','mat'],ladder:1},wide:{name:'Wide complexes',ids:['vt','vpace','lbbb','tca','hyperk2'],ladder:0},brady:{name:'Bradycardias',ids:['sbrady','junct','avb21','avb3','hypothermia'],ladder:1},ectopy:{name:'Early beats',ids:['pac','pvc','sarr','wenck'],ladder:1}};
function buildRate(){const H=$('#aRate');H.innerHTML='';
  // ---- rate methods ----
  const rc=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Working out the rate</h2><div class="row" id="rCtl"></div></div><p style="max-width:86ch">At 25 mm/s a large box is 0.2 s and a small box 0.04 s. For a regular rhythm, start at an R wave on a heavy line and count the following heavy lines: <b>300, 150, 100, 75, 60, 50</b>. The rate is where the next R falls. For irregular rhythms, count the complexes in the 10-second strip and multiply by 6.</p><div id="rS" class="stack" style="gap:8px"></div><div class="vwrap"><div class="vscroll" id="rCv"></div></div><p id="rTx" class="note"></p>`);H.appendChild(rc);
  const rs={hr:75,irr:false,seed:5};segment($('#rCtl',rc),[['reg','Regular'],['irr','Irregular (AF)']],'reg',v=>{rs.irr=v==='irr';mk();drawR()});
  slider($('#rS',rc),'Heart rate',{min:30,max:220,step:1,val:75,fmt:v=>Math.round(v)+' /min'},v=>{rs.hr=Math.round(v);mk();drawR()});
  const rcv=el('canvas');$('#rCv',rc).appendChild(rcv);let rrec;
  function mk(){const R=newRec(rs.seed);const r=R.r,vm=sinMorph(r,{qt:qtF(rs.hr),axis:60,amp:1}),pm=nP(r);if(rs.irr){const rr=60/rs.hr;let t=-.2;while(t<DUR+.6){addV(R,t,vm);t+=Math.max(.28,rr*(.55+.9*r.u()))}addCont(R,bandNoise(r,4,9,.05),nrm([-.3,.35,.9]))}else{let t=.04+0.2*Math.ceil(.1/.2);const rr=60/rs.hr;t=.4;while(t<DUR+.6){addP(R,t-.15,pm);addV(R,t,vm);t+=rr}}R.L=deriveLeads(R);R._c={};rrec=R}
  function drawR(){const d=stripLead(rrec,'II'),qs=rrec.ev.q.filter(q=>q.t>=0&&q.t<DUR);
    drawStrip(rcv,[{data:d,label:'II'}],{t0:0,dur:DUR,rowMM:28,top:26,foot:'25 mm/s · 10 mm/mV',overlay:(g,G,C)=>{if(rs.irr){g.fillStyle=C.accent;g.globalAlpha=.1;g.fillRect(G.X(0),G.TOP,G.X(6)-G.X(0),G.H-G.TOP);g.globalAlpha=1;g.fillStyle=C.accent;g.font='600 11px '+C.ui;g.textAlign='left';g.fillText('6 seconds: '+qs.filter(q=>q.t<6).length+' complexes × 10',G.X(0)+4,G.TOP-8);return}
      const a=qs.find(q=>q.t>.3);if(!a)return;const t0=a.t+.03,labs=[300,150,100,75,60,50];labs.forEach((l,i)=>{const x=G.X(t0+.2*(i+1));if(x>G.W)return;g.strokeStyle=C.mark;g.lineWidth=1.5;g.beginPath();g.moveTo(x,G.TOP-4);g.lineTo(x,G.H);g.stroke();g.fillStyle=C.mark;g.font='600 11px '+C.ui;g.textAlign='center';g.fillText(String(l),x,G.TOP-8)});const x0=G.X(t0);g.strokeStyle=C.accent;g.lineWidth=2;g.beginPath();g.moveTo(x0,G.TOP-4);g.lineTo(x0,G.H);g.stroke();g.fillStyle=C.accent;g.fillText('start',x0,G.TOP-8)}});
    const n10=qs.length,rr=qs.length>1?(qs[qs.length-1].t-qs[0].t)/(qs.length-1):0;
    $('#rTx',rc).innerHTML=rs.irr?`Ten-second count: <b>${n10} × 6 = ${n10*6}/min</b>. Six-second count: ${qs.filter(q=>q.t<6).length} × 10 = ${qs.filter(q=>q.t<6).length*10}/min. Beat-to-beat rates range from ${Math.round(60/Math.max(...qs.slice(1).map((q,i)=>q.t-qs[i].t)))} to ${Math.round(60/Math.min(...qs.slice(1).map((q,i)=>q.t-qs[i].t)))}/min, so the large-box method is unreliable here.`:`R–R ${Math.round(rr*1000)} ms = ${(rr/.2).toFixed(1)} large boxes → 300 ÷ ${(rr/.2).toFixed(1)} = <b>${Math.round(300/(rr/.2))}/min</b>. Small boxes: 1500 ÷ ${(rr/.04).toFixed(0)} = ${Math.round(1500/Math.round(rr/.04))}/min. Ten-second count ${n10} × 6 = ${n10*6}/min (coarser at slow rates).`}
  // ---- anatomy of a beat ----
  const bc=el('div','card stack',`<h2>Anatomy of a beat and normal values</h2><div class="lead2"><div class="vwrap"><div class="vscroll" id="bCv"></div></div><div class="tw"><table class="nv"><thead><tr><th>Measure</th><th>Normal</th><th>Think about</th></tr></thead><tbody>
   <tr><td>P wave</td><td>Under 120 ms, under 2.5 mm in II; upright in I and II</td><td>Tall: right atrial enlargement. Broad, notched: left atrial enlargement</td></tr>
   <tr><td>PR interval</td><td>120–200 ms</td><td>Short: pre-excitation, junctional. Long: AV block</td></tr>
   <tr><td>QRS</td><td>Under 110 ms</td><td>120 ms or more: bundle-branch block, ventricular, paced, pre-excited, toxic, hyperkalemic</td></tr>
   <tr><td>Axis</td><td>−30° to +90°</td><td>Left: LAFB, inferior MI, LVH, paced. Right: RVH, LPFB, PE, lateral MI, reversal</td></tr>
   <tr><td>Q waves</td><td>Small septal q in I, aVL, V5–V6</td><td>40 ms or more, or a quarter of the R, in two contiguous leads</td></tr>
   <tr><td>R progression</td><td>Transition at V3–V4</td><td>Early: RVH, posterior MI, RBBB, WPW. Late: anterior MI, LVH, LBBB</td></tr>
   <tr><td>ST segment</td><td>At baseline (J point)</td><td>Elevation or depression in contiguous leads; reciprocity</td></tr>
   <tr><td>T wave</td><td>Upright in I, II, V3–V6; inverted aVR</td><td>Inverted, peaked, hyperacute, flattened</td></tr>
   <tr><td>QTc</td><td>Under 450 ms men, under 460–470 ms women</td><td>500 ms or more: high risk. Under 350 ms: short QT</td></tr>
   <tr><td>U wave</td><td>Small, same direction as T</td><td>Prominent: hypokalemia, bradycardia</td></tr></tbody></table></div></div>`);H.appendChild(bc);
  const bcv=el('canvas');$('#bCv',bc).appendChild(bcv);
  function drawB(){const R=newRec(3,800);R.opt={noise:0};const vm=V({axis:60,qt:.4,uA:.05,stA:.0}),pm=Pw('n',.17);addP(R,.3-.16,pm);addV(R,.3,vm);addP(R,1.2-.16,pm);const L=deriveLeads(R,false);
    const geo=drawStrip(bcv,[{data:L.II}],{t0:0,dur:1.1,speed:50,gain:20,rowMM:46,base:.62,top:4,cal:false,minPm:2.9,maxPm:6.5,extra:22,overlay:(g,G,C)=>{const b=G.rows[0].base,Y=v=>b-v*G.gain*G.pm,y0=Y(0),yb=G.rows[0].bot,lab=(t,v,txt,col)=>{g.fillStyle=col||C.ink;g.font='700 13px '+C.ui;g.textAlign='center';g.fillText(txt,G.X(t),Y(v)-8)};
      lab(.3-.16+.05,.17,'P');lab(.3+.04,1.05,'R');lab(.3+.016,-.08,'Q');lab(.3+.072,-.35,'S');lab(.3+.4-.1,.5,'T');lab(.3+.48,.12,'U',C.muted);
      g.fillStyle=C.mark;g.beginPath();g.arc(G.X(.3+vm.off),y0,4,0,6.3);g.fill();g.font='600 11px '+C.ui;g.textAlign='left';g.fillText('J point',G.X(.3+vm.off)+6,y0+14);
      const br=(t0,t1,y,txt,col)=>{const x0=G.X(t0),x1=G.X(t1);g.strokeStyle=col;g.fillStyle=col;g.lineWidth=2;g.beginPath();g.moveTo(x0,y-5);g.lineTo(x0,y+5);g.moveTo(x0,y);g.lineTo(x1,y);g.moveTo(x1,y-5);g.lineTo(x1,y+5);g.stroke();g.font='600 11px '+C.ui;g.textAlign='center';g.fillText(txt,(x0+x1)/2,y-6)};
      const z=yb+10;br(.3-.16,.3,z,'PR interval',C.mark);br(.3,.3+vm.off,z+20,'QRS',C.accent);br(.3,.3+vm.qt,z+40,'QT interval',C.good);br(.3+vm.off,.3+vm.t[0].c-.02,z,'ST segment',C.muted);br(.3+vm.qt,1.2-.16,z,'TP (baseline)',C.muted)}});}
  // ---- QTc ----
  const qc=el('div','card stack',`<h2>Correcting the QT for heart rate</h2><p style="max-width:86ch">The QT shortens as the rate rises, so it is corrected to a rate of 60. <b>Bazett</b> (QT ÷ √RR) is the most used but overcorrects at fast rates and undercorrects at slow ones. <b>Fridericia</b> (QT ÷ ∛RR) and <b>Framingham</b> (QT + 154 × (1 − RR)) behave better away from 60. Measure in the lead with the longest QT (often II or V5), end the T wave with the tangent method, and exclude U waves.</p><div class="calc"><label>Measured QT (ms)<input type="number" id="qQT" value="400" min="200" max="700" step="5"></label><label>Heart rate (/min)<input type="number" id="qHR" value="90" min="30" max="200" step="1"></label></div><p id="qOut" class="note"></p><div class="vwrap"><div id="qCv"></div></div>`);H.appendChild(qc);
  const qcv=mkCanvas($('#qCv',qc),230),F={Bazett:(qt,rr)=>qt/Math.sqrt(rr),Fridericia:(qt,rr)=>qt/Math.cbrt(rr),Framingham:(qt,rr)=>qt+154*(1-rr),Hodges:(qt,rr)=>qt+1.75*(60/rr-60)},FC={Bazett:'var(--bad)',Fridericia:'var(--accent)',Framingham:'var(--good)',Hodges:'var(--warn)'};
  function drawQ(){const qt=+$('#qQT',qc).value||400,hr=clamp(+$('#qHR',qc).value||60,30,200),rr=60/hr;const vals=Object.fromEntries(Object.entries(F).map(([k,f])=>[k,Math.round(f(qt,rr))]));
    $('#qOut',qc).innerHTML=Object.entries(vals).map(([k,v])=>`${k} <b>${v} ms</b>`).join(' · ')+`. RR ${Math.round(rr*1000)} ms. ${Math.max(...Object.values(vals))-Math.min(...Object.values(vals))>30?'The formulas disagree by more than 30 ms at this rate; prefer Fridericia or Framingham.':'At this rate the formulas roughly agree.'} Half the R–R is ${Math.round(rr*500)} ms: the QT is ${qt>rr*500?'longer':'shorter'} than half the R–R.`;
    const S=cvSetup(qcv);if(!S)return;const{g,w,h,C}=S,ml=48,mr=14,mt=14,mb=28,pw=w-ml-mr,ph=h-mt-mb,X=x=>ml+(x-40)/120*pw,Y=v=>mt+(1-(v-300)/350)*ph;
    g.font='11px '+C.mono;g.strokeStyle=C.grid;g.fillStyle=C.muted;g.lineWidth=1;[300,400,450,500,600].forEach(v=>{g.beginPath();g.moveTo(ml,Y(v)+.5);g.lineTo(w-mr,Y(v)+.5);g.strokeStyle=v===450||v===500?C.bad:C.grid;g.setLineDash(v===450||v===500?[4,4]:[]);g.stroke();g.setLineDash([]);g.textAlign='right';g.fillText(v,ml-6,Y(v)+4)});
    [40,60,80,100,120,140,160].forEach(x=>{g.textAlign='center';g.fillText(x+'/min',X(x),h-9)});
    Object.entries(F).forEach(([k,f])=>{g.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue(FC[k].slice(4,-1)).trim();g.lineWidth=2.2;g.beginPath();for(let x=40;x<=160;x+=2){const q=qt*Math.cbrt((60/x))/Math.cbrt(rr),v=f(q,60/x);x===40?g.moveTo(X(x),Y(clamp(v,300,650))):g.lineTo(X(x),Y(clamp(v,300,650)))}g.stroke()});
    g.strokeStyle=C.ink;g.setLineDash([3,3]);g.beginPath();g.moveTo(X(hr),mt);g.lineTo(X(hr),mt+ph);g.stroke();g.setLineDash([]);
    let lx=ml+8;Object.keys(F).forEach(k=>{g.fillStyle=getComputedStyle(document.documentElement).getPropertyValue(FC[k].slice(4,-1)).trim();g.fillRect(lx,mt+2,12,4);g.fillStyle=C.ink;g.textAlign='left';g.font='11px '+C.ui;g.fillText(k,lx+16,mt+8);lx+=g.measureText(k).width+34});
    g.fillStyle=C.muted;g.textAlign='left';g.fillText('QT varying with rate as Fridericia assumes: the further a line strays from flat, the more that formula distorts',ml+8,mt+24)}
  $$('#qQT,#qHR',qc).forEach(i=>i.addEventListener('input',drawQ));
  // ---- side-by-side strips with ladder diagrams ----
  const cc=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Side by side, with ladder diagrams</h2><div class="row" id="cCtl"></div></div><p style="max-width:86ch">Rhythms that are easily confused, stacked on the same time scale. The ladder under each strip shows atrial activity (A), AV conduction (AV) and ventricular activity (V): a slanted line is a conducted impulse whose slope is the PR; a line ending in a bar is blocked; a V mark with no line above it started in the ventricle or junction.</p><div class="row" id="cSel"></div><div class="stack" id="cRows" style="gap:12px"></div>`);H.appendChild(cc);
  const cs={grp:'av',lead:'II',recs:{}};Object.entries(CMP).forEach(([k,v])=>{const b=el('button','chip',v.name);b.type='button';b.setAttribute('aria-pressed',String(k===cs.grp));b.addEventListener('click',()=>{cs.grp=k;$$('#cSel .chip',cc).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));mkC();drawC()});$('#cSel',cc).appendChild(b)});
  segment($('#cCtl',cc),[['II','Lead II'],['V1','Lead V1']],'II',v=>{cs.lead=v;drawC()});const nb=el('button','btn small','New examples');nb.type='button';nb.addEventListener('click',()=>{mkC();drawC()});$('#cCtl',cc).appendChild(nb);
  const ccv={};function mkC(){const G=CMP[cs.grp];$('#cRows',cc).innerHTML='';G.ids.forEach(id=>{cs.recs[id]=generate(id,Math.floor(Math.random()*1e9));const d=el('div','vwrap');d.innerHTML=`<div class="vleg"><b>${PM[id].name}</b><span class="lbl" style="text-transform:none;letter-spacing:0">${cs.recs[id].meta.rhy}${cs.recs[id].meta.hr?' · '+cs.recs[id].meta.hr+'/min':''}</span></div><div class="vscroll"></div>`;const c=el('canvas');$('.vscroll',d).appendChild(c);ccv[id]=c;$('#cRows',cc).appendChild(d)})}
  function drawC(){const G=CMP[cs.grp];G.ids.forEach(id=>{const R=cs.recs[id],d=stripLead(R,cs.lead);drawStrip(ccv[id],[{data:d,label:cs.lead}],{t0:0,dur:8,rowMM:26,extra:G.ladder?18:0,overlay:G.ladder?(g,Gm,C)=>ladder(g,Gm,C,R,8):null})})}
  function ladder(g,G,C,R,dur){const y0=G.rows[0].bot+2*G.pm,th=5*G.pm,yA=y0,yAV=y0+th,yV=y0+2*th,yE=y0+3*th,x0=G.X(0),x1=G.X(dur);g.fillStyle=C.panel;g.fillRect(0,y0-2,G.W,3*th+4);g.strokeStyle=C.line;g.lineWidth=1;[yA,yAV,yV,yE].forEach(y=>{g.beginPath();g.moveTo(x0,y);g.lineTo(x1,y);g.stroke()});
    g.fillStyle=C.muted;g.font='600 10px '+C.mono;g.textAlign='right';g.fillText('A',x0-4,yA+th*.65);g.fillText('AV',x0-4,yAV+th*.65);g.fillText('V',x0-4,yV+th*.65);
    if(R.pid==='af'){g.save();g.beginPath();g.rect(x0,yA,x1-x0,th);g.clip();g.strokeStyle=C.mark;g.lineWidth=1;for(let x=x0-th;x<x1;x+=5){g.beginPath();g.moveTo(x,yA+th);g.lineTo(x+th,yA);g.stroke()}g.restore()}
    if(R.pid==='flutter'){const per=60/(R.meta.arate||300);for(let t=0;t<dur;t+=per){const x=G.X(t);g.strokeStyle=C.mark;g.lineWidth=1.6;g.beginPath();g.moveTo(x,yA+1);g.lineTo(x+2,yA+th-1);g.stroke()}}
    R.ev.p.forEach((p,i)=>{if(p.t<-.4||p.t>dur)return;const xa=G.X(p.t+.04);g.strokeStyle=C.mark;g.lineWidth=2;g.beginPath();g.moveTo(xa,yA+1);g.lineTo(xa+2,yA+th-1);g.stroke();
      const q=R.ev.q.find(q=>q.from===i);if(q){const xv=G.X(q.t+.02);g.beginPath();g.moveTo(xa+2,yAV);g.lineTo(xv,yV);g.stroke()}else if(p.k!=='r'&&R.meta.prq!=='none'){g.beginPath();g.moveTo(xa+2,yAV);g.lineTo(xa+8,yAV+th*.55);g.stroke();g.beginPath();g.moveTo(xa+3,yAV+th*.55);g.lineTo(xa+13,yAV+th*.55);g.stroke()}});
    R.ev.q.forEach(q=>{if(q.t<-.3||q.t>dur||q.k==='s')return;const x=G.X(q.t+.02);g.strokeStyle=q.k==='v'||q.k==='p'?C.bad:C.accent;g.lineWidth=2;g.beginPath();g.moveTo(x,yV+1);g.lineTo(x+(q.k==='v'?0:2),yV+th-1);g.stroke();if(q.from==null&&!['af','flutter','svt'].includes(R.pid)){g.fillStyle=g.strokeStyle;g.beginPath();g.arc(x,yV+(q.k==='v'?th*.5:2),2.5,0,6.3);g.fill()}})}
  mk();drawR();drawB();drawQ();mkC();drawC();AX.draws.rate=[drawR,drawB,drawQ,drawC]}
