
/* ============ atlas: signal & filters ============ */
function gainRC(kind,f,fc,n,fs=FS){const x=Math.tan(Math.PI*Math.min(f,fs*.49)/fs)/Math.tan(Math.PI*fc/fs);return kind==='lp'?Math.pow(1/Math.sqrt(1+x*x),n):Math.pow(x/Math.sqrt(1+x*x),n)}
function magK(k,f){const w=2*Math.PI*f/FS,c1=Math.cos(w),s1=Math.sin(w),c2=Math.cos(2*w),s2=Math.sin(2*w);return Math.hypot(k[0]+k[1]*c1+k[2]*c2,k[1]*s1+k[2]*s2)/Math.hypot(1+k[3]*c1+k[4]*c2,k[3]*s1+k[4]*s2)}
const REV={none:['Correct placement',''],LARA:['Left and right arm swapped','Lead I is inverted (P, QRS and T); II and III swap; aVR and aVL swap; aVF is unchanged. The chest leads stay normal, which separates this from dextrocardia.'],
  LALL:['Left arm and left leg swapped','Lead III is inverted; I and II swap; aVL and aVF swap; aVR is unchanged. Subtle: the P wave in I may be taller than in II. Can create or hide apparent inferior changes.'],
  RALL:['Right arm and left leg swapped','Lead II is inverted; I and III are inverted and swapped; aVR and aVF swap; aVL is unchanged. Everything inferior looks upside down, mimicking an inferior infarct or extreme axis.'],
  RARL:['Right arm and right leg swapped','Lead II becomes a nearly flat line (both inputs see leg potential). Lead I and aVL look like an inverted III; aVR and aVF look identical.'],
  LARL:['Left arm and right leg swapped','Lead III becomes a nearly flat line. Leads I and II look identical; aVL and aVF look identical; aVR is the inverse of II.'],
  VHIGH:['V1 and V2 placed too high (2nd–3rd space)','Negative P waves, rSr′ complexes and T inversion in V1–V2, which can mimic septal infarction, incomplete RBBB or a Brugada pattern. A negative P wave in V2 is the clue.']};
function buildSig(){const H=$('#aSig');H.innerHTML='';
  H.appendChild(el('div','card stack',`<h2>From heart to paper: how the 12-lead is recorded</h2><p style="max-width:86ch">Ten electrodes make twelve leads. Every lead is a difference between two points, amplified about a thousand times. Everything that makes a tracing clean or misleading happens along this chain.</p>
  <div class="pipe"><div class="stage"><b>1 Electrodes and skin</b><span>Silver/silver-chloride gel electrodes on clean, dry, lightly abraded skin; clip hair. Poor contact causes wander, 60 Hz and lead-off artifact.</span></div><div class="stage"><b>2 Lead wires</b><span>Four limb wires (RA, LA, LL, and RL as ground or driven reference) and six chest wires. Keep cables untangled and still.</span></div><div class="stage"><b>3 Reference networks</b><span>Limb leads compare limbs; augmented leads compare one limb with the average of two (Goldberger); chest leads compare each electrode with Wilson's central terminal.</span></div><div class="stage"><b>4 Differential amplifier</b><span>Subtracts the two inputs so interference common to both (mains hum) cancels. Right-leg drive improves common-mode rejection.</span></div><div class="stage"><b>5 Digitizer</b><span>500–1000 samples/s for diagnostic ECG. Pacemaker spikes are detected by separate fast hardware and often shown as markers.</span></div><div class="stage"><b>6 Filters and display</b><span>Diagnostic 0.05–150 Hz; monitor 0.5–40 Hz; 25 mm/s and 10 mm/mV. Filter choice changes ST segments, QRS height and pacing spikes.</span></div></div>`));

  // ---- filter lab ----
  const fl=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Monitor mode versus diagnostic mode</h2><div class="row" id="flCtl"></div></div><p style="max-width:86ch">Monitors use a 0.5 Hz high-pass filter to keep the trace steady during movement and a 40 Hz low-pass filter to hide muscle noise. A causal 0.5 Hz filter has a 0.32 s time constant, which bends the ST segment after each QRS and can <b>create or erase</b> ST elevation. Diagnostic mode (0.05–150 Hz) preserves the ST level and the sharp parts of the QRS. Modern carts may use 0.67 Hz with zero-phase (linear-phase) digital filtering, which avoids the distortion. Compare the filtered trace with the true signal.</p>
   <div class="row" id="flSrc"></div><div class="row" id="flChips"></div><div id="flS" class="stack" style="gap:8px"></div><div class="row" id="flOpt"></div><div class="vwrap"><div class="vscroll" id="flCv"></div></div><div class="vwrap"><div id="flR"></div></div><p id="flTx" class="note"></p>`);H.appendChild(fl);
  const fs={pid:'infstemi',lead:'III',hp:.5,lp:40,zero:false,notch:false,on:new Set(['wander'])};let base=null;
  const ss=el('select');[['infstemi','Inferior STEMI'],['antstemi','Anterior STEMI'],['nsr','Normal'],['erp','Early repolarization'],['lvh','LVH with strain'],['vpace','Paced rhythm'],['rbbb','RBBB'],['hyperk','Hyperkalemia']].forEach(([v,t])=>ss.appendChild(new Option(t,v)));ss.value=fs.pid;
  const ls=el('select');LEADS.forEach(l=>ls.appendChild(new Option(l,l)));ls.value=fs.lead;
  const lab=(t,c)=>{const l=el('label','row lbl',t);l.style.cssText='gap:6px;text-transform:none;letter-spacing:0';l.appendChild(c);return l};$('#flSrc',fl).append(lab('Tracing',ss),lab('Lead',ls));
  ss.addEventListener('change',()=>{fs.pid=ss.value;fs.lead=fs.pid==='infstemi'?'III':fs.pid==='vpace'?'V2':fs.pid==='lvh'?'V5':fs.lead;ls.value=fs.lead;mkF();drawF()});ls.addEventListener('change',()=>{fs.lead=ls.value;drawF()});
  [['wander','Breathing / baseline wander'],['emg','Muscle tremor'],['mains','60 Hz interference']].forEach(([k,t])=>{const b=el('button','chip',t);b.type='button';b.setAttribute('aria-pressed',String(fs.on.has(k)));b.addEventListener('click',()=>{fs.on.has(k)?fs.on.delete(k):fs.on.add(k);b.setAttribute('aria-pressed',String(fs.on.has(k)));drawF()});$('#flChips',fl).appendChild(b)});
  const hs=slider($('#flS',fl),'High-pass (low cut)',{min:.05,max:2,log:1,val:.5,fmt:v=>v.toFixed(v<1?2:1)+' Hz'},v=>{fs.hp=v;drawF()}),lps=slider($('#flS',fl),'Low-pass (high cut)',{min:20,max:150,log:1,val:40,fmt:v=>v.toFixed(0)+' Hz'},v=>{fs.lp=v;drawF()});
  const ph=segment($('#flOpt',fl),[['c','Causal (monitor-style)'],['z','Zero-phase (digital)']],'c',v=>{fs.zero=v==='z';drawF()});
  const nc=el('input');nc.type='checkbox';nc.addEventListener('change',()=>{fs.notch=nc.checked;drawF()});$('#flOpt',fl).appendChild(lab('60 Hz notch',nc));
  [['Diagnostic',.05,150],['Monitor',.5,40],['ST mode',.05,40]].forEach(([t,h,l])=>{const b=el('button','btn small',t);b.type='button';b.addEventListener('click',()=>{fs.hp=h;fs.lp=l;hs.set(h);lps.set(l);drawF()});$('#flOpt',fl).appendChild(b)});
  const fcv=el('canvas');$('#flCv',fl).appendChild(fcv);const rcv=mkCanvas($('#flR',fl),200);
  function mkF(){const R=newRec(4242);GEN[fs.pid](R);R.opt.noise=0;const L=deriveLeads(R,false),r=mkRand(99);base={R,L,wan:(()=>{const a=new Float32Array(N);for(let i=0;i<N;i++){const t=i/FS;a[i]=.3*Math.sin(2*Math.PI*.24*t+1)+.12*Math.sin(2*Math.PI*.07*t)}return a})(),emg:bandNoise(r,20,150,.06),mains:(()=>{const a=new Float32Array(N);for(let i=0;i<N;i++)a[i]=.09*Math.sin(2*Math.PI*60*i/FS);return a})()}}
  const run=x=>{let y=x;if(fs.zero){const P=1500,n=x.length,p=new Float32Array(n+2*P);for(let i=0;i<P;i++){p[i]=x[Math.min(n-1,P-i)];p[n+P+i]=x[Math.max(0,n-2-i)]}p.set(x,P);let z=rc1(p,fs.hp,'hp');z.reverse();z=rc1(z,fs.hp,'hp');z.reverse();z=Float32Array.from(ff(z,bq('lp',fs.lp,.707)));if(fs.notch)z=Float32Array.from(ff(z,bq('notch',60,30)));return z.subarray(P,P+n)}
    const P=1500,n=x.length,p=new Float32Array(n+P);for(let i=0;i<P;i++)p[i]=x[Math.min(n-1,P-i)];p.set(x,P);y=rc1(p,fs.hp,'hp');y=runbq(y,bq('lp',fs.lp,.707));if(fs.notch)y=runbq(y,bq('notch',60,30));return y.subarray(P)};
  function drawF(){const clean=base.L[fs.lead],rec=new Float32Array(N);for(let i=0;i<N;i++)rec[i]=clean[i]+(fs.on.has('wander')?base.wan[i]:0)+(fs.on.has('emg')?base.emg[i]:0)+(fs.on.has('mains')?base.mains[i]:0);const out=run(rec);
    const b=pickBeat(base.R,3,7),m=b.m,iB=Math.round((b.t+m.on-.02)*FS),iS=Math.round((b.t+m.off+.06)*FS),st0=clean[iS]-clean[iB],st1=out[iS]-out[iB];let p0=-9,n0=9,p1=-9,n1=9;for(let i=Math.round((b.t+m.on)*FS);i<=Math.round((b.t+m.off)*FS);i++){p0=Math.max(p0,clean[i]);n0=Math.min(n0,clean[i]);p1=Math.max(p1,out[i]);n1=Math.min(n1,out[i])}
    drawStrip(fcv,[{data:clean,label:'True signal'},{data:rec,label:'Recorded'},{data:out,label:`Filtered ${fs.hp.toFixed(fs.hp<1?2:1)}–${fs.lp.toFixed(0)} Hz${fs.zero?' zero-phase':''}`,lc:cssx().accent}],{t0:0,dur:10,rowMM:28,top:0,overlay:(g,G,C)=>{G.rows.forEach((rw,k)=>{if(k===1)return;const x=G.X(b.t+m.off+.06);g.strokeStyle=C.mark;g.setLineDash([3,3]);g.lineWidth=1.2;g.beginPath();g.moveTo(x,rw.top+4);g.lineTo(x,rw.bot-4);g.stroke();g.setLineDash([])})}});
    const S=cvSetup(rcv);if(S){const{g,w,h,C}=S,ml=44,mr=12,mt=20,mb=26,pw=w-ml-mr,ph_=h-mt-mb,fx=f=>ml+(Math.log10(f)+2)/(Math.log10(250)+2)*pw,dy=d=>mt+(-d/40)*ph_,nk=bq('notch',60,30);
      [['ST and T (0.05–10 Hz)',.05,10,C.good],['QRS (5–40 Hz)',5,40,C.accent],['Muscle (20–150 Hz)',20,150,C.bad],['Pacer spike (100 Hz+)',100,250,C.warn]].forEach(([t,a,z,c],i)=>{g.globalAlpha=.12;g.fillStyle=c;g.fillRect(fx(a),mt+i*7,fx(z)-fx(a),ph_-i*7);g.globalAlpha=1;g.fillStyle=c;g.font='600 10.5px '+C.ui;g.textAlign='left';g.fillText(t,fx(a)+3,mt+i*11-6+12)});
      g.strokeStyle=C.grid;g.fillStyle=C.muted;g.font='10.5px '+C.mono;g.lineWidth=1;for(let d=0;d>=-40;d-=10){g.beginPath();g.moveTo(ml,dy(d)+.5);g.lineTo(w-mr,dy(d)+.5);g.stroke();g.textAlign='right';g.fillText(d+' dB',ml-5,dy(d)+4)}
      [.01,.1,1,10,100].forEach(f=>{g.strokeStyle=C.major;g.beginPath();g.moveTo(fx(f)+.5,mt);g.lineTo(fx(f)+.5,mt+ph_);g.stroke();g.textAlign='center';g.fillStyle=C.muted;g.fillText(f+' Hz',fx(f),h-8)});
      g.strokeStyle=C.ink;g.lineWidth=2.4;g.beginPath();for(let k=0;k<=400;k++){const f=Math.pow(10,-2+k/400*(Math.log10(250)+2)),n=fs.zero?2:1;let gv=gainRC('hp',f,fs.hp,n)*gainRC('lp',f,fs.lp,fs.zero?4:2)/(fs.zero?1:1);if(fs.notch)gv*=magK(nk,f)**(fs.zero?2:1);const d=clamp(20*Math.log10(Math.max(gv,1e-4)),-40,0);k?g.lineTo(fx(f),dy(d)):g.moveTo(fx(f),dy(d))}g.stroke()}
    const dst=(st1-st0)*10,amp=(p1-n1)/(p0-n0);$('#flTx',fl).innerHTML=`At the dashed line (J + 60 ms): true ST ${(st0*10).toFixed(1)} mm, filtered ${(st1*10).toFixed(1)} mm, an error of <b>${dst>0?'+':''}${dst.toFixed(1)} mm</b>. QRS amplitude after filtering: <b>${Math.round(amp*100)}%</b> of the true value. ${Math.abs(dst)>=.5?(fs.zero?'':'A causal high-pass corner this high distorts the ST segment. Switch to zero-phase or lower the corner to 0.05 Hz.'):'The ST level is preserved.'} ${fs.lp<=40&&fs.pid==='vpace'?'Note how the pacing spikes shrink or vanish with a 40 Hz low-pass.':''}`}
  // ---- lead reversal lab ----
  const rv=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Lead reversal and misplacement</h2><div class="row" id="rvCtl"></div></div><p style="max-width:86ch">The same normal heart, recorded with an electrode error. Leads that changed are outlined. Learn the fingerprints: a flat lead means a limb electrode was swapped with the right leg; an inverted lead I with normal chest leads means the arms were swapped.</p><div class="row" id="rvSel"></div><div id="rvV"></div><p id="rvTx" class="note"></p>`);H.appendChild(rv);
  const rvs={err:'LARA',show:'err',seed:777};const rvv=Viewer($('#rvV',rv),{foot:'Outlined leads differ from correct placement.',strip:false});
  Object.entries(REV).forEach(([k,[t]])=>{const b=el('button','chip',t);b.type='button';b.setAttribute('aria-pressed',String(k===rvs.err));b.addEventListener('click',()=>{rvs.err=k;$$('#rvSel .chip',rv).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));drawRV()});$('#rvSel',rv).appendChild(b)});
  segment($('#rvCtl',rv),[['err','As recorded'],['ok','Correct placement']],'err',v=>{rvs.show=v;drawRV()});
  function recWith(err){const R=newRec(rvs.seed),r=R.r,hr=72,pr=.15,vm=sinMorph(r,{qt:qtF(hr),axis:55}),pm=nP(r);if(err==='VHIGH')R.opt.pv={V1:nrm([-.32,-.5,.8]),V2:nrm([-.05,-.5,.86])};else if(err!=='none'){const m={LARA:['LA','RA'],LALL:['LA','LL'],RALL:['RA','LL'],RARL:['RA','RL'],LARL:['LA','RL']};R.opt.swap=m[err]}
    sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.meta.rhy='Sinus rhythm';R.L=deriveLeads(R);R.ms=measure(R);computeMeta(R);R._c={};return R}
  function drawRV(){const bad=recWith(rvs.err),ok=recWith('none'),changed=LEADS.filter(k=>{let m=0;for(let i=0;i<N;i+=3)m=Math.max(m,Math.abs(bad.L[k][i]-ok.L[k][i]));return m>.06});const R=rvs.show==='err'?bad:ok;R.ann=rvs.show==='err'&&rvs.err!=='none'?[{type:'hl',leads:changed,txt:'Changed by the error',k:'a'}]:[];rvv.setRec(R);rvv.setAnn(true);
    $('#rvTx',rv).innerHTML=rvs.err==='none'?'Correct placement: upright P in I and II, negative aVR, normal R-wave progression.':`<b>${REV[rvs.err][0]}.</b> ${REV[rvs.err][1]} Changed leads: ${changed.join(', ')||'none'}. Axis as recorded ${bad.meta.axis}° (true ${ok.meta.axis}°).`}
  mkF();drawF();drawRV();
  AX.draws.sig=[drawF,()=>rvv.draw()];
  rcLab(H)}
/* ---- RC lab ---- */
function schem(t){const zig='M0 0h10l5-9 10 18 10-18 10 18 10-18 5 9h10',gnd='<path d="M138 100h24M142 106h16M146 112h8"/>',vz=`<g transform="translate(150 30) rotate(90)"><path d="${zig}"/></g>`;
  return`<svg viewBox="0 0 250 128" width="100%" style="max-width:340px" role="img" aria-label="${t==='lp'?'Low-pass':'High-pass'} RC circuit" fill="none" stroke="var(--ink)" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"><circle cx="12" cy="30" r="3.5" fill="var(--panel)"/>`+(t==='lp'?`<path d="M16 30H40"/><g transform="translate(40 30)"><path d="${zig}"/></g><path d="M110 30H235M150 30V62M138 62h24M138 70h24M150 70V100"/>${gnd}<text x="62" y="12" fill="var(--ink)" stroke="none" font-size="13" font-family="var(--font-mono)">R</text><text x="166" y="72" fill="var(--ink)" stroke="none" font-size="13" font-family="var(--font-mono)">C</text>`:`<path d="M16 30H70M70 14v32M78 14v32M78 30H235M150 30"/>${vz}<path d="M150 100"/>${gnd}<text x="68" y="10" fill="var(--ink)" stroke="none" font-size="13" font-family="var(--font-mono)">C</text><text x="166" y="68" fill="var(--ink)" stroke="none" font-size="13" font-family="var(--font-mono)">R</text>`)+`<circle cx="150" cy="30" r="3" fill="var(--ink)"/><circle cx="235" cy="30" r="3.5" fill="var(--panel)"/><text x="2" y="50" fill="var(--muted)" stroke="none" font-size="12" font-family="var(--font-mono)">Vin</text><text x="205" y="50" fill="var(--accent)" stroke="none" font-size="12" font-family="var(--font-mono)">Vout</text></svg>`}
function rcLab(H){const st={type:'hp',inp:'step',R:318310,C:1e-6,ratio:.2};
  const c=el('div','card stack',`<h2>Resistor and capacitor: why 0.05 Hz and not 0.5 Hz</h2><p style="max-width:84ch">A resistor and a capacitor make a first-order filter, the building block of the ECG's low-frequency (high-pass) filter. A 0.05 Hz corner has a time constant of 3.2 s, far longer than an ST segment, so the ST level is preserved. A 0.5 Hz corner has a time constant of 0.32 s, about the length of the ST segment, so after every large QRS the baseline is pulled back toward zero and the ST segment is bent. Try a step with R × C set for 0.05 Hz and for 0.5 Hz. The capacitor charges through the resistor on a time scale of <b>τ = R × C</b>. The corner frequency is <b>fc = 1 ÷ (2π R C)</b>. Which part is in series decides what passes.</p>
   <ul class="f"><li><b>Low-pass</b> (resistor in series, output across the capacitor): slow changes get through, fast ones are smoothed away. Well above fc it <b>integrates</b>: the output is the running total of the input, so a square wave becomes a triangle.</li><li><b>High-pass</b> (capacitor in series, output across the resistor): only <i>changes</i> get through and a steady level drains away with time constant τ. Well below fc it <b>differentiates</b>: a square wave becomes spikes at the edges.</li><li>Put the two in series and you have a <b>band-pass</b>, exactly what an ECG amplifier does between its 0.05 Hz and 150 Hz corners.</li></ul>
   <div class="rcg"><div id="rcS" class="stack" style="gap:8px"><div class="row" id="rcCtl"></div><div id="rcSv"></div><div id="rcSl" class="stack" style="gap:8px"></div></div><div style="min-width:0"><div class="vwrap"><div id="rcT"></div></div><div class="vwrap" style="margin-top:10px"><div id="rcB"></div></div></div></div><p id="rcTx" class="note"></p>`);H.appendChild(c);
  segment($('#rcCtl',c),[['lp','Low-pass'],['hp','High-pass']],'hp',v=>{st.type=v;if(st.inp!=='step'){st.ratio=v==='lp'?5:.2;rs.set(st.ratio)}draw()});segment($('#rcCtl',c),[['step','Step'],['sq','Square wave'],['sin','Sine']],'step',v=>{st.inp=v;draw()});
  slider($('#rcSl',c),'Resistance R',{min:100,max:1e7,log:1,val:st.R,fmt:v=>fmtSI(v,'Ω')},v=>{st.R=v;draw()});slider($('#rcSl',c),'Capacitance C',{min:1e-9,max:1e-3,log:1,val:st.C,fmt:v=>fmtSI(v,'F')},v=>{st.C=v;draw()});
  const rs=slider($('#rcSl',c),'Input freq ÷ fc',{min:.05,max:20,log:1,val:.2,fmt:v=>'× '+(+v.toPrecision(2))},v=>{st.ratio=v;draw()});
  const tcv=mkCanvas($('#rcT',c),240),bcv=mkCanvas($('#rcB',c),170);
  function draw(){$('#rcSv',c).innerHTML=schem(st.type);const tau=st.R*st.C,fc=1/(2*Math.PI*tau),per=st.inp!=='step';rs.input.disabled=!per;rs.input.parentElement.style.opacity=per?1:.45;
    let T,pre=0,inp;if(!per){T=7*tau;inp=t=>t>=tau?1:0}else{const f=st.ratio*fc,P=1/f;T=4*P;pre=6*P;inp=st.inp==='sq'?(t=>(t%P)<P/2?1:-1):(t=>Math.sin(2*Math.PI*f*t))}
    const n=1600,dt=(T+pre)/n,al=Math.exp(-dt/tau);let y=0;const xi=[],yo=[];for(let i=0;i<n;i++){const t=i*dt,x=inp(t);y=al*y+(1-al)*x;if(t>=pre){xi.push(x);yo.push(st.type==='lp'?y:x-y)}}
    let S=cvSetup(tcv);if(S){const{g,w,h,C}=S,fm=getComputedStyle(document.body).getPropertyValue('--font-mono'),ml=12,mr=12,mt=16,mb=26,pw=w-ml-mr,ph=h-mt-mb,lo=per?-1.25:-.1,hi=per?1.25:1.15,Y=v=>mt+(hi-v)/(hi-lo)*ph,Xn=i=>ml+i/(xi.length-1)*pw;
      g.strokeStyle=C.grid;g.lineWidth=1;g.beginPath();g.moveTo(ml,Y(0)+.5);g.lineTo(w-mr,Y(0)+.5);g.stroke();
      if(!per){
        for(let k=1;k<=5;k++){const x=ml+((tau+k*tau)/T)*pw;g.strokeStyle=C.major;g.beginPath();g.moveTo(x+.5,mt);g.lineTo(x+.5,mt+ph);g.stroke();g.fillStyle=C.muted;g.font='10.5px '+fm;g.textAlign='center';g.fillText(k+'τ',x,h-9)}
        const lv=st.type==='lp'?.632:.368;g.setLineDash([4,4]);g.strokeStyle=C.mark;g.beginPath();g.moveTo(ml,Y(lv));g.lineTo(w-mr,Y(lv));g.stroke();g.setLineDash([]);g.fillStyle=C.mark;g.textAlign='right';g.fillText(st.type==='lp'?'63% after 1τ':'37% left after 1τ',w-mr-2,Y(lv)-4)}
      else{g.fillStyle=C.muted;g.font='10.5px '+fm;g.textAlign='left';g.fillText('4 cycles = '+fmtSI(T,'s'),ml,h-9)}
      g.lineJoin='round';g.strokeStyle=C.muted;g.lineWidth=1.6;g.beginPath();xi.forEach((v,i)=>i?g.lineTo(Xn(i),Y(v)):g.moveTo(Xn(i),Y(v)));g.stroke();g.strokeStyle=C.accent;g.lineWidth=2.6;g.beginPath();yo.forEach((v,i)=>i?g.lineTo(Xn(i),Y(v)):g.moveTo(Xn(i),Y(v)));g.stroke();
      g.font='600 11px '+fm;g.textAlign='left';g.fillStyle=C.muted;g.fillText('input',ml+2,mt+6);g.fillStyle=C.accent;g.fillText('output',ml+46,mt+6)}
    S=cvSetup(bcv);if(S){const{g,w,h,C}=S,fm=getComputedStyle(document.body).getPropertyValue('--font-mono'),ml=44,mr=12,mt=12,mb=26,pw=w-ml-mr,ph=h-mt-mb,fx=r=>ml+(Math.log10(r)+2)/4*pw,dy=d=>mt+(-d/40)*ph;
      g.strokeStyle=C.grid;g.fillStyle=C.muted;g.font='10.5px '+fm;g.lineWidth=1;for(let d=0;d>=-40;d-=10){g.beginPath();g.moveTo(ml,dy(d)+.5);g.lineTo(w-mr,dy(d)+.5);g.stroke();g.textAlign='right';g.fillText(d+' dB',ml-5,dy(d)+4)}
      [.01,.1,1,10,100].forEach(r=>{g.strokeStyle=C.major;g.beginPath();g.moveTo(fx(r)+.5,mt);g.lineTo(fx(r)+.5,mt+ph);g.stroke();g.textAlign='center';g.fillText(r===1?'fc':'×'+r,fx(r),h-9)});
      g.strokeStyle=C.accent;g.lineWidth=2.6;g.beginPath();for(let k=0;k<=300;k++){const r=Math.pow(10,-2+4*k/300),m=st.type==='lp'?1/Math.sqrt(1+r*r):r/Math.sqrt(1+r*r),d=Math.max(-40,20*Math.log10(m));k?g.lineTo(fx(r),dy(d)):g.moveTo(fx(r),dy(d))}g.stroke();
      g.fillStyle=C.accent;g.beginPath();g.arc(fx(1),dy(-3.01),4,0,6.3);g.fill();if(per){g.strokeStyle=C.mark;g.setLineDash([4,4]);g.beginPath();g.moveTo(fx(st.ratio),mt);g.lineTo(fx(st.ratio),mt+ph);g.stroke();g.setLineDash([]);g.fillStyle=C.mark;g.textAlign='center';g.fillText('input',fx(st.ratio),mt+10)}
      g.fillStyle=C.muted;g.textAlign='left';g.fillText('−6 dB per octave beyond fc',ml+6,st.type==='lp'?dy(-30):dy(-6)-14)}
    const reg=!per?(st.type==='lp'?'After a step the output climbs toward the input and reaches 63% at 1τ, 95% at 3τ and 99% at 5τ.':'After a step the output jumps and then drains away: 37% remains at 1τ, 5% at 3τ. This is why a 0.5 Hz monitor filter can create false ST depression or elevation after large QRS complexes.'):(st.type==='lp'?(st.ratio>=3?'Input frequency is well above fc: the capacitor never gets time to charge, so the circuit <b>integrates</b>. A square wave becomes a triangle and the amplitude shrinks as frequency rises.':st.ratio<=.33?'Input frequency is well below fc: the output follows the input and passes unchanged.':'Near fc the output is attenuated to about 70% and delayed.'):(st.ratio<=.33?'Input frequency is well below fc: the circuit <b>differentiates</b>. A square wave becomes spikes at each edge; only changes get through.':st.ratio>=3?'Input frequency is well above fc: the signal passes unchanged.':'Near fc the output is attenuated to about 70% and shifted forward in time.'));
    $('#rcTx',c).innerHTML=`<b>τ = R × C = ${fmtSI(tau,'s')}</b> · <b>fc = 1 ÷ (2π R C) = ${fmtSI(fc,'Hz')}</b> · 10–90% rise time ≈ 2.2 τ = ${fmtSI(2.2*tau,'s')}. ${reg}`}
  AX.draws.sig.push(draw);draw()}


