
/* ============ mechanism lab: coronary anatomy, occlusion and evolution ============ */
/* 17-segment LV model: each segment has an outward normal in body coordinates (x left, y inferior, z anterior).
   Transmural injury makes the injury current point toward the injured epicardium, so the ST vector is the sum
   of the injured segments' normals; leads facing it show elevation, leads facing away show reciprocal depression. */
const LVAX=nrm([.6,.45,.65]);
const SEG=(()=>{const T={1:['Basal anterior',[.25,-.45,.85]],2:['Basal anteroseptal',[-.35,-.25,.9]],3:['Basal inferoseptal',[-.5,.7,-.1]],4:['Basal inferior',[.05,.85,-.5]],5:['Basal inferolateral',[.45,.2,-.85]],6:['Basal anterolateral',[.75,-.55,.2]],
  7:['Mid anterior',[.3,-.15,.95]],8:['Mid anteroseptal',[-.3,0,.95]],9:['Mid inferoseptal',[-.45,.8,.1]],10:['Mid inferior',[.1,.95,-.3]],11:['Mid inferolateral',[.65,.25,-.7]],12:['Mid anterolateral',[.9,-.25,.3]],
  13:['Apical anterior',[.35,.1,.95]],14:['Apical septal',[-.15,.3,.95]],15:['Apical inferior',[.3,.9,.3]],16:['Apical lateral',[.9,.15,.4]],17:['Apex',[.6,.45,.65]],RV:['RV free wall',[-.85,.2,.5]]},o={};
  for(const k in T)o[k]={name:T[k][0],n:nrm(T[k][1])};return o})();
const OCC={
 LM:{name:'Left main (total)',segs:[1,2,7,8,13,14,17,5,6,11,12,16],note:'Total left main occlusion is usually fatal before arrival. Survivors more often have subtotal disease, which shows diffuse subendocardial ischemia: widespread ST depression with ST elevation in aVR.'},
 pLAD:{name:'Proximal LAD (before S1 and D1)',segs:[1,2,7,8,13,14,17,6,12,16],note:'Anterior wall, septum and the first diagonal’s high lateral territory: elevation in V1–V4 plus I and aVL, with reciprocal depression in III and aVF.'},
 mLAD:{name:'Mid LAD (after D1)',segs:[7,8,13,14,17],note:'Spares the basal septum and the first diagonal: elevation in V2–V4, little in I or aVL, and no inferior reciprocity.'},
 dLAD:{name:'Distal LAD',segs:[13,14,16,17],note:'Apical segments only: elevation in V3–V6, smaller amplitude.'},
 D1:{name:'First diagonal',segs:[6,12,1],note:'High lateral wall: elevation in I, aVL and often V2 (the “South African flag”), with depression in III.'},
 pLCx:{name:'Proximal circumflex',segs:[5,6,11,12,16],note:'Lateral and posterolateral walls: often subtle. Look for small elevation in I, aVL, V5–V6 and ST depression in V1–V3 (posterior). Record V7–V9.'},
 OM:{name:'Obtuse marginal',segs:[11,12,5],note:'Mid lateral and posterolateral wall: lateral elevation, posterior depression in V1–V3; easy to miss.'},
 pRCA:{name:'Proximal RCA (before RV branch)',segs:[3,4,9,10,15,'RV'],note:'Inferior wall plus the right ventricle: elevation III > II, reciprocal depression in aVL and I, elevation in V1 and V4R. Preload dependent: avoid nitrates.'},
 mRCA:{name:'Mid RCA (after RV branch)',segs:[3,4,9,10,15],note:'Inferior wall without RV: elevation III > II with aVL depression; V1 neutral.'},
 dRCA:{name:'Distal RCA / PDA',segs:[4,10,15,3],note:'Smaller inferior infarct; posterolateral branches may add V5–V6 or posterior changes.'}};
function occSegs(id,dom,wrap){let s=OCC[id].segs.slice();if(dom==='left'){if(id==='pLCx'||id==='OM')s=s.concat([3,4,9,10,15]);if(/RCA/.test(id))s=['RV']}
  if(dom==='co'&&id==='pLCx')s=s.concat([4,10]);if(wrap&&/LAD/.test(id))s=s.concat([15,10]);return[...new Set(s)]}
function injuryVec(segs){let v=[0,0,0];segs.forEach(k=>{const n=SEG[k].n,w=k==='RV'?1.6:k===17?.6:1;v=[v[0]+n[0]*w,v[1]+n[1]*w,v[2]+n[2]*w]});const m=Math.hypot(...v);return{d:nrm(v),m}}
/* time course (minutes since occlusion; tr = minutes at reperfusion or null) */
function occStage(tm,tr){const ramp=(x,a,b)=>clamp((x-a)/(b-a),0,1),pre=tr==null?tm:Math.min(tm,tr);
  let st=ramp(pre,3,30)*(1-.65*ramp(pre,360,4320))*(1-.5*ramp(pre,4320,20160)),hyp=ramp(pre,2,12)*(1-ramp(pre,60,360)),q=ramp(pre,60,1080),tinv=ramp(pre,720,3600)*(1-.4*ramp(pre,20160,60000));
  let label=tm<20?'Hyperacute':tm<360?'Acute':tm<2880?'Evolving':tm<20160?'Subacute':'Chronic';
  if(tr!=null&&tm>tr){const dt=tm-tr;st*=Math.exp(-dt/45);hyp*=Math.exp(-dt/20);q=Math.min(1,q+.15*ramp(dt,0,600));tinv=Math.max(tinv,.95*(1-Math.exp(-dt/200)));label=dt<90?'Reperfusing':'Reperfused'}
  return{st,hyp,q,tinv,label}}
function corMorph(segs,s,qt=.4){const{d,m}=injuryVec(segs),size=clamp(m/3,.4,1.25),z=s;
  const tN={c:qt-.097,wl:.068,wr:.042,A:.4,d:fv(43,.6)},t=[tN];if(z.hyp>.01)t.push({c:qt-.12,wl:.08,wr:.055,A:.45*z.hyp*size,d});if(z.tinv>.01)t.push({c:qt-.09,wl:.05,wr:.045,A:-.55*z.tinv*size,d});
  return V({axis:55,qt,stA:.3*z.st*size,std:d,stra:.025,t,xq:z.q>.02?[{c:.022,wl:.012,A:.5*z.q*size,d:neg(d)}]:[]})}
function corRecord(cfg,seed=77){const segs=occSegs(cfg.occ,cfg.dom,cfg.wrap),s=occStage(cfg.tm,cfg.tr),R=newRec(seed),hr=cfg.hr||76,vm=corMorph(segs,s,qtF(hr,.41)),pm=Pw('n',.15),pr=.16;
  sinus(R,{hr,pr,vm,pm});R.tm={vm,pm,pr};R.L=deriveLeads(R);R.ms=measure(R);R.meta.rhy='Sinus rhythm';computeMeta(R);autoST(R);R._c={};R.pid='corlab';R.stage=s;R.segs=segs;return R}
const corTime=[[0,'0 min'],[10,'10 min'],[30,'30 min'],[90,'90 min'],[360,'6 h'],[1080,'18 h'],[2880,'2 days'],[10080,'1 week'],[43200,'1 month']];
function buildCorLab(host){const st={occ:'pRCA',dom:'right',wrap:false,ti:3,tr:null};
  const c=el('div','card stack',`<div class="row" style="justify-content:space-between"><h2>Coronary occlusion lab: anatomy → territory → ST vector</h2><span class="lbl">Schematic model</span></div>
   <p style="max-width:88ch">Choose an occlusion site. The myocardium downstream becomes transmurally ischemic; injured cells lose K⁺ and open K-ATP channels, so current flows toward the injured epicardium. The ST vector is the sum of the injured segments' outward directions: leads looking at it show elevation, leads looking from the opposite side show the same vector as reciprocal depression. Then move through time and decide whether to reperfuse.</p>
   <div class="corg"><div><svg id="corTree" viewBox="0 0 360 340" role="img" aria-label="Coronary arteries; select an occlusion site" style="width:100%;max-width:400px;display:block;margin:auto"></svg><div class="row" id="corCtl" style="justify-content:center"></div></div>
   <div class="stack" style="gap:8px;min-width:0"><svg id="corEye" viewBox="-1.25 -1.25 2.5 2.5" role="img" aria-label="17-segment bullseye of the left ventricle" style="width:100%;max-width:240px;display:block;margin:auto"></svg><div class="row" style="justify-content:center;font-size:12px;gap:6px 14px"><span><i class="dot" style="background:var(--bad)"></i>Injured</span><span>Anterior at top, septum left</span></div></div></div>
   <div id="corTS" class="stack" style="gap:6px"></div><div class="row" id="corRep"></div><p id="corTx" class="note"></p><div id="corV"></div>`);host.appendChild(c);
  const tsl=slider($('#corTS',c),'Time since occlusion',{min:0,max:corTime.length-1,step:1,val:st.ti,fmt:v=>corTime[Math.round(v)][1]},v=>{st.ti=Math.round(v);upd()});
  const rp=el('select');[['none','No reperfusion'],['60','Reperfused at 60 min'],['180','Reperfused at 3 h'],['720','Reperfused at 12 h']].forEach(([v,t])=>rp.appendChild(new Option(t,v)));rp.addEventListener('change',()=>{st.tr=rp.value==='none'?null:+rp.value;upd()});
  const rl=el('label','row lbl','Reperfusion');rl.style.cssText='gap:6px;text-transform:none;letter-spacing:0';rl.appendChild(rp);$('#corRep',c).appendChild(rl);
  segment($('#corCtl',c),[['right','Right dominant'],['left','Left dominant'],['co','Co-dominant']],'right',v=>{st.dom=v;upd()});
  const wr=el('input');wr.type='checkbox';wr.id='corWrap';wr.addEventListener('change',()=>{st.wrap=wr.checked;upd()});const wl=el('label','row lbl','Wraparound LAD');wl.style.cssText='gap:6px;text-transform:none;letter-spacing:0';wl.prepend(wr);$('#corCtl',c).appendChild(wl);
  const vw=Viewer($('#corV',c),{foot:'ST vector from the injured segments. Drag to measure.'});
  const PTS={LM:[176,62],pLAD:[188,92],mLAD:[196,150],dLAD:[206,236],D1:[224,118],pLCx:[222,70],OM:[290,130],pRCA:[140,72],mRCA:[86,170],dRCA:[130,282]};
  function tree(){const dom=st.dom,down=k=>{const o=st.occ,dn={LM:['LM','pLAD','mLAD','dLAD','D1','pLCx','OM'],pLAD:['pLAD','mLAD','dLAD','D1'],mLAD:['mLAD','dLAD'],dLAD:['dLAD'],D1:['D1'],pLCx:['pLCx','OM'],OM:['OM'],pRCA:['pRCA','mRCA','dRCA'],mRCA:['mRCA','dRCA'],dRCA:['dRCA']}[o]||[];return dn.includes(k)};
    const art=(k,d,dash)=>`<path d="${d}" fill="none" stroke="${down(k)?'var(--muted)':'var(--bad)'}" stroke-width="${k==='LM'?7:5}" stroke-linecap="round" ${down(k)||dash?`stroke-dasharray="${down(k)?'5 5':'2 6'}"`:''} opacity="${down(k)?.6:.9}"/>`;
    let s=`<path d="M70 120 C60 60 140 40 180 52 C230 40 320 60 320 140 C320 230 250 320 205 330 C160 320 70 250 70 120 Z" fill="var(--soft)" stroke="var(--muted)" stroke-width="1.5"/><path d="M160 20 L160 55 M196 20 L196 55" stroke="var(--muted)" stroke-width="2"/><text x="178" y="16" text-anchor="middle" font-size="11" fill="var(--muted)" font-family="var(--font-ui)">Aorta</text>`;
    s+=art('LM','M172 56 L188 70')+art('pLAD','M188 70 C190 85 192 100 194 120')+art('mLAD','M194 120 C197 160 200 190 203 220')+art('dLAD','M203 220 C206 250 207 280 205 318')+art('D1','M192 100 C215 110 240 130 262 160');
    s+=art('pLCx','M188 70 C215 66 250 70 285 92')+art('OM','M285 92 C295 120 300 160 296 200')+`<path d="M285 92 C305 108 315 140 312 180" fill="none" stroke="var(--line)" stroke-width="3" stroke-dasharray="3 5"/>`;
    s+=art('pRCA','M160 58 C130 60 108 80 98 110')+art('mRCA','M98 110 C84 150 84 200 98 240')+`<path d="M90 150 C110 170 125 200 135 230" fill="none" stroke="${['pRCA'].includes(st.occ)?'var(--muted)':'var(--bad)'}" stroke-width="3" opacity=".7"/>`+art('dRCA','M98 240 C110 275 130 295 160 305',true);
    s+=`<text x="40" y="132" font-size="11" fill="var(--muted)" font-family="var(--font-ui)">RCA</text><text x="140" y="214" font-size="10" fill="var(--muted)" font-family="var(--font-ui)">RV branch</text><text x="214" y="200" font-size="11" fill="var(--muted)" font-family="var(--font-ui)">LAD</text><text x="268" y="176" font-size="11" fill="var(--muted)" font-family="var(--font-ui)">D1</text><text x="296" y="84" font-size="11" fill="var(--muted)" font-family="var(--font-ui)">LCx</text><text x="300" y="214" font-size="11" fill="var(--muted)" font-family="var(--font-ui)">OM</text><text x="150" y="324" font-size="10" fill="var(--muted)" font-family="var(--font-ui)">${dom==='left'?'PDA from LCx':'PDA (posterior)'}</text>`;
    Object.entries(PTS).forEach(([k,[x,y]])=>{const on=st.occ===k;s+=`<g class="el" tabindex="0" role="button" data-k="${k}" aria-label="Occlude ${OCC[k].name}"><circle cx="${x}" cy="${y}" r="${on?11:8}" fill="${on?'var(--ink)':'var(--panel)'}" stroke="var(--ink)" stroke-width="2"/>${on?`<path d="M${x-5} ${y-5}L${x+5} ${y+5}M${x+5} ${y-5}L${x-5} ${y+5}" stroke="var(--panel)" stroke-width="2.5"/>`:''}</g>`});
    $('#corTree',c).innerHTML=s;$$('#corTree .el',c).forEach(g=>{const go=()=>{st.occ=g.dataset.k;upd()};g.addEventListener('click',go);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})})}
  function eye(segs){const ring=(r0,r1,a0,a1)=>{const p=(r,a)=>[r*Math.cos(a*D2R),r*Math.sin(a*D2R)],[x0,y0]=p(r1,a0),[x1,y1]=p(r1,a1),[x2,y2]=p(r0,a1),[x3,y3]=p(r0,a0),lg=a1-a0>180?1:0;return`M${x0} ${y0}A${r1} ${r1} 0 ${lg} 1 ${x1} ${y1}L${x2} ${y2}A${r0} ${r0} 0 ${lg} 0 ${x3} ${y3}Z`};
    const B=[[-120,-60],[-180,-120],[120,180],[60,120],[0,60],[-60,0]],Ap=[[-135,-45],[135,225],[45,135],[-45,45]];let s='';
    const f=k=>segs.includes(k)?'var(--bad)':'var(--soft)',op=k=>segs.includes(k)?.75:1;
    B.forEach(([a,b],i)=>{s+=`<path d="${ring(.8,1.2,a,b)}" fill="${f(i+1)}" opacity="${op(i+1)}" stroke="var(--panel)" stroke-width=".02"/><path d="${ring(.42,.8,a,b)}" fill="${f(i+7)}" opacity="${op(i+7)}" stroke="var(--panel)" stroke-width=".02"/>`});
    Ap.forEach(([a,b],i)=>{s+=`<path d="${ring(.16,.42,a,b)}" fill="${f(13+i)}" opacity="${op(13+i)}" stroke="var(--panel)" stroke-width=".02"/>`});s+=`<circle r=".16" fill="${f(17)}" opacity="${op(17)}" stroke="var(--panel)" stroke-width=".02"/>`;
    s+=`<text x="0" y="-1.08" font-size=".1" text-anchor="middle" fill="var(--ink)" font-family="var(--font-ui)">Ant</text><text x="0" y="1.15" font-size=".1" text-anchor="middle" fill="var(--ink)" font-family="var(--font-ui)">Inf</text><text x="-1.18" y=".03" font-size=".1" text-anchor="start" fill="var(--ink)" font-family="var(--font-ui)">Sept</text><text x="1.18" y=".03" font-size=".1" text-anchor="end" fill="var(--ink)" font-family="var(--font-ui)">Lat</text>`;
    if(segs.includes('RV'))s+=`<text x="-1.2" y="-1.1" font-size=".1" fill="var(--bad)" font-family="var(--font-ui)">+ RV</text>`;$('#corEye',c).innerHTML=s}
  let tmr=0;function upd(){tree();const segs=occSegs(st.occ,st.dom,st.wrap);eye(segs);clearTimeout(tmr);tmr=setTimeout(()=>{const R=corRecord({occ:st.occ,dom:st.dom,wrap:st.wrap,tm:corTime[st.ti][0],tr:st.tr});vw.setRec(R);vw.setAnn(true);
    const up=(R.ann.find(a=>a.txt==='ST elevation')||{leads:[]}).leads,dn=(R.ann.find(a=>a.txt==='ST depression')||{leads:[]}).leads,s=R.stage;
    $('#corTx',c).innerHTML=`<b>${OCC[st.occ].name}${st.dom!=='right'&&(/RCA|LCx|OM/.test(st.occ))?` (${st.dom} dominant)`:''} · ${s.label}, ${corTime[st.ti][1]}${st.tr!=null?`, reperfused at ${st.tr<60?st.tr+' min':st.tr/60+' h'}`:''}.</b> Elevation: ${up.join(', ')||'none'}. Depression: ${dn.join(', ')||'none'}. ${OCC[st.occ].note} ${s.hyp>.3?'Early on, the T waves are hyperacute: broad, tall and bulky relative to the QRS, before much ST elevation.':''}${s.q>.3?' Q waves are forming: dead myocardium no longer contributes forces, so the vector points away from the infarct.':''}${s.tinv>.3?(st.tr!=null&&corTime[st.ti][0]>st.tr?' After reperfusion, ST elevation falls quickly and the T waves invert (reperfusion T waves, like Wellens).':' The T waves are inverting as the infarct evolves.'):''}`},80)}
  upd();return{draw:()=>vw.draw()}}
