
/* ============ analysis tasks: lead selection, WCT algorithms, structured read, alarm triage ============ */
const LGRID=[['I','aVR','V1','V4'],['II','aVL','V2','V5'],['III','aVF','V3','V6']];
const NOLEAD=['vf','tdp','pmvt','vflutter','cpr','tremor','artifact','hyperk2','preaf','bidir'];
function leadSets(R){const L=R.ms.leads,o={ste:[],std:[],q:[],tinv:[]};LEADS.forEach(k=>{const x=L[k];if(!x)return;if(x.st40>=stThr(k))o.ste.push(k);else if(x.st40<=-.05)o.std.push(k);
  if(k!=='aVR'&&k!=='III'&&x.qd>=.03&&x.qa<=-.1)o.q.push(k);if(k!=='aVR'&&x.tmin<-.1&&(x.tmax<.06||-x.tmin>x.tmax*.9))o.tinv.push(k)});return o}
const LQV={ste:{q:'Select every lead with ST elevation',rule:'at least 1 mm at J+40 ms (1.5 mm in V2–V3)',why:'Leads whose positive pole faces the injury current (toward injured epicardium) record the ST segment above baseline. Contiguous elevated leads map a territory; the leads looking from the opposite side show the same vector as depression.'},
 std:{q:'Select every lead with ST depression',rule:'at least 0.5 mm at J+40 ms',why:'ST depression is either reciprocal (the same injury vector seen from behind), subendocardial ischemia (current flowing toward the cavity), or secondary to abnormal depolarization (strain, bundle branch block, digoxin). Which one depends on the pattern of leads.'},
 q:{q:'Select every lead with a pathologic Q wave',rule:'at least 30 ms wide and 1 mm deep (III alone and aVR excluded)',why:'Dead myocardium contributes no depolarization forces. A lead looking through the infarct sees the far wall moving away: an initial negative deflection. Narrow, deep Q waves can instead come from a thick septum (HCM).'},
 tinv:{q:'Select every lead with an inverted T wave',rule:'T clearly negative, fully or in its terminal half (aVR excluded)',why:'The T wave follows the repolarization gradient. When the layer facing a lead repolarizes later than usual (ischemia, reperfusion, strain, cardiomyopathy, raised intracranial pressure), the gradient reverses and the T inverts.'}};
function leadQ(pid,seed){seed=seed??Math.floor(Math.random()*1e9);const r=mkRand(seed+41),rec=generate(pid,seed);if(!rec.ms)return null;const sets=leadSets(rec),p=PM[pid];
  const pref={isch:['ste','std','q','tinv'],chan:['tinv','ste','q'],meta:['tinv','ste','std'],struct:['std','tinv','q'],mimic:['ste','tinv','std'],cond:['tinv','std','q'],pace:['std','ste'],normal:['ste','tinv'],rhythm:['std','tinv']}[p.cat]||['ste','std','tinv','q'];
  const ok=shuffle(pref,r).filter(v=>sets[v].length>=1&&sets[v].length<=9);if(!ok.length)return null;const v=ok[0];
  return{kind:'lead',pid,seed,rec,v,set:sets[v],pick:[],chosen:null,m:{a:1,opts:[]}}}
leadQ.can=pid=>!NOLEAD.includes(pid)&&!!PM[pid];
function jacc(a,b){const A=new Set(a),B=new Set(b);let i=0;A.forEach(x=>{if(B.has(x))i++});const u=new Set([...a,...b]).size;return u?i/u:1}
function leadOk(q){return q.chosen!==null&&q.chosen!==-1&&jacc(q.pick,q.set)>=.75}
/* ---- wide-complex tachycardia algorithms, computed on the median beat ---- */
const WCTP=['vt','fascvt','rvotvt','svtab','antidromic','preaf'];
function wctFeat(R){const tp=template(R);if(!tp)return null;const{L,t0,vm}=tp,i0=Math.round((t0+vm.on)*FS),i1=Math.round((t0+vm.off)*FS),ib=Math.max(0,i0-6),f={};
  PREC.concat(['aVR','I','II']).forEach(k=>{const a=L[k],b=a[ib];let mx=-9,mn=9,imx=i0,imn=i0;for(let i=i0;i<=i1;i++){const v=a[i]-b;if(v>mx){mx=v;imx=i}if(v<mn){mn=v;imn=i}}
    const rs=mx>.1&&mn<-.1&&imx<imn&&imn<i1-Math.round(.012*FS);let s0=0,i=i0;for(;i<=i1;i++){const v=a[i]-b;if(Math.abs(v)>.025){s0=Math.sign(v);break}}let w=0,ipk=0;if(s0){let j=i;for(;j<=i1;j++){const v=a[j]-b;if(s0*v>ipk)ipk=s0*v;if(Math.sign(v)===-s0&&Math.abs(v)>.025)break}w=(j-i0)/FS*1000}
    const n4=Math.round(.04*FS),vi=Math.abs((a[Math.min(i1,i0+n4)]-b)-0),vt=Math.abs((a[i1]-b)-(a[Math.max(i0,i1-n4)]-b));
    f[k]={R:mx,S:-mn,rs,rsInt:rs?Math.round((imn-i0)/FS*1000):0,init:s0,initW:Math.round(w),initPk:ipk,vi,vt,net:mx+mn}});
  const dis=R.ev.p.some(p=>!p.cond)&&R.ev.q.some(q=>q.k==='v'),cap=R.ann.some(a=>/apture|usion/.test(a.txt||''));return{f,dis:dis||cap,qrs:Math.round(vm.qrsd*1000)}}
function wctSteps(F,alg){const f=F.f,pr=PREC;if(alg==='brugada'){const anyRS=pr.filter(k=>f[k].rs),maxRS=Math.max(0,...anyRS.map(k=>f[k].rsInt)),morph=f.V6.S>f.V6.R*1.05||(f.V1.net<0&&f.V1.rsInt>70);
    return[{q:'Is an RS complex absent from every precordial lead (V1–V6)?',fact:!anyRS.length,detail:anyRS.length?`RS present in ${anyRS.join(', ')}.`:'No precordial lead has an R followed by an S: concordant or monophasic complexes.',why:'Absent RS means activation sweeps from one end of the ventricles (apex or base) without the septal-then-free-wall sequence of His–Purkinje activation.'},
      {q:'Is the R-to-S interval longer than 100 ms in any precordial lead?',fact:maxRS>100,detail:anyRS.length?`Longest R-to-S ${maxRS} ms.`:'Not applicable.',why:'Onset of R to the nadir of S reflects how fast the early part of the QRS spreads; slow, muscle-to-muscle spread from a ventricular focus stretches it.'},
      {q:'Is there AV dissociation (independent P waves, capture or fusion beats)?',fact:F.dis,detail:F.dis?'P waves or capture beats show the atria and ventricles running independently.':'No dissociated P waves visible on this strip.',why:'If the atria and ventricles keep separate time, the tachycardia must arise below the AV node.'},
      {q:'Do V1–V2 and V6 meet the morphology criteria for VT (for example, R/S < 1 in V6)?',fact:morph,detail:`V6: R ${(f.V6.R*10).toFixed(1)} mm, S ${(f.V6.S*10).toFixed(1)} mm${f.V1.net<0?`; V1 R-to-S ${f.V1.rsInt} ms`:''}.`,why:'Aberrancy keeps the shape of a true bundle branch block (rsR′ in V1, qRs in V6). Shapes that no bundle branch block can make point to a ventricular origin.'}]}
  const a=f.aVR;return[{q:'Does the QRS in aVR start with an R wave (a dominant initial positive deflection)?',fact:a.init>0&&a.initPk>=.15,detail:`Initial deflection in aVR is ${a.init>0?`positive, ${(a.initPk*10).toFixed(1)} mm`:a.init<0?'negative':'flat'}.`,why:'aVR looks up from the right shoulder toward the base. Normal and aberrant activation moves away from it, so aVR starts negative. An initial R means activation starts at the apex or inferior wall and moves toward aVR: ventricular origin.'},
    {q:'Is there an initial r wave in aVR wider than 40 ms?',fact:a.init>0&&a.initW>40,detail:a.init>0?`Initial r lasts about ${a.initW} ms.`:'aVR starts negative: no initial r. (The original algorithm also counts a wide initial q and a notch on the downstroke; those are not assessed in this model.)',why:'A wide initial deflection means slow initial activation through working muscle rather than fast Purkinje fibres.'},
    {q:'In aVR, is the initial 40 ms voltage change (vi) no larger than the terminal 40 ms (vt)?',fact:a.vi<=a.vt,detail:`vi ${(a.vi*10).toFixed(1)} mm, vt ${(a.vt*10).toFixed(1)} mm (vi/vt ${(a.vi/Math.max(a.vt,.001)).toFixed(2)}).`,why:'In aberrancy the septum is activated quickly through the intact bundle, so the start of the QRS is fast and the delay is at the end (vi > vt). VT starts slowly in muscle and speeds up once it reaches the Purkinje network (vi ≤ vt).'}]}
function wctQ(pid,seed){if(!WCTP.includes(pid))return null;seed=seed??Math.floor(Math.random()*1e9);const r=mkRand(seed+53),rec=generate(pid,seed),F=wctFeat(rec);if(!F)return null;const alg=r.chance(.5)?'brugada':'vereckei',steps=wctSteps(F,alg);
  let concl=1;for(const s of steps)if(s.fact){concl=0;break}const truth=['svtab'].includes(pid)?1:0;
  return{kind:'wct',pid,seed,rec,alg,steps,i:0,ans:[],concl,chosen:null,m:{a:truth,opts:['Ventricular tachycardia','SVT with aberrancy']}}}
wctQ.can=pid=>WCTP.includes(pid);
/* ---- structured read ---- */
function readQ(pid,seed){seed=seed??Math.floor(Math.random()*1e9);const r=mkRand(seed+61),rec=generate(pid,seed),M=rec.meta,no=M.noMeas||[],f=[];if(!M.hr||no.includes('rate'))return null;
  f.push({k:'reg',n:'Ventricular rhythm',o:['Regular','Regularly irregular','Irregularly irregular'],a:{reg:0,regirr:1,irr:2}[M.reg]??0});
  f.push({k:'rate',n:'Rate',o:['Under 60','60–100','Over 100'],a:M.hr<60?0:M.hr<=100?1:2});
  if(M.axis!=null&&!no.includes('axis')&&!near(M.axis,[-30,90,180,-180,-90],9))f.push({k:'axis',n:'Axis',o:['Normal','Left','Right','Extreme'],a:axisCat(M.axis)});
  if(!M.paced&&!no.includes('pr')&&!(M.pr!=null&&near(M.pr,[120,200],12)))f.push({k:'pr',n:'PR',o:['Short','Normal','Long','Variable / none'],a:{short:0,normal:1,long:2,var:3,none:3}[M.prq]});
  if(M.qrs&&!no.includes('qrs')&&!near(M.qrs,[110,120],8))f.push({k:'qrs',n:'QRS',o:['Narrow','Intermediate','Wide'],a:M.qrs<110?0:M.qrs<120?1:2});
  if(M.qtcB&&!no.includes('qtc')&&M.hr>=50&&M.hr<=100&&!near(M.qtcB,[450,500],14))f.push({k:'qtc',n:'QTc',o:['Normal or short','450–499','500 or more'],a:M.qtcB<450?0:M.qtcB<500?1:2});
  const opts=options(pid,r);f.push({k:'dx',n:'Main finding',o:opts.map(x=>PM[x].name),a:opts.indexOf(pid),dx:1});
  return{kind:'read',pid,seed,rec,f,sel:{},chosen:null,m:{a:1,opts:[]}}}
function readScore(q){const n=q.f.length;let c=0;q.f.forEach(x=>{if(q.sel[x.k]===x.a)c++});return c/n}
function readOk(q){return q.chosen!==null&&q.chosen!==-1&&readScore(q)>=.8&&q.sel.dx===q.f.find(x=>x.k==='dx').a}
/* ---- monitor alarm triage ---- */
const ALARMS=[['vt','V-TACH',1],['vf','V-FIB',1],['tdp','V-TACH',1],['avb3','BRADY',1],['sinusarrest','PAUSE',1],['sbrady','BRADY',1],['pvc','PVC BIGEMINY',1],['flutter','TACHY',1],
  ['artifact','V-TACH',0],['tremor','V-FIB',0],['lowamp','ASYSTOLE',0],['dblcount','TACHY',0],['af','IRREGULAR HR',1],['fcap','PACER NOT CAPTURE',1]];
function alarmRec(id,seed){if(id==='lowamp'){const R=generate('nsr',seed);for(const k of['II','I','III','aVF','aVR','aVL']){const a=R.L[k];for(let i=0;i<a.length;i++)a[i]*=.07}R._c={};R.meta.rhy='Sinus rhythm (low amplitude in the monitored lead)';return R}
  if(id==='dblcount'){const R=generate('hyperk1',seed);R.meta.rhy='Sinus rhythm with tall T waves (T waves counted as beats)';return R}return generate(id,seed)}
const ALWHY={vt:'Wide regular complexes without P waves in both channels: a true ventricular rhythm.',vf:'Chaotic activity in every channel with no organized QRS.',tdp:'Polymorphic VT in every channel.',avb3:'P waves march through without conducting; the slow escape is real.',sinusarrest:'A real pause with no P wave, then an escape or sinus beat.',sbrady:'Every beat is real and slow.',pvc:'Real alternating PVCs; usually not an emergency but worth reviewing electrolytes and ischemia.',flutter:'Regular atrial waves at 300 with 2:1 conduction.',af:'True AF: irregularly irregular with no P waves.',fcap:'Pacing spikes without capture: the patient may be bradycardic.',
  artifact:'Native narrow QRS complexes march through the “VT” in the second channel. Movement of one electrode, not the heart.',tremor:'Regular 4–6 Hz oscillation in limb-lead channels with normal QRS complexes underneath: tremor.',lowamp:'The monitored lead shows almost nothing, but V1 shows normal beats. The heart vector is perpendicular to that lead or the contact is poor: change the lead or replace the electrode.',dblcount:'The monitor counts the tall peaked T waves as extra QRS complexes, doubling the rate. Change the lead or adjust the sensitivity, and think about potassium.'};
function alarmQ(seed){seed=seed??Math.floor(Math.random()*1e9);const r=mkRand(seed+71),[id,lab,tr]=ALARMS[Math.floor(r.u()*ALARMS.length)],rec=alarmRec(id,seed);
  const chans=['II',id==='artifact'?'III':id==='tremor'?'II':'V1'];if(id==='tremor')chans[0]='I';return{kind:'alarm',pid:PM[id]?id:null,aid:id,seed,rec,lab,chans,chosen:null,m:{a:tr?0:1,opts:['True alarm: go to the patient and treat the rhythm','False alarm: the signal or settings are wrong']}}}
/* ---- rendering for the four task types ---- */
function renderExtra(q,card,answered){if(!['lead','wct','read','alarm'].includes(q.kind))return false;const p=q.pid?PM[q.pid]:null;let h='';
  const done=`<div class="row"><button class="btn primary" id="qNext">Next (N)</button>${p?'<button class="btn" id="qAtlas">Open in Atlas</button>':''}</div>`;
  if(q.kind==='lead'){const V=LQV[q.v],ok=answered&&leadOk(q),L=q.rec.ms.leads;
    h+=answered?`<div class="verdict ${ok?'ok':'no'}">${ok?'Correct':q.chosen===-1?'Time ran out':'Not quite'}${p?`<span style="color:var(--ink);font-weight:500"> · ${p.name}</span>`:''}<span class="pill">Leads</span></div>`:`<div class="row" style="justify-content:space-between"><h2>${V.q}</h2><span class="pill">Leads</span></div><p class="lbl" style="text-transform:none;letter-spacing:0">Criterion: ${V.rule}. Use the calipers (ΔV) on the tracing above if needed.</p>`;
    if(answered)h+=`<h2>${V.q}</h2>`;
    h+=`<div class="lgrid">${LGRID.flat().map(k=>{const on=q.pick.includes(k),inS=q.set.includes(k),cls=answered?(inS&&on?'hit':inS?'miss':on?'extra':''):(on?'on':'');const val=answered?(q.v==='ste'||q.v==='std'?`${(L[k].st40*10>0?'+':'')}${(L[k].st40*10).toFixed(1)}`:q.v==='q'?`${Math.round(L[k].qd*1000)} ms`:`${(Math.abs(L[k].tmin)>L[k].tmax?L[k].tmin*10:L[k].tmax*10).toFixed(1)}`):'';
      return`<button class="lbtn ${cls}" type="button" data-ld="${k}" ${answered?'disabled':''} aria-pressed="${on}"><b>${k}</b>${val?`<span>${val}</span>`:''}</button>`}).join('')}</div>`;
    if(!answered)h+=`<div class="row"><button class="btn primary" id="lqCheck" type="button">Check leads</button><span class="lbl" style="text-transform:none;letter-spacing:0">${q.pick.length} selected</span></div>`;
    else{h+=`<div class="row" style="gap:6px 14px;font-size:12.5px"><span><i class="lk hit"></i>Correct</span><span><i class="lk miss"></i>Missed</span><span><i class="lk extra"></i>Not part of the set</span></div><div class="note"><b>Answer: ${q.set.join(', ')}.</b> ${V.why}${q.v==='ste'?` Territories: ${[...new Set(q.set.map(leadTerr))].join(', ')}.`:''}</div>${p&&p.mech?`<p style="margin:0"><b>${p.name}.</b> ${p.mech}</p>`:''}`+done}}
  else if(q.kind==='wct'){const stp=q.steps,alg=q.alg==='brugada'?'Brugada (1991)':'Vereckei aVR (2008)',stop=stp.findIndex(s=>s.fact),last=stop<0?stp.length-1:stop;
    h+=`<div class="row" style="justify-content:space-between"><h2>Wide-complex tachycardia: work the ${alg} algorithm</h2><span class="pill">Algorithm</span></div><p class="lbl" style="text-transform:none;letter-spacing:0">Answer each step from the tracing. Any “yes” means VT; “no” to every step favours SVT with aberrancy.</p><ol class="wsteps">`;
    for(let i=0;i<=Math.min(q.i,last);i++){const s=stp[i],a=q.ans[i];h+=`<li><b>${s.q}</b>${a===undefined?`<div class="row" style="gap:8px;margin-top:6px"><button class="btn small" type="button" data-wa="1">Yes</button><button class="btn small" type="button" data-wa="0">No</button></div>`:`<div class="${a===s.fact?'wok':'wno'}">You said ${a?'yes':'no'} · measured: ${s.fact?'yes':'no'}. ${s.detail}</div><div class="msum">${s.why}</div>`}</li>`}
    h+='</ol>';const stepsDone=q.ans.length>last;
    if(stepsDone&&!answered)h+=`<div class="note">The algorithm ${q.concl===0?`stops at step ${last+1}: <b>VT</b>`:'finds no VT criterion: <b>SVT with aberrancy</b>'}. What is your conclusion?</div><div class="qgrid">${q.m.opts.map((o,i)=>`<button class="opt" data-mi="${i}"><kbd>${i+1}</kbd><span>${o}</span></button>`).join('')}</div>`;
    if(answered){const ok=q.chosen===q.m.a;h=`<div class="verdict ${ok?'ok':'no'}">${ok?'Correct':q.chosen===-1?'Time ran out':'Not quite'}<span style="color:var(--ink);font-weight:500"> · ${p.name}</span></div>`+h;
      h+=`<div class="note"><b>${q.m.opts[q.m.a]}.</b> ${q.pid==='preaf'||q.pid==='antidromic'?'This is a pre-excited tachycardia: the ventricles are activated through an accessory pathway, so every algorithm calls it VT. That is the safe call: treat as VT and avoid AV-nodal blockers.':q.pid==='fascvt'?'Fascicular VT exits into the Purkinje network early, so its QRS is narrower and can pass the first algorithm steps; the RBBB with left-axis shape in a young patient is the clue.':q.concl!==q.m.a?'The algorithm and the true origin disagree here, which happens in a minority of cases; when uncertain, treat a wide regular tachycardia as VT.':'The algorithm agrees with the true origin.'}</div>${p.mech?`<p style="margin:0">${p.mech}</p>`:''}`+done}}
  else if(q.kind==='read'){const sc=answered?readScore(q):0;
    h+=answered?`<div class="verdict ${readOk(q)?'ok':'no'}">${readOk(q)?'Correct':q.chosen===-1?'Time ran out':'Not quite'} · ${Math.round(sc*100)}% of fields<span class="pill">Structured read</span></div>`:`<div class="row" style="justify-content:space-between"><h2>Structured read: fill in each part</h2><span class="pill">Structured read</span></div>`;
    h+=`<div class="rform">${q.f.map(x=>`<div class="rrow"><span class="lbl">${x.n}</span><div class="seg ${x.dx?'rdx':''}" data-rk="${x.k}">${x.o.map((o,i)=>`<button type="button" data-v="${i}" aria-pressed="${q.sel[x.k]===i}" ${answered?'disabled':''} class="${answered?(i===x.a?'rk-ok':q.sel[x.k]===i?'rk-no':''):''}">${o}</button>`).join('')}</div></div>`).join('')}</div>`;
    if(!answered)h+=`<div class="row"><button class="btn primary" id="rdCheck" type="button" ${Object.keys(q.sel).length===q.f.length?'':'disabled'}>Check my read</button></div>`;
    else{const M=q.rec.meta;h+=`<div class="note"><b>Model read:</b> ${M.rhy}, ${M.hr}/min${M.axis!=null?`, axis ${M.axis}°`:''}${M.pr!=null&&!['var','none'].includes(M.prq)?`, PR ${M.pr} ms`:''}${M.qrs?`, QRS ${M.qrs} ms`:''}${M.qtcB?`, QTc ${M.qtcB} ms`:''}. <b>${p.name}.</b> ${firstS(p.sig)}</div>`+done}}
  else if(q.kind==='alarm'){const D_=leadData(q.rec,{filt:'mon',notch:true});
    h+=`<div class="alarm"><span class="abadge">${q.lab}</span><span>Monitor alarm · 0.5–40 Hz monitor filter · leads ${q.chans.join(' and ')}</span></div><div class="vwrap"><div class="vscroll"><canvas id="alCv"></canvas></div></div>`;
    if(!answered)h+=`<h2>Is this a true alarm?</h2><div class="qgrid long">${q.m.opts.map((o,i)=>`<button class="opt" data-mi="${i}"><kbd>${i+1}</kbd><span>${o}</span></button>`).join('')}</div>`;
    else{const ok=q.chosen===q.m.a;h=`<div class="verdict ${ok?'ok':'no'}">${ok?'Correct':q.chosen===-1?'Time ran out':'Not quite'}<span style="color:var(--ink);font-weight:500"> · ${q.m.opts[q.m.a].split(':')[0]}</span><span class="pill">Alarm triage</span></div>`+h+`<div class="note"><b>${q.rec.meta.rhy}.</b> ${ALWHY[q.aid]||''} Always look at the patient: a pulse and a talking patient settle most alarms.</div><div class="row"><button class="btn primary" id="qNext">Next (N)</button><button class="btn" id="alFull" type="button">Show the 12-lead</button></div>`}
    card.innerHTML=h;const cv=$('#alCv',card);requestAnimationFrame(()=>drawStrip(cv,q.chans.map(c=>({data:D_[c],label:c})),{t0:0,dur:DUR,rowMM:26,foot:'25 mm/s · 10 mm/mV · monitor filter'}));
    const fb=$('#alFull',card);if(fb)fb.addEventListener('click',()=>{$('#qViewer').hidden=false;qViewer.setRec(q.rec)});}
  if(q.kind!=='alarm')card.innerHTML=h;
  $$('.opt[data-mi]',card).forEach(b=>b.addEventListener('click',()=>choose(+b.dataset.mi)));
  $$('[data-ld]',card).forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.ld,i=q.pick.indexOf(k);i>=0?q.pick.splice(i,1):q.pick.push(k);renderCard()}));
  const lc_=$('#lqCheck',card);if(lc_)lc_.addEventListener('click',()=>choose(1));
  $$('[data-wa]',card).forEach(b=>b.addEventListener('click',()=>{q.ans[q.i]=b.dataset.wa==='1';const stop=q.steps.findIndex(s=>s.fact),last=stop<0?q.steps.length-1:stop;if(q.i<last)q.i++;else q.i=last+1;renderCard()}));
  $$('[data-rk]',card).forEach(g=>g.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;q.sel[g.dataset.rk]=+b.dataset.v;renderCard()}));
  const rc=$('#rdCheck',card);if(rc)rc.addEventListener('click',()=>choose(1));
  const nb=$('#qNext',card);if(nb)nb.addEventListener('click',next);const ab=$('#qAtlas',card);if(ab)ab.addEventListener('click',()=>openAtlas(q.pid,q.seed));return true}
function extraOk(q){if(q.kind==='lead')return leadOk(q);if(q.kind==='read')return readOk(q);return q.chosen===q.m.a}
