
/* ============ integrated case: one fictional patient, heart and brain over 72 hours (shared by both apps) ============ */
const PACASE={title:'After cardiac arrest: heart and brain over three days',intro:'A fictional 58-year-old collapses with ventricular fibrillation. Bystander CPR is started; circulation returns after 22 minutes. The same oxygen debt, ions, drugs and temperature act on both organs, so the ECG and EEG tell one story from two sides. At 12 hours the course branches: choose a recovering or a severely injured brain.',
 steps:[
 {t:30,lab:'Return of circulation',vit:'HR 124 sinus · MAP 68 on norepinephrine · 35.8 °C · pH 7.12 · lactate 9 mmol/L · K⁺ 4.9',ecg:'antstemi',ecgTxt:'Anterior ST elevation: an occluded left anterior descending artery, the likely cause of the arrest. Injured myocardium loses K⁺ through K-ATP channels and its plateau falls, creating the injury current.',
  eeg:'Suppressed (and sedated): synaptic transmission stopped within about 20 s of the arrest, and ATP-dependent pumps failed within minutes. Early suppression is expected and is not yet prognostic.',link:'Both organs suffered the same interruption of flow. The heart shows where its supply is still blocked; the brain shows how much synaptic function has returned. Neither tracing alone predicts outcome this early.'},
 {t:120,lab:'2 h: after coronary intervention, temperature control',vit:'HR 96 · MAP 74 · 36 °C · pH 7.31 · K⁺ 3.4 · Mg²⁺ 0.7 mmol/L',ecg:'wellens',ecgTxt:'After reperfusion the ST segments resolve and deep T-wave inversions appear in V2–V3: the recovering, stunned myocardium repolarizes late.',
  eeg:'Still largely suppressed under propofol; brief bursts may appear as energy returns.',link:'Epinephrine and β-agonists drive K⁺ into cells through the Na⁺/K⁺ pump, and K⁺ falls. Low K⁺ and Mg²⁺ lengthen repolarization and raise the risk of torsades; for the brain, metabolic derangements and sedation must be corrected before the EEG can be interpreted.'},
 {t:720,lab:'12 h',vit:'HR 54 sinus bradycardia · QTc 490 ms · 36 °C · K⁺ 3.6 (replaced) · glucose 9 mmol/L',ecg:'lqt',ecgTxt:'Sinus bradycardia with a long QT: temperature control, sedatives and recent electrolyte depletion all slow repolarization.',
  eeg:{good:'Continuous, low-voltage background: surviving cortical networks are active again. Continuity by about 12 h is a favourable sign.',poor:'Burst-suppression with identical bursts: so few cortical circuits survive that every burst follows the same path. Highly specific for poor outcome, even this early.'},link:'Cooling and sedatives slow ion channels in both organs: long QT and bradycardia in the heart, a slower and more discontinuous EEG in the brain. That is why both are read in the light of temperature and drugs.'},
 {t:1500,lab:'25 h: sedation stopped',vit:'HR 78 sinus · QTc 450 · 37 °C · normal electrolytes',ecg:'nsr',ecgTxt:'Sinus rhythm; the QT shortens as temperature, drugs and electrolytes normalize.',
  eeg:{good:'Reactive background with sleep spindles: thalamus, reticular nucleus and arousal pathways are working.',poor:'Generalized periodic discharges on a suppressed background, unreactive, with myoclonus: a highly malignant pattern after 24 h without confounders.'},link:'Myoclonus and discharges raise heart rate and blood pressure through autonomic outflow; seizures on the EEG can be the cause of unexplained tachycardia on the monitor.'},
 {t:4200,lab:'Day 3: decision point',vit:'Stable hemodynamics',ecg:'nsr',ecgTxt:'The heart has recovered enough to support the circulation.',
  eeg:{good:'A posterior rhythm returns; the patient follows commands.',poor:'Unchanged: no continuity or reactivity by 72 h. Prognosis combines EEG with examination, somatosensory evoked potentials, neuron-specific enolase and imaging, never one test alone.'},link:'Cardiac recovery and neurological recovery are separate questions. The ECG answers whether the heart can sustain life; the EEG, with other modalities, helps answer what kind of brain survives.'}]};
const CASE={i:0,br:'good'},CASEH0=(location.hash||'');
function buildCase(host){host=host||document.getElementById('aCase');host.innerHTML='';const app=LCFG.app,other=LCFG.other;
  const wrap=document.createElement('div');wrap.className='stack';host.appendChild(wrap);
  wrap.innerHTML=`<div class="card stack"><h2>${PACASE.title}</h2><p style="margin:0;max-width:86ch">${PACASE.intro}</p><div class="row" id="csSteps" style="gap:6px"></div><div class="row"><span class="lbl">From 12 h</span><div class="seg" id="csBr"><button type="button" data-v="good" aria-pressed="true">Recovering brain</button><button type="button" data-v="poor" aria-pressed="false">Severe anoxic injury</button></div></div></div>
   <div class="card stack"><div class="row" style="justify-content:space-between"><h2 id="csT"></h2><a class="btn small" id="csOther" href="#">See the ${app==='eeg'?'ECG':'EEG'} at this time →</a></div><p class="lbl" id="csVit" style="text-transform:none;letter-spacing:0;margin:0"></p><div id="csPanel"></div>
   <div class="two"><div class="stack" style="gap:6px"><h3>${app==='eeg'?'EEG':'ECG'}</h3><p id="csMine" style="margin:0"></p></div><div class="stack" style="gap:6px"><h3>${app==='eeg'?'ECG':'EEG'} at the same time</h3><p id="csTheirs" style="margin:0"></p></div></div><div class="note" id="csLink"></div></div>`;
  const q=s=>wrap.querySelector(s),panel=LCFG.casePanel(q('#csPanel'));
  q('#csSteps').innerHTML=PACASE.steps.map((s,i)=>`<button class="chip" type="button" data-cs="${i}">${s.lab}</button>`).join('');
  q('#csSteps').addEventListener('click',e=>{const b=e.target.closest('[data-cs]');if(b){CASE.i=+b.dataset.cs;show()}});q('#csBr').addEventListener('click',e=>{const b=e.target.closest('button');if(b){CASE.br=b.dataset.v;q('#csBr').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));show()}});
  function show(){const s=PACASE.steps[CASE.i],eeg=typeof s.eeg==='string'?s.eeg:s.eeg[CASE.br];q('#csSteps').querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===CASE.i)));q('#csBr').parentElement.style.opacity=CASE.i>=2?1:.55;
    q('#csT').textContent=s.lab;q('#csVit').textContent=s.vit;q('#csMine').textContent=app==='eeg'?eeg:s.ecgTxt;q('#csTheirs').textContent=app==='eeg'?s.ecgTxt:eeg;q('#csLink').innerHTML=`<b>One mechanism, two tracings.</b> ${s.link}`;
    q('#csOther').href=`${other.href}#atlas/case/${CASE.i}/${CASE.br}`;panel.show(s,CASE.br)}
  const h=CASEH0.split('/');if(h[0]==='#atlas'&&h[1]==='case'){if(h[2])CASE.i=Math.min(PACASE.steps.length-1,+h[2]||0);if(h[3]==='poor'){CASE.br='poor';q('#csBr').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.v==='poor')))}}
  AX.draws.case=[()=>panel.draw()];show()}
function openCase(){setTab('atlas');setSub('case');window.scrollTo({top:0})}
